### ISSUE TITLE
Identify Airdrop Farmers

### ISSUE THREAD

**Issue by gihubsfy** [safe-global/safe-user-allocation-reports#106]
11 Safe Address
0xb2af9836db89808964be5db68964ae7d8dffc462
0xf24358f4d8030b0042b9daa8c5a1eed0c26f47fc
0xf3e48a2b1b9808f66321fb1eb385c86d2486dd6a
0xc00b6dd4a257fdb47f5b6e48e008c6c15adf6b82
0xdec1a87eaf2123779f881b7db9ebb60c8bd2b785
0xc048bcfb29489f638de3a8e15e6d6f63ffddefa3
0xd122867f1030b9f471f92eafff5565f1bf984561
0xc7f7a85ce029bd289b958523cbf8f1bb7b102c15
0xe3076724087bc2f8c1a9f51cd63a3e90b3ee428f
0xfa3811e5c92358133330f9f787980ba1e8e0d99a
0xd2c15e47465519789c2e6cdccb3527d989d04955
0xf6094c3a380ad6161fb8240f3043392a0e427cac
0xcf16fa07edf1a49e824cbd46e28f849412085a93
0xb7848eeaad5d44c50d0b7bf8e7d0f8afb892fb44
0xf6bc2e3b1f939c435d9769d078a6e5048aabd463
0xc1386df96ee1e6d2564f3914e64ff47f2885a287
0xeb5ce9fd4ab6cca2515adfe54b58efa3fe9ebca7
0xef2ae1b73f4d9ef1baf135d471b092c27258e71c
0xf0b2802d6010f53a0ba7fdee1c0f036c91a2d5b5
0xf26d1bb347a59f6c283c53156519cc1b1abaca51
0xcc5b47adc690a459adc9cb81896513abe0b4f641
0xccd7cb31b51da5abb7519afe5e7adb65fe9ffe7f
0xd14258621080c38cd87d5141b68b99e346cbafd7
0xd4f5b93b9ab9a6cbe42fe997dcd5a797bd6eac57
0xf203f949c1c4ca53b960c1ba33cb6455bb9b0079
0xb6a99fc8ca375959e0f3a5b48e9fe761e58a41a5
0xd587c172dbbbc0072617dfc9f78c866dc6c531f9
0xf7f52dd34bc21eda08c0b804c7c1dbc48375820f
0xffccdcabfd84b00ec92331ed17e19503dee6a620
0xac321182ed14b2f34fa361c6f38fb8ce0228d9a9
0xf1b17174c015e7ed2be9459e9a9ddd4fafb234bc
0xde372b35fb84ad2fbe4f74750c865baf0b480833
0xdc23c31c57747ee7cb2bb4b06af2ceab29e33cdb
0xbd4707b67d362a0172036b41ba07d2ff18871711
0xfc78f8e1af80a3bf5a1783bb59ed2d1b10f78ca9
0xc663f88da2d09df9a52ab07a2714cab693f7c5f4
0xcc8793d5eb95faa707ea4155e09b2d3f44f33d1e
0xfb3bd022d5dacf95ee28a6b07825d4ff9c5b3814
0xe4422bcdc20e93014f67b73d4120b878c4246804
0xf8eb0e5f6277504716589300377af653ddb5c72e
0xade898c44d65ab28359ac7471fb038de495d1824
0xc00fcd5e5c7d931b1d42b84bf9292b2d28b9aec5
0xb784f92002117f11acf9f3f79769eb9369b25f50
0xfc60020375d6eaf86e299870448b88624ca0202f
0xca9beb825821f3169fc4369898d7af30836094fc
0xf5307a74d1550739ef81c6488dc5c7a6a53e5ac2
0xec5f4829854d1f0478b5b7a1c6f7dc50c4545fc0
0xb40f4ce59da4a0b6d10ae605e10fd4e6ca9ed4ae
0xc192f75bcb64d2e4f7e444a8e6fe8c3729728086
0xf957fa14ea72a9ecd7bdc06c5be89a5a34c7aa89
0xda9c16bcb0b1a9168e66546671e4369bbf353489
0xe1bf344c8be9ede90e3af3badf506dbe0eac79e5
0xc01f3d5f4f19db75eb3eeb1f688eb51fb86d88de
0xcf3bc13c0f19b9549364cc5f4b7ea807b737c062
0xd8f5a1a97f96bf45812e17c0bb3afcb6424953a8
0xd7da77a85d9968137944ad9e8780a058847591bb
0xd6ed746a27dc15dffa1bf71a548b8c8d49620ca1
0xe504ae5ec78abff10a84a17de90f72af09e1f3ac
0xe298a76986336686cc3566469e3520d23d1a8aad
0xfedcba83379eb70e94c28d3837fe2f70e8284d12
0xc8904f2e8c489737f8d5d644b97784f7123da230
0xb020379b395f20b080b090b5d6676bc1670c581f
0xfa49b7e3f713a4996e19557a67a4da897a7b7f52
0xb8a9fada75c6d891fb77a7988ff9bad9e485ca1c
0xcfbd9f6e88dcf93a7c409756013b342858c30a31
0xca67780347e95b4da5845629f759a97231b82ec5
0xfd0d6e5829e27efce71826e41f9add4d36ef0f50
0xdf681e5ffdeaf798f576ca7c7867683e161efebb
0xd38a87d7b690323ef6883e887614502abcf9b1eb
0xd01a46404e3af36a0936f48db312c5e6bb5b06d2
0xe626d419dd60be8038c46381ad171a0b3d22ed25
0xb0d665d9e3c75725b58cff70311b03716ded4332
0xcbb83206698e8788f85efbeeecad17e53366ebdf
0xc03f2a3e1fd0a9a4ff98b0b7cc54a80c9312bffb
0xbbe24603813d7acf87a080633741880e5758347a
0xe4cf7b2c9a95606238caa760048e91b3865b341a
0xb385890f04428695eb669783b501d1940bc103aa
0xfeb4acf3df3cdea7399794d0869ef76a6efaff52
0xe5d57b3546663edeca885cf5e4e4fc318cc51168
0xbefa89d90c112a416139f42046cc2d4a8a308815
0xac0277e264818678e2a95be0fa61f938c9c0be68
0xd44ca2ee97e661e6168416d9011ae63073258c8e
0xb3dfe140a77ec43006499cb8c2e5e31975cad909
0xe75ed5295c13d224036feb6439db7539fe6d7ce8
0xf18107285e9215d1e43089586e80d2649de0af43
0xfb2584d9302f0b15fc82fd1747d8e90df54ce2e7
0xb28b71c694f53c7cfea8dffdc85733237e0c981e
0xb594128d9365ecf60f996ec725087ecc96efb928
0xfb110f8139e50625efe536445702a36ea06e1653
0xeab52134cdb77ba486cd82d6554eb7bd232fd288
0xcaf6a0c4468087d76e6b2917cea10f0e1aa2f9d4
0xe373a19084753bc4746a05fba80d10534ede2c10
0xc5bf10fd721f7078b1715597c4fdbb3018c45e05
0xc981cf76eaa5d535989d11d4585b2a90859ccdbc
0xc5644141ef7d877e5af5dd657aa69481c7c98005
0xb5f7a0760b983ed20d9e543c8c00d2c306a3d6f8
0xb6b9f270ce01aeebfe6eb3becebf00c68d569567
0xb65cef03b9b89f99517643226d76e286ee999e77
0xb7e8a6ff4568592cb78ed67e5863c15650f7bee6
0xe001452bec9e7ac34ca4ecac56e7e95ed9c9aa3b
0xe4762eacebdb7585d32079fdcba5bb94eb5d76f2
0xf12ebcb7d7f8b22d629df78fe9f08a0c1e8a4fe1
0xb96e81f80b3aeef65cb6d0e280b15fd5dbe71937
0xcf2d2da4c2f9b0675a197febc6708704834f9c24
0xefcf76d61503892e184665db37746054670f9966
0xb6b9e9e56ab5a4af927faa802ac93786352f3af9
0xba050d8eaa20b2e2a9348be6866e78a7648d7d59
0xf3b4babd413bb5c572cbd52a8824fdd2d0ab1fa5
0xf2270f39a96af4040f697769f24969c83f182dbc
0xb30b700332b27438c78e95d3ac714542ca6c4cb1
0xc2428eb30a09e1f32da0240747b1931f2ce35b19
0xc59c3fc7379ca341b24be58deb7bdd8cfd15e63a
0xb8e3f772cd13847fed813e77b542e20e0308a93b
0xb3f4f030bc9f8dd7624e39bda342673be7e0981a
0xe01287f84034b327b33c21dd7e1e4134ca1694bc
0xfcf455d6eb48b3289a712c0b3bc3c7ee0b0ee4c6
0xec4e7362dc4e6697409726d6d4960b6a6b35c696
0xb5704d6a7a4b248f283544906a3a158d40990957
0xf80cd14ec747b2adf7b1a9911b38c65a885daeea
0xaedcff980aee98e7764cfef722f039820a16918b
0xfe4202c3f6de22068de5f3b463ae386dccab3e2a
0xd2b3ed0730ce8ede88e941cdbadbd86d4f2a5027
0xc102d2544a7029f7ba04beb133deadaa57fdf6b4
0xfafd604d1cc8b6b3b6cc859cf80fd902972371c1
0xd79ebacb73881bde1c88e00618bf58d88095b1f0
0xd67fd7b8771c4748a555801ea2b11de9f00f20e5
0xb639a0edc1e8b17a4f767e774c0da85db0dad14e
0xd3a322271abccee412ba29bb8a66ac7c8057f785
0xe7636c7ef670a3bcf772d9d57244c9e88ad90437
0xc57ac421d34d67252c71bc0bd18ea63a694b89f4
0xce4a1e86a5c47cd677338f53da22a91d85cab2c9
0xca978e7f14b6fb68deb9f3f894cd34c2e3e3b074
0xe615bb53ac71e621167751fa5a9366e5d01d88a3
0xcac24672160bf214da06610152701c5a90ccc45c
0xcdf7d48d8bb077d198d09308d1bf280c8346438f
0xe6239f6bff1253c4f4d402ed8dff2981fd9bfb12
0xf5f513d0e547432a715fb59cb962aff97af7d37f
0xb5924d7c7593decc6749da574aa261da2597309a
0xc35ac726a530ecc86ec47a008ce9b0db67786b44
0xc932d6a49d2d8b77b4075e537d142ee6cc1e416a
0xd35f01f17d4475fbac399b90b47b7642265cea4f
0xd513d45d3e6bca97cb8e9cf840979273972dac90
0xda12b368a93007ef2446717765917933cebc6080
0xfc058b9b0b0cbd727152873172af3008316d3b27
0xed47ea758095d803bfdd5aff5b363d220923e20f
0xc404d138d3ca1b4467165b6561d19f319fe1edf9
0xd8b2e5c2ba45698dc9f592dcf08a4b23381db787
0xcf6a97d02f9cc47c94de5a4874c32a0182638fb4
0xc7d7346da3076da4220f7efcdb8037fb7951bcf9
0xcce01651b87238d912a4e7292cdb8e9b3417f0c6
0xd0750af38dc9dff547b406aae24fe69780c446c2
0xeabe881eeabc88bd38730621b87f75cf1c5f27e0
0xb1748c79709f4ba2dd82834b8c82d4a505003f27
0xc837661a012a3f0f8d7a99d35207066a69e8e960
0xe28fbe83b3ac5ba34cb636ca8ef89e54a4c97259
0xc2bc2f890067c511215f9463a064221577a53e10
0xd1e70efc9415b147ee96daf134d8673db9b98bc0
0xd6109521e5453f0f4cb4fe73cdcace04fe1936ad
0xf36b85762267c588323bc7246676171d93a7fad0
0xba3a09d60abbe3fd0b8e16f49f1e4b47e6cbeda6
0xffa67f8aec99c144f887a5864aec5d1bff5062f3
0xdf4688b71e9c83b30705f610030c4b3462c0ba9e
0xcc084ebd00db39317b932c2a0126541ae411282f
0xdafca7a5e3b67b8f36c1fdd7691ed85bbb54cc18
0xfbf037cb5167fdf1c54561d2a1370fdcad1d62fb
0xc1ccc7747915ddb0f21c44d16f0af9dc8a2ea088
0xe5a64fc0d3396d11eb63d728791577e254ac18ca
0xb02a9af0869ecf4c2a20268b4e11c7854563eec9
0xcf9a1690c7a49277dce4af2e70c9c2e4210e5868
0xaf7eaf66b5f1fa23158784fb4c17dba90727afad
0xaf417acd9a7e1714cdc8c2d2e0c04dd052633193
0xbf3446771090ae2050ac191b43a93e63b3d65b63
0xf0715a936f7012716e598f928715d15acc9a005b
0xddcb19f73db35aa0edc56f660b1893b2e583cb11
0xe8096f98e90daaebfd4822ed391b6806b377436c
0xb81850c8fa25e0869c7e392e5ac66c2712a988e4
0xfbece8a353adea5be7663c4d8c1b449871a7e4f8
0xf2916d7db8a361a79b475979dd1b437711c48356
0xec9a8f207ec5a0e867f6057cd9d178edf6099eea
0xde21f729137c5af1b01d73af1dc21effa2b8a0d6
0xef650d06265872640e28b043e32e543b74cfb713
0xe184847337728e9e92a958157031d0b07ceb0fc9
0xf06016d822943c42e3cb7fc3a6a3b1889c1045f8
0xb0cdaba779097f5fa32b351b6e2d8fe04ff6d728
0xc5e9febecd9fd19597566aae97a61ebce73b2c8b
0xbc0e5531f3e4ec1c8e69368724161f41caf978cd
0xe610193bb9ed35b7151cd2b9ac10325e950144fe
0xe96eb4507a1d162bbb99301fe592d310e9489e40
0xff343d4b5f7e3781f99c7a4dc8c1750c03185a68
0xc3a1bdddbec6bc896162f22d0d7e260df8fe01c5
0xb16cc3b77c012d75b7a7318cc083ffd7a70bb4e7
0xebd217f5b00ee777dfafcf8d5663c824949c677e
0xe1508434e63d7e2c9ea86971b0287bcab52ccccd
0xafc1b3139d9fdf949c53e4743d4987e78dc1d781
0xc9c9fd5c6e7497c02d24446c83ab0217a400978d
0xeb45c57bf152aaa328e06b98e12a9912448a8da7
0xc6d1df9c778829762445d49ee4f11cd6aef1c453
0xf8608dceb6a4fa1dd4837ba390dd0d456a392e14
0xfbb56e75d48778bb4f1b2d3961b20cec8dab2aca
0xad80e33dc720e5e28267c9a95954b54de876e48b
0xe094a22330b1eb7d69bb6342a63c59c07c1a5b4c
0xc93e3583c6dc8dfdf59b974d704b5b79f02e210a
0xea670c6fdf2bff1d0dda907c3c128bd34fc7044d
0xc9044dd6162106edb5ece3af8a8e8b657b612e42
0xc2410494b9fe6f81f6b0798fa462730d9a9b3d8f
0xad0a58999f8ee0aca3eabf9b994f070eb563211c
0xba42f4d74b501c24a12a96ac8f32a7f1075b6766
0xd30c22d201f1a8c170f79b4735ba59b5968749a2
0xf14d484b29a8ac040feb489afadb4b972422b4e9
0xb4c3a5f129c050960ce9b7b508ac65ab15ee8860
0xe2c91f3409ad6d8ce3a2e2eb330790398cb23597
0xd0a7a8b98957b9cd3cfb9c0425abe44551158e9e
0xd9d698c931a38946c246b4467cdac87f7b3cf8fd
0xcc17001246255cb59847974af59fd4321f3ca55f
0xcff43a597911a9457071d89d2b2ac3d5b1862b86
0xdfb6f5112c2dca55fd9982a6c814cbcc83acf07c
0xb92b3dd377c78d76660271bbcae3b291c4b0a731
0xd4f6c1fb52a2ddc1142a2bd28c8a3702ae07ef60
0xd59df0f73a24ecf28b12d9e4bd8cdf3a6b3f6e3f
0xbfa8502b56e7732d9bc201d6576d1a3a31c0f7f1
0xbb0d4430a597c627a26b55fa30f694c147cb37dc
0xca22f929aa5dbe2db2d0305d31604fe0dfd386b5
0xbd52887f62a84ea3c5b70aca40a6cce30641b4cc
0xdd42948c8bceab0a33298863007e01d3a899ae6f
0xd10ee19667ed9bd74292ca16a07d7d6834a3e8ff
0xf91ec5ec7764e5f6d2ce255ba705c28919ffc366
0xb03f1022d6ce5d7b9f2cb11dc55a7d095c5fa77c
0xc7c712e02b3d99564ae830cec33e5c3ef45d0c8e
0xf7de1f9feb519ce661ca5a5c03dcccf4d28d9044
0xc1e4f1cb76bdd70a9e393a3073de1efafddd4834
0xda100e92739db8fb70a2634fb08ffa8a380d8a6a
0xebae93e31dbec37f6c0a313dc1baa2db1fbe53a0
0xe513823b07f9c428c81b15bdc2bb6db283e1b199
0xb11474f216ecd9c25844a7b745112e5abb42d410
0xbb7564df711294cc6ca15904bb88115d99de90b6
0xd38ae6e4d4c8f788f78e96665ef5343a286261fe
0xbd5ca40c66226f53378ae06bc71784cad6016087
0xcde3153246280c52e932e80fef5481e5702633e1
0xbb981411754958d3471a0f22ae8eb96417220735
0xb78b464a624040fb515ba6ccc33aff46fd9f059d
0xdb506b409b9722deab733b9c50d1086f8fcb7e9a
0xdc0d10cdaf572297678100b3602a242d5db301a8
0xc8ab8bf5913412e08cb08f12df1e57b0c9a1ef5b
0xb4fbcc98d8664322db14dbd7d4afc791bffaa684
0xf5f63126ed968c987b0b1dd876bd749cecd496b2
0xb9a9d0f43d6094cd1645f25a3ebf9a4ba447264b

Methodology

I used sql and python to analyze the association (jupyter notebook), on the footprint platform,
It is mainly the transfer relationship of tokens between the addresses associated with the airdrop. The sender and receiver of the transfer must both be the airdrop addresses and find the corresponding transaction hash.

Code

http://playground.footprint.network:8123/gateway/default/jupyter/lab/tree/GCS/austen/farmer_dectec.ipynb

Hunter Address
0x0fcC42c0789e301A1ea74514359a34602e736d04

**Comment by tschubotz** [comment]
> It is mainly the transfer relationship of tokens between the addresses associated with the airdrop. The sender and receiver of the transfer must both be the airdrop addresses and find the corresponding transaction hash.

This report is incomprehensible, please structure it properly and elaborate.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
