### ISSUE TITLE
Airdrop the giant whale!

### ISSUE THREAD

**Issue by DOGEKINGGL** [safe-global/safe-user-allocation-reports#107]
# Related Safe Addresses

0x8d3a42fd302dfeba6e18f9c48f46ae489fbcbf78
0x3ea4e94791e7ceb84f82fff9decd89c0657fa3c4
0x526f35ed13755a49ff728a1639575972015fdbc9
0x7af79f67ab00a50b4a08390247cc65b8a9512ab4
0xdcb4cf6fc2fed9b80725c1ba0c40723f31a6ff24
0xf08b59fa74174f48e9387b662d4ccfc09b47a7e7
0x95905e9795c6242e1b70c7dca6cb7ff70afe53fb
0x344c416cc1e616223665c0618d123cada1a948fd
0x9715d51c8c5da1c4dfa7ed35750a2bf6d66a47ee
0x27f22677dfab527405bf48b194a1277d2804efc1
0x675b3a5698340dbc0bf4635daa93667b31eea338
0x1500e6a58c031fc9912d301f9a130f9cb3707eed
0xfeb6cfa1d51aa53cd458543e9fd49f3ab87745d4
0x1555dc32f91cf23460bf4b76a2c6196984c02897
0x4985d58c2391ef3caa7502746dc3663e27b2fbc3
0x064210ceb5e1815dc82f274a8ddb8f0d70ac8121
0x993d5adcb4bf8e848ba25a42c92934f59cff5f0a
0x53ff9b7e00c601dcdfeb9d3da5db4252d72757d6
0xb0c67d860158e0592b317488685fbcb3f836c8d6
0x8e1e78354c240f28a01da55611d1bbac2f17fe39
0x5698a89ac10842e658804a9c36a8c5085bfbe3c0
0xcec93b333d4140a7d53b6d72ccf4f5f9dff951b6
0x3b0d3ff250ba494db67fee61d7db296e71a73884
0x3bed69632a03a987cdea408788845bd4818844d4
0x836df11b617bd70c511c56203724c75fee091f0e
0x2502059ec076c5409d7332f57d6f1386710efcb4
0xdb251227116046f5076ae327bd2e8b8cffc22479
0x38810e93eeb9604cccb2ae5a90f8d1e091e3a73d
0x58de9e93c98a88576167d6cd96fc37fe08e4de02
0x7e704b7fa936e14be948338fc9bec46b192bd101
0x37db82ad056447b34aa22feed63fa00fe849c2bf
0x629db9815745cb540bb6526bb3ba19caf6efe011
0x6847b3a7d1d3915dfe361cbb7fb01d79253adde9
0xf4cd502a9eecd2322b453debe9d48a85659670eb
0xa79db9f0fae848a12888f03e5e89e8421c18b71b
0x3b42b6d904b35bf607df792ace74b62b4a9729e2
0xaf7cdadaa6454d2278dc9f6cd0a8eb8f18cf60b3
0xdb7a2deef12a4fb799a3688dc942d92c2feb49aa
0x5c07be8ddd9b34bfb993a98f0b9cf044da08156b
0xbef0e77e3c2c3d07c02ba8a419dab3d95c74dec9
0xfb097c202b55a850a061c09596b4fc709575e020
0xd0ae9c436213ba258cb3fef46733b968c6b3a101
0x6de75bb282898ff5e28e308ee7f8750a0f2b077e
0xb580483068d3a808190287466ab0e524efb908d6
0x0b191f1973c42dd8f1f475752d9272d85f021278
0xc5c22b7afc45ea90e082f4d3b4faea6b30506e8f
0xb687343f5505f33b24eaf395d16f0ec8c5268c26
0xd64ee2aeac0fdb5f431b79c2aed4a2fcda561d23
0xd7fb04241cc0af913bd20433cb732ec4bea57c85
0x02a04a921fbc2716311cb286a3a6fd3636d45421
0xcf16fa07edf1a49e824cbd46e28f849412085a93
0x4d15b6860e2059cb62ec564bfde8b963d6a9c4d8
0x06d169dae221ace6738894b467b6375b37b13f38
0x06368acb396c5b235f5819aac7eff11f6dea142f
0xAE76A64B6Ca68387b953F322cfF7a46097D846E4  
0xF02a2098b49D07F335eb66AEbE4eF55706d9EEDf  
0x329Cf99D6bac536bac492166e4D4d6B20Cc556be  
0x1e2c771266c80dE2dbcbdb57E2716Cfe1C1C9305  
0xF3c2879e3815b4D3851B353C76876b93B8Dda5F7  
0x12790785fbba06c28c6757e8c7DF7cC3f636b5A3  
0x872D65baA9e8fECA7D6dD65796B2855C18C30A54  
0x68e77A8145579416f3edA9aEd049d5cf91a53282  
0x9E77A2839f572f2BF42B294083CAe9Bb4C875264  
0x3bED69632A03a987CDEA408788845bD4818844d4  
0x2916965CB25030CeA3045833E36743bADEF32aeD  
0x85115B8210bE88F28CA35aC38bF272A0E1B8a0af  
0xaDd69F901bAFf4dA16eDA2c1cA0E966918D33502  
0x2949353Eb259A91bfb17398DA5451a5Dd8747729  
0x14674f786b35150205853D705DB81A26Fba21Ed7  
0x3A704C7684238a1b2aeD0ee94A9153Dc1aAC7e6F  
0xb566737B43f0BEe5205BfDba9f7f934AfbA1D0a7  
0xb59b5ea29690F57b411FBbf9a98E6CDBB6BD45f7  
0x4De5bbA9a9FE5EC11d2290a76136C4113552D165  
0xB96eE3ffBDd4d2b5Cd4EBF690d91a60a7cd1f4bE  
0x21fF718dA8F01FdBBA456d85035B9b3529D787aD  
0xd78ae938f0F6df5156EaB14D60DA23Aa3A4aA6E1  
0x956e68ceCc3096Ca1c1A1a234b8C64404e094446  
0x8c5B88Dc02919177452515114a9000E37510cc7C  
0x58e940d446C0899179275B53F9eCF77e1C4c65e9  
0xa8246172595716Fa28D62e0e5E26719A87bA67d1  
0x667dd118c06324DA9f9DF61C2eb894DC48E32D92  
0xa0C33d89C9F8782275B4302f0B37818dF4aCC506  
0x4A8C28B424bbd58799b766edeceD5b29F86Cf8fF  
0xC6dB09a301Bfb0991458074199a905245f13d043  
0x3437977766fe4e39d5AdE5206470ae9aeF15f7aC  
0x08551755227D92fdFdF4d2E164eBfe67ec364D8B  
0x7C9E2A508d93398B65FA2aecE3F256e3320fb065  
0xabB966b8be466a63Ce3B1c5c1cb84C8d923439d5  
0xe828fB89DCFdf3f17200aCadC81610Ca6b3bd105  
0xAb345D31C805DfBC6983734010DA19d5EE920058
0xBef0E77E3C2c3D07C02Ba8a419DaB3d95C74DEC9
0x5Dd2c4b7CEe0d63f59fbD40E345dc7FAD66550F6
0x27B838c2e151E45b82828630841dc58C75929540
0xfc60020375d6EAF86E299870448B88624cA0202f
0xc44b3e6889C08d0df9Ef494aD8a7cBe176896d11
0x7e704B7fA936e14bE948338fC9bec46B192bD101
0xdb251227116046f5076aE327BD2E8b8cfFc22479
0x3b0D3Ff250ba494DB67FEe61d7DB296e71a73884
0xCeC93b333d4140a7d53B6d72ccf4F5f9dFF951b6
0x5698a89AC10842e658804a9c36A8C5085Bfbe3C0
0x8e1E78354c240F28a01DA55611d1bbac2F17Fe39
0xb0C67d860158e0592b317488685fBCb3F836C8D6
0x53Ff9B7E00C601DcDFEb9D3Da5dB4252D72757D6
0x95905e9795c6242e1b70C7dca6Cb7Ff70AfE53Fb
0x2377420b05bB2df71a5B130ac0e472a46e3297F0
0x61e00016d26a700352E8e7ba3868426b000c8E79
0x7aF79F67Ab00a50B4a08390247Cc65B8A9512ab4
0x993D5ADCB4Bf8E848ba25a42C92934f59cff5f0A
0xEDf65B05908C75a447f3B0462C935429011B318E
0x344C416cc1e616223665c0618d123caDA1A948FD
0xBEABD76e274f9F56c2762e4a5991e3D52F730cfc
0xAB5C0F10Edd3972B5Cd3911c9a81eD2180c218D2
0xe36aaF75975720C0FA3D56087Bf910d2A53Cc959
0xa63d3836d37146a8B186C7B20258f988B5d74426
0xCC191076ef2337cCFA15ce7986e68d45A4144Ee8

# Reasoning

What they do - create multiple safes per address - use other addresses to execute transactions - transfer USDT out through the safe - the exchange address that receives USDT has received USDT from other different creators' safes.

So here they are already identified as hunters, because the last exchange address that received USDT received USDT from other creators' safes.

Checking the address, there are almost fifty-plus safe deposit records, and the safe deposit box creators are different.

0x397fe28Eb459303ba2204c24A272F19491a74e17

After the setup is complete, each safe will receive USDT a few days later and transfer it out. All USDT has been transferred to the exchange, and the following is the address of the exchange that he transferred to receive USDT.

0xacE2689da656A159A17e2Fbdc2ebd1e91C75f229 
0xeeB014b4dfb46B11075129fa44E39B1E071F213d 
0x980Fd091b280Cdcb98a06b0e2ac3Ceb167FBaa4a 
0xdeE8786aE7842D3AE5ed9A5121787fd6cC4671Ec 
0x0873b8fCA6E9DA688b9FA46567Ce74A333e1070E 
0x0C642Cfc9d008C1048b4Fd6f496b061eCb3aBeb3 
0x397fe28Eb459303ba2204c24A272F19491a74e17
 0x8A7af05ddf937ec68157b8499c2a9df3Fa290fae 
 0x363C1807eEAd98D7f3F20614b52B8213B8D8BC88 
0xd474ab0BFb3007579Ddb6BF4530DcAA8CF4C1e78 

The following are the addresses for creating safes, because the safe addresses I provided are not complete, and some of them are not found because they have created many safes.

0x54f7393E3F2cE76743331c758ae61727D37f08Bd    
0xCA33B0EDFB55C99d99B1d8F76f07fFe88036083D   
0x196e36D56B480c7FaFa05969122583801C35101a
 0x6eafCd29EDE3A1A8C042bdDF9994C204647cad2e   
 0x1A84e9f0C3E4D4f4278182A126eF6BA55feE0f3c   
 0x185C16001Fe02bF6F52E9F7A11976C19794eecd4   
 0x7bDd6529FDFD78b1125AA4d4d152E37b58fE49C0   
 0x7725913479Ed376B9AcB26Daa4511E8AA335F5AD   
 0x93750d671c8f424E2A9D39aCE60CeDaaf69d03a8 

# Methodology

I found the address of the safe in safe_user_allocations_reworked.csv, and clicked on the creator, and found that multiple safes were created at this address, and then I checked whether his safe is related to other addresses association.

Prove that they are all related, check the following addresses, you will find that they have all transferred to the same USDT receiving address, and the correlation is very high.

Check the safe addresses below as they have all been transferred to the same multiple exchange addresses and they are safes created by different addresses.

0x3bED69632A03a987CDEA408788845bD4818844d4
  0xb59b5ea29690F57b411FBbf9a98E6CDBB6BD45f7  
  0x4De5bbA9a9FE5EC11d2290a76136C4113552D165  
0xF02a2098b49D07F335eb66AEbE4eF55706d9EEDf  
0x4De5bbA9a9FE5EC11d2290a76136C4113552D165    

# Safe Address

0x3B928329f3dA134c1D72123B7731330D88068777

**Comment by DOGEKINGGL** [comment]
# Related Safe Addresses




# Reasoning



# Methodology



# Safe Address

**Comment by DOGEKINGGL** [comment]
Airdrop hunters are very cunning, use different addresses to create safes, and use other addresses to execute transactions, but the USDT of the safes will all be sent to the same exchange address, different safe creators, and finally to the same exchange recharge address.

**Comment by DOGEKINGGL** [comment]
Hopefully, as you can see, these safes are created by different people, deposit USDT, and then transfer out to exchanges.

Please check the USDT records for this address.

https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7?a=0x397fe28Eb459303ba2204c24A272F19491a74e17

There are nearly 50 safe deposit records in USDT with different creators, so it is.

**Comment by tschubotz** [comment]
> # Reasoning
> What they do - create multiple safes per address - use other addresses to execute transactions - transfer USDT out through the safe - the exchange address that receives USDT has received USDT from other different creators' safes.

Creating multiple Safes is not airdrop farming per se. 

> So here they are already identified as hunters, because the last exchange address that received USDT received USDT from other creators' safes.

I don't understand what this means.

> After the setup is complete, each safe will receive USDT a few days later and transfer it out. All USDT has been transferred to the exchange, and the following is the address of the exchange that he transferred to receive USDT.

Using the Safe as store of value of USDT is legit usage.


I don't see how storing stable coins of significant value (>1M USD) is airdrop farming. There is a non-zero chance that we would eliminate legit users.
