### ISSUE TITLE
Sybil attack alert

### ISSUE THREAD

**Issue by CCCCCCremember** [safe-global/safe-user-allocation-reports#120]
# Related Safe Addresses

Provide a list of Safe addresses that would currently receive a SAFE user allocation.

The list must contain at least 10 eligible Safe addresses at the time of review or it will not be considered. 
The eligible address list can be found here: `safe_user_allocations_reworked.csv` 
Reports will be evaluated on a first-come, first-serve basis.

```
0x999c2dd89039284e95346bd15b56ba1e82139b81
0xc7768a53234a72b53a980c977eb07c8c8f5e76a1
0x62eeefab55104bc0d1ae2ad181e2b67476e5ef47
0x4e2f98c96e2d595a83afa35888c4af58ac343e44
0xa4c69fc9d85b6a3ffeeeb58c18ae6777a1960d0c
0x60b7817343f1f74a03b6c8ed043bd1d5e4ade760
0xc1964ebd9814624e0fa4bd20bb314982ba26baf2
0xffe39a197e1e5e05ca077fe0eac402e25bd3844a
0xaa41296be944072430708491915e9b7efeb3ed36
0xee64aa7c1273339fb12fcc603b889666ed0d1621
```

# Reasoning

Describe how the Safe addresses are related to airdrop farming and if applicable also to each other with as much detail as possible.

These addresses are mostly fake users! 
With only one or two txs and very single behaviors on chain. 
The addressed below with one or two txs: 
0x999c2dd89039284e95346bd15b56ba1e82139b81
0xc7768a53234a72b53a980c977eb07c8c8f5e76a1
0x62eeefab55104bc0d1ae2ad181e2b67476e5ef47
0xa4c69fc9d85b6a3ffeeeb58c18ae6777a1960d0c
0x60b7817343f1f74a03b6c8ed043bd1d5e4ade760
0xc1964ebd9814624e0fa4bd20bb314982ba26baf2
0xffe39a197e1e5e05ca077fe0eac402e25bd3844a

The addressed below with single behaviors: 
0x4e2f98c96e2d595a83afa35888c4af58ac343e44
...these are related addresses

# Methodology

Explain the method used to discover the addresses and provide proof that they are all related and likely operated by a single individual/entity with a high degree of probability. The methodology should be easy to verify or the report will not be considered. Please, also include links to any additional materials you’d like to provide like a github repo containing the script used to uncover the reported addresses.

with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0x883CcEdaa962e0b39dAAbC88Ded96b20df50de55')

# Safe Address

Please provide a Safe address or ENS name of a Mainnet Safe that will receive any potential rewards earned from this submission.

`0xc7495E1c9A62e74473d890eaE40537713AAC73f7`

**Comment by tschubotz** [comment]
> These addresses are mostly fake users!
> With only one or two txs and very single behaviors on chain.
> The addressed below with one or two txs:

Just the fact that a Safe made only few txs doesn't mean it's airdrop farming. Please elaborate how the provided Safes are connected.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
