### ISSUE TITLE
0x8ddf4d28ae2fac4a27b1a485ae56194d16aab3bf is a airdrop farmer

### ISSUE THREAD

**Issue by dcswaporg** [safe-global/safe-user-allocation-reports#122]
# Related Safe Addresses
0x8ddf4d28ae2fac4a27b1a485ae56194d16aab3bf
0xc310237250c13443968c429053a2695b15e520d5
0x133030ea9f4bab5246190039be59fdab8040bdb2
0x373bfd94d9ec6874dda9a916aa5032a2b8b35fe2
0x9d2bb8a40faa80b6ea2a05215961837cf91cf742
0x53f9a814ad6bb38101e96f0708b491d70aa00f7d
0xe03786e6205ae8006d293a86a63944b9352c5de1
0x39b0d91ef7e706609885b3113dd7f8ef2e6b20b1

# Reasoning
address 0x8ddf4d28ae2fac4a27b1a485ae56194d16aab3bf transfer eth to 0x459e812222ed3ed1f946c5f4675cbb562f9666f7, and then he transfer eth to 0x0ae00b38e2947fc73b6b836c79ef698435b60920, and the address  0x0ae00920 transfer to 0xc310237250c13443968c429053a2695b15e520d5

# Methodology
see detail https://etherscan.io/tx/0xda7d6753c0d9fb58c40ee411666c23929ce6433311796cfc1a7d36abbcd9d933

# Safe Address
0x8ddf4d28ae2fac4a27b1a485ae56194d16aab3bf

**Comment by tschubotz** [comment]
> address 0x8ddf4d28ae2fac4a27b1a485ae56194d16aab3bf transfer eth to 0x459e812222ed3ed1f946c5f4675cbb562f9666f7, and then he transfer eth to 0x0ae00b38e2947fc73b6b836c79ef698435b60920, and the address 0x0ae00920 transfer to 0xc310237250c13443968c429053a2695b15e520d5

You are just connecting 2 Safes with transactions. I don't understand how this is airdrop hunting. 

(Also you seem to be reporting your own Safe address `0x8ddf4d28ae2fac4a27b1a485ae56194d16aab3bf` as airdrop farmer?)
