### ISSUE TITLE
0x5769770F5EFe8fB017FB09B6dE3B2d096668377D airdrop farmer alert

### ISSUE THREAD

**Issue by CCCCCCremember** [safe-global/safe-user-allocation-reports#127]
# Related Safe Addresses

# Reasoning

# Methodology

with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0x883CcEdaa962e0b39dAAbC88Ded96b20df50de55')

# Safe Address

**Comment by 0xb10xb1** [comment]
https://portfolio.nansen.ai/dashboard/0x5769770F5EFe8fB017FB09B6dE3B2d096668377D?tab=wallet-profiler

**Comment by 0xb10xb1** [comment]
![image](https://user-images.githubusercontent.com/113136576/189204372-8ac10ac5-c951-476f-b59a-c613716decc3.png)

**Comment by 0xb10xb1** [comment]
Congratulations
