### ISSUE TITLE
airdrop hunters 

### ISSUE THREAD

**Issue by Twinkle211045** [safe-global/safe-user-allocation-reports#128]
# Related Safe Addresses

0xe3748b93f54a539e13ccaf3a96dbc17219be8895
0x5410ddb4446dc311433471290f219a64fccba830
0x07a8d768644f57312df2cc38fc6c800d0da5c210
0x7e4458c71bfa1843c654fd55b74a8e84c077fba5
0x586d2cba9427883244b642e0ea898caa87663fa2
0xb5b5e056b75c2919f0b95310b08e61309e6859c7
0x3d5f51d57c9a705722a2b28c356de92e36ecfc91
0x7513c27ed855e0664d5a222d5df2234a5e22a0a0
0x05a9c1b5769da4fddcc620963adc8a3d7f47b984
0xfd0dd0be4e59370bf3fee8ab9e81a932c94d5bd9
0x6d9e930b3fbb7de79eb4facf4c22ed261935ae3b
0x6cc56d62e803eac16fcdc51440aac291f94301f6
0x3aecc3eabd0655dd20903a0a7d5434ddb1b9706d
0x4a864e5ae7ddde835d39f061db35479a63b44255
0xf826b4d578db80004cef06014bce6471fc09de53
0xbe0dae118b8a7ea1e8aad7c116993d20a622430c
0x296cafb17f581c3e0a0c6ac53ee5d11b8312ad56
0x230c32978925741145d5c41af39865f49fd84c27
0xaea51eca9e454b4372ccb41b39096041a7f67ab8
0xc56b328027defb5fb49780e09370d8a101ec76bd
0x06f328725c02888df24385aaabc5fa1fea619394
0xda43394f4c403df53e95865b1a2659039ecdb2a2
0xf2b7195805e7c1e66775d811ebc02d9b83ab54e5
0x8ac00ae8db651c46a7e35263ef0e4350b22ffe68
0xf4f31dae77842165fef83abdc902337dad6169e0
0xd6251a28d17b53c4d59ee85fceef992ca3420c9e
0xe6f0f92e0a0b672fa7293a89f70baa6bcf77d087
0xef7a277dc145410084ed9a31f7b20437298e8bd4
0x69482418ded8ba0b2b2f3fdb93210895497f13e7
0x7ef74555c44d103710a2df9554d61bfbd14a4be7
0x4e020272c031121d7bcf6b2eefdc34aed1b611ce
0x4a6fb0f864313bbc5303a006516b3c0299f3332d
0x593fc161559405253d9b80d0462f0fad2272fad2
0x06f8345ea88db23858cd1d4c585efcfa65cd5dfe
0x24161ecea12f4c0535393e958ef5a186776bab0e
0x7b03ed7c2c748e19da0b455e2b96ebf189e00208
0x79b5278867e3d33229fd7956a29b6371219c7e9c
0xe7f5320c28212a74a2ab038fec940716d71ddaf2
0x727c7f0488ddbd0b520be2a3c3a9b1ccf993d2f3
0x770e1d9628e722f9c101fe63f2c5fa87b6433805
0x1cfbbfc0a2a4bfcece1e7a0cad2647c1d99a1fdd
0x716c65a6f1d6bdc17ec2bbfc2801466885b69010
0x5c017dcedd52743b86711fd8bf39f4bc43393954
0x728708ed43821fc8abf4f94d0b8bf98325923355
# Reasoning
Four wallet addresses are involved：

> 0xed6fd1c824c7269e1f493fb9ad802f049b67760
> 0xa6e087a55837f10b6c01480991c70f62d42c585c
> 0x1fd93d24735d76e8681fa16beb072d55c60d3641
> 0x001eCc91B845e5BdD7732f1C24d3d6c2F2813686

Two of them are used to create gnosis safe Two are used to transaction
0xed6fd1c824c7269e1f493fb9ad802f049b67760 There are only 33 transactions in total, except for 4 transfers, all of them are creating gnosis safe, and these addresses create 3 to 5 gnosis safe at the same time each time, there is no other operation except creating gnosis safe. 

Of course this evidence is not enough. I found that on Mar-30-2022 03:38:36 PM +UTC this address transferred a 1ETH to 0x1fd93d24735d76e8681fa16beb072d55c60d3641 and this new address transacted with each gnosis safe and most of the transactions with each gnosis safe were only once and close in time. After this, the wallet transfers another ETH to 0xa6e087a55837f10b6c01480991c70f62d42c585c, and this new wallet creates 15 more gnosis safe, most of these newly created safes also have only one transaction and all of them are with 0x001eCc91B845e5BdD7732f1C24d3d6c2F2813686 related.

After 0xed6fd1c824c7269e1f493fb9ad802f049b67760 transferred 1 ETH to 0xa6e087a55837f10b6c01480991c70f62d42c585c, the wallet was never used again. The on-chain record of these wallets only shows that a large number of gnosis safe were created at a certain time, and each gnosis safe was traded once, with no other operations

# Methodology

I first found out through my own code and dune that this address only transferred money and created gnosis safe, which caught my attention, then I analyzed his transactions and found out that he only transferred ETH to other addresses to create gnosis safe, and never used this again after creating gnosis safe, then I analyzed the time of their creation and found that these safes were created very close to each other, almost at the same time, and 3-5 were created each time.

# Safe Address
0xA732240f4d1A6F3fc4f7EFb38766AB571229350D

**Comment by tschubotz** [comment]
I'm unable to follow the reasoning. Just checking the first 2, seems like quite a sizable amount of USDT was stored in them. That is legitimate use.

https://gnosis-safe.io/app/eth:0xe3748b93f54a539e13ccaf3a96dbc17219be8895/transactions/history
https://gnosis-safe.io/app/eth:0x5410ddb4446dc311433471290f219a64fccba830/transactions/history

Please elaborate on why this is airdrop farming and how they are connected.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
