### ISSUE TITLE
47 wallets for airdrop hunter

### ISSUE THREAD

**Issue by jjjvvvbb** [safe-global/safe-user-allocation-reports#135]
# Related Safe Addresses
0x8a7e2F5522a2B88c304B6E55012E4DE998B9E13E
0x0ffc126b095525a36a69d3db9b91426257386b88
0x807ef5e50a6a68fc485488c907099daf6a2d2a21
0x4c772b7025696ae8a8ea9b6cbd28b17ba408f10d
0x30415a59f058659870307d0BD1D86073f82dcAbE
0xd0208523563a28ef547cfa0d7baae41c2b406ed8
0x3a615f5732b1dbeb93dfe6017ae10c7ea20eaa90
0xf9138b750d72208baf94478ddd1a20900c64143f
0x83f11092798324e76a5d5feaf3e6ee87cac2fa5f
0xd214bc9f411d6f92ece8eca1af56a2c0bb913afb
0x92006804baa3ae202c3b377234e6177c2b465eed
0xc093eb788a0377b0edbc4b89d3d559c574e49a82
0xfebe2b6af497b9ac2d17eb008314dd1cf1c6a7aa
0xf143ed827c31c7f519445bcfa09281ec36b87c0c
0xa494159efed07ffd1067049c2f610418fe61a332
0x65269102997dce692fef1e2c6919363292db8ab9
0x2DcfA65f1fa4370ABF709E467Bd47A924C95F23F
0xb81617EfD1ef1D4f7B9986F35A8B557C6Ff323dA
0xf5390A093B960Af510C1565e0Ca846ddBE9434D6
0x54D0Aafd908983a96156d98906AFbe66b3fb901b
0xEd9A0b641ffB13f4E55F04dc1E533033D15Fcfe3
0x765e27419750D8c915f5112658602503CA1d57fD
0x36af31222f71E120840651B28Bc63D32508E96E4
0x3b5F1A9E08DFEb03002e07fbC0727525559138D2
0x116a2b47DE982BFD773B14a3E8C8C76e41370f96
0xb8CBC29faf29c32625f25A391993b993A33B132B
0x68A90b88C092d6601894D8D9beBe6547119d54e9
0x35803FaFd46790e847D3695051cB1218d049B633
0x80E766Ac23FF449a77551E7b1c57f1640b15874f
0xDeA4540CF784EEDD4ABd9EF0Cf6aC8e0Fd040D57
0x8fffAeC3b4C3eb69B144d541EC59677572A1957C
0x4bB8Ecd67a169745De327e7E8D6DBa35a7aB406c
0xA3CE148C6260816CF90619f76B446C174BA47b3C
0x322851CD0718619b5d1C11400AB4d7D82faBFB54
0xE91B29E483789CECA58C76BEDaD515f18A568EB0
0x1C95139a844259F2553f9B2b637bC40cf75326df
0xBdB1759712A7940f5509a8898e17BC7fefc575FB
0x46bf5165a1b1597d85703e615a0f406525fD4530
0x175F064566E8994733feb3A87A7076D6999F1014
0xCd201948494F4cC10f4A0a226Ff89292cb70CB6A
0x3067414F0967df2e2468882Af986b0b564C3a6d9
0x8d1a17B25b5d867AE5B230419130b7b50296702F
0x97b14970Dd2bbfE9C35CD98B4b194A8dcA1dB1AB
0x89d86e8461BfE282342761652F3D13Cdc58Ec9aF
0x75f175c2Af6887805F43C010d2867d20B57a93d1
0xe6B44A6481FcAa6C2035D4BFA7Ac68269aFD4cb5
0xD8F493cB313139D1BC727DA3Ada325131d3333FB

#Reasoning
initial account:  0x94cd68f311901d7cc151c48c62fa8cbdca6d2c04   this account creat  47 safe wallets in a short time. Most of thses wallets just have 2 or 3 same transcation from same addresses in same time.  it is clear that this guys is airdrop hunter.  All safe addresses are just for airdrop and no more transcation. i have checked all these wallets one by one.

# Methodology
just discovered by excel and etherscan , it is so clearly for this airdrop hunter.

# Safe Address
my safe wallet is   0x4c4682F81A95F6D76444e3ea20753AD5B7d643b4

**Comment by MisakaCenter** [comment]
already hunted in #24

**Comment by tschubotz** [comment]
> initial account: 0x94cd68f311901d7cc151c48c62fa8cbdca6d2c04 this account creat 47 safe wallets in a short time. Most of thses wallets just have 2 or 3 same transcation from same addresses in same time. it is clear that this guys is airdrop hunter. All safe addresses are just for airdrop and no more transcation. i have checked all these wallets one by one.

I just checked the first address. There are more than 2-3 txs. This needs more info. Please elaborate on why this one is not legitimate usage.

https://gnosis-safe.io/app/eth:0x8a7e2F5522a2B88c304B6E55012E4DE998B9E13E/transactions/history

**Comment by MisakaCenter** [comment]
> > initial account: 0x94cd68f311901d7cc151c48c62fa8cbdca6d2c04 this account creat 47 safe wallets in a short time. Most of thses wallets just have 2 or 3 same transcation from same addresses in same time. it is clear that this guys is airdrop hunter. All safe addresses are just for airdrop and no more transcation. i have checked all these wallets one by one.
> 
> I just checked the first address. There are more than 2-3 txs. This needs more info. Please elaborate on why this one is not legitimate usage.
> 
> https://gnosis-safe.io/app/eth:0x8a7e2F5522a2B88c304B6E55012E4DE998B9E13E/transactions/history

I have already investigated it deeply, please see #24 if you have time~~~ I have tagged every addresses with a reason.

**Comment by tschubotz** [comment]
Closing this since #24 is closed as well
