### ISSUE TITLE
One airdrop farmer (but the person behind might created many accounts)

### ISSUE THREAD

**Issue by p3rcy-eth** [safe-global/safe-user-allocation-reports#137]

**Comment by tschubotz** [comment]
This looks like legit usage to me, I can't follow how this is airdrop farming.

**Comment by p3rcy-eth** [comment]
> This looks like legit usage to me, I can't follow how this is airdrop farming.

Generally speaking, people don't just transfer from a CEX just to immediately create a safe with no practical use. I'll try and index the CEX withdraw txns that have similar amount of ETHs and see if I'm on to something.
