### ISSUE TITLE
59address by 1owner

### ISSUE THREAD

**Issue by TC770** [safe-global/safe-user-allocation-reports#139]
0x8adc75aa643cd5d804bab300a2d5becd9a9e6b8b
0x98a168e8ae8141e505d7d4bb9c47ba3eb1fa8e57
0x4b435b57ab0aa32f169aba415122a4a981dad2a1
0x209584d708633dff4c6a4d7359525bbe26d07333
0x84443f61efc60d10da9f9a2398980cd5748394bb
0x113e304d9bd13ec54929399e265d8ec723c4bbe3
0xa9d04e8b992248834a06e61e4d8602e3434ece37
0x9f10dbe6f9419f73117483503116105d2c7b2c15
0x1adf825f650938a6a93f899d347f3d2cd073dc29
0x94ddea50b0b0846d6a65404a9bd9547ee7995989
0xc0495a7bd160c1aa2a71f9e16891079c7a9de747
0xeb7b1c0ec3d3a5170356fd21ae6ac41423e28403
0xeecaca98f3d4851092e7089d922c61f1feadb843
0x7ab3057b217dedaba453dab9d0b95b5803250007
0xf029f8f3265e77ef6e6eb71511145c5c6ba5d39d
0x27d530b25f13996e9c77135e361eb8bf73759d63
0x1260af8fdbe715bcfc13b257404c07327a600819
0xf5668fbc7378bcc5a6f0795d7e9b5e5c3b4f7215
0x83640976768d490f8456f50456b383a320f0baf9
0xd55929ff0f0d9e30a158baca29cd10300adca839
0xda2d6f7062e8703c79145fa16f7f9f52980c2e77
0x292bacf82268e143f5195af6928693699e31f911
0xb0cf84945f0d8c7535e787c5dfbb4cfa5a672baf
0xdd282d17b0b2c282e4e83f2b7747017f852be4ff
0x52ca5a12c80633c6cac0504a6007a760ad9c3ff9
0x8700c81883b46922d4a9bc1edea0b77337ec0eb1
0xd2e4f9136490d6cb48eb64ceaf1c6fa165f4d2c7
0x1eaa6365c625b09ef45c3b8a6f2aab43376e531f
0xd8bba4d0d953fedd3dcd5a29b2b52e93215544a3
0x436ab15705e0ed23284512770748770ee4c16155
0x91c6842b79ad4a0f4a03ae274af12a54ab71ee8d
0xdb4a1a616e2cc782911ec19cdb5651647f8111c9
0x104d1fee1e1e3647083bfc770074f89e2d4bee4f
0xc2890a210b1f4f7248dfb57491512bd21c53a9cf
0xbc2f73492bed65351b319ccb6fe66a8485a1cb03
0xa89f55b203e289af2c7b13dd1085ff31d3178371
0x0c5095a8837e633312d897b9f51535c5161c8b71
0x5aea111f6f1e65ffc4d3b31f3320405d3f294f05
0xfb87640660b4164c1be3b45c1e6a0fb9f40c4691
0x9d65822e35310342294afb07f5a32347db890fed
0x7589b95b1c732d06d134381f16650fef4e03a1b9
0xc133439da7da854f84f25685d2191464ecd3d21b
0x89b311f344ccddc54c2f7258f6e84a54390cdb89
0x6e68b398924e3da3d29714feefb82400f9993cc7
0xbe0fa187c0d25eb1ccc4a482912d30f66565101b
0xd67fdeeb0dea8693aac0c04efee0786c31b90cb1
0x5a1bc518e8d34979479aa9c48cc3e3c062248fa7
0x2bfd56b4742a63778cc5c034655d5275f0c5e7e1
0x489fe30ca2e433c04f15fcc1d8935c12b4d8183d
0x9fefd869afc9e88aec611a2f5a0510a1be578f1b
0x23cce7a20f4d012424253b5433576e2dd943330f
0x1a67197536c1019b732b64f9d29a1f7a3a892fa9
0x4504282c1ef82e23260f0573eaf5c0463fcc77b3
0xbbbed61c90d6c7f0db93820584fabe06b8570ec7
0xc3f955a5737840394050e526610475407a4e1b23
0x032d80848be927200fb06b47d985f84e49977ae9
0x9d59e70d478a50833e0c834e79220e3d13775d3d
0xe51befe06f6dfdfa43665b8739eae551b165f255
0x1eda046c1aa126b459572a7e6ae329696496671f
```

created by 0xA5b39e8438264691103Ff4a35c8034658FEE1227 
using:
with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0xD81152389720712E74FaBb14C12a4A14BdB6869d')

Hunter Address
0xB1DE9269D1FD8657d2F9c15A6fE24AB32e18E17e

**Comment by tschubotz** [comment]
This is not using the report template, hence it's invalid.

Also, creating multiple Safes from the same account is not airdrop farming per se. e.g. when wallets use a relayer, that will be creator of all wallets. Please elaborate on why you think this is airdrop farming.
