### ISSUE TITLE
safe-user-allocation-reports

### ISSUE THREAD

**Issue by gihubsfy** [safe-global/safe-user-allocation-reports#144]
Related Safe Addresses
0xb7b271238831a3acc2c450d2ac96e424d7cdada7
0x671515ae6e11443ce81f726f60953367b304fc0f
0x7adc603db9ebc6aad7951d04e58048aa72d76fd1
0x624fb845a6b2c64ea10ff9ebe710f747853022b3
0xf1864b5b6ad0219ff578e25eba1a56c603163c34
0x8ddf4d28ae2fac4a27b1a485ae56194d16aab3bf
0xc1e4e90bcf0152aa5e5bb92cadef87be15885413
0xd08fe0c97c80491c6ee696ee8151bc6e57d1bf1d
0x4b370f17ad713af14cfc3a019b28972ec2799d1f
0xbd9495e42ec4a2f5df1370a6da42ec9a4656e963
0xb05335790892d06800fa6c13c9383dba687c7914
0x80edbd38cdafab6c01c84836b8c8d76b983a81b0
0x4bf165787cc147dbc34ca21e4142fd3ba514df14
0x5a9a375cb96c449c85329144fc9506dc2eb47a96
0xcc9d918ae82e3bcc34167a035ffbd46c4a043c3f
0x9ed5881bb64f59e0a8ba17f27af1e57ec46b70be
0x830104442932290b9cf5219d4abe2503bebb7f3c
0xf04711e15c8c6f4887e78923b2e5819cec6b5db7
0x9b83daf7761511c7a2e75c2f00cad7c855ce8143
0x1beac8fcf83c19f42f2784f6b319c931e308d2d3
0xe2ac5bad0fdefb5323cfde970142a00208022b63
0xd1f5d2a59ef194ae00f27b2da6599ce207dde7cb
0x3688fd756a03405cf5e6fd0ca9bd4eb8cee2c6c7
0x6481fbe6fff7add62c771a95db0d0d5d2b8dc910
0x4e8adf466de38865955f43b8c2d0015ace35a115
0x999c2dd89039284e95346bd15b56ba1e82139b81
0x0e7e35d53d9132a59873a7d9fb3f902c4179a8d6
0x565e6ecae06cad5ae40fba82e0c766d6172e3b79
0x6d1f9cf37cfb93a2ec0125ba107a251f459cc575
0xa5c78f01875e1caf6cd65cd2db39ed60050fbe75
0xe7c551e635307ab3ab109f16bbfcae6a892d9b4d
0x97f7dcdf56934cf87a2d5df860fd881fa84ad142
0x74e7b2eba34168107e69d1b75453098937d2c848
0xea29e46a4471030571ae8747d1d25d315c43a473
0x9f2c361fc359f51f97c7da24c2425bedd81c1a94
0xf7204998ae70da0d2df7cb41d490393e03c5133d
0xb2da57e224949acdde173a5b8a8160c023ea86e6
0x38aa51ec58e156b3e87cf2fe304364b5a9ca16d7
0x7b281ac464cd2cc0f7133d4072b7b47899abb119
0x931896a8a9313f622a2afca76d1471b97955e551
0x22a3f7dabf44ed2b08ccc1836b928bad779aee58
0x2a208ec9144e6380016ad51a529b354ae1dd5d7d
0x1d848331deefa05174cfd55d5bfc08d202ee7d87
0x5a16e6dd9ab0bea9a247f92c5aa0b349f2a4e4c6
0x19d9090fcde725db0b24a6019b5ca3864210077a
0x10a26e27bdbadcf6e5dfc8584108f3024678d5de
0x677bb693cf2c8304902d7d0779041c2c89d4bd48
0xd29c6aec6260261c2c4d5120a796a582f7675033
0xede21d217e29b0f345afc9efcb6018287b7a46fb
0x83d95e354a67bbb5ea55755df5cb5a23c86c0b67
0xa725b7330d88cd9332bebd65749b0b438d74cb34
0x8fe30721d48d0395d6d67a316a960cdb3cbaaf51
0x406bd19cf6fd98b4c549cb0f0fb9f592fd78449e
0xc009285ad3d3a33499068c4a0282451658f334ac
0x322929af44c344002ca72cd32a9adbe8791e8f3f
0x206ac89e18a00c55f35e6f56b9dd1757a7e64ea5
0xa12070aa6c52ede9c54e78384d154896d426e1ca
0x9261ad7e2b8f2ec9858e9ed1a371639951eac0b5
0xd50af53c9fd79fb099b9c72fff903a5b5e1e7392
0x1b4c87add7a98d28910a0e1ab616d71aa4b4ce8b
0x24089292d5e5b4e487b07c8df44f973a0aab7d7b
0xdc7f2591268bad243c552c313400c023f6b84230
0xeaa7723633cf598e872d611f5ec50a45b65cbc72
0x657d732cc8ace759a978c9acac8eb3462470360f
0x886df7b8ad92c1515b031e2eae13aab88648075c
0xad278911ad07534f921ed7d757b6c0e6730fcb16
0xae3d17c0bb2b1c99bdd44d1f7b4815d75e3d7544
0x88593250a1792df6aa0cf3a9e1acfa1065b9194d
0x463091f2878063132ebee6179b840111dab492a3
0xe322fd0f1a764aba2c38c2d0d2b85754c9e5705a
0xd5cbc5e664813c7f1ce0a136aa154ce525e97e21
0x02f04cb4f3a32257a246897a4acb8adbb57fcc8c
0x607d56643673649bd25aa47325a7a6afeffc3b4a
0x3896ab65f7191a446f5ba550a92f9fbe5dd658af
0xf0742dcf7398d53c5dd5cdb3867fddcb0537b64a
0x6c1764fd2294ea5a028b986ddbd8ef5379faae76
0x4e7fab65b442b2faabf7ea5248a3c8c1ed663dad
0x5a61a1535551dc4f65dfc9747e5d416db5de04b4
0xaedcff980aee98e7764cfef722f039820a16918b
0x310dd223a6999578f9c0738003cc6ca665e3d830
0x7283adb0bbe7e8497d9e84143c48c86321b596dd
0xfaa1f5851d31f7d42322a76c661c56a5522845df
0x923b64125293d0e682ac98ba638e9b3283d9992a
0xef17933d32e07a5b789405bd197f02d6bb393147
0xc504b73a9b3a37cd6a14910c8ef998f41fc07eed
0xa2968e27a440e2dd09f96eb2d6182ce352a583a4
0xd6f7a20458a10cc20f3f3d7808889e2bfcf2bb86
0x876754091187a4b2ad97bddc9be068fcdd54dc9c
0x2765c429ab05e190805c5ad9cc6cf3df9e363105
0x3e2c016b213fc2ae75ede5f7b85fc919ff0f2055
0xac99fc68d0538463af9dfd61652c47ae090b21ca
0x54ebeb54a5d1942073e28589f27e165953ee0b46
0x7d07fc4336ab7c6c523f02a7d3a074d70c259e2e
0x796bdc018d9a903acca191e6cae6bb300c662674
0x7d19173b97afb918f17860220ff59ca39243eb27
0xd47d945406da72e7775b989c6f4e665fbec45248
0x60b7817343f1f74a03b6c8ed043bd1d5e4ade760
0x44319e6e40e8a6300ceaa2d529e3ca6314c06560
0x5b79121ea6dc2395b8046ecdce14d66c2bf221b0
0xec74a773617cc2076db1cc772e2ebc33d7c4e607
0xe8ab8f6468b3ce78bcebf17c21a420643900e35f
0x852e3722484c0a00c333682ec96ce1cf17119a29
0x57e6571dbe66a3ca3f6dfd896aeec18e998e7a60
0x3244f96166ea03dd4ec25e4cee4d5237a539e331
0x7f2f6d4815ccfdc15361e6d9c8c1ff26141ba5a6
0xbf48693f454dc6e12385ba96a1ed4a56c189b662
0xccd7cb31b51da5abb7519afe5e7adb65fe9ffe7f
0x712f4d7dcebeda8c768d8dd9c3659e11dde4b3b3
0x7d20570cbb185efaeb6e92323ee015f30d566050
0xb230b535d2cf009bdc9d7579782de160b795d5e8
0x17b2717ecc7fbc1538cd268cca7b395541f4a2c7
0x7b6c44da6cc2fd19b4ba56fddfb9202661f7dafc
0x6ef210473e4a98ead9097f996e3f31d5417faa52
0xe62ad123fc2f4b07b961aa42498e8525a31aa4a3
0xf32db904d58cfa503b8c688952d5fd9af64b236e
0xc657ac882fb2d6ccf521801da39e910f8519508d
0xb3e2e3d6028a7f3c65fb65f99a0cc68bb554718e
0xae80f6f976f85a92bbd7637ecd920a8b45561450
0x9d00222c80896ba2da84999a8ab4b78be63b92ff
0xc637bb34a5fa5b8a7dca4710041f466d21b6a5bb
0x3916525a883a7541addb8f37b7be4f8e234c3668
0xb3e785e049ae159cf14e1e0f9b760e63e506c4c0
0x63f3d5e7b8a6fd2298f5bf3ed0b703c33ed72e9a
0xe44699f2cfed99b134ad72b2ade7935e50717f2d
0xaa41296be944072430708491915e9b7efeb3ed36
0xee64aa7c1273339fb12fcc603b889666ed0d1621
0xf95eb8ec63d6059ba62b0a8a7f843c7d92f41de2
0xd19cbc2dabede3db59960911198904f9f92a5164
0xa89fa59b419eedf66e749cbf7bf1f8450e9d1fa8
0x55569f83845395b7dcb870a3be4412d0f0018de4
0xe8d4d93d9728bd673b0197673a230f62255c7846
0xffe39a197e1e5e05ca077fe0eac402e25bd3844a
0xb78c853af8b33d82af1fb4bd97832e9d8b70bc1d
0x294c9f158fc24fb75f6b374bac078bd260c3a557
0xf5c369432debde189070681f30a896d7d74083a8
0x4decadbfb12e0d436d1284dbcb8005b4d0bf6fd3
0xf0e851c578252de531e2c28cd3ff1b324c1ba44f
0xaa4909c4e00de88ef364e78d2984879439f99cdc
0x1adcf8d5fdbdb3584dd632ad6a465d29fb66d15c
0x2b3f6b069f3a0ef3a523ee48713eafa86dba23dd
0x247dce0a5a21344c7971b0ec3881d03c7f1b9dc4
0xb207801d0fa6afe0c47e9d062adbe9894832df38
0x8c086e6bc71db57155843a5c74a4850ce26919c0
0x21dec6657c1fb56b33c6804ee4bb14dabf101327
0xf93edc3cbd5250170c947c2f7d132137e734a188
0xaad80983e702ee600a49c9fc668b7858389ed158
0x3b8910f378034fd6e103df958863e5c684072693
0xcb42fd46b38e96ea901e221c2aba60ee02f353a9
0xbc6eae424ae2438533f2e2f7baca9f262a7ecfc1
0xf18107285e9215d1e43089586e80d2649de0af43
0x9f11fd07251c70c336c8af70980ffb12a894a7cc
0xe62ef30c017335d80bae4f84a40eac2c29683ffb
0x9a8b6eb4c10dd038fc61c991272a0beb2261b52a
0x7e5ae81a39013100fc0084a684317c708ed4f30b
0x31d119fed7ec722f66fb9b2314d199cbde533717
0xa1ced8f318d4e409ba92d5ea30b2193575422484
0x0cf62563ca5bfe9d83dc11d8dc4614ec3f2393e3
0x3702ee7f61e17fc102709aa34228433c2a33ca8f
0x4cd798f54d333c3fdcafe6c0eb4e6a4852b9b5f8
0x5b797199c2eb515ffb903b04d012bfbb1105d946
0x957517dfb9f80b741905f7be7812203b2bbe02ea
0x9508232030c3e9f9a1dcf8afdbf0150e73226763
0x6a268391c1e76ab939bcbe9d0788f944e41c4ba3
0x7c09ff9b59baaebfd721cbda3676826aa6d7bae8
0xfdde8c03feba0d1de366ed7fc544c4b65f568e4f
0xaf968d74e79fd2ad24e366bff96e91f769e0aaea
0x8046b745fcad471334b70147bdd3c3d9cd910cb5
0x57144f872e84de007711ad8591f0124b40e1af6b
0x5b953dfd01bf281974b296191fcbaa25ed6dd05f
0x760657d5d4e1dbf9a741daa54b5eef718bd27a3e
0x7fbe0de6ffa86f4b9528aa27029595429b0c74a9
0xbe7700ce0d59153c5179e53e715597e67e0eb3d4
0x57ab560e10632aceb43c928002abca647749a681
0x6781a24ccc819941b7a4c9cc7b0dc32666e587e4
0xed5d35dc902c543b33496f6feae27b7866525b4f
0x4d742b068366e1d755fa89ad01bb54458f752486
0x84c2024a297fe4496fb8999c03798f33b326b36d
0x10a19e7ee7d7f8a52822f6817de8ea18204f2e4f
0x682338d8abc57f020363ff7b76cacf410e376c76
0x1f7f8da3eac80dbc0b4a49bc447a88585d8766c8
0xafb24fda74e781bdedfd19f2526a63833ea2bca7
0xe0c9ed4ecce6e6a3ff7df619f7c76344eded2ce3
0x85c1819fa435af88f339bd6018ac94af2e11a19e
0x1abfd881cb937e704bb1bf151d67bd97986c5af4
0xe2a7be7862c657b87587e9e59fca270b3ddb0a2d
0x25f55d2e577a937433686a01439e5ffdffe62218
0xe24e8beeba6219cd2f6fa25d5b04a0e78f19aa0a
0xff67d51683b93b390fd709a29f097cc900c0e16e
0xe749839f9d47b5ee50c2873b862e2ed986b31e23
0x8b6452644e1e47097fddc7627c33628706867dec
0x38c0795f230de10b969920ed58cb5eb91a15f189
0x93759be8ba2b84cc7ab52c8d21f91fef2d4e26da
0x1a9dad3e42c6852129351d1c71dfbcfbab6e25ad
0xa8866639a76f2a6748e11889456682d12013eea2
0x117c7c3835e7465926ae4ebc3f4e5a3c5afe108d
0x23dba8b0788e2b3e68f347dc3228619b577aeeb9
0xc1964ebd9814624e0fa4bd20bb314982ba26baf2
0xdb1c4bdf1595e4c06c7bf14e9b34566ef2b2f5e1
0x02d796c53cd946ec546113dd099d0c185f2ee223
0x8e7afee851c9e204a1ae6e2a8c7bf12b78ef799c
0x85e01c9e286a6b2bbc816cf862911572eaa34f04
0xb4de3f8ab9928ac3c18b4daa75194aa6383dcf1e
0x309358e5472b42924eb39910d0afc16173b7b4e0
0xe03786e6205ae8006d293a86a63944b9352c5de1
0x993cbf7210283fcef69d7f6f6cb6cec799361305
0x7c68c42de679ffb0f16216154c996c354cf1161b
0x777c9775ca53b8e4a61e4e8d17ae4570ed6eb230
0x6c3d1111d4995a4994d1120c0b7aa51ff4a51fc7
0xcd982808fcdb673830a985ee50905bc58bd772fc
0x75c9f481430d4afd9391c52b319a75b832fff0d7
0xeea2c1d6207d563e42cc573e72771e5dd1088f78
0x05a57a5d05b14cf3b98a57b5e324698af927800b
0x24c880348363dc9cc25245f4bdefd0151a245b24
0x2eba9e5fea32b4d070b6bb075d235746e2775c05
0x63ef775f15ba3adc1fdd91984edaeb4e5b0d59db
0x4fbe9f8f04247d874a83c39cb5321704575c217d
0x6de83d027747c2f52d64f5a68c83360b5ffca4af
0xd3c507dec5f9bccd250d8d98f7dcfe83c4c64475
0x0d49edd40b35142570459c367a56e1979f2c4cb9
0x3a4d11d08e36f28e809044d8b436d6586b6e39ee
0x763277b752e63eaf491aaae91d6254fbd19b1e55
0x7453c505929a876818e1ab38c5a2f70e68013935
0xbefb0078f5e8ec9685de4ffa14f3605ef44d2e6b
0x443d5fadea2fa4d21869383a34eed3cb2d223e75
0x60ddd94e0d5da6e9ddfce0c39dab1a1b7eb92474
0xf4a80929163c5179ca042e1b292f5efbbe3d89e6
0x2050cc4e48ec7cd8ad94561a3b2df1d187ab9e3d
0xda100e92739db8fb70a2634fb08ffa8a380d8a6a
0x00535dc54ea0bfdfbf3371ea8f59aedd80f241fc
0x89780b0b10b669d82efb020c07cf7f13838d2391
0x8afcf6938dae0439c68e2c4f533e3aad6e967e30
0xda2719cbcebca25c43024b9c526168f8ef049f39
0xc11d077069062ae0b2a3d9f8857d6374d2b0c701
0x1c6cc70d92f2793700abf39e6673b09774f5653f
0x2df30b11a57590f8839438bb46aae3392bf07279
0xf6269806d9f8cc48b87167a19dbcf0214026d22d
0x9d2bb8a40faa80b6ea2a05215961837cf91cf742
0x606f86a1ceb0df78a445695f1f6d150a025d4e55
0x555ed53c4806a47e40d10b1ff63a3ce604eaf950
0xe532529b8bec94ad9ceb35ece39aeaf78ca9ed73
0xc479ee7484a5f30a6fea6c47193dcf261245a817
0x3fc326c83dac2460318dfe4151832d39aff4eca5
0x356a2783c0a205e7be8f09a78e265c39ec44802d
0x9e3c890e01c170a44c1dd7f938b3390722104bf6
0x9b21e09d2daaa0c67f767c6d27ee48f8e538b531
0x677fd4ed8ae623f2f625deb2d64f2070e46ca1a1
0xdfb922a518939e369be746ba4a88d45a063185f4
0x18d91a12e246a0c938a2d247e28e9a0a07945bf0
0x7f2722741f997c63133e656a70ae5ae0614ad7f5
0xcccd4110482f23c4e032a68c3b3e51ca7be65f08
0x615657cd4a78c530f86e84c13d7504fc80a7496a
0x7bf660f3e287d2a05f46b72ae69a048f3781db90
0xb02e622f5d1620a2ca40c6d0d5ed3ff0419d25df
0x9655bfd8c0ae7ca128ad83a384d29565bfea9823
0x111d01d1894429ad69ffa3e0e13190bd3817f343
0xaec4db143753e63c97d1cdc4fd3bfdaad166c094
0xd3f4b92f7ceec671a74e5aeba85dc6e925ae097a
0xb439393ac19bd4dc4f777ff12e93aa295e935969
0x549f552eccbd6187598717fb196fd4b984341378
0xff54c5c8f32b2c8444b765c836172809108f0702
0xd29bb64673c42ae96f0008342ef9a71918b46d7e
0x4a49985b14bd0ce42c25efde5d8c379a48ab02f3
0x39654e8a0e0e166b93768beba6460e1255b210e1
0x4493287882f75dffcdb40fd41d38d6308fb8c181
0xb983afac0406e5931e813a186efc9ab0148ae02c
0x19f4e2214bdbedfb3d2a71ebc96b79bf7f7c69b9
0x03379f9c9e30b57c48c5d8fd00dd1e6ebe715f3e
0xb23ae28bbb906bcabbb8244d9a57386a55e1db00
0x9e1266a31773f1d37e235f5c5080954b98139935
0xc310237250c13443968c429053a2695b15e520d5
0xd14cc7bc7b012aca85a957b366c65818dc5e221f
0x0db737faac55c104e2cca99e982ce8658cabbcc8
0x0499b6ea6ace03955f58b85acb34aa23d1469569
0x655a9e6b044d6b62f393f9990ec3ea877e966e18
0x32e7831e1c530202aea6936fef715a47a25981d5
0x9dc5028949b42d7f0c64d832b89144b805559883
0x30080df30f21a710b31f5fc7fa149a5c452eabfa
0x518d57b87f89240a25e49c4be2cf057081549535
0x66257c9b5800930da0a5d9fad820c093aec486d8
0x24d7a9daf84a3f30b279b931a732f58c4eb0e52b
0x971b4533edbfcfe34e0f6ea053d33231a814fd96
0xeb03dc28e9768fb977951950beda30195db1cc97
0xde7a69f62a0746cf93bf97bca16038d05fb700e5
0x05e56e29e978febb4e4c3d233f034eadbda4ec45
0x3c6cb06deee5b1761e4915fb6b5492f4bd7d8e2a
0xc6f870caafe7a4ea0577301684720280200dd08c
0x06a8efbdbc57135271f1bd296453a8b7ffd62795
0xc38c5f97b34e175ffd35407fc91a937300e33860
0x1932494517f20eb03d652bfdcbabb42018337436
0x19aab7724c64099d4255ab4d25895d6ff82a922d
0x4356f373ea1f611938cfd8b9e8c0a607ab2b4d33
0x373bfd94d9ec6874dda9a916aa5032a2b8b35fe2
0x9e9d877fcb9dd628ec4a6634f2bc37d220317e3f
0x7f4f981fd89be0ef47e87ba5cdb4d02d812ca6c4
0x81fca4166928d49e903e05376ef40b3e7ec243ae
0xfc9428ae498288f212d0cfd4b7ebbf0bfbedb314
0x0dcac06b39eaf6e12295b0e6076da24585fdc3d3
0x9ce673172034701e65c68b4b17371581674ead46
0x68618dd70373475a815e4b7963a98b11bf4356e0
0x4c0223e26721afcc4501f40a27f1d9e2060cd975
0xb3f0ec6487ef33b22b831b4c1b3566047a800271
0xe94b5eec1fa96ceecbd33ef5baa8d00e4493f4f3
0x7f33beaa131a6896b97e27c505c532ce40f88f33
0xfad21a576d73feb67d20f6a302338f99c41acb6b
0x03434ce88793ca2b41b5ab46be4b55630e0a1f53
0x3b473f6fea391d718a9b72446f90b59e415d9baf
0x20678a8aaa215aa66a49a3400caefc1d7aa1ad7c
0x9bb8f845860b4a243fc4b2c42d3f6cb9dea5c34e
0xb5eb779ce300024edb3df9b6c007e312584f6f4f
0x3e8baa708c9731689d52625eb04ac0f1e6b9dc25
0xcbb3a343080e6914053fc22cf2eec31bbd0ebdaf
0xd09dd4f13c5583c8c6029ea2ae4dcdd49f690712
0xc9fef0515d141bb86a13f362e853d7cfabcf29a4
0x29f9630147fde874bc2ec24442f5a6285a5f6ef9
0x024c3771a70d2ee6480f84d768230c363591695b
0xa4c69fc9d85b6a3ffeeeb58c18ae6777a1960d0c
0x55b6922cab1715198bb7b76097d6a21362e8e0f9
0xc495d0fbcdf3dc51ac5c76492e3cbe908db761a1

Reasoning
I traced back the senders of all the airdrop addresses when they were the recipients for the first time, counted the airdrop addresses associated with the senders, kept the senders whose number of airdrop addresses was greater than 4 and less than 8, and retained the recipient addresses associated with them. More than 300 airdrop addresses

Methodology
https://www.footprint.network/chart/safe-user-allocation-reports-fp-29741

Safe Address
0x0fcC42c0789e301A1ea74514359a34602e736d04

**Comment by tschubotz** [comment]
> I traced back the senders of all the airdrop addresses when they were the recipients for the first time, counted the airdrop addresses associated with the senders, kept the senders whose number of airdrop addresses was greater than 4 and less than 8, and retained the recipient addresses associated with them. More than 300 airdrop addresses

This is incomprehensible and is missing info on why this is airdrop farming.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
