### ISSUE TITLE
0x2e173510024d480d195d8875e4d55e9b6198b654 is airdrop farmer

### ISSUE THREAD

**Issue by yebin-xu** [safe-global/safe-user-allocation-reports#149]
# Related Safe Addresses

0xbe401a46d21d92d4096e7c3302e59dfae5bb320a
0xd47c47aca9ea4d7f4c9c7e629a35b8a61815b1d0
0xd669ac924eb6812c48afa984b5effd776d035001
0xe0a0d0081ba638e2c95eb34f2bc949e70ea12ecb
0xe1c3d39e2377f20325f0fdf40b835c768e257c66
0xec65c02a9fb6bb8bb00067a7ee9116f8681945d4
0xed5ff7ad04caa9f69cbc20b6c82d00b4a3daf114
0xf5c26f655da871e6508b36e42c5d78925fb094c4
0xfadff26d4b95a59ff2fc227906ad619b5406e628
0x4f3a6729d0570f61e9b2f5c3277f6cb969183a76
0x607adf506deba187ca0233b410773d0dd583e1d4
0x6a79d177b8ab7e6cd84a4e36210be3e174a20fd1
0x7129f869845e854afa805170a6e42ce42a543b3d
0xb9e4f6b7cfc5f40e7ba40806e0be8726ecf034f0
0xba7dd58e6f294d6e26f22e267a62bb671ee2b297
0xcfe8a7eeefa2182a91a86db3c08ff6229899a50b
0xdd77394ecd4349c25ef3931d5f28e17dadf53d4c
0xdd9626cf3c52fa817816940b937a49b44b3dd674
0xe4a386d9f2bab2afb010cb7130798a634757b599
0xe73604fc1724a50cecbc1096d4229b81af117c94
0xe7f6194d899c8fa0960d685c07125ffaadba5d74
0xf20d27b75d08be30f350d207d5be391cbc20a9ef
0xf4517a782b77dfd62fb5ed7b31cbd78e34523b9b
0x0aa9d96eafcf74415c2d5a8b212546ef2d653932
0x16d956b6ece6d01ac681be3315e97c0b9f6ff0f7
0x2619cd2fb826455f5481040c125f0b8b5aabe1d5
0x797acce57a3d283175351c37b4436d3ae87f0490
0x81f1563ec197c2504c275ed683cf2b1483a26d5f
0x83af1cfbf94f792eeb36741c5372f6660a9be920
0xc242cbc2a919d18895ac19c907b8197148b2697b
0xc5053fbfee038d50bb0e444e2121fccecd722d89
0xc7d44814ce209c08acc59bc4cc597cb164062226
0xcd9b5f73cebf760e7113a71b5f47c4430f42aa28
0xd785d0e45ff76bb12400abfc6d9c84500f2ac02d
0xfb62b4f54c282a81356663fff3961495786a7059
0x002184c787c58638d41d7b6f35b38b2a967e5033
0x0725c16d7e811d03c8c2a64fbbaa579233c10db1
0x0d655471115590137ce3986a111cc5db1c2714ea
0x167460e04fa7f08ab2470dddede0d57c4d5f0883
0x1db4597389199f8851b53ed48ae90bf451c564fe
0x355ec66487dffe146c77ae523c72765a6522161f
0x3bb14861d62021c675a8631386dbbf07f6a15fe5
0x3f7393618972a9d8c74075eb426820948510f2bd
0x4109a530ef9343e2ef776866af5ba579e41a19ce
0x42ced56c69fb9b497ce46d1565d067e47d45194b
0x459c7f5562787b665da29a59f6ad5821594872fc
0x547bc8f6c144d6d833c8a749c90a0fc34cbc50ee
0x56f16a40a00c016bd71bb3144c0cd9932fa9d847
0x6015112ddd3f2eacac088a9393c2cd85d6bca8a9
0x63bff26aee9db95f67676b1b2c1c0fdc841db58f
0x65aaec82f8558667cedb2862232a6772d3e93759
0x7445c64684ba17aaf03b17fc39b208ee67c47eb3
0x74c61ec16d980ac775d306444cedb4414a170370
0x8184d7d86cad5db73722f8f4483187c3f61b4b1b
0x81c89274dc7c9bace082d2ca00697d2d2857d2ee
0x8d8d0d74136ae888aa23eb81f9f0d95cf9d6b8dd
0x9482fa358097193ed699927ca0b1991e90ee4e7e
0x9669de5aa6f9a0ed5a757896fe8840fd7e85c8b5
0x98f55c7665b7d06293518e087de88940417c9699
0x997d8977427e9a691b1535a148190f71faadc7e4
0x9bd926383a3514a1a5b379fc3fa8212fb39ad6ed
0x9eacdeeb7699e997aeecd3974884b4e3f3edbf61
0xa0a20191cbea6826fcebce55ac73c72580c780ef
0xb0c6fec41336d934c7d0deaa749203a39a1dd73f
0xb93192c5584214dd60912d7fd167ae841903220a
0xb93bf9fd0890709d86f319eb5354f520329db2e1
0xb97e64aee69137d3ada7a2a14d9850645fae5387
0xbd44c4198bab1b0ddaee8899e9daecd03292a434
0xbfa03feeb4889f360f61464dab315c1a159289af
0xc40c0d2abfe61ed024e0df709063a52e504d7922
0xd25d24641213d52377fbf7a82990c7d7bc3688ef
0xd2c419057cd372a85b9bba4a363303253de6ff57
0xec3f72253094cbd1ff767dcfc0fbe9ee9e5831ae
0xee79a3bfbeb70c367aba17d26528d231fcefe7ae
0xf002d288087d9b0deeb9185e131a1e77dbdf28f6
0xf0d142931630f7fe354aadf2029a36b58b263842
0xf17965920a9e676fcba7b234605629b5b5727bd1
0xfcb2b2e0bf8b5c034fc68b06d4c9f867c3e76922
0xfed27588535eea65b4254946a717052d5661d5b3
0x024db5796c3caab34e9c0995a1df17a91eeca6cc
0x026617a003616c8f4a660db526ac068c7bd12490
0x0394626f556f772d67c928bb42760c091ff60804
0x04699ff48cc6531727a12344c30f3ed1062ff3ad
0x068183e2057651a1c124c994489236447f9a5030
0x077b3b2dd6c0a0004d1ea775d8983bd2e4cbbb67
0x0c4bbfaa02b14924554715145f83560843e249b9
0x105fa0964f28978e9796b0e17f6f086070a2e2aa
0x1634cb63743c7e360ef6ef367c5b0c3735f564b6
0x17ca9ff2122d98be579904be062af75ad4b0ab57
0x184c6cd5b7482bf53fd9952df1b6c55146d00d16
0x1a17d6f6c0676c2a8986f80be81fff6f4774faef
0x1bf43eb884a0624989f99ed4ac3f1a2bde0152f5
0x1c60b58c72933a9263c928b1d2cd6d2a0188364b
0x1cc2670592a99716e3ae3e6d8132e8b2f924d457
0x1da1042ff6e08a7d75f79abfd1abb46416d54ce2
0x222553e6215115ecfa5392aa915991296b21a8ce
0x2661a8d2a2de9bb48d0aa8c41ad0b7fd9ea04035
0x2755db2e6cf295957fee39eaef1d07852c4c158b
0x282a610b988ca1c9d1be7df02288d63a73f4f124
0x2db377add47f5d1a321a634d5d10e0524cd939ba
0x2f1098c021b96e740f291c2d9d7a9562b2f7539a
0x2f5d0d3a2e4f46083433849a4bf39ac668a2771e
0x328cfd33cf2fc206857738a8bd602cdaab10301e
0x36591116468a74eb8941d46eaec3f4355f102ee3
0x370a076b5b6a10a8355127db728911ed1d99e531
0x37ddd7d2183995e32accacafd24a375110b19f41
0x39601a36170db174774d83d0e8fa8de9e9b6993b
0x3a468dcfbd8b3636372e87c981568d8d3fc76741
0x3c7a1158d85b264cc8cdc715a6fe8d408b5f6129
0x3d184438246ab153fcd5bac2b29680789de35035
0x3eb57ee5885ec7af5677012864f9c8dd1a0972c3
0x40d82b56a4c9fd0a9a650b94c8d0aa8bb120de2c
0x4285ec840f446cb64bfe4e14532512d7c1c68995
0x43a734e3b6db49e20362f2a1ebb76df436a9b0f4
0x43e186b7af9a152f11392c82b3b57a79161f9168
0x43f3752578d9f38677f6138a23960b49c7991703
0x44f5ee112730ce2fffc12d3116eb6c8a1dc1280d
0x4721bee9248389393460344ff03f218aee44a05c
0x483f081bb0c25a5b216d1a4bd9ce0196092a0575
0x4ac1432c02fa477e814a305e69fd975c39c9517f
0x4ce34a79ad190f2e1546b14a70c0fe84bb947792
0x4e748d6b60cd5c83859acf63189669bc83044fa6
0x4f1e062427302410a84a48c45c07834cb9960359
0x50acfc5d2f32cb2acebca468a46e5331c6c696b8
0x51217e4769dfd61a42f8a509d4dccc5683bfcb21
0x51f56e82fc411a78d7d348c707e0de6d0c65cf44
0x55d633df856809c035d1c8fb17462d657ad08a0c
0x575d09e5149f778178da52edebe06d326def24da
0x5c60b16246018638ad230db8343e69aa36793e68
0x64fefc0f6881806ce38f191eb608c717080d932b
0x69107e1aea247566313e2cab4f46d27a3fdc54e5
0x6bd4141af55314cd3f4c81272033b0e025783cc0
0x6c0c324354f26f43ec15c5d2c91f207a18524c1d
0x6c76e2d26ac3010dbe081481698724030aedbe0b
0x7366346810e6760d56c94b844e43e0e319c9ae42
0x7496da28605a040799383b49bbfc93ef0cd580ab
0x79d39b54b664d8af7ef3a685d855db71685d62aa
0x79ed01e900835a657d974f3d0bf99ca3521fe2bb
0x7baeebbd7fd1f41f3da69a08f8e053c8ccbb592b
0x7f2baf8c5db610e6120c6d7be6fd5ed930dc3308
0x89534fa6c72d10dee8a999fab4139e7911f5ea19
0x8e997c4b4f89514ea146d937c9ec89449f270195
0x96ac86684b0657da25ebc55bdb075a0acee1ce94
0x9e21fa74b59f3c3c9250f237b1e039509e0711ab
0x9f6297e7341a1be2474d6fe01779297276463b37
0xa085278322b6e576493fa12a01d0422d987b88e9
0xa232ec1090723b860cbed25480214c9e4607f002
0xa48358d4c0ad126276aa7ba19ccf1eca881a8b79
0xa5821acf51177f8b827709e4863154fb59d6ea6a
0xa5a5506882cdcddd85e1102a18c6057af35bf0ea
0xa8c03018c35383d9a8dbe21f08a617ce67b19341
0xaa4bde8bc545d4730e5e61aa8516fa8e525e9fe4
0xacd4fa35b83e832d400e401b1e87bf68fdead97e
0xaeb53bd66935133b2c4a32241d663f60af8ef5c6
0xb1339aa0b62a49ceb555a54af358fd1f31ed6814
0xb40c8f06f285c5131839bad685dfbf0ead3f57b0
0xb5099ee9a42a7add0afe389bfbcd6c40c5a147c4
0xb7bba2ac0b2c27f8355bf9d8696e05573bca945e
0xbad6fcb58ade50d0fac679b99193a00c452b3f5c
0xbd40d7e895b87b8ff6a3f3203256a8e2003b79f2
0xc019415c47b861ea81f4240ca8667d0a8ca382cf
0xcb5026995eb2e85683e51a3293d264fa5f07dd81
0xd03d4adab29a4323ab0e04d5041324d2fae9fdfb
0xd1128b16691bafafc5d626210a22c8b329ba710e
0xd458144ff2dde7da45bb8a7e67971a44dada0ab7
0xdeaddd02b449bc6b3b253ccb08da83ca5c443326
0xe5764b7479544029ebe238b0f9074e450fa6ded1
0xe6ad3d014324fe724d961840a3dec1326d9d40f2
0xeca54b5cf597c261e2a4ac3dc4413a0a054ec583
0xf8a9e585e91a26b71a84163ad1633f59e57d74e7

There are 170 addresses in total

# Reasoning
0x2e173510024d480d195d8875e4d55e9b6198b654 created a large number of wallets.
All addresses behaviors are basically the same.

# Methodology

[https://etherscan.io/address/0x2e173510024d480d195d8875e4d55e9b6198b654?method=0x519de1ae](https://etherscan.io/address/0x2e173510024d480d195d8875e4d55e9b6198b654?method=0x519de1ae)
All addresses created by it can be queried
[https://etherscan.io/tx/0x19a742e57f38b1d0584f688253dcd1bfb5a1c5456bf95a93d1a75f1f1d4c7248#eventlog](https://etherscan.io/tx/0x19a742e57f38b1d0584f688253dcd1bfb5a1c5456bf95a93d1a75f1f1d4c7248#eventlog)
For more details, you can see the eventlog

[https://etherscan.io/address/0xbe401a46d21d92d4096e7c3302e59dfae5bb320a#tokentxns](https://etherscan.io/address/0xbe401a46d21d92d4096e7c3302e59dfae5bb320a#tokentxns)
[https://etherscan.io/address/0xd47c47aca9ea4d7f4c9c7e629a35b8a61815b1d0#tokentxns](https://etherscan.io/address/0xd47c47aca9ea4d7f4c9c7e629a35b8a61815b1d0#tokentxns)
Behavior query of addresses

# Safe Address
eth:0x8D36B3f5808b99bB51FAC2AD1D3721da3f87b767

**Comment by yebin-xu** [comment]
Trouble helped me reopen, did not know that the original can be directly modified, originally wanted to submit a new issue

**Comment by tschubotz** [comment]
> # Reasoning
> 0x2e173510024d480d195d8875e4d55e9b6198b654 created a large number of wallets. All addresses behaviors are basically the same.

Could you please elaborate on "All addresses behaviors are basically the same.". What are they doing, when, etc. - a valid report needs more context.

**Comment by yebin-xu** [comment]
> > # Reasoning
> > 0x2e173510024d480d195d8875e4d55e9b6198b654 created a large number of wallets. All addresses behaviors are basically the same.
> 
> Could you please elaborate on "All addresses behaviors are basically the same.". What are they doing, when, etc. - a valid report needs more context.

All addresses were created by 0x2e173510024d480d195d8875e4d55e9b6198b654 in April 2020.

They were all transferred once in April 2020 and a second time in September 2020, only these two times, and have not been used since then.

All records are Pointing to this is someone doing some kind of IXO with DXdao's Mesa tool in 2020, and he used 170 addresses in this incident. 

After the completion of the IXO in September 2020, all these addresses created by him were not used again.

Although this is not typical airdrop hunting, I think this is the type of airdrop that should be cancelled.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
