### ISSUE TITLE
0xdf21b894a490cbdf49d9de7b9d780b79f7cb0ac7

### ISSUE THREAD

**Issue by hunter11232** [safe-global/safe-user-allocation-reports#15]
# Related Safe Addresses

Example List:
```
0xc832736fbf1f5db6a0e68c04d8a5c71c5a8d0ef0
0xae95671d94e519b6f0ad65bffd01a89fdc9318d7
0x8a2040510ac1c60d67e98f2fc6a18ff36dc962b8
0xca9cbbf15e2b8e08a684bb1a9e3f70ccce2c5d79
0x014d30c054f29e517bcf4080bac7609892a7e9cf
0x68253883acc8f0936eb9d6a2a796a9caf15d04a4
0xede6df3aee8c7c5fdb39f7e0d4dea7b12b5e2a25
0x7a5603e33f44f18954dd448bc507c0bd731d18af
0x2045f080c8fa63717823f3e3cc49e4ac389e1a38
0x00ce1d63c836e65a27517787f35d97e63b503642
0x55613b55e6e5a2305861009f6f4b9ba5ef0a842b
0x8699a98830062434bfb666125c01160e6362f2c9
0x4d96aaf3ae25779bba98d620302a2d45921a11f2
0x1d4b47507816c148dcfba53327b67a769589dc69
0x2a8cebb42a1b5d650f322209e982847f997c14cd
0x0dd656aacfbf61839a9a21f177fee93dc0146a8b
0x0b1f210669d8d356c9e668dfb2819567f4637b76
0x9d3d4b884693b125ebf1e0dfc9cd4670f7225cd1
0x7f4cabf12341bb1b7af00015c43d3d4d51209124
0xfb4fb239a2953a799786f43955cde5a2c9e7e381
0x30e439e8348fdc0f032574ffff9abe9b7797c120
0x8f63b659a5d0b88a591f6bc202316a0f24a10b7a
0x29d71c73b99cf42eae14b2a0934ac09c68b2a5f7
0xe23a1e679ed7fe2a3e3d1c71fec96d0424505551
0xa3169054f6bb4570a9abe0d3303a2aad79b5c692
0x507c80603d80a95efe9809a9abb9907d39f2d593
0x929c7af2c8583351828be4713761d12724a159e7
0xbdab7bd127d9e259a2930144ab582621bb3e0bf2
0x25decf57589ef137f843ca3bd13388af5d5b15e3
0x1003046735059d97a0de32fc1b059df819221b48
0xf44d57b421b6edc7ea0eb672273eee3236c0bc54

```
Full List
"https://etherscan.io/txs?a=0xdf21b894a490cbdf49d9de7b9d780b79f7cb0ac7&p=8"
-->

# Reasoning
<--Each safe is almost unused but all created with the same address.[0xdf21b894a490cbdf49d9de7b9d780b79f7cb0ac7](https://etherscan.io/address/0xdf21b894a490cbdf49d9de7b9d780b79f7cb0ac7)
Safes are created with high frequency
-->
# Methodology

# MY Safe Address

<--
0xd052e46724C64e554F21C7d256A639d171692494
-->

**Comment by hunter11232** [comment]
[Full List.csv](https://github.com/safe-global/safe-user-allocation-reports/files/9528004/Full.List.csv)
Here is a more comprehensive list.

**Comment by hunter11232** [comment]
The safe has been created continuously by this address.

**Comment by tschubotz** [comment]
Just creating a number of Safes with the same account is not airdrop farmingf per se - could you please elaborate on how you get to the conclusion that it's in fact airdrop farming?



> Each safe is almost unused

I just checked the first address, there are a number of txs, hence "almost unused" is not really true. 
(https://gnosis-safe.io/app/eth:0xC832736fbf1f5dB6a0e68C04d8A5C71C5A8D0Ef0/transactions/history)

**Comment by wjw12** [comment]
https://github.com/safe-global/safe-user-allocation-reports/issues/301 this is the answer to 0xdf21
it's operated by 3rd party relayer service

**Comment by PulsarNetwork** [comment]
Ultimate answer. Must see https://github.com/safe-global/safe-user-allocation-reports/issues/365

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
