### ISSUE TITLE
witch address

### ISSUE THREAD

**Issue by xiangdaye** [safe-global/safe-user-allocation-reports#161]
# Related Safe Addresses

0x798d328407055649acd4360201912e375413e999
0x05c81b8886a8f7c7efbac200d9effd8d7921200b
0xa4a5971ab41cd5af29d11849ab2a376c90f65441
0x59c97465be5b3c3fe1032ce30dd74404564d20dd
0x9d9d9ea1d9422375c6696c953cfba966e6c6c3a0
0xf0833df8eab2f7c4fd1f2d36831364103e844197
0xdd0a87380f8cd911e4ce2dfa82d8c983b002163d
0x8948837501562c53648a82fc5461942189bc65de
0x556f7b2318ec0060c8adc81982838e1a2e10315c
0xd58ac7c455fa89a64bdb271b1237f9d083f639cc
0x6c1cb30ad73f628fb5d0e99a94648a5802f6b51d
0x33d1f73fd14c73f064e4eb0217d7b56b2e0aef8c
0x7fddbf26e0d413f4b18cc8ecd8cb6cb1830f195b
0x069e1ea1c27d09c569cb8b24c7035fdefeed8e73
0x381033fd735a7b7b25d7c75674913e9a7259de4f
0x261c4a747ead7372a314567ed78c9ef7b9b5f5b9
0x014145161be0a3b0fb9000803d1bdddabe532d0e
0x4837044eb492842d6a504475bcf6bd014fb16fb0
# Reasoning
  All the above addresses are transferred from 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D to eth, which is obviously witch

# Methodology

https://etherscan.io/tx/0x0bda5a5272520cbd9761b7d1ac95e4d4fc516ba3668ce2e4c224feb42706bbcb
https://etherscan.io/tx/0xe762691cd6a72c47a69b7d4f5c25281ba22796642e57871c0683a8f736a4e53a
https://etherscan.io/tx/0x9b6b52fa18aa5c0bab842ac710e9c2effee02831ebb121afb239d158fa1e25bd
https://etherscan.io/tx/0x17f7ce028f3f7eac0ceca1bba386ded9309060fb306ef5f0a74ed66b32083e08
https://etherscan.io/tx/0x17f7ce028f3f7eac0ceca1bba386ded9309060fb306ef5f0a74ed66b32083e08

# Safe Address

0x188950d274A7C23Ec2e180Aa0E5cf92997B69D70

**Comment by xiangdaye** [comment]
>

**Comment by xiangdaye** [comment]
> # Related Safe Addresses
> 0x798d328407055649acd4360201912e375413e999 0x05c81b8886a8f7c7efbac200d9effd8d7921200b 0xa4a5971ab41cd5af29d11849ab2a376c90f65441 0x59c97465be5b3c3fe1032ce30dd74404564d20dd 0x9d9d9ea1d9422375c6696c953cfba966e6c6c3a0 0xf0833df8eab2f7c4fd1f2d36831364103e844197 0xdd0a87380f8cd911e4ce2dfa82d8c983b002163d 0x8948837501562c53648a82fc5461942189bc65de 0x556f7b2318ec0060c8adc81982838e1a2e10315c 0xd58ac7c455fa89a64bdb271b1237f9d083f639cc 0x6c1cb30ad73f628fb5d0e99a94648a5802f6b51d 0x33d1f73fd14c73f064e4eb0217d7b56b2e0aef8c 0x7fddbf26e0d413f4b18cc8ecd8cb6cb1830f195b 0x069e1ea1c27d09c569cb8b24c7035fdefeed8e73 0x381033fd735a7b7b25d7c75674913e9a7259de4f 0x261c4a747ead7372a314567ed78c9ef7b9b5f5b9 0x014145161be0a3b0fb9000803d1bdddabe532d0e 0x4837044eb492842d6a504475bcf6bd014fb16fb0
> 
> # Reasoning
> All the above addresses are transferred from 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D to eth, which is obviously witch
> 
> # Methodology
> https://etherscan.io/tx/0x0bda5a5272520cbd9761b7d1ac95e4d4fc516ba3668ce2e4c224feb42706bbcb https://etherscan.io/tx/0xe762691cd6a72c47a69b7d4f5c25281ba22796642e57871c0683a8f736a4e53a https://etherscan.io/tx/0x9b6b52fa18aa5c0bab842ac710e9c2effee02831ebb121afb239d158fa1e25bd 
> 
> # Safe Address
> 0x188950d274A7C23Ec2e180Aa0E5cf92997B69D70

**Comment by tschubotz** [comment]
> All the above addresses are transferred from 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D to eth, which is obviously witch

Please elaborate on how transferring ETH from 1 account to many Safes is airdrop farming per se.

**Comment by xiangdaye** [comment]
> > All the above addresses are transferred from 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D to eth, which is obviously witch
> 
> Please elaborate on how transferring ETH from 1 account to many Safes is airdrop farming per se.

0x569770F5EFe8fB017FB09B6dE3B2d096668377D is a personal address. The first transaction of the above safe deposit box address is the eth transferred from 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D. Without the eth safe address transferred to this first transaction, no other on-chain behavior can be generated. This operation shows that the above safe deposit box address belongs to The same user, this is obvious witch behavior, real users will not appear such operations.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
