### ISSUE TITLE
12 related safe address

### ISSUE THREAD

**Issue by Finelorrew** [safe-global/safe-user-allocation-reports#164]
# Related Safe Addresses

0xff0b18e0f382e980e89177270660dc7db08491b2	
0xfedd7ac9b951881108d143cde3abb7cc92c44a56	
0x792f7dc2207760684c58d32ff12d5e65392043b6	
0x7922ADe2c7CC12aDEFe2465897dDbF2567325901	
0x7923F36d69498eB79e7885331609f1d8DE1B796C 	
0x7925f42f5b436fc58b6050ad1f6393d8146f27bd	
0x792f7dc2207760684c58d32ff12d5e65392043b6	
0x79310388bf1b64364dbf4e269241cfd6902f6665	
0x7934a5e0cad469c97a2d5fec349cad68d774fad4	
0x7937e7b0f7d3cf3d66ffbe2d08c2b057e4872a6e	
0x79401f7dd947321dae6c6bbdbb61b7e11354b8e0	
0x7941dde74ab51ab91e1cb8665fe42c6d93bcf052	

# Reasoning

These 12 rewarded Safe Wallets are all created by the wallet 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D.For these Safe Wallets, the creator only executed one transaction for add/remove owners, which means it's a very potential airdrop hunter.Check its Safe Wallets' transactions which are all add/remove owners, without other txs.
# Methodology

Check the Safe Wallets of which reward is less than 300 $SAFE.The Less reward is, the less cost for hunters take.Check its Safe Wallets' transactions which are all add/remove owners, without other txs.

# Safe Address
eth:0x9b2Fb6224bBB0492bEa27dd9A7130363C5B8840A

**Comment by Finelorrew** [comment]
safe wallets above are created and added/removed owners by  relayers.   but these safe wallets have no other transactions or no zero balance.   In other words, users just create the safe wallets, but don't use them.   Just a wallet creator but not a wallet user.   Maybe the airdrop condition for at least 1 tx for every safe wallet is not proper.   You can fix it from at least 1 tx to at least 2 txs

**Comment by tschubotz** [comment]
> For these Safe Wallets, the creator only executed one transaction for add/remove owners

https://gnosis-safe.io/app/eth:0x7934a5e0cad469c97a2d5fec349cad68d774fad4/transactions/history has quite some txs which looks like legitimate use to me. 

Closing this since there is a non-zero chance that we would eliminate a legitimate user. 

Please elaborate and add more context in case you still believe this is airdrop farming. Your methodology section is not very informative.
