### ISSUE TITLE
Report two groups of 21 addresses

### ISSUE THREAD

**Issue by deshawelafi** [safe-global/safe-user-allocation-reports#167]
# Related Safe Addresses

GROUP1
```
0xd3a322271abccee412ba29bb8a66ac7c8057f785
0x2bd7f702e9c3c5c42d731af95c853405c4ac6d90
0x87c80f22c352038f230ebc9c2b702339d5e11574
0x79dbaeeefc1fe84c51f33eb1e5299ac95ff19804
0xe68bd81411c349318dad4f345b2838f95a896a5f
0xfa12cb208cd411f7e09abef3ca4633898e4c2c76
0x3de64ce6efc6c113ae5941b1fbcd034f800d2928
0xfc4b23012c30a71df5d348ff3c42dd01b6490477
0xbb981411754958d3471a0f22ae8eb96417220735
0x0b7c888c15ff7074c13265af28e46846d7d9e153
```

GROUP2
```
0x72e7d2d761f4c1a1aa6e20ccfe4ad6dedd8bf83e
0xb7405a88e4fa6094d5585a6bcb91a36e93ed981c
0x892ef110a8d9fbf703af867fdf78d7373281f44d
0x681e9c9e75269e52f8959a38e5d744b96c628b8a
0x85ce68b05991183c9eb65620525243387a8a2fef
0x88ed8b7896a2612871c1bc1f03c6397415bb8422
0x6599ea9ba62307f8f0c69f4184edce9a01fa9ca0
0x1019ddb1cf3685b315a295e9001c37b28f0a50f4
0xa5572938a2bc7a2ce998d47683411081e05eab8a
0x3a501ef8cb6e74965e08c1e54dd907b4d62eb7e6
0xaf8623a512fc1a74056e868ecf76d8a279d48321
```

# Reasoning

All 10 safes of Group1 are created by 0x28829cdb803c41cb8a7858455b4ffc70b5dfacf4.
After setup, each safe deposit box receives (0-10) USDC via two transfers and makes one transfer (0-10) USDC. (Except for this address 0xD3A322271ABccEE412Ba29bB8a66AC7c8057F785, which has six transfer USDC)
All transfers are made at (Jul-30-2022 07:28:39 AM +UTC-Jul-31-2022 12:49:06 AM +UTC)

All 11 safes in Group2 are created by 0x30468c50a0e77a6f1a612adb39949cd6c06b4263.
After setup was complete, the first 9 safes passed receiving 0.111 ETH, which is hard to imagine why it would be the same amount if it wasn't for airdrop hunters, and the transfers all happened within 15 minutes (Jan-10-2022 11:21:52 AM +UTC) - (Jan-10-2022 11:36:47 AM +UTC)
And after that, most of the safes in the period performed the same operation again within forty minutes ' ENS Resolver Set' on (Aug-02-2022 05:51:59 PM +UTC)-(Aug-02-2022 06:31:39 PM +UTC)

# Methodology

List of addresses via airdrop
https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv
Compare with the creation address and the safe-drop address of the created safe-drop, extract the duplicate created addresses, and perform manual analysis whether the behavior of each safe-drop address has a certain meaning or suspected airdrop hunters.

# Safe Address

0x4B605c1ac2Fd74b5d6B619940B6fF9fe1C4ca83a

**Comment by deshawelafi** [comment]
Tool:
https://sdk.flipsidecrypto.xyz/shroomdk was used to get the address to create the safe

SQL_QUERY = """
    SELECT 
         TX_FROM_ADDRESS,EVENT_INPUTS['proxy']
    FROM ethereum.events_emitted 
    WHERE
    tx_to_address = '0xa6b71e26c5e0845f74c812102ca7114b6a896ab2'
    ORDER BY block_timestamp asc
    LIMIT 100000
"""

**Comment by tschubotz** [comment]
Your provided address for potential rewards is not a Safe: 0x8A53e15783D003F93ED1dD376EA157b8E304d35A

Please provide a valid Safe address.

**Comment by deshawelafi** [comment]
> Your provided address for potential rewards is not a Safe: 0x8A53e15783D003F93ED1dD376EA157b8E304d35A
> 
> Please provide a valid Safe address.

I mistakenly thought I had provided a Safe address. Thanks.

The current address is correct:0x4B605c1ac2Fd74b5d6B619940B6fF9fe1C4ca83a.

**Comment by tschubotz** [comment]
Regarding group 1: No further questions.

Regarding group 2:
I can't follow your reasoning for the following Safes since they seems to be receiving ETH which could still be legitimate usage. 
- https://gnosis-safe.io/app/eth:0x72e7d2d761f4c1a1aa6e20ccfe4ad6dedd8bf83e/transactions/history
- https://gnosis-safe.io/app/eth:0x892ef110a8d9fbf703af867fdf78d7373281f44d/transactions/history
- https://gnosis-safe.io/app/eth:0x85ce68b05991183c9eb65620525243387a8a2fef/transactions/history
- https://gnosis-safe.io/app/eth:0x6599ea9ba62307f8f0c69f4184edce9a01fa9ca0/transactions/history

Either way, thanks for the report. We've identified the following to be related to airdrop farming.

```
0xd3a322271abccee412ba29bb8a66ac7c8057f785
0x2bd7f702e9c3c5c42d731af95c853405c4ac6d90
0x87c80f22c352038f230ebc9c2b702339d5e11574
0x79dbaeeefc1fe84c51f33eb1e5299ac95ff19804
0xe68bd81411c349318dad4f345b2838f95a896a5f
0xfa12cb208cd411f7e09abef3ca4633898e4c2c76
0x3de64ce6efc6c113ae5941b1fbcd034f800d2928
0xfc4b23012c30a71df5d348ff3c42dd01b6490477
0xbb981411754958d3471a0f22ae8eb96417220735
0x0b7c888c15ff7074c13265af28e46846d7d9e153
0xb7405a88e4fa6094d5585a6bcb91a36e93ed981c
0x681e9c9e75269e52f8959a38e5d744b96c628b8a
0x88ed8b7896a2612871c1bc1f03c6397415bb8422
0x1019ddb1cf3685b315a295e9001c37b28f0a50f4
0xa5572938a2bc7a2ce998d47683411081e05eab8a
0x3a501ef8cb6e74965e08c1e54dd907b4d62eb7e6
0xaf8623a512fc1a74056e868ecf76d8a279d48321
```
