### ISSUE TITLE
0xef0ca09fbf9a5f61e657fb208b46b8685c1d4766 is airdrop farmer

### ISSUE THREAD

**Issue by yebin-xu** [safe-global/safe-user-allocation-reports#168]
# Related Safe Addresses

0x43dbb0f15116b047257346e07afb4a92fd457c4f
0xc3acd297f377730870d543f525a47fecf61978cb
0xec0d26615b64d1688485dd497065857eb4ff85ca
0x049c31b1d55361f51fb422d6cedb2936a28cae28
0xe72e36fc95a09a18c42fa7a3d14bb9b8d26a36df
0xededc2eaecd6b45816924e39150dc883c60abe8f
0x9905b105edac9aaf1d8c2cf03c4bf76bdee8b330
0x48bde6abda3bc38abdc42bf9eec644b1ce93f83a
0x42aeb9519ef07b006218d5dbdae31f25615aa845
0xd023fe05e0f1fe4faccfa78c4ba48ba774b37422
0x8be2011f0a4391874d04a46275f23a480a1fd355
0x5f605d76024692c784b37b98f78972cc6b1b8fb3
0xd5ba7b3979280d0d8a02482d06a8f210f45b13ea
0xc6e2c94432db035be431a8f294b13e2e56555872
0x7d2d7786c15ad31bf5629441eeb965f53a07585a
0x6ed18db6b532115d51eda309420cb2f57983748b
0x75fd5bb3f742b1f9f6caca49dc68f398bde447f0
0x2beed9f414b46fa9268ab6046f8d6745e03a94e2
0xc6062f7cd4f3d4858a2f813b5d2520e76824860a
0x98c7e8edf567c477f71dfd5aaeaf5f8283394824
0x493026427aedb612070d442dd0bdd2cc7e25fe83
0x88d1631481aaa44d88e40145a36a4e0f39281bcc
0x816e75b63a44b02ce1b6ecfc944d09e5a6da7961
0x6e88b0037f67a6d2a71086e934cddd98c8e6d8dd
0xddc07b251564496b9b09faa8f8fb770a97ec4912
0xcb277109833cc5e2df60625c8074549a650b48ee
0x1374d542c6c377784540f195aa4955fb5d1cc079
0xa50ce39dd5b1794d72b00f28a4771ba087258256
0xc030cbadcb3933bc64d59f893eeb8990c96a7677
0xc7b50c03f2e91bf8f5d1a83a3d7a5f471d6b4229
0x517cf87d92b8dcf07a6572d98be1d014b1d510ce
0x345d5b6d029b623b44a214f134a81d21f059d4f1
0x08b5e73f04a25b8cae2995816e7a5cc799dbfa35
0x3ec343b6f205fef63a6b8d93fc0f7c18a940e377
0x340b60dbadb37786e4821a0d3f3bcef7005f0427
0x6c2168ecd3c21012caf7adc5c05946330d3b28ab
0xa421e74a7ebc8f3354b7352ba7841084b701e85f
0x68ed461b3483b9e7e14ab638e98ab2aaf15fc335
0xbdc352c1d77dd87bf2422d61453e6d5d102234e2
0xd53d21dbffbaa3805a5ed30806f525727b1cae75
0xb1f4a373d824f975c54318bd37726dbe0b44df4c
0x4f82daa23cd82340ba642395fa1f57d14c1f1cee
0xdc2b2e2576f04ba20b796258d4a92b56c5cca520
0x745122e5caae7462bc4126bc6f5a5f6fb87ca13e
0xa13a7adad77bc5432ecef3a0c4bba66d7cb6f952
0x08b9d3d054dc8b67555dae43d0e0e55eda921ca4
0xd7c281109e3b6f018cc30b31b9803e8f8ce63b96
0x3dbde37b080ee89e6312c16027c79a29c7dbb8c8
0x08c841202d77513d0865fbae847cbc2e1dde3912
0x413d944592a53e905f0cc10bf75b60ac20e9927e
0x4b449f2bbcea5b9ae06267fda6e748c3acb73339
0x40975a04b5f85c4382e6670e4b39f2487302e090
0x0041fa622ccdb77e720ddcfb21e5c11e43957c95
0xc7a8be637253ebf6537a35316c24dd71aa9fd919
0xdf112ee28fc729a20cec56b85af609ad9c11cb5a
0x6fc175413a669657a22edd21047e5ed6e1b60c2f
0x840f98f0d52de277a12ad148aa5285c3aa904900
0xc5b7b8efa2a64e47cdcfe7775baea1f9dca01438
0xed90b02c26c727a9e5d8dfbc6c6d005bae228dc8
0x4a5c730f0d6f90256590b85582a9ee70fcef0e15

There are 60 addresses in total

# Reasoning
0xef0ca09fbf9a5f61e657fb208b46b8685c1d4766 created a large number of wallets.
All addresses behaviors are basically the same.

# Methodology

[https://etherscan.io/txs?method=0x519de1ae&address=0xef0ca09fbf9a5f61e657fb208b46b8685c1d4766](https://etherscan.io/txs?method=0x519de1ae&address=0xef0ca09fbf9a5f61e657fb208b46b8685c1d4766)
All addresses created by it can be queried
[https://etherscan.io/tx/0x1dc9cb99be66d11d540063aea736e56b64d4d2e2590b3738176062f62dfa6313#eventlog](https://etherscan.io/tx/0x1dc9cb99be66d11d540063aea736e56b64d4d2e2590b3738176062f62dfa6313#eventlog)
For more details, you can see the eventlog

[https://etherscan.io/address/0x43dbb0f15116b047257346e07afb4a92fd457c4f#tokentxns](https://etherscan.io/address/0x43dbb0f15116b047257346e07afb4a92fd457c4f#tokentxns)
[https://etherscan.io/address/0xc3acd297f377730870d543f525a47fecf61978cb#tokentxns](https://etherscan.io/address/0xc3acd297f377730870d543f525a47fecf61978cb#tokentxns)
Behavior query of addresses

# Safe Address
eth:0x8D36B3f5808b99bB51FAC2AD1D3721da3f87b767

**Comment by tschubotz** [comment]
> # Reasoning
> 0xef0ca09fbf9a5f61e657fb208b46b8685c1d4766 created a large number of wallets. All addresses behaviors are basically the same.

Could you please elaborate on "All addresses behaviors are basically the same.". What are they doing, when, etc. - a valid report needs more context.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
