### ISSUE TITLE
24 safe addresses created by the same address pointing to a RUG PULL project

### ISSUE THREAD

**Issue by STephcuYY** [safe-global/safe-user-allocation-reports#170]
# Related Safe Addresses
0xa5361000c661cffc4afda1dc075e6cdf554494a9
0x9a8db724493af5b607f896db1db5dafb4edaf154
0x545b5f104ce8da0f37e63e5a977043291f790e04
0x3047570d07521e5967ea1909270769f90fdf1f05
0xd40a7f8efbdfbd5c9c2428ad81e8db6d53292e35
0x8a6a35db19567e21580e28feb3994e0de6b930d8
0x15bb78ed1a9ac8b3c02869decebc72c1cb6c313d
0x8e3c62eda37287be1daa40db00ddaa13028d52ce
0xfc52320b42733d7af775f2d6dab1b1daa76fc83f
0x21efb8c09cb22fd9761b5c280f8c8aec03502e06
0x24553725f1dc1548d3a046e49dae2e44b09425e3
0xff44cf4ed99695afdfedb3fe3faf8020ab9abf81
0x763e365a606527fa4511b0e83d8252f46c4ddb56
0xa664693d89b7086e9f7a4299e3b9cae74b54a313
0xbfc842e1dd050fcfd7711bb7e4a87716c10c64a4
0x9505538d02ea45b93d531feb2d3ebafdabc74607
0xd5c0d8ffc9c90b6dfc55614a5c5b844214c99716
0xf5e48dfd5bc1e548d7417d1f569774af767f17d9
0x0ebc541c3f518d23d6b02b4ce1a9147d551d3660
0x0875385d86cacf735b81f110fd37755eacc8c30b
0xa85402f04a68ab052d0273b772439012bb398209
0xfe3030ee66756f40fcc9873539feee1ea1d7e1e1
0x681d9f765039aafd4aee1a0cd359340497fbfe3f
0x055dbbe0a2fca92a67de714a5ecb13d420f934f0
# Reasoning
all created by a same address——0x3a0319d7dF4E3f0De81a6B90DdCe0C7eDCA693B3

After my careful research, this seems to collectively point to a two year old spam project from China: WCDS. they use safe to enrich themselves and complete rug pulls using 24 separate vaults.
![3](https://user-images.githubusercontent.com/113139158/189226387-213cbe70-67fb-443b-bca7-301a4a59f3bc.png)
![4](https://user-images.githubusercontent.com/113139158/189226399-52f96dd3-9cdc-4b4b-a5a3-c40aa96452ae.png)
![5](https://user-images.githubusercontent.com/113139158/189226403-98e96646-8840-460f-9007-09d604cdcb30.png)

This is the only trace I found of this project today.
https://ethplorer.io/zh/address/0x70bda5a9130a93541960320a09812da1cdaf38f2#chart=candlestick
![6](https://user-images.githubusercontent.com/113139158/189226359-a7f03741-b3f5-43c6-abb0-65b0e06497e0.png)

As it turns out, the safe airdrops available at these 24 addresses will actually remain unclaimed forever. Or go to the evil people who had rug pull.

We must avoid this kind of thing so that the safe token flows to the right, real users.

# Methodology
with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0x3a0319d7df4e3f0de81a6b90ddce0c7edca693b3')

# Safe Address
0xA61B43b55193670579d959c94a6b0303Ecd12201

**Comment by tschubotz** [comment]
> # Reasoning
> all created by a same address——0x3a0319d7dF4E3f0De81a6B90DdCe0C7eDCA693B3

Creating multiple Safes is not airdrop farming per se.

> After my careful research, this seems to collectively point to a two year old spam project from China: WCDS. they use safe to enrich themselves and complete rug pulls using 24 separate vaults.

You report doesn't explain how these Safes are connected. The fact that 2 Safes hold the same ERC20 doesn't mean anything. Anyone can send ERC20s to any Safe.

Please elaborate.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
