### ISSUE TITLE
 10 related safe address

### ISSUE THREAD

**Issue by Finelorrew** [safe-global/safe-user-allocation-reports#172]
# Related Safe Addresses

```0xcdba83e03059fdd2ef71073da503a29184e2fda9 ( contract creator 0xc645893a9154764Ec4a3345b9Edd8a7532B5b0e7)
0x583788f490a278db2a8d6d7226264b4985f75678( contract creator  bensmith.eth)
0x3a11f4c84688a1264690d696d8d807a25ee02dd2( contract creator  bensmith.eth)
0xce6cb757f9535c01510e000b3329bf8b9b08dbfa( contract creator  bensmith.eth)
0x20026f06342e16415b070ae3bdb3983af7c51c95( contract creator  bensmith.eth)
0xa1097b957a62b75482cfb9af960cbd6b8f9f02e8( contract creator  bensmith.eth)
0x58fdd0fa08ccde333e1f17d232dd418258fc5150( contract creator  bensmith.eth)
0xbeef4dade5ca40347ed018bf80c6fd244ed44492( contract creator  bensmith.eth)
0xf15c5d8f49ca91de918caa9a844e4141bd079394( contract creator  bensmith.eth)
0xcdba83e03059fdd2ef71073da503a29184e2fda9( contract creator  bensmith.eth)
```

# Reasoning

first wallets contract creators have only been transferred one or more times from an ENS namedbensmith.eth.  eth and have compatible txns .
https://etherscan.io/tx/0xf71e93407188048dd6c28fd9d302b2041ad05dff3104c62040a57fe00bb67e91
https://etherscan.io/tx/0x8bd1fce6729b6713411f3ab96767b6ceeffe14684cf62cc5264c146ab3b5e563>
and most safe address only use several times!which means it's a very potential airdrop hunter.just discovered by excel and etherscan , it is so clearly for this airdrop hunter.

# Methodology

First I wrote some code in SQL. Then I visited the airdrop csv file and manually checked each safe's creator, and input that creator address into my SQL codes.The reported addresses were discovered by checking irregularities in the Safe addresses created by one unique owner.  Then I analyzed each address manually, checking the tx patterns.  All txs are involved with either swapping, sending or receiving HEX tokens.

# Safe Address

eth:0x9b2Fb6224bBB0492bEa27dd9A7130363C5B8840A

**Comment by tschubotz** [comment]
> first wallets contract creators have only been transferred one or more times from an ENS namedbensmith.eth. eth and have compatible txns .

Creating multiple Safes is not airdrop farming per se.



> and most safe address only use several times!which means it's a very potential airdrop hunter.just discovered by excel and etherscan , it is so clearly for this airdrop hunter.

I checked the first 2
https://etherscan.io/address/0x583788f490a278db2a8d6d7226264b4985f75678
https://etherscan.io/address/0x3a11f4c84688a1264690d696d8d807a25ee02dd2

They have been used quite often. Looks like legit usage to me.



> # Methodology
> First I wrote some code in SQL.

Why not share the query?

> All txs are involved with either swapping, sending or receiving HEX tokens.

I don't see this in the 2 safes I checked.
