### ISSUE TITLE
Abnormal behaviors

### ISSUE THREAD

**Issue by KnightMafiaLau** [safe-global/safe-user-allocation-reports#173]
# Related Safe Addresses

## Group 1:
0x35fd62a2c33f63df1d0aa3ca6a56b1d6264aee9d
0xec6b031eec228a9a5d6c047b3904f636d4d499c3
0x8a5dd154c8f9f80ea2052544d01121e0bd252fd8
0xdc98014f02563ae331e088dcd244d99dd5fd0c84
0x0664950a084145b091e5f7d2ef6714e0b2cc3daa
0x1cd10d006d3f7279915e79b162d305a594656260

## Group 2
0x51f78d81194cb282e3bd5ff4bbd468f56fdbffe0
0x521fe1bd7dec39362809cac1a237629d458e459b
0x692a7d771c69bf1664690b5a072e04f14254aece
0x8cb1f9ad02e57eca18065d83efdfb6ff0c57392c
0x9063569beec766261538e7612ffb2d79bfcf6a00
0x30cd6df997d3c153624fcc560823a32e8886d69a
0x70c9fd1651ca952314965764012ab63e60fd4eb9
0x1deafddfc62c7d6113204adff6fda8a2d2e55a69
0x199aa8a209884ffb1e0849eaeb072bce573bf871
0x4153f0145d48bbd3eb2438dbe1d4535734ec78e3
0xf7525acad4cac16e4f4b873e514cb4ef171d7d69
0xfed79ad04bc452420e6df9f40625cec8e8a3373d
0x082c22f06acf8f603b98946c8f6392a453ff63b0
0x61f744a03b89f7267d26839d4913693c58eadbde
0xf03a139c3d0d26a07e2939204ae7f3ea1dbd9919
0x56515294acc335ed825d640cc5dff615ffed132c
0xeae5e0d63285f24f3a089fdb6a0082ff6801eba1
0x7c3d8bc495b7d2dcc995a3a0dc6444480483988c
0x8f6a8cbacb7aab99d80c39eac0a412653756f83a
0xb05335790892d06800fa6c13c9383dba687c7914
0x3d326c63cc0f126866104c97bc130b31e1104bae
0x310dd223a6999578f9c0738003cc6ca665e3d830
0x3204596e8cd53a791767340c93fb5ee2f11b5840
0x1d02f0a433a999a777d1b11311c4bc9fac33af65
0x8afcf6938dae0439c68e2c4f533e3aad6e967e30
0x7ec0740988c8d01ef4acfb8ac280dbc7b1d2462b
0x47d1ec908b261adf318f16d52752eec0b2c38be6
0xde7a69f62a0746cf93bf97bca16038d05fb700e5
0x6673fa2045ae0324c68c0cc6f66e7d91c446d728
0xafc1b3139d9fdf949c53e4743d4987e78dc1d781
0xadca2254b9b40a48ef44140482e912a03cbc7f5d
0x52b14b11ef687dbad8e422d655a45ea551948760
0x4d8a16f1f414852185e6216fbb9bc4daf4a23713
0xab61f7cb67dbce3612f3eefd617b2df2a27d5215
0x670a36a15e1435099c8621e3ea7fa928abd0ef2e
0xbfa3e74ecac5b2ecf20b2bafcdc02cd659435a45
0xc813081d835c27eb08112a390654bf4b0e7c6f9f
0x7f630885074b976570152a712589e0ceca9086d3
0x676758b7c610acec42d47e414d5335cf6fa11899
0x5deaba8f3d9ac196df20987987a3b15eac629927
0x91155176f8911c6a34dbca8537a59c2c4816d2d3
0x09778357c90993eb74c5dd80087c92fdf98e86fa

## Group3
0x96dbdb6c6605fe55a91b50f68e255db49f5ab1d2
0x4563eb8c42e1f83f3899f96d71c66e213da9f980
0xbfedb0d21af59c0d18a2e9a79718864ded2e9a26
0x6c80fb58a78ee5a60f46ad3c8bede98945993734
0x6cb480cb2a8e4b0c95692c9612cc062dbd652baf

## Group4
0x6c642cafcbd9d8383250bb25f67ae409147f78b2
0xa03be496e67ec29bc62f01a428683d7f9c204930
0x5cc3a4c846ab8b0b78a729b8b1a50e2e0bb66740
0x3a11f4c84688a1264690d696d8d807a25ee02dd2
0x583788f490a278db2a8d6d7226264b4985f75678
0x77736e4d6d46ba57b2a5d663a7ec3463d59d90fc
0x5de36c8ec55ae7bf16858b8f28c405b0d76028c6

## Group5
0x6c642cafcbd9d8383250bb25f67ae409147f78b2
0xca07eaa4253638d286cad71cbceec11803f2709a
0x423cec87f19f0778f549846e0801ee267a917935
0x5d00c6bf2b664d545381188122887b03c64488a5
0xa03be496e67ec29bc62f01a428683d7f9c204930

## Group6

0x74311284973f6e7dadf82ab4700f68f324e58165
0xcfbcec545ee6b24c3772cbd8b15bc482cdd30f36
0x23247828096358066ed51604f99e860affea42fc
0xdb1ffee1b3b3876eebe6d7285db0fb006c780ddc
0xc94154473a8bc3513756a891beb6c48616c9e60c
0x84c2024a297fe4496fb8999c03798f33b326b36d
0x6d1f9cf37cfb93a2ec0125ba107a251f459cc575
0xdaea7dddc1baf1bacf5971c57479edefdfe9fe26
0xdf120b4d1ad9170728b9745ddc480ecf7e147b22
0xbb9e814df9c008050283fa4eea5b2bcfbbd6ecf2

## Group 7
0x693fb04d603d800fa9456a02564ba060da8939fc
0xa9f7cbc91c083866a8f542990fdc8cd6e23b6157
0xbdb8e1bdb1c94654a99d4e70b55c8f4a7fefac91
0x78e084445c3f1006617e1f36794dd2261ece4ae3
0x77f6c1385ebd43ebe2b2de51c3e5d52cd4651278

## Group8
0x693fb04d603d800fa9456a02564ba060da8939fc
0xa9f7cbc91c083866a8f542990fdc8cd6e23b6157
0x78e084445c3f1006617e1f36794dd2261ece4ae3
0xbdb8e1bdb1c94654a99d4e70b55c8f4a7fefac91
0x77f6c1385ebd43ebe2b2de51c3e5d52cd4651278

# Reason

## Group 1:
These safe addresses are all created by the same address, and all the tokens that are used for interaction are from the same wallet. This is a typical air drop farming method.

## Group2
These 42 addresses are created by the same wallet, 0x20c05cf93223e39d75b6266b4044e2e5c588d089, each one has a 0.001 eth txn from this main wallet. Also a typical air drop farmer's behavior

## Group3
these 5 are created by the same address, and they have multiple txns from the same wallet exactly at the same time. Typical bot behavior.

## Group4
These 7 are created by the same wallet, 0x5c886B3Ed9fb762f1eB55EB98c00df4D3cF63322, and they all have transaction with 0x2CaEf7f0EE82fb0ABf1AB0dCD3A093803002e705, which is also the creator of Group5's address. This address has multiple deposit from Tornado Cash (for example, txn: 0xa8ef992b2dac47ca1624955c8ef17e839fe37427caad8cd830b83fa3e59db846), is probably a hacker's wallet.

## Group5
See detail in group4

## Group6
these address are all created by 0x4532280a66a0c1c709f7e0c40b14b4dea83253c1 at the exact the same time, and all the transaction is 0eth from the same address. Typical air drop framer act.

## Group7 & Group8
All belong to one address, with main wallet of 0xdc0046b52e2e38aee2271b6171ebb65ccd337518 and another wallet 0xdC0046B52e2E38AEe2271B6171ebb65cCD337518 create group8, they interact with each other, which is a typical air drop farming act

# Methodology
I use a machine learning model on python to check wallet address that has similar txn patterns, and found these addresses

# Safe address
0xCe7385A7874f595617D299b0c790809b6875F623

**Comment by tschubotz** [comment]
> ## Group 1:
> These safe addresses are all created by the same address, and all the tokens that are used for interaction are from the same wallet. This is a typical air drop farming method.

I checked the first 3 Safes
- https://etherscan.io/address/0x35fd62a2c33f63df1d0aa3ca6a56b1d6264aee9d holds >15k USD of wBTC
- https://etherscan.io/address/0xec6b031eec228a9a5d6c047b3904f636d4d499c3 holds almost 400k USD in NFTY

I don't see how they are connected and how this matches your reasoning.

> ## Group2
> These 42 addresses are created by the same wallet, 0x20c05cf93223e39d75b6266b4044e2e5c588d089, each one has a 0.001 eth txn from this main wallet. Also a typical air drop farmer's behavior

I checked https://etherscan.io/address/0x692a7d771c69bf1664690b5a072e04f14254aece and it holds 355k USDT and almost 60k USDC. Safe as store of value is legitimate behavior.

> ## Group3
> these 5 are created by the same address, and they have multiple txns from the same wallet exactly at the same time. Typical bot behavior.

- https://etherscan.io/address/0x96dbdb6c6605fe55a91b50f68e255db49f5ab1d2 made 245 txs and holds a speciific ERC20
- https://etherscan.io/address/0x4563eb8c42e1f83f3899f96d71c66e213da9f980 sends and receives various amounts of stable coins

With your provided info, I'm unable to see how this should be airdrop farming.`they have multiple txns from the same wallet exactly at the same time. Typical bot behavior.` is not sufficient, please elaborate

> ## Group4 & 5

I don't think you have actually checked the Safes. I don't see how the following 2 should be airdrop farming with your reasoninig 
- https://etherscan.io/address/0x6c642cafcbd9d8383250bb25f67ae409147f78b2 and 
- https://etherscan.io/address/0xa03be496e67ec29bc62f01a428683d7f9c204930

> This address has multiple deposit from Tornado Cash (for example, txn: 0xa8ef992b2dac47ca1624955c8ef17e839fe37427caad8cd830b83fa3e59db846), is probably a hacker's wallet.

This needs more information. Having used Tornade in the past doesn't mean someone is airdrop farming.


> ## Group6
> these address are all created by 0x4532280a66a0c1c709f7e0c40b14b4dea83253c1 at the exact the same time

Not true.
- https://etherscan.io/address/0x74311284973f6e7dadf82ab4700f68f324e58165#internaltx creted 2020-11-07
- https://etherscan.io/address/0x23247828096358066ed51604f99e860affea42fc#internaltx created 2021-02-12

>, and all the transaction is 0eth from the same address. Typical air drop framer act.

https://etherscan.io/address/0x74311284973f6e7dadf82ab4700f68f324e58165#internaltx there's more than just 1 tx


I'm closing this report as invalid. If you believe one of those groups is legit, please open separate issues per group and provide more details on reasoning.
