### ISSUE TITLE
0xeadb10137e4d7eb2d1c7612b6f9cbd5958abb10b

### ISSUE THREAD

**Issue by adslwang4601** [safe-global/safe-user-allocation-reports#181]
# Related Safe Addresses

0x5b575f0c9c1aef1ac6fb5a998d21fbfb8a235f86
0x9ee36996a48b07d33dad33e8bf3b737510dbd3f4
0x6157438b82edcb1c1ba7a4332a02e8d00b7ccc20
0xcce55049d4210bccf57631e5690c4afa58b569bd
0xa1f4f540ec1a650bbfdb47de51b9f75a61579f0a
0xd6081dd70267f6e5a3d28ba4cdcc5e7804f703c3
0x44f50a1212fea781c0a382390a6bc91d33a66ed3
0xea8557c92ae738f09ab28ca25307d668f7a0df1c
0xddba2fcaa3a2ce9f5d52bf9d4f228969c6441ef3
0x624446485376bb1cd0d784a0ad3aa401569b5f38
0x413d11063da67333896b4f6a9e01a560dc6ce96c
0x90187b2e3da687e3d48c2ad57928655cdfadac90
0x56ff905a89148a61130639083d4de74071d5205a
0xb65913cafc6c666868c53bf2484f4c696ab8ca0b

# Reasoning

All wallet behaviors are basically the same. Plus all of the wallets were created by 0xeadb10137e4d7eb2d1c7612b6f9cbd5958abb10b. This address 

# Methodology
All wallets created by it can be queried
https://etherscan.io/txs?method=0x1688f0b9&address=0xeadb10137e4d7eb2d1c7612b6f9cbd5958abb10b

The address 0xeadb10137e4d7eb2d1c7612b6f9cbd5958abb10b sent almost the same transactions to those wallets.  
**Create Proxy with Nonce -> 0x60806040 -> Exec Transaction -> Exec Transaction**
https://etherscan.io/address/0xeadb10137e4d7eb2d1c7612b6f9cbd5958abb10b

# Safe Address

0x2578ebA8A0b98Fc47EC48fd9fD9A8172fFa398DC

**Comment by tschubotz** [comment]
> All wallet behaviors are basically the same. 

https://etherscan.io/address/0x5b575f0c9c1aef1ac6fb5a998d21fbfb8a235f86 made 1 tx
https://etherscan.io/address/0x9ee36996a48b07d33dad33e8bf3b737510dbd3f4 made 4 txs

That's different, not the same.

> Plus all of the wallets were created by 0xeadb10137e4d7eb2d1c7612b6f9cbd5958abb10b. This address

Creating multiple Safes with 1 address doesn't mean it airdrop farming per se.
