### ISSUE TITLE
Airdrop farmer report

### ISSUE THREAD

**Issue by xiaohu1882** [safe-global/safe-user-allocation-reports#193]
# Related Safe Addresses
0xbccc6c3d126aa9e6e3f12cf57ec1452ff8069262,
0xede6e41769c23a0d3e4e516e513a45cd680ab05d
0x2f6a59b56f58771b79acf9819f6bd04c5b69f4a1,
0x5a874b153288aaa27477ec51b23a8fcc7114f63f,
0xa93e787dc5542b971ad89bf97efabe0160a119c6,
0x8fe500ba8ddc735b142e6b124daa7898ff39fcda,
0x3e97e19a1cb3ede300cede85d77b67760eb99094,
0x814e68f2ead2b5dd0e94affd3ab20de2a890904d,
0x43f17188688e847c0e4bb4df646fbfcbf081a67f,
0xc3b0b34922f19f0dcd9327756abf331416257923,
0x25cb2e900ad263bcf8e1cb1eb01d853bd29eae12
0x2996C14b4bb10450E394904863Cc1bb853d2Ec4E
0xb907657b79b59a82ab1687146b9b7196b4e9a6f4

# Reasoning

**1.  The owners' wallets, transaction hash and multisig wallets addresses are shown below.  

owner: 0x251bbab319ea8b95af7dc1d2a01c17a962fa252d
transaction hash: 0xabd44eb328566c6cf2a0a002a8ea5a6228eb417753b04021dd6a62ac3e33e4a1
safe wallets: 0xbccc6c3d126aa9e6e3f12cf57ec1452ff8069262

0xaf8579979abce8a1bf522096309e318ed11b9af2
0xf6497a0dd62effc2c0fa7bda15dc78d51c2268c493846a19fc9b9e0b3ec372e8
created: 0x0e938e53d79d3f2b15556a14d7720076ce20e185

0xe338a8109b4a20acc487de066c78488f57ad853d
0xa0ed7e9016995681a3f9c0a6ccae32cd4a79d8e57c9e8e818073f6e7337ebf30
created: 0x2f6a59b56f58771b79acf9819f6bd04c5b69f4a1

0x69a878144400dc1d29ab9bd2e933696a44f33368
0xef7aa2e959d4145effee2235fd2b7d4d39a4f9003707531cd35dacc4899b1384
created: 0x5a874b153288aaa27477ec51b23a8fcc7114f63f

0xb7bc67a855031ba493eca439fc9f368d6e6518e2
0x974788559e1d13e07ad34e85d3baa711f9cba60c84d4efb1ddd7cd1f0f3630d9
created: 0xa93e787Dc5542B971aD89bf97efAbE0160A119c6

 
0xe936cefd218bd7744c524061b8db1ac40dedaeeb
0x3b308acb001b94d5f87be503696aa405836320e9f3130f828bb3102eaa357224
created: 0x8fe500ba8ddc735b142e6b124daa7898ff39fcda

0x2422e63c380c237eb37f7131b5a5d6bda1b1c5ec
0xd244264dd5f76d3c11dcee027b097cab28a603ed556b8da843484fd884c62240
created: 0x3e97e19a1cb3ede300cede85d77b67760eb99094

0xaf8579979abce8a1bf522096309e318ed11b9af2
0xce8ecebe194e64530ce6ec74c2e5abe951071bfc31b1c6dc74598f34ef68998e
created: 0x814e68f2ead2b5dd0e94affd3ab20de2a890904d

0x204f7e550e570a9d90a2db6348a7f57a027db21a
0xe73033f93c0da90b5335373a0d41004ac7abb959f72c96fea1f4eaca7db779c9
created:  0x43f17188688e847c0e4bb4df646fbfcbf081a67f

0x7f1fde1629c038ebf6fac57687ecab5531cb176d
0xf9e15967733041dfc2f672d4bfc9eef87300e591e61a5c4e9f73125ae4b05df0
created: 0xc3B0b34922f19F0dCd9327756aBf331416257923

0xa27b9e1aa581972d82daffcc67790e1f60f690f8
0xa6f27a05fec2974722a056fd7b47f1bbedc6cd620741e1136fc3a3d76f14c5b5
created: 0x25cb2e900ad263bcf8e1cb1eb01d853bd29eae12

0x98f47aad2d78f7aefcb106cd290bbe795467ca7b
0x9ccec98e12a0aa061adf6ff4d0d518309b9a13568e8fc116eb04c5c9051ea0e2
created:  0x2996C14b4bb10450E394904863Cc1bb853d2Ec4E

0x7bc8d762067705fcc44c8349d2bb19bf7193ac96
0x95cd5225acfaf3c49bf05b3d499e26fbb041b3793393b691d458aadae51c9c81
created: 0xb907657b79b59a82ab1687146b9b7196b4e9a6f4

**2. All of the wallets above have extremely similar behavior on ETH**
**transfer - pledge - transfer  - transfer - transfer  - Mint - Mint - Mint - Deposit ETH - Fill Order RFQ**

https://etherscan.io/address/0x251bbab319ea8b95af7dc1d2a01c17a962fa252d
https://etherscan.io/address/0xaf8579979abce8a1bf522096309e318ed11b9af2
https://etherscan.io/address/0xe338a8109b4a20acc487de066c78488f57ad853d
https://etherscan.io/address/0x69a878144400dc1d29ab9bd2e933696a44f33368
https://etherscan.io/address/0xb7bc67a855031ba493eca439fc9f368d6e6518e2
https://etherscan.io/address/0xe936cefd218bd7744c524061b8db1ac40dedaeeb
https://etherscan.io/address/0x2422e63c380c237eb37f7131b5a5d6bda1b1c5ec
https://etherscan.io/address/0x204f7e550e570a9d90a2db6348a7f57a027db21a
https://etherscan.io/address/0x7f1fde1629c038ebf6fac57687ecab5531cb176d
https://etherscan.io/address/0xa27b9e1aa581972d82daffcc67790e1f60f690f8

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/106882397/190647123-4178710e-f047-468b-85e9-3382e77ffc60.png">

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/106882397/190647168-635d2dc9-7efd-4611-955f-0b46c33e4271.png">

**3. Those multisig wallets have similar behaviors and the transactions almost happened in the same time window.**

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/106882397/189289197-f598f832-6c44-45f2-97da-0a7ada745355.png">

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/106882397/189289303-15342435-9e33-4648-83f6-be6e3cf5d675.png">

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/106882397/189289362-32fc8857-dcdc-4d9d-94fc-e5d34f600878.png">

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/106882397/189289426-3d90f64c-da97-472b-9354-c88c47524411.png">

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/106882397/189289615-38852ab1-c7ef-4935-9706-483f424a8b27.png">

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/106882397/189289667-b3bd6e17-c8fa-49e2-af8b-f21f2df6b688.png">

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/106882397/189289734-846ef44f-69e0-4f2e-a14b-24d407a64ffd.png">

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/106882397/189289815-27a629f8-3221-42db-91da-aeefd5ad4c09.png">

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/106882397/189289850-06fb78b7-99e7-4a46-917c-406257b650ea.png">

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/106882397/189289902-c4987fbe-6a95-42b2-a9b2-e9c45ff96f9d.png">

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/106882397/189289937-8cb8ab4d-7de6-4c0d-8048-45d4c914591d.png">

# Methodology

1. 
  select *
  from create_wallet_tx
  where block_timestamp = '2022-05-22 08:37:39'

2. 
with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)
select distinct to_address
from transactions
where from_address = lower('0x251bbab319ea8b95af7dc1d2a01c17a962fa252d')

4. More detalis about the query can be provided on request.

# Safe Address

0xc78CdC3dd169f1308f11a0E9Fb30d86dBfED444b

**Comment by tschubotz** [comment]
Thanks for the report, the following address have been found to be related to airdrop farming:

```
0xbccc6c3d126aa9e6e3f12cf57ec1452ff8069262,
0xede6e41769c23a0d3e4e516e513a45cd680ab05d
0x2f6a59b56f58771b79acf9819f6bd04c5b69f4a1,
0x5a874b153288aaa27477ec51b23a8fcc7114f63f,
0xa93e787dc5542b971ad89bf97efabe0160a119c6,
0x8fe500ba8ddc735b142e6b124daa7898ff39fcda,
0x3e97e19a1cb3ede300cede85d77b67760eb99094,
0x814e68f2ead2b5dd0e94affd3ab20de2a890904d,
0x43f17188688e847c0e4bb4df646fbfcbf081a67f,
0xc3b0b34922f19f0dcd9327756abf331416257923,
0x25cb2e900ad263bcf8e1cb1eb01d853bd29eae12
0x2996C14b4bb10450E394904863Cc1bb853d2Ec4E
```

**Comment by xiaohu1882** [comment]
> Thanks for the report, the following address have been found to be related to airdrop farming:
> 
> ```
> 0xbccc6c3d126aa9e6e3f12cf57ec1452ff8069262,
> 0xede6e41769c23a0d3e4e516e513a45cd680ab05d
> 0x2f6a59b56f58771b79acf9819f6bd04c5b69f4a1,
> 0x5a874b153288aaa27477ec51b23a8fcc7114f63f,
> 0xa93e787dc5542b971ad89bf97efabe0160a119c6,
> 0x8fe500ba8ddc735b142e6b124daa7898ff39fcda,
> 0x3e97e19a1cb3ede300cede85d77b67760eb99094,
> 0x814e68f2ead2b5dd0e94affd3ab20de2a890904d,
> 0x43f17188688e847c0e4bb4df646fbfcbf081a67f,
> 0xc3b0b34922f19f0dcd9327756abf331416257923,
> 0x25cb2e900ad263bcf8e1cb1eb01d853bd29eae12
> 0x2996C14b4bb10450E394904863Cc1bb853d2Ec4E
> ```

I created https://github.com/safe-global/safe-user-allocation-reports/issues/499 as a supplement of this report.

**Comment by skydotone** [comment]
@tschubotz  Hello

Maybe, this issue should be checked further?
edit lots of times

![image](https://user-images.githubusercontent.com/49084147/191139470-12d18e09-fb13-475a-a5ea-9a785c284ea7.png)
