### ISSUE TITLE
This person  has created more than 90+ addresses

### ISSUE THREAD

**Issue by js9d** [safe-global/safe-user-allocation-reports#195]
# Related Safe Addresses
0xac4d0d17aead3ae5555d6bf5b22f5f9470e67fce
0x4cdcbaed9be1be2e59e349e615b4a7dafb934a28
0x2bfa25f946fbef42333098e8898171817d1c3348
0xa3c1bd39ba24420cd04d6f97b78b911698a5a67d
0xdb37c2d3825b79203bbaa71166ffdea25347b673
0xa6e9822bd49dd0faec0664870beea8d48a122051
0x09a8ee7b662cc0c8d1effaf6c9fc526383f5bca1
0x6ebcf2f709693968710e441c9f70573dba718627
0x598874bfb8865f6d37bbdf56346dad780973cd6d
0xaf1f5c6f8d8065ecd8106212b0241cc2345cd7db
0x3e26190daacc364eca378e4591bca6eb6c05078d
0x30c011f8b14add6c009b210aad2e084cd152f2d7
0x6f9a33c8aa249bfe63b285f3815d08410675513c
0xab6ac840a1852046c8953333fc4f869cbb64b794
0x1ddef81e9d3a5aa4d30ff740b5c9bfa66a176969
0xa58bf3fe3caedaa9738fac00857dfd9150969075
0x68b9afc779d86099fd378fc31c037e19c6cc8440
0xc1f19a941bbaa3aa7b70e13eed958b6744c3baf6
0x89e1d7759ff1c8f0283df0c17f0618caf7b694f2
0x976c3d006b1e3cd7ef1a4fbca9aa34b25ff07f2e
0xb4e5db6ae290a8990b1316145e84db9f55993748
0x8ff7bf90a90e5da515b4e9ea086016af7e8465c1
0x8099b697663447ed94ec028e005327765a44ba70
0xf9092d4ae81464c0a0430acbe1d570d04ac799ac
0x4aa9ce2404aab305a0cae4ebfb7445894a2f2939
0xfb6df432f02d4099e0c176902351d8e79120af7d
0x9cA43d919569D1E86799220FA9AFab71423B1697
0x4c54158862efca245de42af011b3306afeb9c6bb
0xF2dC50beb378f48146401603B6B770Deb359F6ED
0x13dadbed45d857cffdaa0e14769ac258fb672250
0xb26ad38491a45c44b69b1322155b5dfbffc98cb0
0x7dfe2213e2bfa1fdd03e8f39b8b69b70bc23ea1e
0x77aa1a0f716e98be1fc7968554b2c65586cb0d89
0xece1ed6fa335350a242addc97493b781ce17f960
0x8fd100c68015993468bd41c7410e46044111131f
0x0c6df9ca3805b95094596cd6fb24d335b7adca0e
0x71D18Fd8f78C4afDa917A6297F611f012b05d1c6
0x149B0C5E1e91911C141c24db4386589B4E08ba09
0xa029107e4e564fcd858489874e122117ce40c135
0xb17c5cd5671233bc1697b50e8298d401110b90bb
0xb5824001cef4324cb211606bb10dd69a6fc3591e
0x307191F294323F6d84168ca88d9c8e69EAd638f6
0x7A0C7B161f706f3d0b806e33606f623E14f94197
0x20f7bC4d4C65D4C3fA2F72b4820c72C3190Ac4e8
0x00b2e3c4347e314a931bfff899d239222ec8cc9f
0x8ba8a3e0ac02fe8f91f30afcd9f19720b5ad04a4
0xafa96b1af942cd9ae789c5e4d86e4c7174503efa
0x53754c51bd2ddccdbb85c8e63827011d2fed646b
0x067a373420e67e4c0edbb547ed6133b83eb8c7a4
0x17dcf09ae8525d49ad92a319e603ce564c4ca002
0x860d04e3cf4856f1697e09a9b64fab4b4dfc5d0b
0xd32469f7afefe0c9e9592b460e5d310980144be7
0x6229842f1c8243ecf90dc271ec8d069e65b43e8a
0x157c68b10a3f9311ac6d01862b69203ffe5e08d8
0xf37e79d7e1bb76875d288d2719afafa640479812
0x57a50a09bd0378b0154f27d9d0ac87ae9e8c9ecc
0x0a194d74ee18ffe5b464e74f2ff745bf9b7790fc
0x0ca7f4fa293118f7f31cd8154d5242323c9e572e
0xd15c6c2848c4e132c925d55f3d6bf41799ddbe54
0xc1fb49056ae14bfd814630a21cc1e902d229797b
0x8a2d1c9c8946b8efebd1994688eddd3f9822c747
0x31422acef5b42363f0e3b2f9090a21367b7663db
0x52d48f2a8b8b23533a6d407d38b8a19b12ca6df3
0xaef10838d3b01355e2531d992f700cfb8467ea96
0xc135363f9b418740cdfd10c8b38c7ac91f215d17
0xf29c1553a5d815148ea6b6dfe29abfe181c019b6
0x16dd55be903e0ed4c6fbdba703c3c223b76cc8cd
0xbe2aec3d9f951767034e8bce739b227f4878c3c4
0x6b925675a51c9ff22afae5f3c2e0bbdc9d16097c
0x3e7bd7229665d19fe319b76605edc0b437655d7b
0x2d83946b530b99e823e9c9896e0e0f05bd5d1fce
0x6d152c1191ef723876ff5fcee6c9b6acb861a73b
0x53e8272301d4db1a57d3604f8b0cb1503d4cefa1
0xc9b90bcf2c45b48defcadecd638c356ae949717f
0x09239e16302cc0a6676ba0928ac44ff922a31992

# Reasoning
# Here is my dune: 
https://dune.com/nisa9801/safe
<img width="1423" alt="1" src="https://user-images.githubusercontent.com/94033242/189383888-adc26259-5f9a-4e6c-aa46-8cc224374f8c.png">

The person's address list below:
0x00125c609527061996b1f30fccd75334495691fe
0x5b55059279b593f6417ff3ddcc2f34c70260c45c
0x445e6e83e87c32024bb4774a776017b468f012ec
0xb52f4d17f2a70fe4492e784c52e9c7f0e9ac7402

All these 90+ addresses created by the four user address in a limit time, 
From Sep-01-2021 02:01:10 AM +UTC to Sep-01-2021 03:53:31 AM +UTC.
This person create 90 wallets in less than 2 hours.

tx is below:
from : https://etherscan.io/tx/0x6afc315e44712758bb4eafdb956acdbed5a3fff330afa87b46819491112aa564

to : https://etherscan.io/tx/0xdf9b9d3c07a74b1fac847f67bbd6f44b3f0176f0275c0bf9b83e686399f5d2e3

Moreover, I checked all these safe wallets and find something fun.
Each wallet has only two operations:  Contract Creation and execute a unique Exec Transaction. No assets inside the wallet, one interaction or two interaction per wallet, value equal to 0, only gas fee paid.
Each wallet HAS Got almost 600 SAFE!!!

Firstly : 
Some examples : 
https://etherscan.io/address/0x976c3d006b1e3cd7ef1a4fbca9aa34b25ff07f2e
<img width="1404" alt="0x976c3d006b1e3cd7ef1a4fbca9aa34b25ff07f2e" src="https://user-images.githubusercontent.com/94033242/189254135-cd12d5d5-6bec-47bf-bdb8-b7969af45eb5.png">

https://etherscan.io/address/0xb4e5db6ae290a8990b1316145e84db9f55993748
<img width="1423" alt="0xb4e5db6ae290a8990b1316145e84db9f55993748" src="https://user-images.githubusercontent.com/94033242/189254148-602149bf-35e0-432c-9367-29479418927f.png">

Secondly:
all these wallets interaction with [Azimuth Point] at the same time : 2021-11-19 08:00:00- 10:00:00
tx1: https://etherscan.io/address/0xe105c07bddfdcc5c02b14a02773321aec416117c
tx2: https://etherscan.io/address/0x16afeb33f384d99ac27390ee6e19c30189312e2f
tx3: https://etherscan.io/address/0xdb0bb1455c0cecd15c42274c03cf025cae8710d2
tx4: https://etherscan.io/address/0xdb0bb1455c0cecd15c42274c03cf025cae8710d2
tx5: https://etherscan.io/address/0x9E7a1400Efd39176A32Ee6E4506797dACD730BB0
Some examples : 

<img width="1232" alt="0xe105c07bddfdcc5c02b14a02773321aec416117c" src="https://user-images.githubusercontent.com/94033242/189259469-edf64a9c-ee2e-44ba-ba64-23a330fdf82d.png">

<img width="1246" alt="1" src="https://user-images.githubusercontent.com/94033242/189259490-74d0fb1d-c191-4b13-a3ed-6ace5724b3c4.png">

This is a clear case of airdrop farmer.  Created by The Four User address  in two hours(2021-09-01 02:01:00 --- 2021-09-01 03:53:00), each safe address has only one  or two limited interaction(All these interactions happed in **2021-09-02**, **2021-09-03**, **2021-11-19**, see my dune above), and only paid gas, no real interaction with others. Their interaction actions are identical. This is not any deployer and is a completely private airdrop farm behavior.

# Methodology
https://dune.com/nisa9801/safe

Then I found the address was so scared that I decide to check out his specific behavior.
Through some basic behavioral analysis, I determined that he was an airdrop farmer.

# Safe Address

0x8AE1a8edFC7Be9C575e80a7D4f20b70b3D74D464

**Comment by tschubotz** [comment]
Thanks for the report. Most of the Safes have been removed by another report already.

Except:

```
0x7dfe2213e2bfa1fdd03e8f39b8b69b70bc23ea1e
0x77aa1a0f716e98be1fc7968554b2c65586cb0d89
```

Those 2 Safes differ from the others those. [One executed `transferCommitment`](https://gnosis-safe.io/app/eth:0x7dfe2213e2bfa1fdd03e8f39b8b69b70bc23ea1e/transactions/history) instead of `transferBatch` which is different from the majority.[ And the other one executed a Multisend](https://gnosis-safe.io/app/eth:0x77aa1a0f716e98be1fc7968554b2c65586cb0d89/transactions/history) which might still be legitimate use.

Hence I'm closing this issue.

**Comment by js9d** [comment]
Very sad, but I have to say that my https://github.com/safe-global/safe-user-allocation-reports/issues/195 was rejected on the grounds that https://github.com/safe-global/safe-user-allocation-reports/issues/124 was already certified. But I checked the git edit history and I found that I committed at least 20 AirDrop wallets 11 days ago, but https://github.com/safe-global/safe-user-allocation-reports/issues/124 only modified the content to add those wallets 9 days ago. https://github.com/safe-global/safe-user-allocation-reports/issues/195 is a full 2 days ahead of https://github.com/safe-global/safe-user-allocation-reports/issues/124, simply because https://github.com/safe-global/safe-user-allocation-reports/issues/124 was created first and it can always modify the content.
The content of https://github.com/safe-global/safe-user-allocation-reports/issues/195 was finished and unmodified 10 days ago.
@tschubotz Could you please double-check?
https://github.com/safe-global/safe-user-allocation-reports/issues/195

I Have Posted These Wallet 11 Days Ago

![1](https://user-images.githubusercontent.com/94033242/191028238-8bc21a5e-f623-46db-a932-2ce164861338.png)

Not Submitted Until This Version

![2](https://user-images.githubusercontent.com/94033242/191028261-eeb4bba3-45a4-4f9d-8ee6-4bfd6c41bbc3.png)

Git Wallet Address Version Comparison
[compare.xlsx](https://github.com/safe-global/safe-user-allocation-reports/files/9599227/compare.xlsx)
