### ISSUE TITLE
the same user created 17 safe wallets, and only transferred 0.001 ETH to interact with safe wallets

### ISSUE THREAD

**Issue by zefzhou** [safe-global/safe-user-allocation-reports#196]
# Related Safe Addresses

```
0x199aa8a209884ffb1e0849eaeb072bce573bf871
0x7ec0740988c8d01ef4acfb8ac280dbc7b1d2462b
0x8cb1f9ad02e57eca18065d83efdfb6ff0c57392c
0x30cd6df997d3c153624fcc560823a32e8886d69a
0x7c3d8bc495b7d2dcc995a3a0dc6444480483988c
0x1deafddfc62c7d6113204adff6fda8a2d2e55a69
0xadca2254b9b40a48ef44140482e912a03cbc7f5d
0x521fe1bd7dec39362809cac1a237629d458e459b
0xeae5e0d63285f24f3a089fdb6a0082ff6801eba1
0x692a7d771c69bf1664690b5a072e04f14254aece
0x52b14b11ef687dbad8e422d655a45ea551948760
0x7f630885074b976570152a712589e0ceca9086d3
0x6673fa2045ae0324c68c0cc6f66e7d91c446d728
0x676758b7c610acec42d47e414d5335cf6fa11899
0x61f744a03b89f7267d26839d4913693c58eadbde
0xfed79ad04bc452420e6df9f40625cec8e8a3373d
0x91155176f8911c6a34dbca8537a59c2c4816d2d3
```

# Reasoning

These 17 rewarded Safe Wallets are all  intensively  created by the wallet
```
0x20c05cf93223e39d75b6266b4044e2e5c588d089
```
For all these Safe Wallets, the creator did 1 transaction for transferring 0.001 Ether.
We can check by https://etherscan.io/txs?a=0x20c05cf93223e39d75b6266b4044e2e5c588d089
Take care, it's not a relayer.
Besides, the wallet were still creating safe wallets in recent two days, and transferred 0.001 ETH.

# Methodology

Step[0]:
Aggregate Safe Wallets by token rewards  in ascending orders.

Step[1]:
Check the Safe Wallets of which reward is less than 150 $SAFE. The Less reward is, the less cost for hunters take.

Step[2]:
Query the corresponding creators for the Safe Wallets found in Step[1] by using eth_scan API;
Sort creators by the numbers of Safe Wallets ;

Step[3]:
Choose one of the top creators: 
```
0x20c05cf93223e39d75b6266b4044e2e5c588d089
```

Check its Safe Wallets' transactions  are all  transferring 0.001 ETH executed by the creator

https://etherscan.io/txs?a=0x199aa8a209884ffb1e0849eaeb072bce573bf871
https://etherscan.io/txs?a=0x7ec0740988c8d01ef4acfb8ac280dbc7b1d2462b
https://etherscan.io/txs?a=0x8cb1f9ad02e57eca18065d83efdfb6ff0c57392c
https://etherscan.io/txs?a=0x30cd6df997d3c153624fcc560823a32e8886d69a
https://etherscan.io/txs?a=0x7c3d8bc495b7d2dcc995a3a0dc6444480483988c
https://etherscan.io/txs?a=0x1deafddfc62c7d6113204adff6fda8a2d2e55a69
https://etherscan.io/txs?a=0xadca2254b9b40a48ef44140482e912a03cbc7f5d
https://etherscan.io/txs?a=0x521fe1bd7dec39362809cac1a237629d458e459b
https://etherscan.io/txs?a=0xeae5e0d63285f24f3a089fdb6a0082ff6801eba1
https://etherscan.io/txs?a=0x692a7d771c69bf1664690b5a072e04f14254aece
https://etherscan.io/txs?a=0x52b14b11ef687dbad8e422d655a45ea551948760
https://etherscan.io/txs?a=0x7f630885074b976570152a712589e0ceca9086d3
https://etherscan.io/txs?a=0x6673fa2045ae0324c68c0cc6f66e7d91c446d728
https://etherscan.io/txs?a=0x676758b7c610acec42d47e414d5335cf6fa11899
https://etherscan.io/txs?a=0x61f744a03b89f7267d26839d4913693c58eadbde
https://etherscan.io/txs?a=0xfed79ad04bc452420e6df9f40625cec8e8a3373d
https://etherscan.io/txs?a=0x91155176f8911c6a34dbca8537a59c2c4816d2d3

# Safe Address
```
0x5382D51cD168493F480F7944D9d5b07E71338979
```

**Comment by zefzhou** [comment]
codes for check: https://github.com/zefzhou/safe_hunter_checker
run aggregate.py for Step[0],
run hunter_check.py for Step[1-2]. By the way, please Input your own eth_scan api

**Comment by Teecash96** [comment]
Check #190

**Comment by tschubotz** [comment]
Thanks for the report, however these wallets have been reported in #58 already.
