### ISSUE TITLE
11 safe wallets were created and operated by the same wallet address, each safe wallet's tx count is 1 and is same  for `ChangeThreshold`

### ISSUE THREAD

**Issue by zefzhou** [safe-global/safe-user-allocation-reports#198]
# Related Safe Addresses

```
0x999c2dd89039284e95346bd15b56ba1e82139b81
0xc76c8e9bd5a2341dd7cf5ad17ed2ccf647e102b4
0x957517dfb9f80b741905f7be7812203b2bbe02ea
0xfa002b29130bdb1f464473e7c524c1c287f1c969
0xe452420eede6a8075470a5decd40ef3e1f6d2493
0xffe39a197e1e5e05ca077fe0eac402e25bd3844a
0xc1964ebd9814624e0fa4bd20bb314982ba26baf2
0xee64aa7c1273339fb12fcc603b889666ed0d1621
0x56c2366b0f7a64d49a4ff7b04c28ddb813edc588
0xc1d512d5e1550b196be47c5234ec566cee7c8d37
0xaa41296be944072430708491915e9b7efeb3ed36
```

# Reasoning

These 11 rewarded Safe Wallets are all  intensively  created by the wallet
```
0x883ccedaa962e0b39daabc88ded96b20df50de55
```
For all these Safe Wallets, the creator did 1 transaction for  `ChangeThreshold`
We can check by one safe wallet tx event : https://etherscan.io/address/0xaa41296be944072430708491915e9b7efeb3ed36/advanced#events

Take care, the wallet above is not a relayer. 
3 reasons for this: 
1、it has nft mint, nft sale on opensea,defi activities such as providing lp on uniswap 
2、by now the tx count is less than 90  
3、it is the owner of all safe wallets which are created by itself [the most important]

can check this —— https://etherscan.io/txs?a=0x883ccedaa962e0b39daabc88ded96b20df50de55&p=1

# Methodology

Step[0]:
Aggregate Safe Wallets by token rewards  in ascending orders.

Step[1]:
Check the Safe Wallets of which reward is less than 150 $SAFE. The Less reward is, the less cost for hunters take.

Step[2]:
Query the corresponding creators for the Safe Wallets found in Step[1] by using eth_scan API;
Sort creators by the numbers of Safe Wallets ;

Step[3]:
Choose one of the top creators: 
```
0x883ccedaa962e0b39daabc88ded96b20df50de55
```

Check its Safe Wallets' transactions  are the same activities for `ChangeThreshold`, and tx count is just 1.

take the first safe wallet as an example:
events: https://etherscan.io/address/0x999c2dd89039284e95346bd15b56ba1e82139b81/advanced#events
tx:  https://etherscan.io/address/0x999c2dd89039284e95346bd15b56ba1e82139b81/advanced

# Safe Address
```
0x5382D51cD168493F480F7944D9d5b07E71338979
```

**Comment by tschubotz** [comment]
Thanks for the report @zefzhou , we've verified that the following addresses seems to be airdrop farming.

```
0x999c2dd89039284e95346bd15b56ba1e82139b81
0xc76c8e9bd5a2341dd7cf5ad17ed2ccf647e102b4
0x957517dfb9f80b741905f7be7812203b2bbe02ea
0xfa002b29130bdb1f464473e7c524c1c287f1c969
0xe452420eede6a8075470a5decd40ef3e1f6d2493
0xffe39a197e1e5e05ca077fe0eac402e25bd3844a
0xc1964ebd9814624e0fa4bd20bb314982ba26baf2
0xee64aa7c1273339fb12fcc603b889666ed0d1621
0x56c2366b0f7a64d49a4ff7b04c28ddb813edc588
0xc1d512d5e1550b196be47c5234ec566cee7c8d37
0xaa41296be944072430708491915e9b7efeb3ed36
```
