### ISSUE TITLE
Suspected airdrop hunters' wallets are too frequent, and they are all fixed amounts.

### ISSUE THREAD

**Issue by yimubenxi** [safe-global/safe-user-allocation-reports#199]
# Related Safe Addresses

# Reasoning

# Methodology

# Safe Address

**Comment by tschubotz** [comment]
has no info

**Comment by yimubenxi** [comment]
0xeE9898f5580a4D7DCCd765DeCDB882A410F9e7e5


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "safe-global/safe-user-allocation-reports"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 晚上9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [safe-global/safe-user-allocation-reports] Suspected airdrop hunters' wallets are too frequent, and they are all fixed amounts. (Issue #199)





 
Closed #199 as completed.
