### ISSUE TITLE
I think these addresses are suspicious. They have the same address in your block and operate similarly

### ISSUE THREAD

**Issue by 000xiaoyan** [safe-global/safe-user-allocation-reports#201]
0x00c0d5c7d6bdf4b584dd91a8e93c444f3c605a31
0x00c668fea3b2283c43d02c72f9ca7f00ae341a91
0x00c6738c69ad9fa5151328464239a51f11bfac17
0x026a23eb9f17fa5ff94ebb1dc41212f0075778ab
0x0278cb6d7a9cd04d118db2c8e71555b4dc8132f1
0x02b1630c1a25877131032417fb7a6bcb0cfb4b45
0x03f09e588d197c08befc81720cec9ceb0d88570b
0x0586544637dc9208d1c2c30d16134a04deade5e2
0x09074373644142bee4226b9278bc2de2a1e509ce
0x09919e1b25858ec5f90c79b3aa9aee0fb34ca05f

**Comment by tschubotz** [comment]
No info provided, doesn't meet guidelines. Hence closing.
