### ISSUE TITLE
166 transaction records

### ISSUE THREAD

**Issue by edssssa** [safe-global/safe-user-allocation-reports#209]
# Related Safe Addresses
0x2E2C0eF26fA67C20a5dd49708F367261240c4bbF
0x015dd85c69debf23a567df80e7480261bbd55127
0x051f64e3a2d5ca37f929f1b4901fed5365605445
0x076b07007baac3d3690bdc2fc03690eda9a40d14
0x144973cc3e520c7e30a54c0ba1b2f1a39c37c130
0x1a94961d6a1d91e8768d57183903a74f6578c399
0x1ab42ba63d8a1fbf3d314dcf7d51c51e444b1d1a
0x1c57bed3db5313dde5049c5391c9869da004cd05
0x1d6b8c4380548d9356e24c6fb25cbb86a9060c6b
0x286cabf860b6ed0a43b29a565631daab6425e149
0x33cb163f8166528670936e2d881dde8e716f1384
0x341e15f0e1b2fb09d9bd5b782f7cf1fc9c1a09db
0x3b6e35435e2d47019e1f872c3f3157424a426079
0x3bc66599aa2755cca6a4e8d7dee056386ccc09a0
0x3ce6a7eecd81bbfce6c7b039e5077eef7cd8f2ce
0x3f77180cb0d14cbe65d8fe7530054d268ff0b75b
0x402a20145216eed247c8426924996f5068cc91d4
0x5205b843efb9c297e0eff3cce34e9b32b755e44e
0x556775c2ee90ce830eddea29de524c6f9d365f6b
0x56cac161df77ce5d60e635553b3bb2fb7fd78a7f
0x5bc240d9ef9cef94b56d7f8a38a83e3f8e47e893
0x5e44fd3077ae205c7eb53dd2e3d51b87b863f7df
0x677a11828e06196950ee02b226696a44f691c980
0x6a3399031cd11debe387cb91aeec2e993bc0b8a7
0x7521634e724861fce46b3e6d40314d7cf0c9497d
0x7647f3fe140656ebee7833c61cd333abd3aa870b
0x7bce07eee7f6a6e7b115bb50278dcafdffea5854
0x809d021c5a91be46078024661900bf9ce15de9f5
0x81b7433a7fa1fdd6baa362d1fe9aba4a1e42b98a
0x86c31b915b84378cfd18c472980922d8faada58f
0x8b7cbb06f193bcb5f80f5f1e66c8518c2e2fac00
0x96a674c05961cf0a84020c561e71de3091a97c60
0x972c3a64c4c0ccac2fd6b9f259496ef20900b10c
0x99a258661cc39c02d1f5b2877bb43b6f491e139e
0x99bfa23ecdd539badc746bbc1963e026c06b02f1
0x9e4bfb53769b46afbd9126ffe1ad56e019f5684f
0x9ed19640ab6855d791f7b48b995f9bd372ed00e4
0x9f23f685b5108478e69c4dd45e73dc7a75674cf8
0xad56b99b17d14987b0ee20cd4a620c4246091a3b
0xaddbb774d31150aec2ed7b1cf27e23f10b143738
0xb50c842463be4d1bd933117c04a35419ce3fb6a4
0xb655f7e5ed94fcf420040bcd61944667c7ce6e1b
0xc075fc07c9ff1b4496cf167b0ed6c2cb1c36a85c
0xc158ed1732d6351222f0030fb9cde3e60a12d2b1
0xc5e89b37ee508845a057ccf26ffedebe8d360d2b
0xd1100fb481990cdd06202d30f73e2f09c9a12f89
0xd62cd0c5a392386179fd5d313fbbf602f95fbbb1
0xdacf71e33b63bff2b4dc41e362cbd9424cf4a432
0xdbee4e9a1b2037e02210e906f4d1bb05dcc130c8
0xdcc2622232dd2766509d8794b34e2127dd9f6029
0xe6d339a7c5cbfa813f4d5ee44ef8fd77fadb5005

````
-->

#reasoning

<!--
Found through the form data, these data were all transferred together and activated the account more than 240 days ago, very similar, and there is no other interaction record, it can be suspected that the account was made by the same person

Example:

https://etherscan.io/address/0x2e2c0ef26fa67c20a5dd49708f367261240c4bbf

-->

#Methodology

<!--
All by 0x2E2C0eF26fA67C20a5dd49708F367261240c4bbF
Transfer to the wallet above, there are 166 transaction records, and then go to create and get rewards

Example:
Through data comparison, it is found that the main account is transferred one by one, and then the account is activated.
Because they are all compared manually, you can see that these accounts have no other operations except for witch interaction.
https://etherscan.io/tx/0x8963d352c0ff0592b9d20cfd3d447f5bffab23ac9bd2ca461d906963cfcbfb6c
https://etherscan.io/tx/0x914c745ad812d255a6b5c62e084a259facce835915c5ee8e85645656a64f0dd8
The above is the interaction record
https://etherscan.io/address/0x8b7cbb06f193bcb5f80f5f1e66c8518c2e2fac00
https://etherscan.io/address/0x9e4bfb53769b46afbd9126ffe1ad56e019f5684f
Both are 240-280 days ago

-->

# Safe Address
`0x8D3DbF1E4E172dDceEB7B72d033CdF0C71dd4609`
-->

**Comment by edssssa** [comment]
https://etherscan.io/tx/0x1d21f7afdca9975525d84d62a9dbb80bc54230523570fe1e7e4beb362ce5f7b4
https://etherscan.io/tx/0x38f612f3a0fe8a8830411d1c4e5933ed90636e622ee9c8cd7e8bc0927e211fe5

**Comment by tschubotz** [comment]
This report doesn't meet the quality standards, please format properly.



> Found through the form data, these data were all transferred together and activated the account more than 240 days ago, very similar, and there is no other interaction record, it can be suspected that the account was made by the same person

Also, this reasoning is incomprehensible.
