### ISSUE TITLE
女巫地址

### ISSUE THREAD

**Issue by yimubenxi** [safe-global/safe-user-allocation-reports#210]
0x1a98d87c9649fa089ebcececf970ab13bdf544a8
0xd85872db2628c55591e7bfbe4349058b53facb97
0x49ad12e50d9b8fe6c97325f6d3e9a6bc0e8f2639
0x638e5da0eebba58c67567bceb4ab2dc8d34853fb
0xb618f903ad1d00d6f7b92f5b0954dcdc056fc533
0x4fc805fb977adf214377191833a7e4ad0d2fa738
0xe1398c437ad0ab711e427ca9d65255b93eb28d04
0xde52163dcda4a3d6055ba914eeadff3382f7ce80
0xf6032c7c15bf4b56bfc5d69208f9ce47f5958512
0x68618dd70373475a815e4b7963a98b11bf4356e0
0x7b3135be81279c3da8f22386cb708540e953435d
0x02bcb9675727ade60243c3d467a3bf152142698b
0xe19930195f8c9ae08df502661eb56152a756354b
0xc53078925db52afaa2c420676a18b11cdbfbf582
0x69cbb00fb8c5436f61bb9c182808d18f2bb4c37b
0xa09c41bde0d6827e197bdd59bece0ab03f9ec987
0x6413d2ed4561de21df1b36b84ddc1a8e239f90a7
0x88ed545f3b258ac405f0366bc5a5e1c34a2e271e
0x4a5c730f0d6f90256590b85582a9ee70fcef0e15
0x840f98f0d52de277a12ad148aa5285c3aa904900
0xc5b7b8efa2a64e47cdcfe7775baea1f9dca01438
0xed90b02c26c727a9e5d8dfbc6c6d005bae228dc8
0xeb51c2d5987e09c9ed1d4eb7551d545d55f854fd
0x7808da0764b16631ac4a9bfc65524ee0ea1498fb
0x5b297ebc674cced0146282945acf8a53b204920a
0x259ae4de033ae672da0cfd8f5d8e745ce82e0e4f
0x6ed10a52d4ee87299e2bd98512362f5e46cc68f6
0x76a03f6341eeafe3234275326faf1486aedaeef8
0x5b9047b9261020f72757edd4b7fb2e6bf82de178
0x16e6c57af3622e0cb093fc54134e2d58b30053cf
0xb797cc62afb7550e7d72bdd1772ee69f2ebf86d1
0x6538118df30c16e638ada9b2ee36d71d95c85600
0x8675e9c19d3a8153bb2da88619d08a2773f739de
0x99bfa23ecdd539badc746bbc1963e026c06b02f1
0x693261f2796e3008d5ae20967ea4bf7c9a05edfe
0x7b6e72d007653b49a0b1e214fd74dc81cc6db1a5
0xe75699440de58230450832e671a85e42f0d303e9
0xf89768ad980883cb43bfd3c1dc32cf694802c4ed

**Comment by tschubotz** [comment]
no info provided.

**Comment by yimubenxi** [comment]
0xeE9898f5580a4D7DCCd765DeCDB882A410F9e7e5




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "safe-global/safe-user-allocation-reports"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [safe-global/safe-user-allocation-reports] 女巫地址 (Issue #210)





 
Closed #210 as completed.
