### ISSUE TITLE
Community Challenge: Identify Airdrop Farmers

### ISSUE THREAD

**Issue by Kabasiki** [safe-global/safe-user-allocation-reports#216]
# Related Safe Addresses
0xa1cb0a8e8b3efc315d99d8447ab085e1acdd2473
0x126bbac5148ef8f786114860564debee5183a357
0x821d5e2e8f439fe2ec5b53b15ed760e2c11e993e
0x6823d6b9bb7cb8b2c832e36d17881e5caf363e82
0xb950850fbe17d7e8c808d650697caaf31eae3bc5
0xea773c7fd7ee4bf6fb3a3c787c0d42cc2e1c493d
0x081926887951c8c6cfdcbcc08d8d10c102087fcf
0x99f3bbc0766d93ee8d28ce4a11c98f49e05af74c
0xffee6faf439bf1be7c6f512aa60cf3b02cd01000
0xd999505dbb1f33c11bb92d57ddfaa6e38d61faf6
0xef679212ccbe735225cb02cb57b3e72af668ee3f
0x6e91d2d3052c4bbd33fea7ebd487ca79c6e99d6c
0xcb1c3b015f5f2a9256ef5773abbd4ea47fc019e9
0x6269ac49731125fc6ea71698720eaa4d10cacc12
0x1768c21e2d7524ec4f31f7b7c572b8a6fbdfec91
0x1227da57a9ceabafe227d621610a19a3472bf4f7
0xdccf7964bbba40f2da94060929c476d6a7883418
0x1b467c7aa79f66a98e617d78ec2c683ac32971bf
0xab975481541841367185affd8638424a2f0bc59c
0x18ad45eea94979cb617362a0466ad0c4e2329d65
0x718d79d02d9dd30f52d9b659a5541811417a2824
0x926f4b6637db95837af8ebff4e3fd7fbd926b39c
0x8cdd9ff541ece7c75e974e7f4d1b43042feff8a1
0x7b13dc1088fba6c3b11db00b548455ef0d10f9c4
0x760e1cef2b6cb81dfeda09f109a4ffc3c94d81c1
0x8bcb71b1df609d31ab899eb4e124b8fbae157252
0x5135ef87a0c6b3acf36e3c4784c7ce16434910a0
0x23416ccc0e32ba401adf34f4da7db4ad4040f1e5
0xd294c7e078080dc41988172c962e9d4048a4b630
0x4283bff1e9caa42629b39d2d452978f1c688aae4
0xce00e6b17c99cbb05ae94329c582214ef0cbca4d
0x0c2c1a03000c9f081c10ae6cd2fdd140ae508193
0x0efd33e60df0a81cc117a0ea19cccc1062798d9c
0x1768c21e2d7524ec4f31f7b7c572b8a6fbdfec91
0xfbb141ddd7320c804aa68bce25b8f6116e0f01e9
0x7654e94516f7601caef64c4fd6ac0170dbc5ef79
0xaae7cbddf5effad91aeb081fcc51827b047d95c0
0x1bee01a6b7a7724fa9a36d907eec00a235f1382b
0xe75272d17ed63278a487a97f023481b900205934
0x79770be829989b040032405f11127948737cd879
0xf7c74a9e4a2085663e18c01ffc856834f6f3ba76
0xac01ea337757b16432cbae8de547e732efe26360
0x780447f065775c1004329698b856a4cf201efc2f
0xb8544e65c9086e885bba74fd2ee418c69ce1493d
0x8d295bc4960a935bd18f7e73fe559be9b046dbdb
0x909e844fb1ada0f45906af2eb6afa9a36d36222e
0xfbc6e8ddd5250f9736c547254b7ef89500da7795
0x7f30560fa87581793319ed33f0a5b41d59360c5b
0xab975481541841367185affd8638424a2f0bc59c
# Reasoning
These safe addresses are all associated with the same eth address, and that address is 0x421f3dac4fe3bd06fa4d51c53647511aeb8ccf69
# Methodology
When I was investigating this address（0x2357e572d36488bD72bc177c585e86bC1Ccb1c69），I found the 0x421f3dac4fe3bd06fa4d51c53647511aeb8ccf69 with whom I have been dealing very closely. Then I investigated the transaction records of this ethereum address on the website and found that they were all related to the safe  
# Safe Address
eth:0x234A42b0E49d8a23476f6F781Ff9C0806eaAD193

![1_20220909141520](https://user-images.githubusercontent.com/90546631/189276629-42ce2bda-46d5-48e9-9901-4dec14fe7a4d.png)
![222](https://user-images.githubusercontent.com/90546631/189276740-60641b3a-311a-42d8-a6ca-e8ecaaa79c43.png)

**Comment by Kabasiki** [comment]
Related tools：https://www.watchers.pro/

**Comment by Kabasiki** [comment]
The number of interactions are 2, and all are safe addresses, very planned, rather than disorderly and volatile like other real users appear.This ethereum address transfers with a large number of safe addresses, and all times 2, showing strict self-discipline and planning
![07_20220909212127](https://user-images.githubusercontent.com/90546631/189348829-77fec7a0-e363-40e9-a73f-bae2d8b8ed08.png)

**Comment by tschubotz** [comment]
> # Reasoning
> These safe addresses are all associated with the same eth address, and that address is 0x421f3dac4fe3bd06fa4d51c53647511aeb8ccf69

Using multiple Safes doesn't mean it's airdrop farming. Owning several Safes is not airdrop farming per se but quite common. Please elaborate on how this is airdrop farming and how you can be sure to no eliminate legitimate usage.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
