### ISSUE TITLE
51 safes with same action

### ISSUE THREAD

**Issue by yaoydong** [safe-global/safe-user-allocation-reports#218]
# Related Safe Addresses

Provide a list of Safe addresses that would currently receive a SAFE user allocation.

0x08da44502a931767d90d66308caae1ab5dff3f08
0x0aa870dc38556003d61cb8b9c45e09c9ec5a245e
0x1c0264ef21a64be37ebf05ee1a454d5dbfb4194d
0x3006fa35e30742241eb9ee145ce416997600d85e
0x3695c7c6dde2b6d935d31bf9659f4cc044b32cce
0x3813a12e16044668067a5429c128ef0633d88176
0x3fc6d0574a0c52a68c40b736f61aa798c500be7c
0x418332c1ffd31209ef0b844909b1b4a0b6bdb209
0x49be0c4397cc8ffa02bd564a15ce3ef6bab82bb0
0x531b0653bc9f0edca487a163c92d52fc364873a0
0x56589cee2ca3c816a92f9b5e91bbbebd809be55d
0x56c9f74ed3ea3b18288486419a0c94e065574c2f
0x56eb3e9974206cf9fa91754ca8519226efd8b1e8
0x596f51a9e70d1751255f5460e94345be32897450
0x59bd691a7787638555b904137a1cdbfcab9dc8e1
0x5b52a7831202967bb3379b448b9739e1614634c8
0x6320a1c4ced68c06ad81792f3cf2fa1a040be958
0x6c27c1ec042a64e8b39d81eff33649a1334f7ad3
0x793f410d6e27bd2a255ba3598a76cffec0ff0e3f
0x7ecf09bd8ca887593d47fa715876f275f7ce7227
0x82c0c0b4a383352b82e892a884e82c94d458b024
0x8c4d2c88f8127aed495ac93a1d3a84279e070eda
0x8e6c8d00b68b0d207817ae6f28c1ad8ec9734c28
0x8f0df23a409a5d2cc9f70a729d9a9cedd1e7b7eb
0x951956984bd338dba308c77f625983eb6fc764ad
0x9b7dcd8496cc07f26cd6e6f53548bf0dce066faf
0x9d90a29c21c80ddebf25a81020a8373d1095c357
0x9ebc3301d31627593a9164dbfcc208077b52d1e4
0xa48e046d36ca5d20f93f5d18aace97d19f360e71
0xa8f426ddb04e60ff9e84e0389ef423d935497738
0xabb81b2b97ad14c6d5c6d788d887256a497afc5e
0xae65292071beb351f7bf467236376747206c0cb8
0xb21054291842ed9a3eea632acf1d60004a0fa1b0
0xb33d70ed7b093fdbe1835581dec22e594d3e5bf0
0xb64faae285c7453faf70a7e951c9171e3f2b723a
0xbe126172bf1da9e444abedb898f833f6e1d2431f
0xbf0fc4eef21abb716dcc9d0dd90e8b9446f71b5c
0xc38225bf8416c3672c4434a9f35acf205fe47cb7
0xd1719926f893d088754c2eabe2f7e45fe8f70b62
0xd5c6120ade5a8133f59250b84f820be2db5b30f5
0xd6273dfb6389325bcf4788051791262f62f7a0fb
0xd6555e4c8064936e9689eb72c03370f203cc1922
0xdcdc9795e090b1db09e966bd02af537201bf6fcc
0xde5c6affc458136dcfc2d1e0c6c1f1fd172d2514
0xdffeb421b9a51a38bbbfd988c63540eab20c0e6b
0xe2aec992e70918106915b261ab290a59e14f6c85
0xe2c9c32fe8271bfef0765c2ed4ba14b0d51cada2
0xe75d423aef82e809b47831a877ddb30c226f3442
0xf12ab45d171dcd406ba8fb640b46b265d1a46106
0xf2d78edcd90f6f52cc4c421b381c812d9509b182
0xfa195e9629d720915b8fd9bab875a4aa484effd3

# Reasoning

These addresses have exactly 1 transaction . and the transactions were called by 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d

This behaviors are obviously non-organic.

You can just search this record:

the main wallet's records:
https://etherscan.io/address/0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d

or theses records from safe:
https://etherscan.io/address/0x08da44502a931767d90d66308caae1ab5dff3f08
https://etherscan.io/address/0x7ecf09bd8ca887593d47fa715876f275f7ce7227
https://etherscan.io/address/0x49be0c4397cc8ffa02bd564a15ce3ef6bab82bb0

# Methodology

I sorted the excel sheet by the amount of eligible SAFE tokens. I identified that there are some addresses eligible of exactly the same amount of tokens (165.6222489 SAFE). After manually checking etherscan tx history, I found these addresses with exact same activity pattern.

# Safe Address

0xfdf11fa8ae68ddb3ff2b9138a517e6518f2e8796

**Comment by tschubotz** [comment]
Thanks for the report, we've verified that the following addresses seems to be airdrop farming.

```
0x08da44502a931767d90d66308caae1ab5dff3f08
0x0aa870dc38556003d61cb8b9c45e09c9ec5a245e
0x1c0264ef21a64be37ebf05ee1a454d5dbfb4194d
0x3006fa35e30742241eb9ee145ce416997600d85e
0x3695c7c6dde2b6d935d31bf9659f4cc044b32cce
0x3813a12e16044668067a5429c128ef0633d88176
0x3fc6d0574a0c52a68c40b736f61aa798c500be7c
0x418332c1ffd31209ef0b844909b1b4a0b6bdb209
0x49be0c4397cc8ffa02bd564a15ce3ef6bab82bb0
0x531b0653bc9f0edca487a163c92d52fc364873a0
0x56589cee2ca3c816a92f9b5e91bbbebd809be55d
0x56c9f74ed3ea3b18288486419a0c94e065574c2f
0x56eb3e9974206cf9fa91754ca8519226efd8b1e8
0x596f51a9e70d1751255f5460e94345be32897450
0x59bd691a7787638555b904137a1cdbfcab9dc8e1
0x5b52a7831202967bb3379b448b9739e1614634c8
0x6320a1c4ced68c06ad81792f3cf2fa1a040be958
0x6c27c1ec042a64e8b39d81eff33649a1334f7ad3
0x793f410d6e27bd2a255ba3598a76cffec0ff0e3f
0x7ecf09bd8ca887593d47fa715876f275f7ce7227
0x82c0c0b4a383352b82e892a884e82c94d458b024
0x8c4d2c88f8127aed495ac93a1d3a84279e070eda
0x8e6c8d00b68b0d207817ae6f28c1ad8ec9734c28
0x8f0df23a409a5d2cc9f70a729d9a9cedd1e7b7eb
0x951956984bd338dba308c77f625983eb6fc764ad
0x9b7dcd8496cc07f26cd6e6f53548bf0dce066faf
0x9d90a29c21c80ddebf25a81020a8373d1095c357
0x9ebc3301d31627593a9164dbfcc208077b52d1e4
0xa48e046d36ca5d20f93f5d18aace97d19f360e71
0xa8f426ddb04e60ff9e84e0389ef423d935497738
0xabb81b2b97ad14c6d5c6d788d887256a497afc5e
0xae65292071beb351f7bf467236376747206c0cb8
0xb21054291842ed9a3eea632acf1d60004a0fa1b0
0xb33d70ed7b093fdbe1835581dec22e594d3e5bf0
0xb64faae285c7453faf70a7e951c9171e3f2b723a
0xbe126172bf1da9e444abedb898f833f6e1d2431f
0xbf0fc4eef21abb716dcc9d0dd90e8b9446f71b5c
0xc38225bf8416c3672c4434a9f35acf205fe47cb7
0xd1719926f893d088754c2eabe2f7e45fe8f70b62
0xd5c6120ade5a8133f59250b84f820be2db5b30f5
0xd6273dfb6389325bcf4788051791262f62f7a0fb
0xd6555e4c8064936e9689eb72c03370f203cc1922
0xdcdc9795e090b1db09e966bd02af537201bf6fcc
0xde5c6affc458136dcfc2d1e0c6c1f1fd172d2514
0xdffeb421b9a51a38bbbfd988c63540eab20c0e6b
0xe2aec992e70918106915b261ab290a59e14f6c85
0xe2c9c32fe8271bfef0765c2ed4ba14b0d51cada2
0xe75d423aef82e809b47831a877ddb30c226f3442
0xf12ab45d171dcd406ba8fb640b46b265d1a46106
0xf2d78edcd90f6f52cc4c421b381c812d9509b182
0xfa195e9629d720915b8fd9bab875a4aa484effd3
```

**Comment by PulsarNetwork** [comment]
Hey @tschubotz could you please double check these two addresses?

https://etherscan.io/address/0x9b7dcd8496cc07f26cd6e6f53548bf0dce066faf#tokentxns
https://etherscan.io/address/0xbe126172bf1da9e444abedb898f833f6e1d2431f#tokentxns

They have incoming token transfer history. I believe they are valid user wallets created by StakerApp as I found out in https://github.com/safe-global/safe-user-allocation-reports/issues/365

Contract creator 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d is a manger address of StakerApp
