### ISSUE TITLE
75 safes with same action

### ISSUE THREAD

**Issue by yaoydong** [safe-global/safe-user-allocation-reports#219]
# Related Safe Addresses

Provide a list of Safe addresses that would currently receive a SAFE user allocation.

0x008acc4bb1c1060cd81f6f49bc63736c45b22573
0x08ee36d1c1e0f932d64e54e8f774ce79b85c67a5
0x119480965616c38bed1ecd996ea31311041b7213
0x15d2e4104f90ba0af112802062ab20eee9b5f7ae
0x173ad4c340001f89009beb45c32458ecaf095c12
0x189e307d57f7d9dbf94658986cf69a1a24175921
0x1aabccae98e1c34625bebeee7c980577410cdf61
0x1bd9bb020df083c5ebb8ab47252eca0e10003bbf
0x1dbb74d64d723b5f02cf8c8b344a6d108b95af57
0x23142f22ec7688731ba1f87fa541f9722f516fdc
0x2770b87a98bab738d601a17b99b2843d369cf6f1
0x2d5b41dbc00ee67c1f2c6a81dc5043132bf085f8
0x3197b70753cdf1940afba9b302907549fe3af260
0x31d7f361160e26dd38fd0576999e40a473090452
0x3449c0669b9c341f5f35f77210071a9521364953
0x35b44e93b3c8e5e11c445612da492cb725fb37b2
0x3adf0497a079b1632e96cb650b5dae197e93553b
0x3b604b43587239dc59744fdc94dd49e00b9bd2d0
0x3fafb386b1b7a3857085096c0926bdf65bb1e584
0x42c8e7baacca2e7697edd89b148bda7726fe7862
0x47656e24a06c65cbf2c7c819ce9d1acba6cbd60c
0x4a6749f78a275c8b257ca6ad2f366166654eb5c1
0x4b08f3b662c01ed58cc19001bc397193d8d59d70
0x4ca1a33fbb6a18b4fb1110c60128134d20dae828
0x4eaca53da79cc619908d8650473e38e4c63d99e8
0x58f228556dff2b87ad8bbdd7251181e0807bba22
0x5ab688956951db7db6df47418b7c2a6c8ae5fcbb
0x62b5a2e429441032e1e76a3f59183a999fe25148
0x673650ff5bc6c7592503c3f798e473938f7766e5
0x69245367f0d11f355b75ff81a34d49e53454b1e1
0x6a3e9fa682a759b58378baa209d418723d65a37a
0x6a7de36e5d5e010a7bfa60718516f7b54611890d
0x6b6b2f8f947543514c3d6d62112a8d13737ad913
0x6c8399d0d562cf2d7320fa827c5934ffb15cc685
0x6ff5ee43ee9d7878acb1d22818921a21d82c8bb5
0x71d1e3e46336328e0b01c7514377f0795f504aa0
0x71f6c6c3a95812c2a36db7a2d8fea7f56da590f6
0x73ddb4e69278cb7d889bcd176a55037a3963ac56
0x77502b6db9656be39099f7dc7b86097a3c626da7
0x7aea138f41857659603df52037df9d3123f618ca
0x7b349c057d11111413cf8e132b288ae106a0ebec
0x7e00f16a60d86cc82ea50ff7cd01ac2583a93888
0x864fe78f21ccf839d555aa567e030d4c1ac21792
0x869dc49f86b87e862a94243693e8dea7fd624650
0x895aea4325fbcb3e8f806b859020068caae2e320
0x92924ef0d8fb13f9b7a05067154b662f6ccd00b0
0x9648bf225f2cca2e028c3aae509e835dfbc46c33
0x9cc3e18454cd14afe31f6d651d392b33d7f6e7f0
0xa14954f11bb3d11e2c192005c185a9304b063c2b
0xa1ee409696ca9b62485d8d2bd58192df8feda675
0xa603498744e04e9e97eba2098409c563ca9f20a8
0xa89e3ee7b73fc55c316dfcade27e279a1168987a
0xa989d947ef9c64c9cfaab4db365b56ebc26560eb
0xad0350f056bc0a5e4cfb9131e75932e0f0175714
0xbc83e72ace784ebec052cf28272460e167a9d76d
0xc1bf9cbe6464f93abe77b5a2ccb67e912045c09d
0xc67181ce82f64ff797f7748781cae34179013ca3
0xc883db3cf5099584d0e014bbd2574c54d9d356ce
0xca4f5cf31b890e3a24ec061878980c63c5296c1b
0xd088ac7ac48d59895b563d0c6fac46788fcd8272
0xd16a6465c821621fdcd94ba698fcd6c9eac732d5
0xd38b24235f63093848a64ff82c57cba37d80f84a
0xd3e9075990e9d4890683fb678b37dd68372bd94d
0xd5d51237063e7dae04b2babe3719b831f4d591ef
0xd7ccb2ed24c05d5942768f32018de8a458790f81
0xdd0686b02733de2452c1ae04837d2f2af003d5de
0xdffe454c592f8f35e504081726f3e562943bf26a
0xee4276bc9ee7a84e71a653633d59cb1e09005b45
0xeef205db9196ebdb5b2c653df0ca4db401784531
0xf083a179d5b5295fc9e7e5410fa4adf6a81b23b7
0xf37c3cd0e37a0f4844923a0858b2bcd0ecb13792
0xf7da419e8ebab335d6869717db9b4c8f2228a900
0xfa77cf9ebb3b4db17e945113f8cf6869a2e3a88b
0xffa984905cdb5592163d4ed1f7a8f670acad3760
0xffc6173d68048184f8f583c6b00bcfc0e569c3f4

# Reasoning

These addresses have exactly 1 transaction . and the transactions were called by 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d

This behaviors are obviously non-organic.

You can just search this record:

the main wallet's records:
https://etherscan.io/address/0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d

or theses records from safe:
https://etherscan.io/address/0xffc6173d68048184f8f583c6b00bcfc0e569c3f4
https://etherscan.io/address/0xd3e9075990e9d4890683fb678b37dd68372bd94d
https://etherscan.io/address/0xad0350f056bc0a5e4cfb9131e75932e0f0175714

# Methodology

I sorted the excel sheet by the amount of eligible SAFE tokens. I identified that there are some addresses eligible of exactly the same amount of tokens (165.6222489 SAFE). After manually checking etherscan tx history, I found these addresses with exact same activity pattern.

# Safe Address

0xfdf11fa8ae68ddb3ff2b9138a517e6518f2e8796

**Comment by wjw12** [comment]
nice job. you are copying my methods! https://github.com/safe-global/safe-user-allocation-reports/issues/214
however, if you are the first to publish the addresses, you win

**Comment by yaoydong** [comment]
> nice job. you are copying my methods! #214
> however, if you are the first to publish the addresses, you win

yes, good method ,and I'll looking into the wallet's txs. thx

**Comment by tschubotz** [comment]
Thanks for the report. We've identified the following address to be airdrop farming:

```
0x008acc4bb1c1060cd81f6f49bc63736c45b22573
0x08ee36d1c1e0f932d64e54e8f774ce79b85c67a5
0x119480965616c38bed1ecd996ea31311041b7213
0x15d2e4104f90ba0af112802062ab20eee9b5f7ae
0x173ad4c340001f89009beb45c32458ecaf095c12
0x189e307d57f7d9dbf94658986cf69a1a24175921
0x1aabccae98e1c34625bebeee7c980577410cdf61
0x1bd9bb020df083c5ebb8ab47252eca0e10003bbf
0x1dbb74d64d723b5f02cf8c8b344a6d108b95af57
0x23142f22ec7688731ba1f87fa541f9722f516fdc
0x2770b87a98bab738d601a17b99b2843d369cf6f1
0x2d5b41dbc00ee67c1f2c6a81dc5043132bf085f8
0x3197b70753cdf1940afba9b302907549fe3af260
0x31d7f361160e26dd38fd0576999e40a473090452
0x3449c0669b9c341f5f35f77210071a9521364953
0x35b44e93b3c8e5e11c445612da492cb725fb37b2
0x3adf0497a079b1632e96cb650b5dae197e93553b
0x3b604b43587239dc59744fdc94dd49e00b9bd2d0
0x3fafb386b1b7a3857085096c0926bdf65bb1e584
0x42c8e7baacca2e7697edd89b148bda7726fe7862
0x47656e24a06c65cbf2c7c819ce9d1acba6cbd60c
0x4a6749f78a275c8b257ca6ad2f366166654eb5c1
0x4b08f3b662c01ed58cc19001bc397193d8d59d70
0x4ca1a33fbb6a18b4fb1110c60128134d20dae828
0x4eaca53da79cc619908d8650473e38e4c63d99e8
0x58f228556dff2b87ad8bbdd7251181e0807bba22
0x5ab688956951db7db6df47418b7c2a6c8ae5fcbb
0x62b5a2e429441032e1e76a3f59183a999fe25148
0x673650ff5bc6c7592503c3f798e473938f7766e5
0x69245367f0d11f355b75ff81a34d49e53454b1e1
0x6a3e9fa682a759b58378baa209d418723d65a37a
0x6a7de36e5d5e010a7bfa60718516f7b54611890d
0x6b6b2f8f947543514c3d6d62112a8d13737ad913
0x6c8399d0d562cf2d7320fa827c5934ffb15cc685
0x6ff5ee43ee9d7878acb1d22818921a21d82c8bb5
0x71d1e3e46336328e0b01c7514377f0795f504aa0
0x71f6c6c3a95812c2a36db7a2d8fea7f56da590f6
0x73ddb4e69278cb7d889bcd176a55037a3963ac56
0x77502b6db9656be39099f7dc7b86097a3c626da7
0x7aea138f41857659603df52037df9d3123f618ca
0x7b349c057d11111413cf8e132b288ae106a0ebec
0x7e00f16a60d86cc82ea50ff7cd01ac2583a93888
0x864fe78f21ccf839d555aa567e030d4c1ac21792
0x869dc49f86b87e862a94243693e8dea7fd624650
0x895aea4325fbcb3e8f806b859020068caae2e320
0x92924ef0d8fb13f9b7a05067154b662f6ccd00b0
0x9648bf225f2cca2e028c3aae509e835dfbc46c33
0x9cc3e18454cd14afe31f6d651d392b33d7f6e7f0
0xa14954f11bb3d11e2c192005c185a9304b063c2b
0xa1ee409696ca9b62485d8d2bd58192df8feda675
0xa603498744e04e9e97eba2098409c563ca9f20a8
0xa89e3ee7b73fc55c316dfcade27e279a1168987a
0xa989d947ef9c64c9cfaab4db365b56ebc26560eb
0xad0350f056bc0a5e4cfb9131e75932e0f0175714
0xbc83e72ace784ebec052cf28272460e167a9d76d
0xc1bf9cbe6464f93abe77b5a2ccb67e912045c09d
0xc67181ce82f64ff797f7748781cae34179013ca3
0xc883db3cf5099584d0e014bbd2574c54d9d356ce
0xca4f5cf31b890e3a24ec061878980c63c5296c1b
0xd088ac7ac48d59895b563d0c6fac46788fcd8272
0xd16a6465c821621fdcd94ba698fcd6c9eac732d5
0xd38b24235f63093848a64ff82c57cba37d80f84a
0xd3e9075990e9d4890683fb678b37dd68372bd94d
0xd5d51237063e7dae04b2babe3719b831f4d591ef
0xd7ccb2ed24c05d5942768f32018de8a458790f81
0xdd0686b02733de2452c1ae04837d2f2af003d5de
0xdffe454c592f8f35e504081726f3e562943bf26a
0xee4276bc9ee7a84e71a653633d59cb1e09005b45
0xeef205db9196ebdb5b2c653df0ca4db401784531
0xf083a179d5b5295fc9e7e5410fa4adf6a81b23b7
0xf37c3cd0e37a0f4844923a0858b2bcd0ecb13792
0xf7da419e8ebab335d6869717db9b4c8f2228a900
0xfa77cf9ebb3b4db17e945113f8cf6869a2e3a88b
0xffa984905cdb5592163d4ed1f7a8f670acad3760
0xffc6173d68048184f8f583c6b00bcfc0e569c3f4
```
