### ISSUE TITLE
Addresses receiving 195.94902 SAFE airdrop are from the same guy

### ISSUE THREAD

**Issue by wjw12** [safe-global/safe-user-allocation-reports#220]
# Related Safe Addresses

```
0x03e8cd1783b7e04518ec14a15b37741ee6a08f1d
0x081edd86c296091f723a698084d18ddb3f3edd9c
0x1310f4ef504d21bb774937afc8275863afe1bce5
0x1510b54643541e731767000f9ae93a7369988eb7
0x1b228a7d1550b47b6d609e4937a39038e1c8e6d2
0x1fae4cf5345ea71e0e5785d8dbc093571a9a332a
0x3f7f04ab5ad9970b2d710cca375fcd28eafeeab4
0x45701312ad912bcd336729e0ca6a1db061af0222
0x4f9d6f8b453a198ec93142238ebeb328ad99acc2
0x52d1ec1fcca9271afeaa18c4df25b22cac6f1b61
0x5e95c302b8b8bcc4cd0f9fe09bef84718bed9e73
0x6312e6d2a7324fd6ccf8d49a2d3be5260fc330ad
0x68e591f84678dc2534286c4a0ecdb044dc4eb91d
0x693fd64d21723c1a95dc5ecee70a256ce97c9a9c
0x69e77cefab916cb47e35f412f8dab1ed2a415c05
0x79a9969e98be9c9bde852cf7d81634f4eb817eeb
0x79d5ece4d76f1b779426442966f13ed77309c489
0x7a4ad59eb4a37033762f4dabf091d6c4c109b03c
0xa2bab96a41bd86ebd49936c9cf9f06981ce03ffb
0xa3f8405ce6d06bd2134aabd617371f37007c23f2
0xa55c367f1258c97778d3cb632849eb8b070390a1
0xa5a141bdbbcdb0a2e8d26a015c8e57a170f6ac2c
0xaca913eb567fb86c319a42bb504f464701e45633
0xad00293b3bbe2281bab9d8112ddc3df3b517d2e6
0xb106fa9a8080ea975e36b57968e94d3269d4f5a1
0xc2e0283da19df3d8e439fcae68b05f8893b7fe0d
0xc7de22f729bd92faa6a6a420808db0e6fdfd7863
0xefcebb7c99d29f79a79929595e4d13c2796e2dbf
0xefdd3e15971722897e726f324144e78e2083ee2a
0xf125c3543272b5d4b3e94f7f456eec035ed44b13
0xf1fb747189632a1d6ab99b422cc07e09e52d5291
0xf53a9356ba89e8a127d8bf5e85e7b0d0bd3cf104
0xff06efdf05882c2268cb051f32d568b13cf7aef5

```

# Reasoning

These SAFEs were created on Jun-05-2022 UTC. They only have 1 tx history happened on that day, and that tx is identical for all of them:

for example:
https://etherscan.io/tx/0x2b9312279ee74c333280cdbb6b5d61f35726d2bf4706caa0ecf984506f000127#eventlog

https://etherscan.io/tx/0xfcd18adb5d655f81c4c76b3f0802af271bd3940b8a7eee04efe5ccf0dfcf2929#eventlog

![image](https://user-images.githubusercontent.com/8369203/189280409-c313b241-af7a-4d79-9948-81d7c8b53205.png)

it approved a token on Uniswap.

If we check the owner addresses who created these safes, their activities are identical, too. For example:

https://etherscan.io/address/0xb334de1bee7bef8cce8f0d37aae0e7b41dff5620

https://etherscan.io/address/0xe4e244f8de69e719049f252c8b890e17ff59c962

They all claimed 5798 RADAR token airdrop on Dec-18-2021, they all made deposits into arbitrum on Sep-11-2021, and they call claimed One Day Punk NFT on Sep-04-2021

# Methodology

I sorted the excel sheet by the amount of eligible SAFE tokens. I identified that there are some addresses eligible of exactly the same amount of tokens. After manually checking etherscan tx history, I found these addresses with exact same activity pattern.

Since the airdrop amount is determined partially by the balance of SAFE, it very unlikely that different SAFEs have exactly the same amount of airdrop. This is a useful clue.

# Safe Address
eth:0x984129b1C8D6048DF516D81f730475AF7D0E4223

**Comment by wjw12** [comment]
Why did I say the tx approved a token on Uniswap?
It's found from the tx log, "Approval" event is for [0x7a250d5630b4cf539739df2c5dacb4c659f2488d](https://etherscan.io/address/0x7a250d5630b4cf539739df2c5dacb4c659f2488d) which is Uniswap V2 router

**Comment by tschubotz** [comment]
Thanks for the report @wjw12, we've verified that the following addresses seems to be airdrop farming.

```
0x03e8cd1783b7e04518ec14a15b37741ee6a08f1d
0x081edd86c296091f723a698084d18ddb3f3edd9c
0x1310f4ef504d21bb774937afc8275863afe1bce5
0x1510b54643541e731767000f9ae93a7369988eb7
0x1b228a7d1550b47b6d609e4937a39038e1c8e6d2
0x1fae4cf5345ea71e0e5785d8dbc093571a9a332a
0x3f7f04ab5ad9970b2d710cca375fcd28eafeeab4
0x45701312ad912bcd336729e0ca6a1db061af0222
0x4f9d6f8b453a198ec93142238ebeb328ad99acc2
0x52d1ec1fcca9271afeaa18c4df25b22cac6f1b61
0x5e95c302b8b8bcc4cd0f9fe09bef84718bed9e73
0x6312e6d2a7324fd6ccf8d49a2d3be5260fc330ad
0x68e591f84678dc2534286c4a0ecdb044dc4eb91d
0x693fd64d21723c1a95dc5ecee70a256ce97c9a9c
0x69e77cefab916cb47e35f412f8dab1ed2a415c05
0x79a9969e98be9c9bde852cf7d81634f4eb817eeb
0x79d5ece4d76f1b779426442966f13ed77309c489
0x7a4ad59eb4a37033762f4dabf091d6c4c109b03c
0xa2bab96a41bd86ebd49936c9cf9f06981ce03ffb
0xa3f8405ce6d06bd2134aabd617371f37007c23f2
0xa55c367f1258c97778d3cb632849eb8b070390a1
0xa5a141bdbbcdb0a2e8d26a015c8e57a170f6ac2c
0xaca913eb567fb86c319a42bb504f464701e45633
0xad00293b3bbe2281bab9d8112ddc3df3b517d2e6
0xb106fa9a8080ea975e36b57968e94d3269d4f5a1
0xc2e0283da19df3d8e439fcae68b05f8893b7fe0d
0xc7de22f729bd92faa6a6a420808db0e6fdfd7863
0xefcebb7c99d29f79a79929595e4d13c2796e2dbf
0xefdd3e15971722897e726f324144e78e2083ee2a
0xf125c3543272b5d4b3e94f7f456eec035ed44b13
0xf1fb747189632a1d6ab99b422cc07e09e52d5291
0xf53a9356ba89e8a127d8bf5e85e7b0d0bd3cf104
0xff06efdf05882c2268cb051f32d568b13cf7aef5
```
