### ISSUE TITLE
SAFEs created by the same address, and later owner changed to another

### ISSUE THREAD

**Issue by wjw12** [safe-global/safe-user-allocation-reports#222]
# Related Safe Addresses

```
0x007b07593e6372187f2da1a2aad13f7f23de702a
0x01e03f23cbee2094c3b0be46e7e7bfad0e4e6ff9
0x03b5eae70b3a1d05fa90c3395b5b3602d20ec45a
0x0574998cbdbda675512d64c197c2b1115d80d631
0x07193e45e556a88e610d64861768a411fa7457ff
0x097bfe8b64b4000bf2db25bba4e5dee9611602fc
0x0f6334c713b4f83d6ef7fc9a8e3920d48548e873
0x0fe7c3b110fbe4e26c95841252d8d6219f476274
0x11cf6a132dbcec3a503e34141197f43a6a07ba55
0x156320d5ff3230cddb6dc82fad536a14d3d184e5
0x19a356e8cb1d31a37c77ac569506922d38af03bc
0x25e846502b8287ef0fc8529d4d0defde89a83666
0x32321d914e09cfdc7e442ed4a92fdce6926c78c9
0x3be95ce5fc30c1d39726d26b6fa7cc2d20098711
0x3d2bea8661c4cd9aa654174f1464c6bcaf4336f1
0x4354ee60dffc1584b0664719b90a9bb1fb68ca66
0x44f3394fd421044dc4a7dea26b697c76e0ac37c6
0x457757c64dcb76e807a6815315985dd9678471dd
0x507664465cf9d6b165d00ac758270b2b5233de24
0x521626e12bf8bbc401ca467a0856f0339e5b805d
0x54b00fc57f3247d254d93a229a758eb3786cc3f4
0x584c9dae00000c624a8278abae2a037e7388b8b2
0x5980b3b99513e3ed9667338e691d39c7358da990
0x6693b34ef25d09c1097c12093baadbc4eb76bb23
0x67aeb37852b2dcaf8fb266e5bd0e3b34b9dc4cf6
0x6a9c7fff0be8220c0a9579300633fb4a62f3c19d
0x713acc0d416d56968ffe200b3f33b3ab409c5f70
0x76e49491933b819d66b0347f9f7f989b60c507d5
0x790e7da450c96a5aa5c74f42b489b882aeaff664
0x7c44a73dd5ebe4050f87a21fcf6382098b3d6d35
0x8a1bc72a098989fe9b071815d13c17da40e8d563
0x9830ca4d48e153e597867f607904c2603309da1e
0x9f5e951e852d7fdbfd2410cd09c955dfcaa6fe09
0xa19243e0ab41335ffee5dfa28c506e27225b9b50
0xa22b5c46b4bd8edacb98d4805c66080e045070ae
0xa28684fe9a07cabb1f3d328a7f1126730755fc2d
0xa2e437b784c7e505dd59c508b00c2d806809c3c1
0xa9814ab5971efb75cf4d7f2eb0251dc2d4bfe1b0
0xabb4ca5232548ce01eae8591d9ecae1232de4109
0xadf4d11434efad78149f6f13734d41bab819f512
0xb839be4aca76ce2010bb9ee610e24c65a9e41c6b
0xbf7db69914e2e255b3b3d57290b890567718ffca
0xc6878676d252abca4b5b0d8c1b365334148281ef
0xc93fcbe938708f8182c9fcd9ae4ce757b2173943
0xcdd1e9fa9d78d4b861a57ecbf47c3dd0ea81f02c
0xdac116f0f50974338dab2403a7349f3e1216f2b3
0xe3978e2b106180720d2301e313c2661d8675a58e
0xe54210973728766e910e6a52cd5a8de7832776b4
0xe80ca7076ed4313e8f6e4431707744750128070f
0xf2763e7f8c498eb1f4ed21c34d0998c646ab8145
0xf6e3720723c95ce76b49783dc305fa751dfa9bd2
0xf782c0cf22540b214166809e8f83fdb936a9725f

0x093e5d0230be06a666cc4dd60f9aade131c1e2a3
0x09c1c5528470186c7315ccab747e0c63ce9b5dd8
0x0c026c881cea76ee136413648bb2f6e7a1d54ab2
0x12eb773dc61b09032d0aa29f1fb8974613a28cc5
0x38b809a5ba5cc55a9d6833bcdeaa109299e3c296
0x3eda186875ff19021c47dd8e643ee87edbb28282
0x3f5f7d23d947d5a4fcd90410f285c499e1f01cc8
0x88afd13701ef28cd27aef5db059b50fb222b14b6
0x89dba0f80a51a6ba98083e226e6eaca6d175a8b7
0x904eb465688a32dfea98875620d05d874ed0788c
0x9a3f2b668aac77d358a5d9566843a184ccd0d211
0xae9dd0aa39bcbabf87418baf0ee9acb336b53843
0xaffc9f431aca4f53b009ce45e4cb5b61ad378b5c
0xbe0fb9b0513a5b3f88ef602041a2bc9b7a91e33d
0xd448e2a887a7e0e886620eb641a3129870654d00
0xe1ccddf323de46c87a4b49df112b4fd810d86797
0xed3da570ad8a13dae23d8694a63ea2e070f2c42b
0xf3bc5ce277c67c8b7309ebe85205cc01809754fd
0xf9906288694864c4967f025fe19f88378791c6c3
```

# Reasoning

They were all created by 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D on Apr-03-2022 UTC. The only tx history they have respectively is from 0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7 on the creation day, and the single tx changed owner from [0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d](https://etherscan.io/address/0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d) to some other address. 

Example txs to change owner: (see the event log)

https://etherscan.io/tx/0xd1ab3230a4306afa6eac6e0a857d8ffd504d1072200f3902f7793f2369391890#eventlog

https://etherscan.io/tx/0x6d278962c118ea9a7457b85e5c6caf1e3053ae1d83dae71fa5b32ae27a1b76b8#eventlog

# Methodology

I sorted the excel sheet by the amount of eligible SAFE tokens. I identified that there are some addresses eligible of exactly the same amount of tokens (some are 216.1194, some are 211.0456). After manually checking etherscan tx history, I found these addresses with exact same activity pattern.

Since the airdrop amount is determined partially by the balance of SAFE, it very unlikely that different SAFEs have exactly the same amount of airdrop. This is a useful clue.

# Safe Address

0x984129b1C8D6048DF516D81f730475AF7D0E4223

**Comment by wjw12** [comment]
I have a hypothesis for these tx, as well as txs in https://github.com/safe-global/safe-user-allocation-reports/issues/217:

They are created by a relayer, and right after the creation, the relayer sets the owner address to the original person who made the request. 

If this is true, these SAFEs are not really sybil farmers. However, they are inactive addresses because the only tx history being the "change owner" action. In this case, I'd like to question the 1 tx threshold for airdrop eligibility. @tschubotz

**Comment by skydotone** [comment]
why can't you check me issue?  [issue124](https://github.com/safe-global/safe-user-allocation-reports/issues/222)
you said ` first-come, first serve`
but you skip lots of issues

**Comment by tschubotz** [comment]
Thanks for the report @wjw12 . All Safe addresses have this report have been reported by an earlier one before and removed from the csv. Hence closing this one.
