### ISSUE TITLE
Assumption: all over 10 accounts of the exact same award amount are airdrop hunters

### ISSUE THREAD

**Issue by Hnsr0327** [safe-global/safe-user-allocation-reports#223]
# Related Safe Addresses

0x03387968fd685fb406fa04327cfd5454d82816d8
0x048485f840264e36963bb69b5d05b29ca8a09a84
0x04da9ff106ba0ec0bca0274763e7f82db4474d55
0x1325838508d8685527acfef44427252811179e04
0x13697eb94761c6eb108a729b758b75c35d04bcf8
0x16f3cc6b7e1721d62edfd00bf7b70c2e9345dc32
0x1ce38658c02936d6f846bfd33ad8b40276e33f1a
0x205fba575e77a9682e4e1f91cdf242f2acbd7480
0x2383095ffbfd2c24d6b4a663d8087e44228bd289
0x249beb1c58f516c5aa15309714eb49b96f5e764a
0x27ab3caf8505e741ebf43f5f6079c2a72fc41380
0x369c8b608d0b048c42492c0d15eb01ccb1bcfe62
0x36aae73f7fadc837678f0ffd576ff09e8bc1a6f8
0x3aab326dc672d574f384128857029a6846f6fde9
0x3b24181ba24707172e14fcb6d6457a5609a2b221
0x3eb35aa31e845f7fa77cc8190286795b00d94d74
0x467b2a5d2e29e669a5386d3348e74b5e8f744e0a
0x468ee05e47553e02ab950bc777ea0b815f24ba4d
0x471d9350d16a942a3736b464ef13a5f4f3c90284
0x505479be841191a15abec0d7693dc197a6fd4fd0
0x522dca3171c6da92ddcd6a9f53a533ff2ee9ed29
0x52d33e06c34ceec428412d76d4dbb7c8af21d2d7
0x5ee40950ae2d73a87a87b2eefcb6657a17a81437
0x63ec11693162738d553df512942e1eb2b34b4532
0x6a096809f5712d64146a26cd2be1dd5ea72da282
0x6e690060c6052a242424eebde082052a9611c5f9
0x73b3abeaa9c66e6ec1dcea36a391848d60b9d132
0x78ec680b9421a997e49c000726bd614d7802e26d
0x8556c98384a52e3c5c8cb858e5fc1e3e4bd31525
0x8af23d9308882cb6bcc75cb04074b568b836c07f
0x902de9d91fd98ddff379ce2c4a61d1e74ec85d73
0x91e06d6bf2ffa61dc829f25619b97b504e38914a
0x958c8d326535c789022df99a750a99516bf57880
0x962aec1195077194977c2384e9b2c2015127efde
0xa2ad93b9ab31c33b2cd60e55d02b21589b6e82a5
0xa6d3270ccdc73f0d222542a375055bb7d8968175
0xab57a91f7953654617eebe75472ff7aa7d78613d
0xb37b65e3fcb2ae8b26d706ad49951cb9f435c6eb
0xb76d04ec5534d92a4b8ea03533ed5444e9c84c64
0xba03c695e1783e7662adf22cea67bee4b0a8c924
0xbe153fa5b96648ff46c02e8223029c49263edaef
0xc47b1770cab767f198656b5abb2520d87383743a
0xc9cf2934f582790a6c06b532fd301bf9fecb3e22
0xd441cebe9887e77007791ddf327b8bd79c56e457
0xd5748bb9a9df036fd84d7bf4c5b3d34ed274025a
0xd8cde918d0520cc117fb663d0b9668c10558b351
0xd9d2bfe5e455f061e2e4702150ffaf90e4991bf8
0xda4764233da06ebb76e6510c595cb699e51f0b8c
0xdaafeb37ae9da4f3bc0372ea73842e3ba95a58e8
0xddbcf259debd2effb0810ecb60644c7cb5e38e17
0xe2dba08537d9542e813aa6d3870a5c4ff2fa6ec5
0xe592766d2d57fd869ddd9c54fd46d8c4c75a170c
0xf0105c795ee9deadced06b5b646cd9b7995f153e
0xf2194fb7c7619c178a43b1916136d82ae269d59b
0xf4ea36910aa8d4f7699e6bfb0e91b2a20b10159f
0xf5de70c8861732b586c1583f35816ec68e9bc198
0xf86a293731deaa6a1d698e5a3b609edf2c0f486d
0xf90003b6cf6e55072cc0eec441a99d81303dca49
0xfa01787576f65adde74dace5aacef54537081651

# Reasoning

same 197.663932141739 SAFE amount, same create time, almost same txs:
https://etherscan.io/txs?a=0xc0c4cdaa5556f7136df6c3e67d396c05721d4f8b
https://etherscan.io/txs?a=0x8dac72f9c97c80d162b1f79521fa77057821302c
https://etherscan.io/txs?a=0xa6e11b806eac54e3a264ef78ecf1f0ad76405d2e

# Methodology

used #220 's method

# Safe Address

0x06b800D0825e2E018915D8528d56CB148dE8a03f

**Comment by wjw12** [comment]
if you receive bounty, please consider gifting me a fraction :)
0x984129b1C8D6048DF516D81f730475AF7D0E4223

**Comment by tschubotz** [comment]
Thanks for the report @Hnsr0327, we've verified that the following addresses seems to be airdrop farming.

```
0x03387968fd685fb406fa04327cfd5454d82816d8
0x048485f840264e36963bb69b5d05b29ca8a09a84
0x04da9ff106ba0ec0bca0274763e7f82db4474d55
0x1325838508d8685527acfef44427252811179e04
0x13697eb94761c6eb108a729b758b75c35d04bcf8
0x16f3cc6b7e1721d62edfd00bf7b70c2e9345dc32
0x1ce38658c02936d6f846bfd33ad8b40276e33f1a
0x205fba575e77a9682e4e1f91cdf242f2acbd7480
0x2383095ffbfd2c24d6b4a663d8087e44228bd289
0x249beb1c58f516c5aa15309714eb49b96f5e764a
0x27ab3caf8505e741ebf43f5f6079c2a72fc41380
0x369c8b608d0b048c42492c0d15eb01ccb1bcfe62
0x36aae73f7fadc837678f0ffd576ff09e8bc1a6f8
0x3aab326dc672d574f384128857029a6846f6fde9
0x3b24181ba24707172e14fcb6d6457a5609a2b221
0x3eb35aa31e845f7fa77cc8190286795b00d94d74
0x467b2a5d2e29e669a5386d3348e74b5e8f744e0a
0x468ee05e47553e02ab950bc777ea0b815f24ba4d
0x471d9350d16a942a3736b464ef13a5f4f3c90284
0x505479be841191a15abec0d7693dc197a6fd4fd0
0x522dca3171c6da92ddcd6a9f53a533ff2ee9ed29
0x52d33e06c34ceec428412d76d4dbb7c8af21d2d7
0x5ee40950ae2d73a87a87b2eefcb6657a17a81437
0x63ec11693162738d553df512942e1eb2b34b4532
0x6a096809f5712d64146a26cd2be1dd5ea72da282
0x6e690060c6052a242424eebde082052a9611c5f9
0x73b3abeaa9c66e6ec1dcea36a391848d60b9d132
0x78ec680b9421a997e49c000726bd614d7802e26d
0x8556c98384a52e3c5c8cb858e5fc1e3e4bd31525
0x8af23d9308882cb6bcc75cb04074b568b836c07f
0x902de9d91fd98ddff379ce2c4a61d1e74ec85d73
0x91e06d6bf2ffa61dc829f25619b97b504e38914a
0x958c8d326535c789022df99a750a99516bf57880
0x962aec1195077194977c2384e9b2c2015127efde
0xa2ad93b9ab31c33b2cd60e55d02b21589b6e82a5
0xa6d3270ccdc73f0d222542a375055bb7d8968175
0xab57a91f7953654617eebe75472ff7aa7d78613d
0xb37b65e3fcb2ae8b26d706ad49951cb9f435c6eb
0xb76d04ec5534d92a4b8ea03533ed5444e9c84c64
0xba03c695e1783e7662adf22cea67bee4b0a8c924
0xbe153fa5b96648ff46c02e8223029c49263edaef
0xc47b1770cab767f198656b5abb2520d87383743a
0xc9cf2934f582790a6c06b532fd301bf9fecb3e22
0xd441cebe9887e77007791ddf327b8bd79c56e457
0xd5748bb9a9df036fd84d7bf4c5b3d34ed274025a
0xd8cde918d0520cc117fb663d0b9668c10558b351
0xd9d2bfe5e455f061e2e4702150ffaf90e4991bf8
0xda4764233da06ebb76e6510c595cb699e51f0b8c
0xdaafeb37ae9da4f3bc0372ea73842e3ba95a58e8
0xddbcf259debd2effb0810ecb60644c7cb5e38e17
0xe2dba08537d9542e813aa6d3870a5c4ff2fa6ec5
0xe592766d2d57fd869ddd9c54fd46d8c4c75a170c
0xf0105c795ee9deadced06b5b646cd9b7995f153e
0xf2194fb7c7619c178a43b1916136d82ae269d59b
0xf4ea36910aa8d4f7699e6bfb0e91b2a20b10159f
0xf5de70c8861732b586c1583f35816ec68e9bc198
0xf86a293731deaa6a1d698e5a3b609edf2c0f486d
0xf90003b6cf6e55072cc0eec441a99d81303dca49
0xfa01787576f65adde74dace5aacef54537081651
```
