### ISSUE TITLE
0x4575a64468cca887757773cc0cd48e24a501d2a5 create safe accounts in one hour

### ISSUE THREAD

**Issue by sharkme** [safe-global/safe-user-allocation-reports#226]
# Related Safe Addresses

```
0xa4897933c4754fa3b2d00306a89b233964071541
0x625b77e1daf4df7e26cd8d5bad70ff095589267f
0x07442f52c92152de8a8a3984de7a999770809e57
0x1cd291e75bd43f27a6e81ea0b0c4862ed41406d6
0x284ac2a249a6ab1faef688b4de6e9746c47b0cae
0x4d83b3728850fdaefe65360ae1b99665186a5866
0x57a71e92cf9d9d88d2a81127e61c642d0174b2bf
0x637de2da47603af37cb3a4a0df5d03590dd9de4a
0x7dd72870863c6bb12534334a14d15b5ef5801421
0x91598e8b03332339db7fcd0cfaedb41f0c77131e
0xb51c321b30a173fd160ddc21dea46f91a75e24a4
0xbb8a6547f79790d3f7a5a7a0f7e73c7aa04a7d90
0xcc91634e10345125e0234ef88cf422381d9e7483
0xf67fdd47f522e7d6ea11324e45a01914653f0dbc
0xf917b392d20f186a11fdb7a660bde64b426d6776
0x65a6fb41ed0f7806add5969984ca77f7b5a0e4e7
0xe08f9e738ddfc58ddc669e7400b817b099ac2592
0x74ea753cf82dac5d73817a53972c7f32778319f6
0x47abfa594b9b2813cc82a42b180008c3f7dbaa30
0x5636351e9fc58070fc9e4dde36c1ff76a1fbc5d6
0x679c358d6d5ec3f8fe5d19b8c454c11c4d0f2208
0x475023418a5fdf5a395453078470649c2191273d
0x6dc834bef57e60470e35b3e333ceed45eb32ba22
0x448b287e0dd7a932d1c5a80a4f4f4a12e5ae2b88
0xa12852fe4f088b1d6118377b1f57622adfc4b0e3
0xdbf46cabd90ba5c0d56f85ef1b9d4d04234e13ee
0xeb99b563fb084c0bae3a0fb123d776c650aa4766
0x6b8a61f82b34b6a6c3141deac6aa9714e7b0a7a4
0x81d3430bf6a609f40365868914c154182d8ee576
0x952a27ec90c52bf00d540458e769114db893cf65
0xaf52d0bfd8a8802261213d6715ff3fea1e5d0006
0x7b1560ec3b6e77aebfa82cd8ea6eb1cb02331029
0xab27410c58f34f17e14d16381616e949ab24229e
0x3db6773d641ddd0d2e866f9b8a2c87269b518d1b
0x164dba559a5273b05e98fdf2d50d87ca65c5bfd5
0xd08f4a3ec4ae05080bed374a2947562b520e1dfb


```

# Reasoning

all of this safe address create by one ens  address  0x4575a64468cca887757773cc0cd48e24a501d2a5 
follow these transactions you all the safe  addresses created  in one hours 

https://etherscan.io/txs?a=0x4575a64468cca887757773cc0cd48e24a501d2a5&ps=25&p=2
the transactions shows that he is a hunter,so all the safe address  created by him should be canceled 
I get all his created safe safe_wallets out 

# Methodology

use the  api of etherscan https://api.etherscan.io/api?module=contract&action=getcontractcreation&contractaddresses u can find the creator of contract and if they are created in short time the account may the airdrop hunter!

The reported addresses were discovered by checking irregularities in the number of Safe transactions made via Dune. Based on the resulting list of Safes, a dataset was built that categorized each Safe transaction. Based on that, an algorithm was used to identify repeating patterns in the order of those interactions.

# my Safe Address
`eth:0x67c6728323613a8d883AdEe4d83611Ad015Ec262`

**Comment by tschubotz** [comment]
> # Reasoning
> all of this safe address create by one ens address 0x4575a64468cca887757773cc0cd48e24a501d2a5 follow these transactions you all the safe addresses created in one hours
> 
> https://etherscan.io/txs?a=0x4575a64468cca887757773cc0cd48e24a501d2a5&ps=25&p=2 the transactions shows that he is a hunter,so all the safe address created by him should be canceled I get all his created safe safe_wallets out

Creating multiple Safes is not airdrop farming per se.

I checked the top3 Safes:

https://gnosis-safe.io/app/eth:0xa4897933c4754fa3b2d00306a89b233964071541/transactions/history
https://gnosis-safe.io/app/eth:0x625b77e1daf4df7e26cd8d5bad70ff095589267f/transactions/history
https://gnosis-safe.io/app/eth:0x07442f52c92152de8a8a3984de7a999770809e57/transactions/history


I don't see any pattern and your explanation doesn't make sense .Please elaborate.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
