### ISSUE TITLE
Report address with same action

### ISSUE THREAD

**Issue by Snrat** [safe-global/safe-user-allocation-reports#227]
# Related Safe Addresses

Provide a list of Safe addresses that would currently receive a SAFE user allocation.

```
0xaCe7fa0bdBfC29269AeFb5C3C44450a4D3CC8fDa
0x46584b12204053e621a6D2ae3eaE29D9Acdb6e8a
0x19bc98B2E8D3BcB0230E9d27157af0bffc099118
0x550c3B89b5253aef6C7B121Bb0AF123021b76eAa
0xA1Aae3ef46C84c3d77f6b868b6cFa4a6C2584A82
0xa0A10e4F682B16b93446bE1E30d8e4796b2D4d14
0x31fA8f493505BB98247943C8DD0c5FDcFA4DAcD7
0x4Dc96bf4E57CCc866695771EA28D058656778Ce3
0x4d90A597fF8e3344adc07622bCdb1105A6DA6321
0x9c12F7109DC975dA8741f459B188c244C3B7328B
0x970a7A7A44307fF8C43fEEfa6Cada6c4Ff22F28d
0xcDAC7588326D7Be1D8eea7A9aCBd9199Ec854bdc
0xe7ECF8e438eb5525EA600901E7D2EbE5fc7c2929
0xa0978CF2D256f77452B948B12335B9EeD9a55a72
0x84415522Da6325540786F929E9aD5CF4a1b0742f
0x4A36Fc66Ec3A2364963705B47e0EEccd877F5745
0x65A2DA15Bbe34b34452Ae578B7B71fB473cCf99C
0xc7cdD0E5fB2a726c581855835357c81eCDC36F3F
0x9E4Eb23a3BAe6eBF4B3e347d3089E1f8E6FA0eE5
```

# Reasoning

Describe how the Safe addresses are related to airdrop farming and if applicable also to each other with as much detail as possible.

Same Creator in same time.
All interacted with the same personal address.
Own by same address.
The vault was never used.
0x9f8ddc8160c1509335e6861995b8555694e4546a
------------
https://etherscan.io/tx/0x63b2996f4e3c58066457df4f27294f517b6efe56ab9e49a05fe62b74adc7d00f
https://etherscan.io/tx/0x05acde2d98587acf9752ce2f42a30d0051906b13061e44570b9a16ef0433cdf8
https://etherscan.io/tx/0x3c5ffc808443efc6bd216f39812e786bdb0fb2f21a5c0d50f65a160e376a72db
https://etherscan.io/tx/0xe4ecc5ec03d4a7b298b28d5533ac490aa1520c35f7f5072d8a64decdc71f9923
https://etherscan.io/tx/0x971070d8e2963e8802a8ac4b2e7d854eff89f82b379efa80b13e881ebc8f849e
https://etherscan.io/tx/0x164a82fe123c3764bd7cb83e3c443ebed0635975f1450ddc15576a2e73cf20f6
https://etherscan.io/tx/0xb9c523b2efa0b4bb537c3e9a1f48d40af214414117cca84ddc877718274f4cc1
https://etherscan.io/tx/0x82706ccbcb96730247fa2f5d822acee1e9c833644954c12d0c8ed84c86455edb
https://etherscan.io/tx/0xa039cd99a1805eebc5033f1b34a3dd88755e25215fc4aeda56b6ddabe08a92e3
https://etherscan.io/tx/0x7c4031393be1d6d9a40248342ab7cc4c931207ca67edc9b568f12cc272f98c7a
https://etherscan.io/tx/0xf3a4d8955ab88b7eb1e55ce22a22b50ceb2b2faa7d32d5e0c1301a02ccfe759e
https://etherscan.io/tx/0x0809df19789f2228e55a9a99d55b71b8d6dfbda1fa58dc2c8260badd872e686d
https://etherscan.io/tx/0x2ae63e030f3219eed8a2401d6dd413ae9e6b3b2e083cf5f5de0718f68a9bb27e
https://etherscan.io/tx/0x98f69a1e3c394dd84f12ae5122a2aea563ac2232a0c9bdfc359e2a377c259e20
https://etherscan.io/tx/0xf2a40c99e5388e42242ec3e37d7a7833d2e55ad5bb584196c85de95364f2aef6
https://etherscan.io/tx/0x8c5832418d3d51a23829fb5058e43161ca88f6bbbf504da1ec4207bd206279ad
https://etherscan.io/tx/0x78411b85d674f02032eb4ef9c68947e38c5570716c2cf1e812d85704af32c6de
https://etherscan.io/tx/0xe98a83ca57c62b0eaf2410bafb8a5f7d467158971714ae7e6b2c6ad89b9e8893
https://etherscan.io/tx/0x145365980183800d9346de1c15bf38bf26101476c1495a8aa776f40183d2bad4

# Methodology

Explain the method used to discover the addresses and provide proof that they are all related and likely operated by a single individual/entity with a high degree of probability. The methodology should be easy to verify or the report will not be considered. Please, also include links to any additional materials you’d like to provide like a github repo containing the script used to uncover the reported addresses.

I sorted the excel sheet by the amount of eligible SAFE tokens. I identified that there are some addresses eligible of exactly the same amount of tokens. After manually checking etherscan tx history, I found these addresses with exact same activity pattern.

# Safe Address

Please provide a Safe address or ENS name of a Mainnet Safe that will receive any potential rewards earned from this submission.

`0x804709550560A6E4bFF44355A57900924681264E`

**Comment by tschubotz** [comment]
Thanks for the report. We've identified the following addresses related to airdrop farming:

```
0xaCe7fa0bdBfC29269AeFb5C3C44450a4D3CC8fDa
0x46584b12204053e621a6D2ae3eaE29D9Acdb6e8a
0x19bc98B2E8D3BcB0230E9d27157af0bffc099118
0x550c3B89b5253aef6C7B121Bb0AF123021b76eAa
0xA1Aae3ef46C84c3d77f6b868b6cFa4a6C2584A82
0xa0A10e4F682B16b93446bE1E30d8e4796b2D4d14
0x31fA8f493505BB98247943C8DD0c5FDcFA4DAcD7
0x4Dc96bf4E57CCc866695771EA28D058656778Ce3
0x4d90A597fF8e3344adc07622bCdb1105A6DA6321
0x9c12F7109DC975dA8741f459B188c244C3B7328B
0x970a7A7A44307fF8C43fEEfa6Cada6c4Ff22F28d
0xcDAC7588326D7Be1D8eea7A9aCBd9199Ec854bdc
0xe7ECF8e438eb5525EA600901E7D2EbE5fc7c2929
0xa0978CF2D256f77452B948B12335B9EeD9a55a72
0x84415522Da6325540786F929E9aD5CF4a1b0742f
0x4A36Fc66Ec3A2364963705B47e0EEccd877F5745
0x65A2DA15Bbe34b34452Ae578B7B71fB473cCf99C
0xc7cdD0E5fB2a726c581855835357c81eCDC36F3F
0x9E4Eb23a3BAe6eBF4B3e347d3089E1f8E6FA0eE5
```
