### ISSUE TITLE
List of safes created with no utility at the same exact time

### ISSUE THREAD

**Issue by walrusur** [safe-global/safe-user-allocation-reports#23]
# Related Safe Addresses

0x07442f52c92152de8a8a3984de7a999770809e57
0x1cd291e75bd43f27a6e81ea0b0c4862ed41406d6
0x284ac2a249a6ab1faef688b4de6e9746c47b0cae
0x4d83b3728850fdaefe65360ae1b99665186a5866
0x57a71e92cf9d9d88d2a81127e61c642d0174b2bf
0x637de2da47603af37cb3a4a0df5d03590dd9de4a
0x7dd72870863c6bb12534334a14d15b5ef5801421
0x91598e8b03332339db7fcd0cfaedb41f0c77131e
0xb51c321b30a173fd160ddc21dea46f91a75e24a4
0xbb8a6547f79790d3f7a5a7a0f7e73c7aa04a7d90
0xcc91634e10345125e0234ef88cf422381d9e7483
0xf67fdd47f522e7d6ea11324e45a01914653f0dbc
0xf917b392d20f186a11fdb7a660bde64b426d6776

# Reasoning

All safes created at the same time (within seconds), the only transaction is the creation of the safe. Which wasn't used for anything else.

# Methodology

Looked for similar values of airdrop amount.

# Safe Address

0x87122A072DaCF42bcCA5F4583fF08dEd2fb89176

**Comment by tschubotz** [comment]
> the only transaction is the creation of the safe. Which wasn't used for anything else.

I just checked the first 2 Safes and they made more than 1 tx:
- https://gnosis-safe.io/app/eth:0x07442F52C92152dE8A8A3984de7A999770809E57/transactions/history
- https://gnosis-safe.io/app/eth:0x1cD291E75bd43F27A6e81Ea0B0C4862ed41406D6/transactions/history

Looking further at those 2 Safes (and I assume it's similar with the other address, but haven't checked.), the only owner is `0x583788f490a278DB2a8d6D7226264b4985f75678` which is an address associated with GnosisProtocolv1 (Mesa) (cf. https://dune.com/queries/1034933). I remember there was a feature called Custom Market Maker which deployed a number to provide liquidity. (cf. https://docs.gnosis.io/protocol/docs/intro-cmm/)

So this looks to me rather like legit usage and not airdrop farming.

Hence marking this report as invalid.
