### ISSUE TITLE
Big farmer from 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d with 1731 SAFE addresses

### ISSUE THREAD

**Issue by TjdnskEhdksk** [safe-global/safe-user-allocation-reports#231]
# Related Safe Addresses

Provide a list of Safe addresses that would currently receive a SAFE user allocation.

1731 safe address:
[farmer.txt](https://github.com/safe-global/safe-user-allocation-reports/files/9533360/farmer.txt)

# Reasoning

I found these safes with 1 transaction from 1 wallet,and the wallet is 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d

so I checked this wallet's txs,and then find these safes are from one person

the main wallet's records:
https://etherscan.io/address/0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d

or theses records from safe(any of safe addresses above):
https://etherscan.io/address/0xbb7e9c0503191f7337a9b32dd6613ddcc70afe89
https://etherscan.io/address/0x529539769a82fa100550ae02725976dcf2bb733d
https://etherscan.io/address/0x4fcd575a1a3f2dc3549385407c160dd8f0c6cbe6

# Methodology

I sorted the excel by the amount of eligible SAFE tokens. I identified that there are some addresses eligible of exactly the same amount of tokens . and i found txs were from 1 same wallet

url = 'https://api.etherscan.io/api?module=account&action=txlist&address=0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d&startblock=0&endblock=99999999&page=1&offset=0&sort=asc&apikey=' + apikey
s = requests.get(url)
txcount = len(s.json()['result'])
print('records count:',txcount)

multi_contract_list = []
for j in range(txcount):
    print('begin to handle:',j+1,'/',txcount)
    if s.json()['result'][j]['isError']  == '1':
        continue
    elif s.json()['result'][j]['functionName'].find('execTransaction') != -1:
        multi_contract = s.json()['result'][j]['to']
        print('    handle contract:',multi_contract)
        if len(web3.eth.getCode(web3.toChecksumAddress(contract_address))) == 0:
            print('   not a contract，skipping...')
            continue
        url = 'https://api.etherscan.io/api?module=account&action=txlist&address=' + multi_contract + '&startblock=0&endblock=99999999&page=1&offset=100&sort=asc&apikey=' + apikey
        s_sub = requests.get(url)
        txcount_sub = len(s_sub.json()['result'])
        print('    records counts:',txcount_sub)
        if txcount_sub <= 1:
            print('    found it:',len(multi_contract_list)+1,multi_contract,multi_contract_list)
            multi_contract_list.append(multi_contract)

# Safe Address

0x94A9cd6b66b480D5D4eFc0a0feF0e3cE2E5D022F

**Comment by tschubotz** [comment]
First of all, I really appreciate that you put the addresses in a file instead of pasting them raw in this issue. Makes it easier to digest.

> # Reasoning
> I found these safes with 1 transaction from 1 wallet,and the wallet is 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d
> 
> so I checked this wallet's txs,and then find these safes are from one person
> 
> the main wallet's records: https://etherscan.io/address/0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d
> 

This is the relayer address of StakerApp afaik. Just the fact that those wallets have been created by 1 account doesn't mean it's airdrop farming.

3 example addresses from your list:
https://gnosis-safe.io/app/eth:0x6Bb500f73f82BaCe5BAbdA72d4717b8549aCA6c9/transactions/history
https://gnosis-safe.io/app/eth:0xbd69e120c3110340dc2e17880d82f2adf4565d2c/transactions/history
https://gnosis-safe.io/app/eth:0x5d3c580673893d592533f008f6e10f6eb81e5b14/transactions/history
https://gnosis-safe.io/app/eth:0x2136e3ffc2a8e86e907b46696e04848d3996e150/transactions/history

While not being greatly used Safes, they have been used to make some txs. So it's more than just a Safe creation. Please elaborate how you can be sure that those (+ all others in your list) are not legitimate use?

**Comment by TjdnskEhdksk** [comment]
> First of all, I really appreciate that you put the addresses in a file instead of pasting them raw in this issue. Makes it easier to digest.
> 
> > # Reasoning
> > I found these safes with 1 transaction from 1 wallet,and the wallet is 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d
> > so I checked this wallet's txs,and then find these safes are from one person
> > the main wallet's records: https://etherscan.io/address/0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d
> 
> This is the relayer address of StakerApp afaik. Just the fact that those wallets have been created by 1 account doesn't mean it's airdrop farming.
> 
> 3 example addresses from your list: https://gnosis-safe.io/app/eth:0x6Bb500f73f82BaCe5BAbdA72d4717b8549aCA6c9/transactions/history https://gnosis-safe.io/app/eth:0xbd69e120c3110340dc2e17880d82f2adf4565d2c/transactions/history https://gnosis-safe.io/app/eth:0x5d3c580673893d592533f008f6e10f6eb81e5b14/transactions/history https://gnosis-safe.io/app/eth:0x2136e3ffc2a8e86e907b46696e04848d3996e150/transactions/history
> 
> While not being greatly used Safes, they have been used to make some txs. So it's more than just a Safe creation. Please elaborate how you can be sure that those (+ all others in your list) are not legitimate use?

thanks tschubotz for your comment, I'll post some comment later

**Comment by TjdnskEhdksk** [comment]
Thanks @tschubotz .

I looked into creator,tx count, wallet who execed transactions, execed time ,logs count and logs detail of all these 1731 safes.

then, I got a whole list (pls see the excel file attachment "Origion Data" Sheet for all information).

after that, i filtered with Txs Count = 1 and logs count =3 (pls see the excel file "after filter" sheet), and i got 1319 safes.

All these 1319 safes, We can see several characteristics：

1.execed transaction only once by 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d;
2.the only transaction was add owner and remove owner;
3.All execution actions are executed in batches, which can be seen from the timestamp in excel;

after all, I don't think these 1319 safes, only execed same action once by same wallet should be rewarded,so please help to check.

thx very much

and if any need, I can share my python code for that.

[safe_list.xlsx](https://github.com/safe-global/safe-user-allocation-reports/files/9594230/safe_list.xlsx)

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.

**Comment by TjdnskEhdksk** [comment]
Thanks  @lukasschor , please take a closer look at the following information:

in #115 ,which is  the last accepted issue，

<img width="914" alt="WX20220919-070008@2x" src="https://user-images.githubusercontent.com/113167298/190931912-86d8386e-6ed7-4fd7-8469-fea2e784ef06.png">

<img width="940" alt="WX20220919-070029@2x" src="https://user-images.githubusercontent.com/113167298/190931918-d91bccc4-ff4b-4c85-b03c-8bc91c9b231f.png">

I think there is almost the same situation between the two issues：

In my list, these Safe Wallets, created by 5 relays, and then  executed  one transaction for add/remove owners with same wallet , which means it's a very potential airdrop hunter.

[safe_list.xlsx](https://github.com/safe-global/safe-user-allocation-reports/files/9595467/safe_list.xlsx)

On the "after aggregate" sheet page of excel file, it is clear that several safe wallets are executed only at the same timestamp,As shown in the figure below


<img width="1140" alt="WX20220919-071529@2x" src="https://user-images.githubusercontent.com/113167298/190932321-518c405b-8a80-4782-a2ef-bd8f5ed8c689.png">

All these safe wallets have no other transactions or no zero balance. In other words, users just create the safe wallets, but don't use them. Just a wallet creator but not a wallet user. Maybe the airdrop condition for at least 1 tx for every safe wallet is not proper. You can fix it from at least 1 tx to at least 2 txs.

**Comment by TjdnskEhdksk** [comment]
@tschubotz @lukasschor 
I find that some wallet addressed in #246 have been accepted,but I found them earlier, so what happened ?

**Comment by TjdnskEhdksk** [comment]
hi @tschubotz @lukasschor 

I don't think this topic should be closed yet, instead, it should be opened and attached with the "staker" label.


No matter whether the team finally thinks that the staker should be airdropp or not, this topic should be opened together with other related topics

thanks.

**Comment by TjdnskEhdksk** [comment]
> hi @tschubotz @lukasschor
> 
> I don't think this topic should be closed yet, instead, it should be opened and attached with the "staker" label.
> 
> No matter whether the team finally thinks that the staker should be airdropp or not, this topic should be opened together with other related topics
> 
> thanks.

Dear @tschubotz @lukasschor , can u help to open this issue and tag with "staker" label pls, thx

**Comment by TjdnskEhdksk** [comment]
hi @tschubotz @lukasschor 

As mentioned above, the wallet addresses I reported in this issue are all from the StackerApp, and whether the StackerApp can be identified as the object of this airdrop through only one changeowner has not been determined, so I think that my issue should be opened and labeled as a "staker"

No matter whether the team finally thinks that the staker should be airdropp or not, its acceptable.

thx very much

**Comment by TjdnskEhdksk** [comment]
Ser,According to your suggestions above, I have updated the file (including address and description), please take a look again
[farmer.txt](https://github.com/safe-global/safe-user-allocation-reports/files/9613817/farmer.txt)

thx.
