### ISSUE TITLE
46 safe address of 0xb8150a1B6945e75D05769D685b127b41E6335Bbc

### ISSUE THREAD

**Issue by possib1e** [safe-global/safe-user-allocation-reports#233]
kingjacob.eth	0xb8150a1B6945e75D05769D685b127b41E6335Bbc

Related Safe Addresses

0x6bf96fd7346b408f6c657cb5c385dbd9e7f35d5f
0x62ef8d0c260f125c467c8bc54c5ef4ff3cd49412
0xaa6b0ea9e304be0cb6dc36aba0721dc9768b2804
0xc523e761d340efc872a43343192b9e78b2a8cfd1
0x2bf3c35a2503ae042696453769936fa9956890ec
0xb883888d8291987ae27d68aeec9165a757fe7336
0x40ca7e89e01114991d74bcdc2e0e4dc4adf1937e
0x351c346c2414941b33ffe359ab08c6ca14aeb7a8
0x3e4cb3a22bc78853bef740df8cad6c4039d1a517
0x03848a24512debf7200420ce08022f5fc5bd0118
0x11d5366c797e8886ed8210106633ed57ef36f248
0xef64c0ca3eb04cfc013b902f39bf579294fe94aa
0x5c866db4da6f912a8f6ceb8c557e04e647e3cd3f
0xdb08b2da92169cd3b6e18c4069fbdbe9d52e8420
0x581a87367c5183e9da21690b5c503ea1f680c825
0x9d41362a7c028925129f6358b73dbdd849fc837d
0x6c335f4031abb8d2c4445c636fe2827bfc8d2615
0xbaac0cf96e327c341d6b9477835e48c38033ae73
0x6e029d061f898dd9da01579a559eb4e606489558
0x1bb8361ae6c92d42668ae325c5376516857cb2f9
0xc4d3d76bc1a5840fa743fafd3996c4d41dec9442
0xed577c900b2b4181c1fc8aa61a7216013fc14dcc
0x4f48564d1b285f85ba54df17f8a9acd318c2e1ef
0xa423809dec7b578ba3cea823e6cd28f09b934830
0x5c94922cad2df62f362b19aaee5cdc1852cdc54e
0x25c691aa4144d1dc0edae10eecb489c674ebeb39
0x8357e896fe5f979271134ead5ba6dae0a301648e
0x94759b2a3476ae1626ebefcdc67d7a660a350013
0xa2d92540f3835af7bbcbe18f799359e830ecdcb3
0x6ecb2517fe8f2b3b75fd4713f7d90e7c87f04bee
0xf8fa82bf3077aa9bad6b75016d5a286775159bba
0x36e9933008cf5304635ee255eb4953c8d2e48d53
0x18249e4bfffab3ae2fe69634dbade620b1aa4011
0x6d8efda24b41242e30d27695808526e669fabb2f
0xb6fa08ed701f9f0d66942742d6fb1f63a2af447a
0xf4e13ad6add428e034c40da2d5f33cb9976875eb
0xeb2bc55856179ddc8cdae12e43ebfe4b3db32b5f
0x7fd489011bbd6271b07d2bd9298a9ba218de3820
0x1faddd8ece8fe38c7bc0733dcccebbc1ba041884
0xa51d3181d753d721b13eb949b1f6803a58e9dde0
0xa8d369a1f833b95b1f97a866eda31dc4261b1b42
0x21f091c65ef83e8230d7365df0ba231b9461177d
0x665e39c168bba60065472bd004982247f954f0bc
0x57606bc5926f63087a8de2551a275aa91453e3d7
0x409016df79bd9abb2bf81164ea62459ba28ccdf8
0x0cd8a3cac1694281dc1e4114b7b19e3901f46690

Reasoning
They are all create by 0x497c20fed24d61c7506ef2500065e4fd662f3779 or 0xb8150a1B6945e75D05769D685b127b41E6335Bbc(this 2 addresses are EOA addresses by person, and not activity after doing interaction to the create safe addresses ),and the safe addresses only Exec Transaction by 0xb8150a1B6945e75D05769D685b127b41E6335Bbc one time, and most of the safe addresses are 0 eth balance.

Methodology
download txs of safe addresses , check their creaters, and check the common of the creaters.

Safe Address
0xd8878417378CB18D315b4768503fC39487f90580

**Comment by tschubotz** [comment]
> Reasoning
> They are all create by 0x497c20fed24d61c7506ef2500065e4fd662f3779 or 0xb8150a1B6945e75D05769D685b127b41E6335Bbc(this 2 addresses are EOA addresses by person, and not activity after doing interaction to the create safe addresses ),and the safe addresses only Exec Transaction by 0xb8150a1B6945e75D05769D685b127b41E6335Bbc one time, and most of the safe addresses are 0 eth balance.

Creating multiple Safes from the same account is not airdrop farming per se. Also executing txs from 1 single address is quite a common pattern of e.g. relayers.

The addresses might not store ETH, but e.g. the first 2 Safes stored >1M USDT. Store of value is legitimate use.

https://gnosis-safe.io/app/eth:0x6bf96fd7346b408f6c657cb5c385dbd9e7f35d5f/transactions/history
https://gnosis-safe.io/app/eth:0x62ef8d0c260f125c467c8bc54c5ef4ff3cd49412/transactions/history
