### ISSUE TITLE
Report address with same action

### ISSUE THREAD

**Issue by Snrat** [safe-global/safe-user-allocation-reports#235]
# Related Safe Addresses

Provide a list of Safe addresses that would currently receive a SAFE user allocation.

```
0x3f3df308ef35283544ca8eb3345b38dcceb40b2d
0x656afbfb370e763bb2354b4d2f4a1e3b6da5f109
0xc90db3aea38970621f2d81fdfe70b1b30103c4a9
0xfec1d52128816efbf64681606d21ee047f4f77b7
0xb1eec8AE289d0B89F0D79a638D12bf4493847b78
0x2a9A2A816AAe3fF46156201a7C782C554BAd397E
0x30b678c41dFa60dE7C1071a06eCE452CBa118045
0xa0157F46bD08442E1062c177B384E124FfDfd435
0x4A87B5e313Af8933DBF71908cb4765B069772c12
0x6415F7017b945821B33d84586eE6f005c36A9403
0x9B52e865d86912998E456f0AD177647c0B01c764
0x28EF8dFa7779E7496483B6c4a794A73282f59EAb
```

# Reasoning

Same Creator in same time.
All interacted with the same personal address.
And get same erc20 token.
Own by same address.
0xe60CE58E4dC308B78cCac3A16C292D90EFd671E6
------------
https://etherscan.io/tx/0x318064f76c0dac6c00866185713b07f1a6bc5631ed038e66213c8d7b3457ffeb
https://etherscan.io/tx/0xf365fcaf81785c2aba5519d43a04a915ef1d8a2150976aedf59a49d00080b963
https://etherscan.io/tx/0x07d6a3e22bb4d847f1261884231be375d0ab2ec4cd1096fac08b490f0c94efd2
https://etherscan.io/tx/0x86dba8ff3d6441d4f5bd6b0dfa1f3c87be079dd4288e6c7f14dd34fa434f7161
https://etherscan.io/tx/0xa59dd7f74d4d3ab56dd86157166b333725c96a2206c00720476cc81b264df76c
https://etherscan.io/tx/0x90f8f68a3001c493688697acf0e2b2319aed9ad711dce80369fac7aec3bae422
https://etherscan.io/tx/0xa5aebbe3bacd29685495f69917c489f52ac0ddad3b52eeb66fc5e5ec26cae77e
https://etherscan.io/tx/0x3f2ce1b1f283e5ee3a4fac7ef091a5cc8ce8e4dc1d23101d244ef2263bc3f652
https://etherscan.io/tx/0x41d340894b17f9f4b7f1c8d70bc759dfd28f675e0449b6e05141e7dcb0dac1ea
https://etherscan.io/tx/0x21267a956edb80616c14ae8f016da96b0ac085cc8471708e0d298174c157c937
https://etherscan.io/tx/0xbb31833614be6d133ba5d9c66316e10ffc8358622ab3e3ad0e652852dbbea0f9
https://etherscan.io/tx/0x6e52ff7b75a8ec2fcb73f6c6d57709f2c221387d482d889380287c5443b6d016

# Methodology

Explain the method used to discover the addresses and provide proof that they are all related and likely operated by a single individual/entity with a high degree of probability. The methodology should be easy to verify or the report will not be considered. Please, also include links to any additional materials you’d like to provide like a github repo containing the script used to uncover the reported addresses.

I sorted the excel sheet by the amount of eligible SAFE tokens. I identified that there are some addresses eligible of exactly the same amount of tokens. After manually checking etherscan tx history, I found these addresses with exact same activity pattern.

# Safe Address

Please provide a Safe address or ENS name of a Mainnet Safe that will receive any potential rewards earned from this submission.

`0x804709550560A6E4bFF44355A57900924681264E`

**Comment by skydotone** [comment]
@tschubotz 
Why don't you check my issue?
I have spent a lot of time, experience, to present the most concise way, you skip!

**You don't even reply to me!!!*8

**Comment by tschubotz** [comment]
> # Reasoning
> ## Same Creator in same time.
> All interacted with the same personal address.
> And get same erc20 token.
> Own by same address.
> 0xe60CE58E4dC308B78cCac3A16C292D90EFd671E6

Seems the Safes receive and hold the ERC20 you mentioned. Store of value is a legitimate use case.

Owning several Safes is not airdrop farming per se but quite common. Please elaborate on how this is airdrop farming and how you can be sure to no eliminate legitimate usage.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
