### ISSUE TITLE
A group of airdrop hunters created by the same contract creator:

### ISSUE THREAD

**Issue by hushgif** [safe-global/safe-user-allocation-reports#236]
# Related Safe Addresses

0x1bac1284c4de3dd00304369134fff4f5abeaaf5a
0x1ddef81e9d3a5aa4d30ff740b5c9bfa66a176969
0x30c011f8b14add6c009b210aad2e084cd152f2d7
0x68b9afc779d86099fd378fc31c037e19c6cc8440
0x89e1d7759ff1c8f0283df0c17f0618caf7b694f2
0x8f24659356998ba459fea898f738362237eed53c
0x8ff7bf90a90e5da515b4e9ea086016af7e8465c1
0x976c3d006b1e3cd7ef1a4fbca9aa34b25ff07f2e
0xa58bf3fe3caedaa9738fac00857dfd9150969075
0xab6ac840a1852046c8953333fc4f869cbb64b794
0xb4e5db6ae290a8990b1316145e84db9f55993748
0xc1f19a941bbaa3aa7b70e13eed958b6744c3baf6
0xdb37c2d3825b79203bbaa71166ffdea25347b673

# Reasoning

These 13 addresses get exactly the same SAFE tokens, all of them are 636.90565915208
And they are created by the same contract address: 0x460e497744f41E80BCb0D143Ee3aCA56f25F5E52
The amount of money transferred after creation and the time are the same: Sep-02-2021 11:57:18 PM +UTC, the value is: 0
And there is only one transaction record, you can check the following link for details

# Methodology

First find the token-related addresses through the airdrop form, then check the correlation of these multi-signature wallets through etherscan and find that they are all from the same contract address:

https://etherscan.io/address/0x1bac1284c4de3dd00304369134fff4f5abeaaf5a
https://etherscan.io/address/0x1ddef81e9d3a5aa4d30ff740b5c9bfa66a176969
https://etherscan.io/address/0x30c011f8b14add6c009b210aad2e084cd152f2d7
https://etherscan.io/address/0x68b9afc779d86099fd378fc31c037e19c6cc8440
https://etherscan.io/address/0x89e1d7759ff1c8f0283df0c17f0618caf7b694f2
https://etherscan.io/address/0x8f24659356998ba459fea898f738362237eed53c
https://etherscan.io/address/0x8ff7bf90a90e5da515b4e9ea086016af7e8465c1
https://etherscan.io/address/0x976c3d006b1e3cd7ef1a4fbca9aa34b25ff07f2e
https://etherscan.io/address/0xa58bf3fe3caedaa9738fac00857dfd9150969075
https://etherscan.io/address/0xab6ac840a1852046c8953333fc4f869cbb64b794
https://etherscan.io/address/0xb4e5db6ae290a8990b1316145e84db9f55993748
https://etherscan.io/address/0xc1f19a941bbaa3aa7b70e13eed958b6744c3baf6
https://etherscan.io/address/0xdb37c2d3825b79203bbaa71166ffdea25347b673

# Safe Address
0xa3179e715A97c5aD6F0CeB76464A263A75c132F3

**Comment by tschubotz** [comment]
All these addresses have been found by another report already.
