### ISSUE TITLE
Unveil 1317 SAFEs that interacted with 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D

### ISSUE THREAD

**Issue by PulsarNetwork** [safe-global/safe-user-allocation-reports#237]
I see there are some confusion around those SAFEs that were created by the same relayer, and were mistaken as airdrop farmers. According to @tschubotz, a wallet uses a relayer to create Safes, the relayer would be the account that created all user Safes which is not airdrop farming per se.

However, I think the airdrop criteria is ambiguous about one thing:

If a Safe was created by relayer, but the user him/herself had never actually used the Safe, would that qualify the airdrop?

Why are such Safes included in the airdrop list if the user never used them? You may ask. The answer is - another "relayer" configured the Safe with 1 tx to set the owner to user. This tx qualifies the airdrop.

To prove this hypothesis, I did some analysis

# Related Safe Addresses

entire list: https://github.com/PulsarNetwork/safe-analysis/blob/main/66a0.txt

I list 10 examples here

```
0xbb7e9c0503191f7337a9b32dd6613ddcc70afe89
0x305311938fc814ec29cf89c7c945f64af6262bbc
0x7c8017cf8b8a5b14de6105500a758e39f57de068
0x05f4b2e7e1395858895c0657a572b54e43c7e129
0x21f5d99f674112b0f8132e6ed35f7d0008e074a8
0x7131e83c43d5597c46a3482b94a46514843d5f62
0xdba2abb2890d85f747497f4b4e1695e623de1b67
0xd0c7daf802dd90b55e6db99912f21c89c1cfe70b
0xab6098d02095ec4f8328f6c12c96b83fc6088ee3
0x1a92fbdd49e6258bdd771ff37d6718ad9ff96d00
```

# Reasoning

All these Safes were created by https://etherscan.io/address/0xa5b39e8438264691103ff4a35c8034658fee1227 (Etherscan tag: Rockside relayer 1) or https://etherscan.io/address/0xfc84905742406479eca0ff233f0b7be03a9c99af (Etherscan tag: Rockside relayer 6)

0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D is the "manager" of all these addresses. It was active since Feb-03-2021 until Jun-26-2021. 

The duty of the manager was, it removed itself from the owner list, and assigned a new owner after the Safe was created by the relayer. Examples picked from the top of the list:

https://etherscan.io/tx/0x2d655e576621faa006274750774abee065253526cb05510c498259e893b3818d#eventlog

https://etherscan.io/tx/0x2efec5d45a316dd9ca88f218cb1527e8a57b461b186ba78273b4f711a27fda39#eventlog

Generally, this indicates a valid use case where the protocol renounces its ownership over user's safe. However, if such an owner configuration tx is the only tx that the Safe has, should it be qualified for the airdrop? I don't think these are airdrop farmers, but neither do I think they should be qualified. I'll leave it to the team to decide.

The tenet of the airdrop is to incentivize / reward organic usage of Safe but not to send free money to whoever just happened to create a Safe without actually using it. That's why those Safes without any tx history are ineligible. Having 1 tx in Safe's tx history doesn't necessarily mean the user has ever used it for real transaction. Instead, the user may have never heard of Gnosis Safe, but just happened to create one via third-party apps.

# Methodology

1. I identified 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D (let's call it the "manager") in https://github.com/safe-global/safe-user-allocation-reports/issues/222, in which I found this address interacted with multiple Safes that have only 1 tx in the history, and those interaction times are close.
2. Using a script, transaction history of the manager is retrieved from etherscan API
3. Out of all transactions from the manager, I filter those txs calling "execTransaction" method, and record the callee addresses. These callees are the Safes.
4. Out of all Safes obtained from last step, I retrieve the tx history of these Safes from etherscan API, and filter those safes with only 1 record in the tx history.
5. Lastly, I manually checked a handful of safes to validate that the creators belonged to "Rockside" tag (there isn't a way for me to retrieve etherscan tag programmatically)

Finally, these Safes are the ones that users didn't actually interact with, but instead the manager configured the owner as the only tx in their lifetime shows. The Safes were inactive ever since then.

The script I used is https://github.com/PulsarNetwork/safe-analysis

# Safe Address

0x984129b1C8D6048DF516D81f730475AF7D0E4223

**Comment by PulsarNetwork** [comment]
Please see https://github.com/safe-global/safe-user-allocation-reports/issues/301 for more addresses with the same manager-relayer pattern

**Comment by PulsarNetwork** [comment]
Previous execution was interrupted in the middle.

I reran the script, and got 1731 Safes in the end

Results: https://github.com/PulsarNetwork/safe-analysis/blob/main/66a0-updated.txt

**Comment by PulsarNetwork** [comment]
Final results are aggregated here, and some false positives are removed: https://github.com/safe-global/safe-user-allocation-reports/issues/365

**Comment by DeveloperThing** [comment]
see https://github.com/safe-global/safe-user-allocation-reports/issues/63#issuecomment-1243398345 and https://github.com/safe-global/safe-user-allocation-reports/issues/63#issuecomment-1250258266

**Comment by PulsarNetwork** [comment]
> see [#63 (comment)](https://github.com/safe-global/safe-user-allocation-reports/issues/63#issuecomment-1243398345)

hey @DeveloperThing 

Tongue wallet is one of a few smart contract wallets using Rockside API, but not the only one.

Actually, Tongue wallet is a very small app with only a few hundred users, and it was only active late 2020 and early 2021. It was built by https://twitter.com/vincentLg if there is any uncertainty we may reach out to him directly. 

After doing more research, I found 0x66a0 belongs to StakerApp which has much more users and active till today. Please see my issue https://github.com/safe-global/safe-user-allocation-reports/issues/365

Why do I say this, you may wonder. I mistook the addresses as Tongue wallets at first lol

**Comment by tschubotz** [comment]
Thanks for this elaborate report! As you mentioned yourself, some false positives are included in this list. So there is a chance this would eliminate legitimate users. I'm closing this one and will take a closer look at the mentioned issues #301 and #365
