### ISSUE TITLE
17 airdrop hunter's safe wallets

### ISSUE THREAD

**Issue by xiaohu1882** [safe-global/safe-user-allocation-reports#238]
# Related Safe Addresses

0x0ca7f4fa293118f7f31cd8154d5242323c9e572e
0x16dd55be903e0ed4c6fbdba703c3c223b76cc8cd
0x2d83946b530b99e823e9c9896e0e0f05bd5d1fce
0x31422acef5b42363f0e3b2f9090a21367b7663db
0x3e7bd7229665d19fe319b76605edc0b437655d7b
0x52d48f2a8b8b23533a6d407d38b8a19b12ca6df3
0x53e8272301d4db1a57d3604f8b0cb1503d4cefa1
0x6b925675a51c9ff22afae5f3c2e0bbdc9d16097c
0x6d152c1191ef723876ff5fcee6c9b6acb861a73b
0x7a0c7b161f706f3d0b806e33606f623e14f94197
0x82ca887f3ce5f07dddb3f05c67b881dea9de7da9
0x8a2d1c9c8946b8efebd1994688eddd3f9822c747
0xaef10838d3b01355e2531d992f700cfb8467ea96
0xc135363f9b418740cdfd10c8b38c7ac91f215d17
0xc9b90bcf2c45b48defcadecd638c356ae949717f
0xd15c6c2848c4e132c925d55f3d6bf41799ddbe54
0xf29c1553a5d815148ea6b6dfe29abfe181c019b6

# Reasoning

1. Those17 safe wallets have the same amount of rewards 647.3899846506166. And they also have similar behaviors which happened almost at the same time. Only address "0xb52f4d17f2a70fe4492e784c52e9c7f0e9ac7402" interacted with those wallets. 

https://etherscan.io/address/0x0ca7f4fa293118f7f31cd8154d5242323c9e572e
https://etherscan.io/address/0x16dd55be903e0ed4c6fbdba703c3c223b76cc8cd
https://etherscan.io/address/0x2d83946b530b99e823e9c9896e0e0f05bd5d1fce
....
https://etherscan.io/address/0xf29c1553a5d815148ea6b6dfe29abfe181c019b6

2. More importantly, the creators of those wallets have the exact same transactions on chain.  I will showed some pictures below. 
You can check the transaction histories of those entities with https://etherscan.io/address/{wallet address}

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/106882397/189311561-a31df0a1-f471-4a2d-bf3b-9efa7da03ffa.png">
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/106882397/189311717-45537022-cb62-4e25-9240-1ad12db3ea66.png">
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/106882397/189312110-2c270854-f708-4525-9f4c-16f6b3bd31a0.png">
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/106882397/189312338-5264cb85-7637-4ac7-ab4e-c80fef1f045b.png">

# Methodology
Analyzed the safe wallets that have the same amount of rewards and then check the behaviors of those safe wallets.  And then found only one address interacted with those safe wallets. Besides, the creators of those safe wallets have similar on chain transacionts.

# Safe Address

0xc78CdC3dd169f1308f11a0E9Fb30d86dBfED444b

**Comment by tschubotz** [comment]
Thanks for the report. These Safes have been reported before, hence closing this issue.

**Comment by xiaohu1882** [comment]
> Thanks for the report. These Safes have been reported before, hence closing this issue.

0x53e8272301d4db1a57d3604f8b0cb1503d4cefa1
0x6b925675a51c9ff22afae5f3c2e0bbdc9d16097c
0x6d152c1191ef723876ff5fcee6c9b6acb861a73b
0x7a0c7b161f706f3d0b806e33606f623e14f94197
0x82ca887f3ce5f07dddb3f05c67b881dea9de7da9
0x8a2d1c9c8946b8efebd1994688eddd3f9822c747
0xaef10838d3b01355e2531d992f700cfb8467ea96
0xc135363f9b418740cdfd10c8b38c7ac91f215d17
0xc9b90bcf2c45b48defcadecd638c356ae949717f
0xd15c6c2848c4e132c925d55f3d6bf41799ddbe54
0xf29c1553a5d815148ea6b6dfe29abfe181c019b6

For the above 11 wallets,  I believe I found those addresses before this report https://github.com/safe-global/safe-user-allocation-reports/issues/124. 

If you check his edit histories in issue #124. you will notices that he didn't include these 11 addresses 9 days ago. 

<img width="893" alt="image" src="https://user-images.githubusercontent.com/106882397/190916914-bcb72f79-95d2-405f-bd82-5fdaaddd2c36.png">

<img width="599" alt="image" src="https://user-images.githubusercontent.com/106882397/190916943-49c10cec-1267-43b3-b12c-d98784c4adc0.png">

My edit hostories
<img width="790" alt="image" src="https://user-images.githubusercontent.com/106882397/190916981-fa89b53e-58dd-4852-9646-dd36c40a0433.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/106882397/190916996-41800c82-b1d1-45e2-ae8b-a7f00120c7a9.png">
