### ISSUE TITLE
Hunter safe addresses

### ISSUE THREAD

**Issue by sybilhunter** [safe-global/safe-user-allocation-reports#239]
0x06945a60de9fc0a5c04ca971b1abe4c918e8298f
0x1c00938031c920a8c3e7f2766f0989bbb49c82e1
0x37b5ec8652ce8a8db1db7dc6508149bbd9d55c7f
0x3e4b5342ebc0e04df4c856d9e52d47fe373fcc1f
0x4179a8d32ee15a6fbf177a42551b899f66aaad8a
0x4ada52a582c0d70e8e756856d29b76baf044c464
0x4fa84117532dd6fb42781ea0bc047d21f1657c7e
0x5d620a8afc4284dbeee44c62027d3e95e2633897
0x62814d379bd3687d3070235b77c99a75569c5cd4
0x664a0e6fb3cdc5c2e816359cd81cbc8095351fc6
0x6a12e4725273c9fb009a6b665a8a2508c0ea73df
0x6a83a974d55b9fb64b2ca256d6bca71d3026af98
0x702bb8219614825c61a0c60f963c8eceeb30e550
0x81c42352cac4a1af5907d3d8b47de6cf00d9d027
0x8f77308af6d111c879d57458496bb226b9c43872
0xb4d0b774b2225bb624ad48e24092ead5f478c94e
0xb61f45381aac141e4bcb1403e9bff4204ca463c8
0xbc5a39e27fa00ac26632c631b826f26cc0bb8fac
0xd0090bf962b05c03668998a3c7602b95e57a9af4
0xd32dbab5cb5efa2ef618ec86bb1d48619b621a63
0xe597b57a6774e10450b07a5aa76cfd17d7508385
0xe6e1b857aca58893f428019eba140a1d7e2a3322
0xf0a6b40353b6e88cb9304e7218b53855a077265a

**Comment by sybilhunter** [comment]
0x0db185eb4b9509492096c17d3c9e046bdfd6ffc2
0x2923d896e67f9e658cc9e6e1fa3c1d3cd4dd8330
0x487f8846a018cfc67d774f9e1c71742a2597c942
0x56d9ab7f00856e0259fdf68e3111eebb702c840c
0x5f630145bffe2b0a2fca4e82a236815f34e096a2
0x71c8e4899ac173156f115d7f6db261168e573673
0x85927aefdcfd6d78c1dcebb40d28f5a9c4086464
0xa7ec84b39670627dcb1816d4390d4b22c5783f63
0xc1834cbfa6121b21374e827af71192031a3c41e1
0xe62e6d9aba7446390c7049c17c4f83c9f418a2dd

**Comment by tschubotz** [comment]
This report doesn't use the report template and doesn't contain reasoning and methodology.
