### ISSUE TITLE
0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C04

### ISSUE THREAD

**Issue by MisakaCenter** [safe-global/safe-user-allocation-reports#24]
# Related Safe Addresses

```
0x4c772b7025696ae8a8ea9b6cbd28b17ba408f10d
0x4110e87896ba59b59852740744f1debcd8957212
0x54d0aafd908983a96156d98906afbe66b3fb901b
0x175f064566e8994733feb3a87a7076d6999f1014
0x36305683abe9a7bb74d5060f26303e4a92afcf76
0x30415a59f058659870307d0bd1d86073f82dcabe
0x8fffaec3b4c3eb69b144d541ec59677572a1957c
0xfebe2b6af497b9ac2d17eb008314dd1cf1c6a7aa
0xdea4540cf784eedd4abd9ef0cf6ac8e0fd040d57
0x807ef5e50a6a68fc485488c907099daf6a2d2a21
0x8a7e2f5522a2b88c304b6e55012e4de998b9e13e
0xbdb1759712a7940f5509a8898e17bc7fefc575fb
0xd214bc9f411d6f92ece8eca1af56a2c0bb913afb
0x116a2b47de982bfd773b14a3e8c8c76e41370f96
0x1c95139a844259f2553f9b2b637bc40cf75326df
0xf5390a093b960af510c1565e0ca846ddbe9434d6
0x3067414f0967df2e2468882af986b0b564c3a6d9
0xe6b44a6481fcaa6c2035d4bfa7ac68269afd4cb5
0xb81617efd1ef1d4f7b9986f35a8b557c6ff323da
0x8d1a17b25b5d867ae5b230419130b7b50296702f
0xcd201948494f4cc10f4a0a226ff89292cb70cb6a
0x35803fafd46790e847d3695051cb1218d049b633
0x75f175c2af6887805f43c010d2867d20b57a93d1
0x7164dd96bd893c9d4366bf6cc4dcb9e93e8182f6
0x3a615f5732b1dbeb93dfe6017ae10c7ea20eaa90
0x65269102997dce692fef1e2c6919363292db8ab9
0x3b5f1a9e08dfeb03002e07fbc0727525559138d2
0x15c3f46a8ff4722d1f3d3946b5a56fd7b681d2fd
0xed9a0b641ffb13f4e55f04dc1e533033d15fcfe3
0x322851cd0718619b5d1c11400ab4d7d82fabfb54
0x97b14970dd2bbfe9c35cd98b4b194a8dca1db1ab
0xe91b29e483789ceca58c76bedad515f18a568eb0
0x92006804baa3ae202c3b377234e6177c2b465eed
0x36af31222f71e120840651b28bc63d32508e96e4
0xa3ce148c6260816cf90619f76b446c174ba47b3c
0x80e766ac23ff449a77551e7b1c57f1640b15874f
0xa494159efed07ffd1067049c2f610418fe61a332
0x765e27419750d8c915f5112658602503ca1d57fd
0xb8cbc29faf29c32625f25a391993b993a33b132b
0x68a90b88c092d6601894d8d9bebe6547119d54e9
0xd0208523563a28ef547cfa0d7baae41c2b406ed8
0x83f11092798324e76a5d5feaf3e6ee87cac2fa5f
0x89d86e8461bfe282342761652f3d13cdc58ec9af
0xac12e98a058248a996adf9a8e31176f287510778
0x46bf5165a1b1597d85703e615a0f406525fd4530
0xf143ed827c31c7f519445bcfa09281ec36b87c0c
0x2d61101b595111b0df83381730a8c5a762a93773
0x4bb8ecd67a169745de327e7e8d6dba35a7ab406c
0xc093eb788a0377b0edbc4b89d3d559c574e49a82
0xd8f493cb313139d1bc727da3ada325131d3333fb
0xf9138b750d72208baf94478ddd1a20900c64143f
0x0ffc126b095525a36a69d3db9b91426257386b88
0x2dcfa65f1fa4370abf709e467bd47a924c95f23f

```

# Reasoning

all created by 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C04

# Methodology

with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C04')

**Comment by MisakaCenter** [comment]
1. all safe multisig wallets created have no balance && only contain <5~10 transactions.
2. they are all created in 200~150 days ago, in a row.
3. It's weird for a relayer only have ~430 transactions.

**Comment by MisakaCenter** [comment]
Also, it's a non-contract address. It must be an airdrop farmer who doesn't actually use these wallets based on these wallets are seldomly used.

**Comment by MisakaCenter** [comment]
my safe address:
eth:0xc7495E1c9A62e74473d890eaE40537713AAC73f7

**Comment by MisakaCenter** [comment]
I make a detailed investigation for all the addresses I mentioned in this PR, and the result is shown below:

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



index | address | entity | entity_cat | tx_count | current_balance | tx_first_datetime | tx_last_datetime | TIME diff | reason
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
15 | 0xf9138b750d72208baf94478ddd1a20900c64143f |   |   | 3 | 0 | 2022-04-27 01:38:57 | 2022-04-27 01:39:30 | 0.000382 | Very short time between transactions, never used again after swiping transactions
6 | 0x54d0aafd908983a96156d98906afbe66b3fb901b |   |   | 3 | 0 | 2022-03-30 12:53:54 | 2022-03-30 12:54:36 | 0.000486 | Very short time between transactions, never used again after swiping transactions
1 | 0x3067414f0967df2e2468882af986b0b564c3a6d9 |   |   | 3 | 0 | 2022-03-21 12:59:21 | 2022-03-21 13:00:08 | 0.000544 | Very short time between transactions, never used again after swiping transactions
18 | 0xa494159efed07ffd1067049c2f610418fe61a332 |   |   | 2 | 0 | 2022-04-10 13:46:07 | 2022-04-10 13:46:56 | 0.000567 | Very short time between transactions, never used again after swiping transactions
30 | 0xc093eb788a0377b0edbc4b89d3d559c574e49a82 |   |   | 3 | 0 | 2022-04-21 21:11:17 | 2022-04-21 21:12:08 | 0.00059 | Very short time between transactions, never used again after swiping transactions
40 | 0x30415a59f058659870307d0bd1d86073f82dcabe |   |   | 2 | 0 | 2022-05-04 14:14:28 | 2022-05-04 14:15:19 | 0.00059 | Very short time between transactions, never used again after swiping transactions
7 | 0xd8f493cb313139d1bc727da3ada325131d3333fb |   |   | 2 | 0 | 2022-03-24 05:26:01 | 2022-03-24 05:26:54 | 0.000613 | Very short time between transactions, never used again after swiping transactions
48 | 0xd214bc9f411d6f92ece8eca1af56a2c0bb913afb |   |   | 3 | 0 | 2022-04-27 01:11:22 | 2022-04-27 01:12:15 | 0.000613 | Very short time between transactions, never used again after swiping transactions
39 | 0x65269102997dce692fef1e2c6919363292db8ab9 |   |   | 2 | 0 | 2022-04-19 05:42:55 | 2022-04-19 05:43:50 | 0.000637 | Very short time between transactions, never used again after swiping transactions
45 | 0x75f175c2af6887805f43c010d2867d20b57a93d1 |   |   | 3 | 0 | 2022-03-23 01:09:40 | 2022-03-23 01:10:35 | 0.000637 | Very short time between transactions, never used again after swiping transactions
27 | 0xb8cbc29faf29c32625f25a391993b993a33b132b |   |   | 3 | 0 | 2022-03-29 12:31:41 | 2022-03-29 12:32:38 | 0.00066 | Very short time between transactions, never used again after swiping transactions
32 | 0x0ffc126b095525a36a69d3db9b91426257386b88 |   |   | 2 | 0 | 2022-05-10 12:18:24 | 2022-05-10 12:19:24 | 0.000694 | Very short time between transactions, never used again after swiping transactions
2 | 0x83f11092798324e76a5d5feaf3e6ee87cac2fa5f |   |   | 3 | 0 | 2022-04-27 01:33:53 | 2022-04-27 01:34:54 | 0.000706 | Very short time between transactions, never used again after swiping transactions
29 | 0xf5390a093b960af510c1565e0ca846ddbe9434d6 |   |   | 2 | 0 | 2022-03-31 03:33:57 | 2022-03-31 03:35:01 | 0.000741 | Very short time between transactions, never used again after swiping transactions
4 | 0x3b5f1a9e08dfeb03002e07fbc0727525559138d2 |   |   | 3 | 0 | 2022-03-29 12:37:53 | 2022-03-29 12:39:00 | 0.000775 | Very short time between transactions, never used again after swiping transactions
37 | 0xe6b44a6481fcaa6c2035d4bfa7ac68269afd4cb5 |   |   | 3 | 0 | 2022-03-23 01:12:34 | 2022-03-23 01:13:41 | 0.000775 | Very short time between transactions, never used again after swiping transactions
46 | 0x765e27419750d8c915f5112658602503ca1d57fd |   |   | 3 | 0 | 2022-03-30 12:29:36 | 2022-03-30 12:30:44 | 0.000787 | Very short time between transactions, never used again after swiping transactions
24 | 0x1c95139a844259f2553f9b2b637bc40cf75326df |   |   | 3 | 0 | 2022-02-10 04:13:32 | 2022-02-10 04:14:42 | 0.00081 | Very short time between transactions, never used again after swiping transactions
49 | 0x3a615f5732b1dbeb93dfe6017ae10c7ea20eaa90 |   |   | 3 | 0 | 2022-05-04 13:59:05 | 2022-05-04 14:00:20 | 0.000868 | Very short time between transactions, never used again after swiping transactions
25 | 0x8d1a17b25b5d867ae5b230419130b7b50296702f |   |   | 3 | 0 | 2022-03-22 13:08:31 | 2022-03-22 13:09:49 | 0.000903 | Very short time between transactions, never used again after swiping transactions
5 | 0x116a2b47de982bfd773b14a3e8c8c76e41370f96 |   |   | 3 | 0 | 2022-03-29 13:16:42 | 2022-03-29 13:18:21 | 0.001146 | Very short time between transactions, never used again after swiping transactions
26 | 0xcd201948494f4cc10f4a0a226ff89292cb70cb6a |   |   | 2 | 0 | 2022-03-19 01:06:11 | 2022-03-19 01:08:00 | 0.001262 | Very short time between transactions, never used again after swiping transactions
10 | 0x92006804baa3ae202c3b377234e6177c2b465eed |   |   | 3 | 0 | 2022-04-26 05:13:42 | 2022-04-26 05:15:32 | 0.001273 | Very short time between transactions, never used again after swiping transactions
17 | 0x4c772b7025696ae8a8ea9b6cbd28b17ba408f10d |   |   | 3 | 0 | 2022-05-05 04:56:50 | 2022-05-05 04:58:58 | 0.001481 | Very short time between transactions, never used again after swiping transactions
47 | 0xb81617efd1ef1d4f7b9986f35a8b557c6ff323da |   |   | 3 | 0 | 2022-03-30 13:00:40 | 2022-03-30 13:02:59 | 0.001609 | Very short time between transactions, never used again after swiping transactions
36 | 0x89d86e8461bfe282342761652f3d13cdc58ec9af |   |   | 3 | 0 | 2022-03-22 23:08:13 | 2022-03-22 23:10:34 | 0.001632 | Very short time between transactions, never used again after swiping transactions
44 | 0x8fffaec3b4c3eb69b144d541ec59677572a1957c |   |   | 3 | 0 | 2021-12-25 12:27:42 | 2021-12-25 12:30:32 | 0.001968 | Very short time between transactions, never used again after swiping transactions
3 | 0x807ef5e50a6a68fc485488c907099daf6a2d2a21 |   |   | 3 | 0 | 2022-05-05 06:15:57 | 2022-05-05 06:22:09 | 0.004306 | Very short time between transactions, never used again after swiping transactions
19 | 0x175f064566e8994733feb3a87a7076d6999f1014 |   |   | 4 | 0 | 2022-03-18 12:27:32 | 2022-03-22 03:31:41 | 3.627882 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C04, alextaub.eth. for the number of transactions swiped
23 | 0x35803fafd46790e847d3695051cb1218d049b633 |   |   | 5 | 0 | 2021-12-15 11:12:14 | 2021-12-22 00:39:13 | 6.560405 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C05, alextaub.eth. for the number of transactions swiped
28 | 0x97b14970dd2bbfe9c35cd98b4b194a8dca1db1ab |   |   | 5 | 0 | 2022-03-22 13:11:50 | 2022-03-29 03:18:03 | 6.58765 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C06, alextaub.eth. for the number of transactions swiped
35 | 0x46bf5165a1b1597d85703e615a0f406525fd4530 |   |   | 6 | 0 | 2022-02-15 12:03:11 | 2022-02-26 07:14:43 | 10.79968 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C07, alextaub.eth. for the number of transactions swiped
16 | 0x2dcfa65f1fa4370abf709e467bd47a924c95f23f |   |   | 13 | 0 | 2022-04-04 12:30:06 | 2022-04-21 02:45:47 | 16.59422 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C08, alextaub.eth. for the number of transactions swiped
38 | 0xed9a0b641ffb13f4e55f04dc1e533033d15fcfe3 |   |   | 6 | 0 | 2022-03-30 12:47:27 | 2022-04-25 23:16:58 | 26.43716 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C09, alextaub.eth. for the number of transactions swiped
41 | 0xac12e98a058248a996adf9a8e31176f287510778 |   |   | 30 | 0 | 2022-05-04 01:50:03 | 2022-05-31 07:02:51 | 27.21722 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C10, alextaub.eth. for the number of transactions swiped
8 | 0xfebe2b6af497b9ac2d17eb008314dd1cf1c6a7aa |   |   | 6 | 0 | 2022-04-20 12:42:42 | 2022-05-19 03:07:46 | 28.60074 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C11, alextaub.eth. for the number of transactions swiped
34 | 0xdea4540cf784eedd4abd9ef0cf6ac8e0fd040d57 |   |   | 10 | 0 | 2021-12-18 09:39:09 | 2022-01-24 03:43:57 | 36.75333 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C12, alextaub.eth. for the number of transactions swiped
9 | 0xe91b29e483789ceca58c76bedad515f18a568eb0 |   |   | 30 | 0 | 2022-01-26 14:17:47 | 2022-04-02 04:10:30 | 65.57828 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C13, alextaub.eth. for the number of transactions swiped
12 | 0xd0208523563a28ef547cfa0d7baae41c2b406ed8 |   |   | 21 | 0 | 2022-05-04 14:11:19 | 2022-07-25 15:49:16 | 82.06802 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C14, alextaub.eth. for the number of transactions swiped
51 | 0x8a7e2f5522a2b88c304b6e55012e4de998b9e13e |   |   | 12 | 0 | 2022-05-10 12:41:07 | 2022-08-03 22:56:41 | 85.42748 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C15, alextaub.eth. for the number of transactions swiped
11 | 0x2d61101b595111b0df83381730a8c5a762a93773 |   |   | 66 | 0 | 2022-04-11 00:32:27 | 2022-07-19 09:13:30 | 99.36184 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C16, alextaub.eth. for the number of transactions swiped
31 | 0x4bb8ecd67a169745de327e7e8d6dba35a7ab406c |   |   | 15 | 0 | 2022-01-04 03:29:40 | 2022-05-03 10:17:26 | 119.2832 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C17, alextaub.eth. for the number of transactions swiped
33 | 0xa3ce148c6260816cf90619f76b446c174ba47b3c |   |   | 66 | 0 | 2022-01-12 05:32:15 | 2022-05-25 22:21:54 | 133.7011 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C18, alextaub.eth. for the number of transactions swiped
22 | 0xf143ed827c31c7f519445bcfa09281ec36b87c0c |   |   | 24 | 0 | 2022-04-20 04:05:53 | 2022-09-08 08:19:34 | 141.1762 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C19, alextaub.eth. for the number of transactions swiped
13 | 0x36af31222f71e120840651b28bc63d32508e96e4 |   |   | 48 | 0 | 2022-03-30 12:15:36 | 2022-08-23 00:36:45 | 145.5147 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C20, alextaub.eth. for the number of transactions swiped
53 | 0x68a90b88c092d6601894d8d9bebe6547119d54e9 |   |   | 96 | 0 | 2022-03-24 21:55:03 | 2022-09-07 23:08:12 | 167.0508 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C21, alextaub.eth. for the number of transactions swiped
50 | 0x80e766ac23ff449a77551e7b1c57f1640b15874f |   |   | 54 | 0 | 2021-12-15 11:22:04 | 2022-06-03 11:38:41 | 170.0115 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C22, alextaub.eth. for the number of transactions swiped
43 | 0xbdb1759712a7940f5509a8898e17bc7fefc575fb |   |   | 97 | 0 | 2022-02-15 11:57:19 | 2022-08-29 07:30:59 | 194.815 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C23, alextaub.eth. for the number of transactions swiped
20 | 0x7164dd96bd893c9d4366bf6cc4dcb9e93e8182f6 |   |   | 31 | 0 | 2021-12-25 12:35:59 | 2022-07-30 03:51:42 | 216.6359 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C24, alextaub.eth. for the number of transactions swiped
14 | 0x322851cd0718619b5d1c11400ab4d7d82fabfb54 |   |   | 45 | 0 | 2022-01-12 06:04:29 | 2022-09-06 02:26:45 | 236.8488 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C25, alextaub.eth. for the number of transactions swiped
42 | 0x36305683abe9a7bb74d5060f26303e4a92afcf76 |   |   | 72 | 0 | 2021-11-18 14:52:24 | 2022-07-30 02:51:50 | 253.4996 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C26, alextaub.eth. for the number of transactions swiped
52 | 0x4110e87896ba59b59852740744f1debcd8957212 |   |   | 23 | 0 | 2021-12-07 23:19:14 | 2022-08-22 23:46:58 | 258.0193 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C27, alextaub.eth. for the number of transactions swiped
21 | 0x15c3f46a8ff4722d1f3d3946b5a56fd7b681d2fd |   |   | 107 | 0 | 2021-11-23 11:43:41 | 2022-09-02 04:37:48 | 282.7042 | No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C28, alextaub.eth. for the number of transactions swiped



</body>

</html>

**Comment by MisakaCenter** [comment]
Here is the result file (just as same as markdown, but easier to edit)
[result.zip](https://github.com/safe-global/safe-user-allocation-reports/files/9535913/result.zip)

**Comment by MisakaCenter** [comment]
cc @tschubotz  I think this one is with solid & clear proof now.

**Comment by tschubotz** [comment]
Looking at the initial list of Safes, I've checked the following 3:

```
0x36305683abe9a7bb74d5060f26303e4a92afcf76
0x15c3f46a8ff4722d1f3d3946b5a56fd7b681d2fd
0x68a90b88c092d6601894d8d9bebe6547119d54e9
```

Your reasoning is based on timing and number txs. The user seems to use batching quite a bit which is one of the core features of the Safes. I'm unable to follow with your reasoning that this is airdrop farming. There is a chance that this would eliminate at least some legitimate usage. Hence I'm closing this.

**Comment by MisakaCenter** [comment]
> No actual transactions are generated, and the interaction address only exists for the remaining 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C21, alextaub.eth. for the number of transactions swiped

My reasoning is based on timing, number txs and *who they are interacted with*. I have mentioned that these wallets only interact with 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C28 and alextaub.eth.

**Comment by MisakaCenter** [comment]
please check this evidence I provided (in case you didn't see it). **who they interacted with** is the key point of my report.
cc @tschubotz
