### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by Snrat** [safe-global/safe-user-allocation-reports#242]
# Related Safe Addresses

Provide a list of Safe addresses that would currently receive a SAFE user allocation.

```
0x30415a59f058659870307d0bd1d86073f82dcabe
0xa494159efed07ffd1067049c2f610418fe61a332
0xf5390a093b960af510c1565e0ca846ddbe9434d6
0x0ffc126b095525a36a69d3db9b91426257386b88
0x5b575f0c9c1aef1ac6fb5a998d21fbfb8a235f86
0xb65913cafc6c666868c53bf2484f4c696ab8ca0b
0xd8f493cb313139d1bc727da3ada325131d3333fb
0x44f50a1212fea781c0a382390a6bc91d33a66ed3
0x116a2b47de982bfd773b14a3e8c8c76e41370f96
0x3067414f0967df2e2468882af986b0b564c3a6d9
0x3a615f5732b1dbeb93dfe6017ae10c7ea20eaa90
0x3b5f1a9e08dfeb03002e07fbc0727525559138d2
0x4c772b7025696ae8a8ea9b6cbd28b17ba408f10d
0x54d0aafd908983a96156d98906afbe66b3fb901b
0x6157438b82edcb1c1ba7a4332a02e8d00b7ccc20
0x75f175c2af6887805f43c010d2867d20b57a93d1
0x765e27419750d8c915f5112658602503ca1d57fd
0x807ef5e50a6a68fc485488c907099daf6a2d2a21
0x83f11092798324e76a5d5feaf3e6ee87cac2fa5f
0x89d86e8461bfe282342761652f3d13cdc58ec9af
0x8d1a17b25b5d867ae5b230419130b7b50296702f
0x92006804baa3ae202c3b377234e6177c2b465eed
0x9ee36996a48b07d33dad33e8bf3b737510dbd3f4
0x9f89d33ef6376498465974cedfcb91ecdbdcf44b
0xb81617efd1ef1d4f7b9986f35a8b557c6ff323da
0xb8cbc29faf29c32625f25a391993b993a33b132b
0xc093eb788a0377b0edbc4b89d3d559c574e49a82
0xcce55049d4210bccf57631e5690c4afa58b569bd
0xd214bc9f411d6f92ece8eca1af56a2c0bb913afb
0xd6081dd70267f6e5a3d28ba4cdcc5e7804f703c3
0xe6b44a6481fcaa6c2035d4bfa7ac68269afd4cb5
0xf9138b750d72208baf94478ddd1a20900c64143f

```

# Reasoning

All interacted with the same personal address.
Don't actually use the vault, just create it.
Own by two same address and a random address. 
0x36392A7242cAb77D7A5cb00a6A177aE5EdEEf01b
------------

# Methodology

Explain the method used to discover the addresses and provide proof that they are all related and likely operated by a single individual/entity with a high degree of probability. The methodology should be easy to verify or the report will not be considered. Please, also include links to any additional materials you’d like to provide like a github repo containing the script used to uncover the reported addresses.

I sorted the excel sheet by the amount of eligible SAFE tokens. I identified that there are some addresses eligible of exactly the same amount of tokens. After manually checking etherscan tx history, I found these addresses with exact same activity pattern.
I created a table to count all the vault owners, by time and quantity and by human inquiry.
# Safe Address

Please provide a Safe address or ENS name of a Mainnet Safe that will receive any potential rewards earned from this submission.

`0x804709550560A6E4bFF44355A57900924681264E`

**Comment by skydotone** [comment]
@tschubotz
Why don't you check my issue?
I have spent a lot of time, experience, to present the most concise way, you skip!

**You don't even reply to me!!!**

**Comment by tschubotz** [comment]
Checking the first 2

```
0x30415a59f058659870307d0bd1d86073f82dcabe
0xa494159efed07ffd1067049c2f610418fe61a332
```

> # Reasoning
> ## All interacted with the same personal address.

What does this mean?

> Don't actually use the vault, just create it.

Both Safes above made 1 tx after creation

> Own by two same address and a random address.
> 0x36392A7242cAb77D7A5cb00a6A177aE5EdEEf01b

Owning several Safes is not airdrop farming per se but quite common. Please elaborate on how this is airdrop farming and how you can be sure to no eliminate legitimate usage.

**Comment by Snrat** [comment]
I understand what you mean, so I will tell you more about these vault.
1.They have created by 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C04 or 0xEadb10137e4d7EB2D1c7612B6f9cBD5958ABB10b[jadan.eth].
2.They all have 2 or 3 actions(Create; Add Member 0xA494876207Ae80D8669Dd347Fe11Fadae31c48E7[alextaub.eth], 0x36392A7242cAb77D7A5cb00a6A177aE5EdEEf01b[jadan.eth] or 0x536477541741334A42c4495cFAd651D14B1a0381 and one/two erc20-contract address/random address; Move self owner)
3.The erc20-contract was all created by 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C04. nearly the time of creating the vault
4.0xEadb10137e4d7EB2D1c7612B6f9cBD5958ABB10b[jadan.eth] received ETH from 0x94cd68f311901d7cC151C48c62FA8cbdcA6d2C04 any times like https://etherscan.io/tx/0x2fa04c760fc64dbb7f67a2ddef4596955f684bc1493759340d3b7658e94332ee ;
Also received ETH from 0xA494876207Ae80D8669Dd347Fe11Fadae31c48E7[alextaub.eth] any times like https://etherscan.io/tx/0xe2e3c1e1dd6a3baf0400808bdc096bba097f0d2a6869dd1dd31a737c75b34e81 
5.0x536477541741334A42c4495cFAd651D14B1a0381 received ETH from 0xEadb10137e4d7EB2D1c7612B6f9cBD5958ABB10b[jadan.eth] any times like https://etherscan.io/address/0x536477541741334A42c4495cFAd651D14B1a0381
5.Firstly, he create an erc-20 contract, and set it  been an owner, but then he chose ramdon address, since he doesn't keep any assets in the vault, it doesn't have any risk
6.0x9f89D33ef6376498465974CedFcb91EcdBDCf44b is the vault he actually used; he created so many vaults to get airdrops, and even tried to circumvent checks by having different owner addresses, which was pretty obvious cheating.

**Comment by MisakaCenter** [comment]
@tschubotz  please check #24 . I have already done a deep investigation into this address.

**Comment by tschubotz** [comment]
Closing this one since #24 is closed too.
