### ISSUE TITLE
Report Vault Ownd by 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d

### ISSUE THREAD

**Issue by Snrat** [safe-global/safe-user-allocation-reports#246]
# Related Safe Addresses

Provide a list of Safe addresses that would currently receive a SAFE user allocation.

```
0x009f78ef7f7433d8d3b6ea51fed051361626d556
0x2d0325c5daf57ca5e4fef23d22073a9f94eee057
0x73da4f5fc3bcdbb94349c4bfa2be473f8e43a7d7
0xb1399667a1dffb6edf091a8b46e4b5ba3829a115
0xdd5726f504f2fa242f545fc29467be03082ade10
0xe1db59e43c414abca9ba1fc784eeb1a79a5cd10c
0x03154d383d10852afc8ad9f8c51bd501436ab211
0x5b2c7292ad5a65301d565d43534e15dda27e845e
0x6e7e0d2b1579fc3288960f6284f31c4ee24f86ef
0xce6cbf1198fb3ce7f7f9be4c83a69ba2e35800b0
0xeaf4a1b853c09641706f36e77e612de602a9675f
```

# Reasoning

Describe how the Safe addresses are related to airdrop farming and if applicable also to each other with as much detail as possible.

1. Once the owner is 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d
2. The creation time is close
3. None of them are actually used
4. The owners are batch (close to the time) from 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d replacement for the other two address

------------

# Methodology

Explain the method used to discover the addresses and provide proof that they are all related and likely operated by a single individual/entity with a high degree of probability. The methodology should be easy to verify or the report will not be considered. Please, also include links to any additional materials you’d like to provide like a github repo containing the script used to uncover the reported addresses.

Through batch traversal vault permissions change log, I found a lot and 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d related operations. By manually checking Etherscan records, I found that they were mostly operated in bulk and had no assets.

# Safe Address

Please provide a Safe address or ENS name of a Mainnet Safe that will receive any potential rewards earned from this submission.

`0x804709550560A6E4bFF44355A57900924681264E`

**Comment by tschubotz** [comment]
Thanks for the report, we've identified the following addresses related to airdrop farming:

```
0x009f78ef7f7433d8d3b6ea51fed051361626d556
0x2d0325c5daf57ca5e4fef23d22073a9f94eee057
0x73da4f5fc3bcdbb94349c4bfa2be473f8e43a7d7
0xb1399667a1dffb6edf091a8b46e4b5ba3829a115
0xdd5726f504f2fa242f545fc29467be03082ade10
0xe1db59e43c414abca9ba1fc784eeb1a79a5cd10c
0x03154d383d10852afc8ad9f8c51bd501436ab211
0x5b2c7292ad5a65301d565d43534e15dda27e845e
0x6e7e0d2b1579fc3288960f6284f31c4ee24f86ef
0xce6cbf1198fb3ce7f7f9be4c83a69ba2e35800b0
0xeaf4a1b853c09641706f36e77e612de602a9675f
```

**Comment by d3centra** [comment]
@lukasschor I think you've mistakenly added the "Invalid report" label to this report, since it already was marked valid just hours ago

**Comment by Snrat** [comment]
@lukasschor Hi, what happened in this issue?

**Comment by lukasschor** [comment]
Sorry, fat-fingered this one!
