### ISSUE TITLE
Hunter addresses

### ISSUE THREAD

**Issue by sybilhunter** [safe-global/safe-user-allocation-reports#247]
# Related Safe Addresses

0x7b23ebcd241b360ef20797667d141d391033e8f6
0xdc44a717f3005fa1056d054904a5534d8b0bd9ce
0x22e52b001faea90588179bf4ce961ff73f99534a
0xd49da37e2c89b27d6358df36048dd5b2dc6cdff8
0x0f2daf24466fcb6898bb2cd6ec8e31089325cfc0
0xe9179c95f8e6958f7d7d932553361e8286addf93
0xbba9bfb0f7cefe755b890bdf582f94523b260f76
0xc0f773d1d12930884e3ae013e4173ad3211d2108
0xaad0ca45d8f543bac2cd35221d27bff3fb1f4679
0xe8b9ca6cb7b637b067dfe047c46f7501a6404457
0xf3a22647a4abf109dd1542d9dab4998dc27212ef
0x6684db920f87fd3ba8f35aa89397ae308c636abc
0xb47a0dca4026f3186f7aa99ea4328be66fe0cd99
0xbc052f490853da99d14cb837413d3c80c1a54ff5
0x6129217939025a4cf575a2a215301b91130871c7
0x74b504c209fc2c2956fb3745371bbc8d204c39b6
0x5f8ae1a4d621432c218ec44c20edb0ab469bcb4f
0xaa04bd0231af84a91b2ef58d69633aae9a13471c
0x89862cbbe11a0d5af808f1428c8d8542e2356044
0x1d4eefa3ebd6d6e9d13c3e43f32b127d739493f8
0xe8d601728cf47a31c0fb45fc7fcebaf3e25c5374
0x0b683590f3f6637a890a4dfa007a229f16897ff4
0x69ed884522820266f6d50c0e71e7d90ec4048cd4
0x893d2b013937f00e70bc5edc00ddfed8cdc636b0
0xe478c8f35f18d694bf85352317339a3ee17a9daa
0x2b6f8e4b67657260001962772f44339c0fb4e3fc
0xf4b0b32b9fb3d9289674424447715eb694e9974a
0x9aff41a486cb48873c4f55c8cea4bf35dee57d87
0x0f3b959a8820ae0374397baa1d5bf2f9bc0192c0
0x99c5b29d688badf230bb3b3346f42f8fe65c643d
0xbea336626a2d370f4795eb5c3ee04ad8d544853c
0x1a1da0146af964550ab620fb5278125ec2e3a7a4
0x6525617a828dadb66460eaac035b0769e11f474e
0xd29c371ce139f82e1a374cfe4a04ead91c3170b9
0x7d83873044596597226a69dea67b610f4e0b0a2a
0x5d39c755ffdb3193a42d65e13fbb0dfc0d4ee140
0x7ede32be8fff518920aca509098f874e16bea3db
0x2c637b3963f60cc8af75c41275b55ee06a848fbc
0x78b2eac3eb9eef6a90947da059ed79466a4df35a
0xf668b876db6777a62d3e1e651a4e4063c717db4e
0xbec2b75b9f14bd42f5818ffbd0455e09b0af905c
0x583f5a736f62a838fbb00b076593d588a1033674
0xea1cc8b788110f7a0cd61072785343f3147f7169
0xd110abdb22b9d09c5eeb927047fe29b206c57bab
0x04d89bceb0a3b9302735b23f0f6a3d7b0ac085c2
0xbf2a3d5911b78e36b7d5ebc65af6306c63644086
0xa9c1b95708d26afebb2a3792d3d9a692a2fae4c6
0x0eecf436974ac2f011ea9a55e72e9d597d8e20fb
0xc63fa445ef568ad20528010f7559cb2daab305fa
0xe250ac543342183c8c71d0a75e949df43b6b4e31
0x2a829f2c869b3f72478a88e2d4814a448243adb1
0xcd37dcb108d6b992e40503634263f4022761a504
0xf7248323647e47d342893fee3a237efb0c796546
0x9f6703bf9e33b14cf1dd094cfe5b16ca654bcf3d
0x5c7d903b6023834ab49f3a251f081265f2e9ea18
0x98c17ad86f6548115e732af4e90b64ded1781291
0x318a3e139614aa00508a02df3460150e88074598
0xa3f110f188cbc9af11382c30ed1796db2ed171f4
0x79f60fa06dc03da24051f59cc46663668533d0e3
0xb8da19bc85a709ee2ffb3ba8836fdb90bdd17704
0x704d676dc69bc9585d3f0e99ad8530bea86630a1
0xd27741ac18d9cb3df03ceafa605c29546b421edf
0xa5096a828fbeaf9ce329de115722c7609cef9286
0xb230e78e07339127c065dd877e357ed1cdef30a2
0xf1e9f52f4f31aeb2fb24c3cbc7db05c771679c46
0xa8c3d15ba6e0bff7e99cab85ea010e930b94ebb2
0x984e3a672be28a815594fe7694b4fbedce24a262
0xe94d259ce91020c4a07fdaec85eb9f17f9b179a5
0xeef590d31ceac4e8dfda964e9f4ed20fcb5d1765
0xc9106c4906adc0e9fcf158eafced03a672d3bed1
0xce9efd3278127af4a44101dc3cb8fbe9307d7875
0x8107cb0ba9686a4feb1c355d54b2e2535fd635f6
0x8fadf8979e57c968e53e879731cc26c9933dd532
0x0547847774be131affb807d8a77d2be55f30ab7a
0xf94f6c7d54bd766ecfa1c11df17789e969293854
0xad27c29f84400315a882901a0ac29cc43d425a3e
0x048c5abccecff12281f936a375b76773ce0ffc5e
0x5ff8d8d3bee52918bd6dfbd22030847afa4cb329
0x3c00aa36b23606e627f165caf8c2ea6eff990065
0x55cc89666309636921fe37be8316aaf701e163a4
0x0f2284ca64da38736dd089e272a04e1e58cc0e6b
0x79abf8d362bc50daea3dfacf6166459b859cd5ce
0xd529dbedcb38d4501231305c632fa8d857094cb7
0x8116aa233416b5639593ad8ecbb667e183568c55
0xca68e8b606d9f2aa650660707e4756796ac8bde1
0xd531fa380b2146027331035f7a5a2cfe0e85a052
0x20e0d4b6892fab48fee40e4fc4131e23b388a162
0x69f5a976c80865b367bc01c449bc9222f41ec606
0xed96b62a729a118c4f02ff2cb40423200abd6b08
0x2e7d966ea6f77eac66ca8bc1495e19bf1a527af8
0x66f2a2faa695dd7f171f03435649d4d5d6b6c137
0xdcb3abbec9e8e8396c75db11391b61f77586dddf
0xccbe0690160a7ab98aa211475e28497233111f4f
0xb96bd784e4ec6fd0aacffdf71d593c7019929b85
0xe6ff7cb23e34d39b71a08b855d9ec1df8daf6d1a
0x2ab8093c199cb818abe6543976356e2e8484cc87
0x1a7aa01a566fc81201f7be7c6e78339ea28aaf01
0xd2acee6474000f2dc7e45f15f822d2ba63b7e28f
0x67c002cbeb8e0ce4eadb8cd4bd1ca262f1c1e578
0x76ec326d705802b4358ff817a7d8fd70774717db
0x0d54840964b43bae903ca2dab7497dcc7bdc247b
0x651245f70040ee0ce4918aed2f5d4076ba381281
0x92b100aa3fdbe71fc8286bfa199c7cdfe63dc98c
0x346312cfc3af0135485b8d3fa153977292ae6298
0x87b03eb944eee7fe10952e217bad5b0bc4ed89c5
0x7b6ca3cac31610ddba46b4da5c356858d8f74a27
0x7d0b7f6265743c952d5107615ebbedbbc706e909
0x69f575f089742ba40946e744168167424da305a7
0xc1a144f7366560baa9daa3ca2296ae3d21389a10
0xbad208a710df50eb00a81479c9741c39b33a333e
0x6c51fa6c75121cc85c0a589a31686b6a0db9498a
0x10110a9aa2f3349d9e37221bd7598d3e9f3e58f0
0xd0d1c4c107ed1eba883cfd54c28ba265e0eaf69d
0x482b4cb3d5e25287eab66a306bb79ea8ff1416b4
0x1d27aeb6f4d86f9ba25f440bfc970465a7b5c79b
0x033d00fc07c5fd0a714c39d70ed41c2d27896259
0xb7080983ff76377acde4a8a5e94a29290c5ae91e
0xcfd12d42f07143194b486bac3f8e74706d68c5cb
0xf430fe9b620536693957b10fd01895becb030d48
0x244e765fc17cde65c8d5894bba68824eee47fdad
0x3687cfb0001ea9f6ce46f64331a75976603c08d9
0x48f7fd042bda7e19584e7d4f0ab75ed3a26409ca
0x53368b290b2188c15aeb69c6fb11b1ce15ec1e3c
0x9f4ec707be3e7c0fac801f5c676d387104212c1c
0x70da5bb760ec2718667ebd52501d8998bb5b2815
0xf6cd884abe036221605ee091d1a1f03d2833c276
0x8ceb6c7afc9b6e8f09675b0d3f6ca61689cf47e7
0x8afc1ecb235b71a080fb552fde532dfa06deeb53
0xcf8cf10f249369fcb200b02c763a7665b07d9963
0x870556b89db0d4684f2efdbe6f74d0d67cf453cb
0x9b9c078dd79b67d19a26bbd294cc11ec13dbd048
0x0d650be928f43a6d6f384c26a3ca0cb22a20f567
0x99c83c0ba6e062bcf5485df4368014d52f0fd941
0xc96e2242916abc7e1365b8bb855d719ba7ded9d7
0xe828c7a072079e42bff9fbae403cd6e90f23c730
0x709b7501ded116070fe1e5ef7b31f2c6324f5a08
0x8e1ce879e952c46682e56e484c1aca1687cc73bf

# Reasoning

These addresses all have signers from HOP's confirmed sybil [list](https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eliminatedSybilAttackers.csv).

# Methodology

Got the sybil address list from HOP, and then got all signer info of the eligible safe address via getOwners method of their contracts, and check for collision.

# Safe Address

0x565439F974b8F7Fc98F7932C4091ca84CA036A72

**Comment by sybilhunter** [comment]
A few more got accidentally dropped...

0x99fe9743c3e770801c67c82e9b4a8d18e1654015
0x3eab92956bd393c222e22a5065674075e651541d
0x7740bfda05f1148f07c06d14de1ec5f92010599d
0xdfcc527e75451e9237839a79f90d463535241e4c
0x4b151114afca39297df2c1dcc6e2083db6a82f2d
0x3e23fb99463b06faa4cd6176e89e5172ef30fba1
0x0820d420e2b117ab1bcf7419b0429d16209d985e
0x79a684767eebe458682f083bd099fe2239be2b7a
0x78e2bbbab92d313adfa7c3a78e459025600387f0
0xf31f0ebeb746cce429c9b2001f80d50065275ab4
0x0e59fdf43927d5dde3fec3c525e851948a1319fe
0x14c40ea486bcab3a89ede068a158080fdf9cfe10
0xbbdb8a7f91962123bf466a0e55a62d3cb9362c81
0x8b227db1a4b3c158785a89eb39f6dfccbd0bff0a
0xb90ad12f148dbffab6d4eaba17a44931ec9cc892
0xd5e3dd7de6088a4df46a1cbb1389928759e05a8b
0x06f0daa7146d0eaee0a04e1538e24073aaff4a1d
0x2b94fea32fbcb222eec5aeff5f1bee99e143fdfe
0xe2792f0d37f5f995c069c227de437dad47ba035e
0x68acb1b8e33f812c6eab5dfc2cf8e5db5dfcf406
0x07f48b1a03e1169c15654a47d533a699041476bc

**Comment by younuo2022** [comment]
I only have 1 gnosis-safe address, the signature wallet to generate this address was previously used HOP, why is it that some people say I am an airborne hunter, you can't report it in order to get the reward, don't report it, okay?

**Comment by younuo2022** [comment]
This table is obviously wrong and not rigorous at all, if you want to get the reward please put in the time and show real skills. I believe that the official will not let this kind of muddled people get rewarded

**Comment by lootboxer11** [comment]
This HOP list is so hilariously wrong. I've checked through this and most of these wallets only have 1 safe that they appear to be using for personal use... so where is the sybling or airdrop hunting?

**Comment by tschubotz** [comment]
I just checked a couple Safes e.g.

https://gnosis-safe.io/app/eth:0x0f2daf24466fcb6898bb2cd6ec8e31089325cfc0/transactions/history
https://gnosis-safe.io/app/eth:0xe9179c95f8e6958f7d7d932553361e8286addf93/transactions/history
https://gnosis-safe.io/app/eth:0xc0f773d1d12930884e3ae013e4173ad3211d2108/transactions/history

Looks like legitimate usage to me, I'm unable to see any pattern. 
Please elaborate on how this is airdrop farming and how you can be sure to no eliminate legitimate usage.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
