### ISSUE TITLE
Hunter addresses

### ISSUE THREAD

**Issue by sybilhunter** [safe-global/safe-user-allocation-reports#249]
# Related Safe Addresses

0xa5cdd1409bd40fd76817b936f85a539d2e72496c
0xa5cdd1409bd40fd76817b936f85a539d2e72496c
0xebd03dc9769d3b6ececb90192b1be84be8594de9
0xda868e1f8e1a4754af63907632c2b27015da078a
0xc1d905c3305e8e5713c852df0a27b86b34832f13
0x1c435160ebfcf88d98247c8b3fc366c1c154a069
0xb0ecdd2c63581e5181f727f9b58a13a719a47bad
0x0771602cbe07b110166f2c6a75c9fa09f2b0f1ed
0x66ffd3e95a222c6b84148a18b0a52b0e0c4b477e
0xede2442f70c23fcfbde099dbbafb1c0b175eeecd
0x8cb417e2a7e6658f9b1f70361c70ba90fc3939d8
0xd2aa0f4dd20c67587e061d98d1a74ff603bfba6f
0x199874b895ad562e2a294b7e4d067c879ca6db32
0x2e4de23bd96232eff0caefddc28ec84ad01d780d
0x7dc5597632176999aecce1e6ebfc4ad08ebe684b
0xdc02c33ce0d46bd1496b42858ed78e2d98f10008
0x6b56a23374ce7940f6e27f5f42ea1f7442b813c7
0x57304a59a20ddf830e233a372e7e1012a4fe5d0c
0xcb195420899b24ba074c8d3ab7684fc8c701bb56
0x55d582b3dd82c92a0e2b14a57e2019c078c62507
0x16acfaad54dfceea4ce122252e003047673f8804
0xbe2d8a239973f7d1460f3ff928786c8c62d7e4d8
0x460e7ce176b1282dbe6a930e22af1e739750e43f
0xd067b9661450b7bf87791a4123c0a61e599edf63
0xf607b187f8650b167356a1e850c97c6d3ab95c3e
0x2b6f8e4b67657260001962772f44339c0fb4e3fc
0x806dc7529c947c64c6c7eb19525c97f7f4a2dc8a
0x03a40f968be5c37bcb0dfd463e0caac24b101e9f
0x5d39c755ffdb3193a42d65e13fbb0dfc0d4ee140
0x75c5d4b456b697c9cca3daaf4c4a2392b3e1ddbb
0xbec2b75b9f14bd42f5818ffbd0455e09b0af905c
0xd3bfe8574d2f0476732acd820b93630fe7efe657
0xdc44a717f3005fa1056d054904a5534d8b0bd9ce
0x42095c257c713ee866cdca7a11cb4cdb90c3713a
0xb7080983ff76377acde4a8a5e94a29290c5ae91e
0x8ee6df8c9c943acfb76ddbc66692bd82ce3cecda
0xf430fe9b620536693957b10fd01895becb030d48
0xaf6b7badf0089461ca8e268d6d87d5779727558f
0x9f4ec707be3e7c0fac801f5c676d387104212c1c
0x8ceb6c7afc9b6e8f09675b0d3f6ca61689cf47e7
0x46554f7561be6046b610477802ea8a44d9499fa4
0x8afc1ecb235b71a080fb552fde532dfa06deeb53
0x9f6703bf9e33b14cf1dd094cfe5b16ca654bcf3d
0xe09965208e2f35114bbfe65bc8dbca885d07103f
0xb2cd19f1fadd15e54d5441d4c769efc05bc2b7ea
0xe11e6ed94d59e7c8d25e55ded1e79d8aee4a433a
0x1e9dea1cbaa1714b05957a899ca202d168738f55
0x6eb0b3c74ee88005093916b709e00dc873fc9602
0xd6b7ff538a749e0c02a263007c113240925a32c6
0xf737278d4b1b2fa719f02e9de2f1f441584ad839

# Reasoning

These addresses all have signers from OP's confirmed sybil [list](https://community.optimism.io/docs/governance/airdrop-1/#additional-sybil-filtering).

# Methodology

Got the sybil address list from OP, and then got all signer info of the eligible safe address via getOwners method of their contracts, and check for collision.

# Safe Address

0x565439F974b8F7Fc98F7932C4091ca84CA036A72

**Comment by sybilhunter** [comment]
4 more from same criteria:

0x99fe9743c3e770801c67c82e9b4a8d18e1654015
0x3eab92956bd393c222e22a5065674075e651541d
0x7740bfda05f1148f07c06d14de1ec5f92010599d
0x2b94fea32fbcb222eec5aeff5f1bee99e143fdfe

**Comment by tschubotz** [comment]
Thanks for the report. I looked at the txs of the Safe and some seem to have a little bit of a pattern. I'm however afraid that this would eliminate legitimate users.

e.g. https://gnosis-safe.io/app/eth:0xf607b187f8650b167356a1e850c97c6d3ab95c3e/transactions/history seems to be used in a legitimate way to store value.

Please elaborate on how all Safes in this list are related to airdrop farming and how you can be sure to no eliminate legitimate usage.

**Comment by lukasschor** [comment]
Just the fact that signers have been marked as sybils in other airdrops is not proof enough that they the above Safes were systematic airdrop farming. Closing this due to insufficient evidence.
