### ISSUE TITLE
13 wallets have same owner 0x00125c609527061996b1f30fccd75334495691fe

### ISSUE THREAD

**Issue by Bug-terminator** [safe-global/safe-user-allocation-reports#259]
# Related Safe Addresses
```
0xbe2aec3d9f951767034e8bce739b227f4878c3c4
0xb73532b04fb598f5d719ec40be68db02f798bcf3
0xe15161ff8bd124d1d38d7d0c36ce8a5998eb25bb
0xf9092d4ae81464c0a0430acbe1d570d04ac799ac
0x8099b697663447ed94ec028e005327765a44ba70
0xabb5de65bb69ee8e1389be0a490c8e23478ac0f4
0x4aa9ce2404aab305a0cae4ebfb7445894a2f2939

0x5eb03d359e6815d6407771ab69e80af5644104b9
0xbce9e7d8bdfb8c6b771b3d434b629bdf236830a7
0xac32a4c1719e2cce840c13933685220c287dde91
0x44c98aa6c90f530b7742b33a45d5273621e4a354
0xdb0bb1455c0cecd15c42274c03cf025cae8710d2
0x9e7a1400efd39176a32ee6e4506797dacd730bb0
```

# Reasoning
- The 13 wallets mentioned above are all empty and all have a same owner `0x00125c609527061996b1f30fccd75334495691fe`
- I seperated these wallets into 2 groups, the first group are all less than 5 txns(seems only build for the airdrop) and all executed a non-token transferred txn(only gas paid, I guess his intention was to interact with gnosis-safe), for example https://etherscan.io/tx/0xe3639bf85cce19439989f5f42af4f522f8fd2e4fde07e7367d4336875f8070bc
```
0xbe2aec3d9f951767034e8bce739b227f4878c3c4         
0xb73532b04fb598f5d719ec40be68db02f798bcf3
0xe15161ff8bd124d1d38d7d0c36ce8a5998eb25bb
0xf9092d4ae81464c0a0430acbe1d570d04ac799ac
0x8099b697663447ed94ec028e005327765a44ba70
0xabb5de65bb69ee8e1389be0a490c8e23478ac0f4
0x4aa9ce2404aab305a0cae4ebfb7445894a2f2939
```
- The second group are all less than 10 txns and all transferred a NFT(named AZP) to `0xdb0bb1455c0cecd15c42274c03cf025cae8710d2`
```
0xbce9e7d8bdfb8c6b771b3d434b629bdf236830a7--https://etherscan.io/tx/0x823817faea682aadd0f132f41eb1639cf006bf12fca889f9ea8b4172b6cbd3fb
0xac32a4c1719e2cce840c13933685220c287dde91--https://etherscan.io/tx/0x38e4fa7b94b514ad6820813acdc80d1483fa0de6af75d2fd4a8a7ca7ddf4498d
0x44c98aa6c90f530b7742b33a45d5273621e4a354--https://etherscan.io/tx/0xd9a0ef698dfb2c03c0879dee2af4f76dddb6cf93a225602c431831112c981930 and other 3 transfers
0xdb0bb1455c0cecd15c42274c03cf025cae8710d2--https://etherscan.io/tx/0xc458b6a2035bb5d908369a8edbd5c14e2240787b1e36f73e9b3665527f3408e2 and other 2 
0x9e7a1400efd39176a32ee6e4506797dacd730bb0--https://etherscan.io/tx/0x655f2a3168b93bc48aa932e810296e5738bd48dd86d10d54c67dc74e3e17a6c6
0x5eb03d359e6815d6407771ab69e80af5644104b9--destination multi-sig wallet
```
# Methodology
https://luabase.com/notebook/0f7ceb70e7184f759cc8004e363382cc

# Safe Address
`0xDAb68E3122f9153bEa7a5894580DC447C5836b8e`

**Comment by tschubotz** [comment]
From your submitted Safes, 4 have been found by another report already.

The remaining ones are:
```
0xb73532b04fb598f5d719ec40be68db02f798bcf3
0xe15161ff8bd124d1d38d7d0c36ce8a5998eb25bb
0xabb5de65bb69ee8e1389be0a490c8e23478ac0f4
0x5eb03d359e6815d6407771ab69e80af5644104b9
0xbce9e7d8bdfb8c6b771b3d434b629bdf236830a7
0xac32a4c1719e2cce840c13933685220c287dde91
0x44c98aa6c90f530b7742b33a45d5273621e4a354
0xdb0bb1455c0cecd15c42274c03cf025cae8710d2
0x9e7a1400efd39176a32ee6e4506797dacd730bb0
```

Checking the first one, it looks like several interaction with sth called Azimuth: https://gnosis-safe.io/app/eth:0xb73532b04fb598f5d719ec40be68db02f798bcf3/transactions/history




> # Reasoning
> * The 13 wallets mentioned above are all empty and all have a same owner `0x00125c609527061996b1f30fccd75334495691fe`

Owning several Safes is legitimate use, no airdrop farming per se.

> * seperated these wallets into 2 groups, the first group are all less than 5 txns(seems only build for the airdrop) and all executed a non-token transferred txn(only gas paid, I guess his intention was to interact with gnosis-safe), for example https://etherscan.io/tx/0xe3639bf85cce19439989f5f42af4f522f8fd2e4fde07e7367d4336875f8070bc

What about the other txs? There are many multisends etc. 


There is a possibility that this woud eliminate legit usage, hence marking this as invalid.
