### ISSUE TITLE
98 Safes: Report by d3centra

### ISSUE THREAD

**Issue by d3centra** [safe-global/safe-user-allocation-reports#263]
# Related Safe Addresses

0x0787b9ed69e0c9515912ff2fdd5852440ea2e07f
0x0a77cdcd1a3a8c3acac39ceb23d1c5c68dc88e7a
0x0da47ee5087f317b74feda30a813dbf58e384d2a
0x11c8e65ba81af35a91fdef0e1f2aa8bd73550bea
0x1878630f6157b03cd16898009de9924399ba8b39
0x18ddfae7f507d05fc9c24ee5726e930138c618a2
0x1f1afcc9c9a9268bacd20990442acab5a612cb26
0x22f7633603e208b5962ef1034f472a9bcf727581
0x2451c50247e101f07ce0477b795b5759c5486f01
0x26869ec98cccea8daeb147e879c90438c2faa3c6
0x2bda702aa8898497b282210d4a699cfaf6a85e8c
0x2da530ed3f443e5ec997d1a17bd9f801b8757fea
0x2e0b7c2c01af4360675aa57bc36d025fd726386e
0x2e5b2fb941bd736e59eaabba2a74f0d4bf5078bb
0x3094bbe1262062a1780d58bd0f364fa1d9086898
0x317b5f878e7e6eff22163fbf5c88813b1b79ad76
0x3422425bd2d1903821bad16eccc0256ba5186873
0x39272828cbe580f28e1ef14cf29fd6adc9206841
0x3a8c465007e2c94ef03ca86c3fa9f7e793bf15c4
0x3b6c7a50456f283d95005d09b0f7be12c23880d8
0x43c7c80d0c63097f545658316d50aaa22de1a0a7
0x44b2827347d38d39ad12cbd14f39c34297225282
0x452ab093ea785cd7189a5d23ba702457d1432ebd
0x46657e0be695cf6f1a3ec20291510f16fc6d9d50
0x47120dcb4e16391dd6dc29ef4eb56871ad2ed16f
0x4e3b787a5b929bd22c5c730ff5704d444822b23c
0x4ee231030706554d772039bd5d103e5436c1dfdd
0x5113b60a2196820f1d3840dce7e45b64b1074b5d
0x53db5919420b27ebd14579a4af52aa6a518c2d9d
0x53f6e3f986b2d78c57c9bb26860e1703db39d3dc
0x54d98484c1a2b5f7d8ab4289eaa93c1d5700765d
0x5888cd2c4a26abf5ea49d58692d73faa64dc10d9
0x5dbb573a23f959179ce0528d5a77e3fa9adaf6fe
0x5dcbf03be1aaf7fb60266150d2cacd5fe3aa0c9f
0x6445df1689a681af1e71a6569d59474fa55090f3
0x65f6a316ea2dde0dbbf368c65e038a2ddd860278
0x6865f20d582bc39f0883b3d7c71ca77348b74c84
0x6cae282513961c0af64c94bd0d8df7753088f7fa
0x70a61f046a571a8a473ef549dc3c6f6d45868f37
0x70b033e54ace30b36d43af3edc0be21735497a12
0x725858cbb320b34f00cb4ece6245ff6a42768d7c
0x72dce054e8f5ec4c9c98b22ba5158100ec07b086
0x74502537f4f5fdc4719e2894c131e661757038e7
0x74e586bcf7563db1858d048f65c00031051af4ad
0x781e9c916992acb9661806beeb9ccbd9ce78f80f
0x7c8837986d8f32802411c69377f1868d2ff79077
0x80957c8e83eddbec32e4bc9885c29740b3bfadd2
0x848a62a680adac2d62aedc23a2c31bebd00b5133
0x849633fb6c2a9514f449c506b8ba543b94d43f07
0x852891d10515360ae025668fcc93d6232fe1cd75
0x89ae88cc751a8ba5d225a4a869817aa6a1355a33
0x89f9ecf1462de1e6421b906589751946c95f497a
0x8c099c30dd4e4a85f326af9c6ea9a6847da54337
0x91f7e30abc8b4301a8cefd3eda2b21c7886af2b7
0x9698b287a65d6132198e16025beaa588fe447c33
0x9cd2f5dff36110dbeb78c2115f7a3064af6fc968
0x9e60df1898d70b9858ada5dd85b2fa70382ee703
0xa5de681c8ed20a89426959b731bd0e9952d7f873
0xa632e7007f10f362f528626385a19ab9bb62bf48
0xa9f405b6975314d13be372375a16f1488b93d2fb
0xab106e1705edd61ce3575c2168c17f3bba1f4d42
0xab3baaba75fd8230e147fa95a9464ba42c28cddb
0xac0dea79df0ea7d48738d97e664e58037ef0546c
0xae5690b829fff0d3458a9afaeddbd85eb455dc01
0xaee719f06b54bb68622bb71ac4ab4be29ab3e658
0xaf2fb67d0e7623090f627ed46d014adae9b7b866
0xb2c33a65f5de4d06cb43229fca2e3869c3f0aa78
0xb52326488c4a9902bf18c94ac3d8e6fbeb71bfdd
0xb66bf8189d63c115b128d5530f759692b6c80159
0xb79de3f91b80e4b34172a5b9cd92b15c377acfae
0xbbb462f440caff23c05151289247a31c1a8f2d08
0xbef7f91eb55b65df4a76446b8e3accc50823d59e
0xbf34e690d8a8ba315ed77e89aa7bb9271b7ae5e9
0xc0b287725ea4019cf53903af95ea13086a88dce8
0xc3c7e7ef1aef44f8255b2e29694526e99503c7be
0xc785d6ab1e0c493b6bdbf7468b840179feea657a
0xca6421f261243546910f16a38d986458eac2d601
0xcb7d6582a9f06f6cd1cdc82a802d89f1349dbd2d
0xcbe4c5f6312cb8dd7357af27b44f093d1a1fdd8f
0xd22fd8327d004cb254616134f235df78c04e1d22
0xd34c84ccdde541dd5b45680b570f46041bac91e1
0xd404bdf95da413681c8196702b70491fa6d02ab9
0xd4461b17502960c979db2dec7c238ea85d510a9a
0xd5b355e740a4920fcb522c36f1b07966361815cb
0xd98b474c95d5fbab38dd9dd6d4d53cc193d769ab
0xdc275db516d2e46e145146c1d01eb36aa8864d8b
0xe330a9914b7acff273230a51e78b080dd3ae7d14
0xe355fe9d087e9aa1122b9709399ec9bc535ae00d
0xe8143edb2b419eb061d1926b02deb71097213546
0xed22677e28398659e1bec73ed7b3aad6f9e7b37d
0xee32ea0cb497632f741fa1d20fe5a674a674c1a7
0xef0daf615b4e9b13b028ed0f924842a5350df54d
0xf038b693c95436493a3f1b833d8ffeed8e28997d
0xf3cc82dccea613ee135b6b3a90bae8b6edd597e4
0xf42479a66bb6b9859f7ba387a391069ed4b00725
0xf70f7b88d82e2f91329dfa1f94ef6ca62f4deb40
0xf94fc2c691823bb2712ed9a5e42e4f1a7f7fba75
0xfaf9aa7d34eb83090ddfd3e48d2c111651cb6347

# Reasoning

All 98 Safes were created by the same address (0x58A0Dc767EF35AD853B258E783D610bFC7205039), have a "swapOwner" transaction that gets executed by the same address (0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7) and all got allocated the exact same amount of $SAFE tokens (315.9892631609089). A lot of them were created at the exact same dates, more information about this soon after I've compiled a more detailed report.

# Methodology

Analyzed the .csv file, found 98 safes that got allocated the exact same $SAFE tokens and then run a script to check if they were all created by the same EOA. 

# Safe Address

0x81058ff64a2D765E73fC04c6a19E051701D101C8

**Comment by d3centra** [comment]
Update: It seems those addresses were all created in batches through Staker App which explains why they all got allocated the exact same amount of $SAFE tokens. 

I'm not gonna close this issue since I don't know (yet) the stance of the Safe team on whether or not they want to remove those addresses from the list, as they were never used and only have a "swapOwner" transaction which allowed them to become eligible.

**Comment by tschubotz** [comment]
Thanks for your report. We found the following should not be eligible with regards to the user allocation criteria:

```
0x0787b9ed69e0c9515912ff2fdd5852440ea2e07f
0x0a77cdcd1a3a8c3acac39ceb23d1c5c68dc88e7a
0x0da47ee5087f317b74feda30a813dbf58e384d2a
0x11c8e65ba81af35a91fdef0e1f2aa8bd73550bea
0x1878630f6157b03cd16898009de9924399ba8b39
0x18ddfae7f507d05fc9c24ee5726e930138c618a2
0x1f1afcc9c9a9268bacd20990442acab5a612cb26
0x22f7633603e208b5962ef1034f472a9bcf727581
0x2451c50247e101f07ce0477b795b5759c5486f01
0x26869ec98cccea8daeb147e879c90438c2faa3c6
0x2bda702aa8898497b282210d4a699cfaf6a85e8c
0x2da530ed3f443e5ec997d1a17bd9f801b8757fea
0x2e0b7c2c01af4360675aa57bc36d025fd726386e
0x2e5b2fb941bd736e59eaabba2a74f0d4bf5078bb
0x3094bbe1262062a1780d58bd0f364fa1d9086898
0x317b5f878e7e6eff22163fbf5c88813b1b79ad76
0x3422425bd2d1903821bad16eccc0256ba5186873
0x39272828cbe580f28e1ef14cf29fd6adc9206841
0x3a8c465007e2c94ef03ca86c3fa9f7e793bf15c4
0x3b6c7a50456f283d95005d09b0f7be12c23880d8
0x43c7c80d0c63097f545658316d50aaa22de1a0a7
0x44b2827347d38d39ad12cbd14f39c34297225282
0x452ab093ea785cd7189a5d23ba702457d1432ebd
0x46657e0be695cf6f1a3ec20291510f16fc6d9d50
0x47120dcb4e16391dd6dc29ef4eb56871ad2ed16f
0x4e3b787a5b929bd22c5c730ff5704d444822b23c
0x4ee231030706554d772039bd5d103e5436c1dfdd
0x5113b60a2196820f1d3840dce7e45b64b1074b5d
0x53db5919420b27ebd14579a4af52aa6a518c2d9d
0x53f6e3f986b2d78c57c9bb26860e1703db39d3dc
0x54d98484c1a2b5f7d8ab4289eaa93c1d5700765d
0x5888cd2c4a26abf5ea49d58692d73faa64dc10d9
0x5dbb573a23f959179ce0528d5a77e3fa9adaf6fe
0x5dcbf03be1aaf7fb60266150d2cacd5fe3aa0c9f
0x6445df1689a681af1e71a6569d59474fa55090f3
0x65f6a316ea2dde0dbbf368c65e038a2ddd860278
0x6865f20d582bc39f0883b3d7c71ca77348b74c84
0x6cae282513961c0af64c94bd0d8df7753088f7fa
0x70a61f046a571a8a473ef549dc3c6f6d45868f37
0x70b033e54ace30b36d43af3edc0be21735497a12
0x725858cbb320b34f00cb4ece6245ff6a42768d7c
0x72dce054e8f5ec4c9c98b22ba5158100ec07b086
0x74502537f4f5fdc4719e2894c131e661757038e7
0x74e586bcf7563db1858d048f65c00031051af4ad
0x781e9c916992acb9661806beeb9ccbd9ce78f80f
0x7c8837986d8f32802411c69377f1868d2ff79077
0x80957c8e83eddbec32e4bc9885c29740b3bfadd2
0x848a62a680adac2d62aedc23a2c31bebd00b5133
0x849633fb6c2a9514f449c506b8ba543b94d43f07
0x852891d10515360ae025668fcc93d6232fe1cd75
0x89ae88cc751a8ba5d225a4a869817aa6a1355a33
0x89f9ecf1462de1e6421b906589751946c95f497a
0x8c099c30dd4e4a85f326af9c6ea9a6847da54337
0x91f7e30abc8b4301a8cefd3eda2b21c7886af2b7
0x9698b287a65d6132198e16025beaa588fe447c33
0x9cd2f5dff36110dbeb78c2115f7a3064af6fc968
0x9e60df1898d70b9858ada5dd85b2fa70382ee703
0xa5de681c8ed20a89426959b731bd0e9952d7f873
0xa632e7007f10f362f528626385a19ab9bb62bf48
0xa9f405b6975314d13be372375a16f1488b93d2fb
0xab106e1705edd61ce3575c2168c17f3bba1f4d42
0xab3baaba75fd8230e147fa95a9464ba42c28cddb
0xac0dea79df0ea7d48738d97e664e58037ef0546c
0xae5690b829fff0d3458a9afaeddbd85eb455dc01
0xaee719f06b54bb68622bb71ac4ab4be29ab3e658
0xaf2fb67d0e7623090f627ed46d014adae9b7b866
0xb2c33a65f5de4d06cb43229fca2e3869c3f0aa78
0xb52326488c4a9902bf18c94ac3d8e6fbeb71bfdd
0xb66bf8189d63c115b128d5530f759692b6c80159
0xb79de3f91b80e4b34172a5b9cd92b15c377acfae
0xbbb462f440caff23c05151289247a31c1a8f2d08
0xbef7f91eb55b65df4a76446b8e3accc50823d59e
0xbf34e690d8a8ba315ed77e89aa7bb9271b7ae5e9
0xc0b287725ea4019cf53903af95ea13086a88dce8
0xc3c7e7ef1aef44f8255b2e29694526e99503c7be
0xc785d6ab1e0c493b6bdbf7468b840179feea657a
0xca6421f261243546910f16a38d986458eac2d601
0xcb7d6582a9f06f6cd1cdc82a802d89f1349dbd2d
0xcbe4c5f6312cb8dd7357af27b44f093d1a1fdd8f
0xd22fd8327d004cb254616134f235df78c04e1d22
0xd34c84ccdde541dd5b45680b570f46041bac91e1
0xd404bdf95da413681c8196702b70491fa6d02ab9
0xd4461b17502960c979db2dec7c238ea85d510a9a
0xd5b355e740a4920fcb522c36f1b07966361815cb
0xd98b474c95d5fbab38dd9dd6d4d53cc193d769ab
0xdc275db516d2e46e145146c1d01eb36aa8864d8b
0xe330a9914b7acff273230a51e78b080dd3ae7d14
0xe355fe9d087e9aa1122b9709399ec9bc535ae00d
0xe8143edb2b419eb061d1926b02deb71097213546
0xed22677e28398659e1bec73ed7b3aad6f9e7b37d
0xee32ea0cb497632f741fa1d20fe5a674a674c1a7
0xef0daf615b4e9b13b028ed0f924842a5350df54d
0xf038b693c95436493a3f1b833d8ffeed8e28997d
0xf3cc82dccea613ee135b6b3a90bae8b6edd597e4
0xf42479a66bb6b9859f7ba387a391069ed4b00725
0xf70f7b88d82e2f91329dfa1f94ef6ca62f4deb40
0xf94fc2c691823bb2712ed9a5e42e4f1a7f7fba75
```
