### ISSUE TITLE
0x0e68cc646e2b9878d1472a218f0a505aa8f8555d has created 36 safe-wallet, And 28 wallet got rewards.

### ISSUE THREAD

**Issue by js9d** [safe-global/safe-user-allocation-reports#27]
# Related Safe Addresses

0x32f5ed8c01f12b3f62ccb1847f8b6b0d52009858
0x66c6109a83df890f468f878d9d853a2ee17a5e00
0x6e3014acd56b2d19153ff877fb45beed41c89730
0x0615ec388d1ee4d3ffb0437621692ee1d15adcff
0xdeca10175bb531e04dd2a080861b52ce2f1b4d07
0x2ed1b419b8c07c957f625f067df0399ad1257975
0xf56e6362147fd0c4fa0eb7165d55a8ebcd01c989
0x31bc80f88d54e733386fa1b485a523a81a09b889
0x1148a2c1fcf3a2ccf827c43e300524cde91ca561
0x657b95bb0f9a0ccffbdb34bd24ddb49cb863ea29
0x1a5390f3499302d41b74af6370a2d3bb22b8f0f9
0x2c20dfdd506c42b370e8ae05df1c910f2a32ab0d
0x3efd25587b9199d204e2ef1e9006e1ea25b4c481
0x15a079ba1c362cd81e0ac771203754d5c086d89f
0xcdf7d48d8bb077d198d09308d1bf280c8346438f
0x93351236ff32d02d09e8c778b928361469a26a5e
0x988b58a6014c3deffb452ded90965ecbec0c3e70
0x6b8b32a809edeb6e01028fc9fe7873eea0276f6d
0xec4e7362dc4e6697409726d6d4960b6a6b35c696
0x0c563016439ee2583e4a72284c136df98120c96b
0xd851948f8260d78a2a2d68c824cf4669c58ad721
0xba8d0b509d040b712837f282e5cb6d4a7a1455c2
0x69c68828aaabb43ef5bc9a97ca9080d62e633ae1
0x94b6672eaa320fffddfb9f2c608f9da911d74045
0xb41387be32a9c796c1c37f8b46c1fa6e07353e90
0xa4d8fb3891a2afad98a78e964c223c2255b7ed10
0x14eaf1a316d2822c1ce3ae367cc47d353e908136
0x16cbb219c2f56f7112bde3c7e2a88cedf8142ef9

# Reasoning

https://etherscan.io/address/0x0e68cc646e2b9878d1472a218f0a505aa8f8555d?method=Create__Proxy__With__Nonce~0x1688f0b9

# Methodology

https://etherscan.io/address/0x0e68cc646e2b9878d1472a218f0a505aa8f8555d?method=Create__Proxy__With__Nonce~0x1688f0b9

# Safe Address

**Comment by tschubotz** [comment]
Please elaborate on how this is airdrop farming.

**Comment by js9d** [comment]
closed
