### ISSUE TITLE
Creation of more than 120+ Safe addresses by a single wallet

### ISSUE THREAD

**Issue by Thephantom25** [safe-global/safe-user-allocation-reports#277]
# Related Safe Addresses
0xB73B47486f567Ba43fEd10E56c65DADC1B9D2a97 Ethereum main address

0x48B7145238bc081E2F4B05b3b3231f55d632e73B
0xc06bfC62D21132b05B51B78FB75Ad2E036be9317
0x0129aB3bdaBf68E968a09a2d2E56189a0b80E1a9
0xeaE672f6e4F6B92977494F29178667AD051DD332
0x71635b4A333196B832A87CB29dBC0286A347286e
0xbc598A0E6c0f06eFDF425ae953fFD9b2f505B60B
0x6C135ee358C47B897950802571D9A08c482d794B
0x26b6b6b54d7D6f9C4aDD11DD893AB2fAF0DFBb74
0xc03b32166b5A2e7fE61159855718Cc7B9f9f071C
0x139ebdB1F59462CA6C906Ce9B6c33dD59cC7c317
0xd6ecD118eA5CFd7464B3275877600a3be14782f2
0x4a6D1e6Ba8fC3572a1F47bD3451C09787198eA78
0x7A2c4c7ce52843F7F04236BB143C87dC1Cefd46b
0xb8426123177D5aF43D385Ed6821f399f76261b01
0x50FC9Cb5EBB299D3E5033E902436dcC8C7B7ff87
0x024EC2d653749d3341751284d244C8EA59AF2E3c
0x1B6331e5D35A812254E95d2693668B90Ed43029E
0x7CF700240Df74bfE4806Aa0d9d6fbC715542262C
0x0C4231da0C2C5D0E6150f943881B44157520584d
0xC5d71Da1006FC1d35D053dD9FD79D04B159511D6
0x64749deA460B83C154AFcfDA134587351f123dd6
0x8534B895f2E0A89C69cfcC9b054Ed26F057069c9
0xb5bF7e255e956cD789040422CA4741AF594a38fF
0x9166b99686e2e99c78A49A872C682e958177560B
0x4518ca272031De3Bf3685f25Da3B6965Feb8b988
0x3c5C4B5d22a41ACcB55d568625af2D77cb94B4e3
0xe6B18dA30045F0517De4A1e8562bB2cd7f172B4B
0x59e0feBf24E6aB2C1Ed2eD43777169151aBa09EE
0xA243141CF44a1076271D742Ed63A2E8FD300eB42
0x0dBEBf1202a1427C088D0c75DcDC45Ba518081E7
0x999dCA262B4d353594f3b06e24D55269C4288901
0x72E6F454a811C38Fe4dE3F5a5002989A4CDB3AAc
0x3F9510f66BB9Aa85acb5929B8C8D2BEd35dFe637
0xB3354c6b683cF84e55A8d658ea4AdE5d4241B351
0xd761396b124B2E94731544eb64B7aa36F41C1751
0x6aec1cc510c0B30C7Cb3c56de06DbFE8AFB9B5db
0xe7e715a3645652e82fE34BF0580BAB178fc0AB8F
0x9617Fc390a5EE5b41E4a2a3A3051244503CA37E1
0xADBc9dd5E6ed2AAcbc8Dc4087835E6f75dBfEdad
0xC67415689fF5Dcf5f5615a37aaa4E62975eBBAed
0x3889bFe2C40cD88512Ba0489246B0442415C53C8
0xa434A875d148Cbb06685b49163e3449a639A5961
0xFD5B7E4ffD04ceBe2Ee007CAbe33dE6ddFD38e17
0xF038d756f16Cf116987054302272fB43766c78Ac
0xFacf5faB4CcAf5488b9f15a8B75e57Ca34963d07
0xb4eF0FD8B92E325B4a83ED2061adf23d25a63aA9
0x563d334175D3999d1DB44AAB904567AC918DB18d
0x0e0Cfce549c8d5829fb1D61264cFDb5309DbCC34
0x0bcaf31F301dc1457175e30A95F73830B54A447b
0xB4C1230Cf28371fbF31d155a362b80089A07e6F3
0xfb5a5eFa6D3cB688E317ED5EE558565cD3a75693
0x8A4d1C91115F625Bc828112E5b270581E8AB3Fc0
0xD7FAeFc59d599FE093222631f78eEB39711FF481
0x1D499218299bF6EA77C7a60Ca843655A1a6c74EC
0xA2fCf410AB6fD2D339C8a0F067116aC53762E3A0
0x34BDA91dc5130e1864056558A14bF691fa2b3848
0x5eE3B31BdD182365Bbb8CFd1de3EA49A892a7C17
0x5a87643e7e7584AfAF7E3c559B0885F0457916a2
0x0703ee211745a8a71CB2F757E0b47d7095441e37
0x0220D797202095BaE6894fd849Cf6C3D27A6782a
0xB8B693Db391B10Ba7BD195115Ae5065167C36e5f
0x1AB0729B9D5916815a626D5c9D15549Ac9F30c6b
0xBa584694962dA02d59f8616C54c6C91480C27963
0x84152262b295AFcF9C7cb30F7e826AaeC8c90Be2
0x951B315ABc65B33A302673Eff4a1503FC15Cc4dC
0x8FbffD2A6aAe5699DCB84b96902f690C211d40c3
0xf77830f0250E691B7c806267160f9cf03EeBfD4B
0x91dB0011Dce7E62D4b9afc251959904163C8FA5b
0x1323054D5f2442660dE4E77e60C2d257c5Bb03ac
0x41d78D946080678536B6E9Cccf03E8D9A05b69e1
0x32C1d344559C234361BEaE73A2d2F6E2a7964146
0x10E1B6F338CCA0da8a9341381b619597896A0544
0x9817a4866369744ba7130517E676B82E691899ae
0x693BF9F21e89DD1c61493c8B232D0d7e9330EF09
0x1a59E3f1c9c5958d1e29806C59e3D7808b797b93
0x6c251B5E62A72b6A0ef50B87Df5B22D0C8036f29
0xe6B424C2d4478fD9BE17E28de1235aaC22af66db
0xCBE694681D9103f6e6a2208825629b2eeC540ad8
0x450893409B53250903097C727C3c4B514677894f
0xb9112346E35123c57A6D94a419a7fd6d48b4E8c1
0x09784d59BA12cC894B3c0952B1FA8701005c7351
0x1e54Cfe3f6f806dD2b2fBd63aBd899049BE38c31
0xbD795aB17D87410a8806692Bf1D37C288a897bbb
0xB3354c6b683cF84e55A8d658ea4AdE5d4241B351
0x280Ce412afBFc676EBDCdb25cE7aB22B94991330
0x19A907e2F66f910a621b60DaF77c087A75ca31EC
0x614F3418209E23a419f9e692aa8C08A890E99625
0x7C297EE6553F9D590Be68B48DEfDF4f2881530D2
0x7C297EE6553F9D590Be68B48DEfDF4f2881530D2
0x2003B8e32daD9aA162d185B2Ab3B4d78efC0BC28
0x41F559Cae5a1896a7968b72b3E5715ADa980B902
0xAAA4d387Fb2Ba5023AddaF45F52bAB3dE117d6fe
0xfd6EbF8bf9e143d6b538156dDC5217a51c26506B
0xCBE67eCc9655180eb84cE9E9480661065A24151B
0xDa31495f389B45c15E9219B686f4ceecD58f00D4
0x58885cF5F496c9d4491BF50C3107502db1B415cF
0x83c0247c3e3585BE7660ea43E48a3eE3DD9EbE4D
0x9662f077da9D7214e93aB05c4E07B1eF84F418B5
0x7E4B2c618838eDC798192bE30d312d43e69D4013
0xefBA5297AFB782F1d008Cc2dfcCF097256c1e723
0xA782B8C358FCaA466Ce550bA0542826863d95E59
0xb95bee583bd8Df762f9Ad5b9E120dF06Cf31a155
0x337b4aBcb005F9164aA860094e5855d11f53a9Ff
0x12401838af53da3E80703378390c45Dad243Ecf0
0xf94cD5863ddc5687d6b8Ba17Eaa087685430A1E6
0x6bCBa06c8c98d64be0386EA8d48cd28bE75078C1
0xBD5932267E6d95841bC817C6e2F0f060aA91eeB0
0xF9D9Ca620145d3Aea957ef9baC0a7aA78fF4f310
0xE41d1eEFE89Af291fA4D7536D0cF08137adeB81c
0x0f93dd048E122538f84a94D64979ad127783dBe8
0x2a141dC23bFFE0653B96D9eF33D462E6aa985544
0x009C1F47325fC51E9FC79E74b85a14b85CA9645C
0xbB2A181469b94450b51409178D9C8dDDCb5344DE
0x4e5A6591908BF032C556A6BBCA739b9d5197871D
0xb54Af45F64c2308046Fd76346dd48970569e06D0
0xC8cd18825cA8569f60284a469549F958584E7Fc7
0xF298A40915fb49f0149cdB45392b247467132C51
0xC1349850c24c796cDAc517DF65997dd32c86b5C3
0x02Dc88dc52D0FFb1Ca97b6985bc3411468CfAB3c
0x6dEc6241312693ee57c37A1FD1F6CbC4F39E45e8
0x363e1420261463C8969F92a32851e291f39D7cAE
0x577A339D209d7d5a727694eAb35CA9c2a96a207A
0x1D6a34214122f6B99A1Da73Eea9495D18BBAeD1a
0x3B2A5c8469CAdc78598920018ddDc0C22BfC79A6
0xbF38EB7B58aF179781332e7538a584A11385291b
0xE30Cf160C6f38C6a88d2cF8de8CD22b47b327743
0xB775A854Bc30D7bcc16b80fE40269AC60781fb14
0x20dE079A5C5Cc993cA38c75DFe1c4C0E754D230E
0x8d2359D774Bf1BeFc7DAAdCB2533EEa332Ea6b2c
0x6bc2bFE9f54343Ad64fA1D5B28EFF5FE4fc33995
0xCCeABf14b806dD4eee45F98b26bc5c825f493134
0x72Aa03689C5DE52493402fDE0A220FC7A2570d83

# Reasoning

0xB73B47486f567Ba43fEd10E56c65DADC1B9D2a97 I think he is the sole owner of more than 120 accounts because the same transactions were always performed on the contracts he interacted with, let's prove it

# Methodology

I can see that these 120 addresses interact with around 5 wallets, here are some of them:

1. https://etherscan.io/address/0xf038d756f16cf116987054302272fb43766c78ac (safe contract with which it interacts)
ENS address: 0x-40.eth

2. https://etherscan.io/address/0xba584694962da02d59f8616c54c6c91480c27963
ENS address: 1satoshi.eth

3. https://etherscan.io/address/0x9817a4866369744ba7130517e676b82e691899ae
ENS address: 0x9499.eth

4. https://etherscan.io/address/0xbb2a181469b94450b51409178d9c8dddcb5344de
ENS address: 0xaccount.eth

5. https://etherscan.io/address/0xcb6201c2afb028a5f7f71b1c0d3f88137c2ef1cc
ENS address: 0x1st.eth

Now let me send you pictorial evidence to further explain why it's the same person/organization.

![Screenink_2022090917345](https://user-images.githubusercontent.com/78061162/189374886-854f9ab4-a503-443f-9e46-2c82cbcc310b.png)
![Screenink_2022090917334](https://user-images.githubusercontent.com/78061162/189374898-e4524c90-aaf9-4fdd-8f7a-048bda674ca8.png)
![Screenink_202209091733](https://user-images.githubusercontent.com/78061162/189374907-563fb46d-ccbe-4611-9377-2c1a2c2529da.png)
![Screenink_202209091731](https://user-images.githubusercontent.com/78061162/189374917-e876a476-35c3-4901-ab7b-91a5b7cbb3f4.png)
![Screenink_202209091730](https://user-images.githubusercontent.com/78061162/189374927-6017b4ab-a635-49a5-8585-c6c5b86ef2eb.png)

If you look carefully, I think it is an important detail that its latest transactions have interacted with similar cotracts such as Proof Of Stake Pages (PoSp), Aztec connect, Metamask: Swap Router, Rocket Pool: rETH Token, Arbitrum Nova: Delayed Inbox.

Coming to the most important part, the ENS addresses I gave above interacted with each other.

https://etherscan.io/tx/0xb23ee05291a10470e6c6297695716fee6b55aaccc55acc3fa637236aa48a4ecc
![123](https://user-images.githubusercontent.com/78061162/189376850-d5ed42fb-b6ea-48a4-8de3-917ebc11f84c.png)

https://etherscan.io/tx/0x6f35cb4898fad5016c17ec9f4b5726e74f1b49d2faffa09aecce3d15be4b3376
![1234](https://user-images.githubusercontent.com/78061162/189377447-d54ad92b-80f8-47c8-a2bc-794b00140880.png)

https://etherscan.io/tx/0x92a248f0e3f79eadd05bfdf8036573a2fd89e838301e40c4d27d3562fb16f86b
![123431](https://user-images.githubusercontent.com/78061162/189378227-20620e35-e7e8-4605-9c98-891e143c36dc.png)

https://etherscan.io/tx/0x1bed85b81f482a9113ffd5eba23781b733fe08342955c76fc54a76cbcf079bca
![312](https://user-images.githubusercontent.com/78061162/189379268-9b41ae07-2713-4002-96da-600dde6aaae0.png)

And the biggest proof that this person is the only person is that the addresses I gave above deposit the same Gate.io cex coin deposit.

I additionally used onebitcoin.eth ENS to prove the Gate.io deposit address.

![Screenink_202209091813](https://user-images.githubusercontent.com/78061162/189384214-358e9d0c-d2e9-415d-b640-6891cf0ee230.png)

Tx's I marked in the picture:

https://etherscan.io/tx/0x09c3bc11537d015f40dd461e2ffc48723bd7be0b63fbf6d180826074efd292ad
https://etherscan.io/tx/0x201ea2a2a57f1d6587e79180ca3e891c5e763689717a1a4f4603e17326e9d915
https://etherscan.io/tx/0x2c75e1dc6939666ddd47bbb20264a91b6e5c9ebc15f38c86ecdc34b4709e96d1
https://etherscan.io/tx/0xbb9b97febc3e5ac73c35c54221ec943a520144c30f360de6eecf729e35160f58

Gate.io deposit address: 0x75CD04a6dBfb80611dCab1Fc771874e942c9ac4d

pictorial evidence:

![Screenink_202209091821](https://user-images.githubusercontent.com/78061162/189385302-d1d3cdfc-ceb1-4d8f-9fe4-664a7f186bde.png)

If you look in detail, these wallets always end up in multiple accounts that are used in the same style, they are all similar and use the same cexes.

# Safe Address

minastark.eth

**Comment by tschubotz** [comment]
I checked the first 40 Safes on your submitted Safes. Besides 4, all of them are safes that didn't even receive a SAFE allocation. I'm closing this as invalid since those Safes aren't relevant for this challenge.
