### ISSUE TITLE
Repeated addresses for obtaining tokens

### ISSUE THREAD

**Issue by yumi4552** [safe-global/safe-user-allocation-reports#280]
# Related Safe Addresses

# Reasoning

# Methodology

# Safe Address

**Comment by tschubotz** [comment]
The reasoning is rather weak, however these Safes seem to 

> # Reasoning
> 
> I found these safes with 1 transaction from 1 wallet,and the wallet is 0xdf21b894a490cbdf49d9de7b9d780b79f7cb0ac7

0xdf21b894a490cbdf49d9de7b9d780b79f7cb0ac7 is a relayer account. This is not sufficient as reasoning that this is airdrop farming.
