### ISSUE TITLE
Repeat address for tokens

### ISSUE THREAD

**Issue by yumi4552** [safe-global/safe-user-allocation-reports#282]
# Related Safe Addresses

# Reasoning

# Methodology

# Safe Address

**Comment by tschubotz** [comment]
> # Reasoning
> 
> I found these safes with 1 transaction from 1 wallet,and the wallet is 0x421f3dac4fe3bd06fa4d51c53647511aeb8ccf69

I don't understand what this means.


Looking at the first 3 Safes, I'm unable to see a pattern, looks rather like legitimate use to me. 

https://gnosis-safe.io/app/eth:0x5b21e1e3cb1ea2c28589e7141066181a6a9bf9d5/transactions/history
https://gnosis-safe.io/app/eth:0x5b28a7f4cb62032c91f2b651e85625f75decadcd/transactions/history
https://gnosis-safe.io/app/eth:0x5b40a53d4971f6ff7b1ffcd470031545a7091e8a/transactions/history
