### ISSUE TITLE
31 Safes created by 5-letter ENS wallets which are closely correlated

### ISSUE THREAD

**Issue by PulsarNetwork** [safe-global/safe-user-allocation-reports#294]
# Related Safe Addresses

```
0x74ce9337aab93ea1eba2f72fadd9dedef3f4ddcc
0x35345e852c4b70883cb0710945bf63bc32c01369
0xc2f38537f14c707ea75a6bfe719a8dab9eee1f3b
0x8157a6d2560840feb273a2d6f08170b7f16debef
0xde77b3daa28714e8a21ad1ae68d93bf65d7e4d34
0xf41e53a089854f71eeea2934967c759658d8560a
0x4429fb5d1282170c3c644bd4244700f272a71fc5
0xad9f8a27647e07914b47813c7705e2b3ae0fe0eb
0x6d8af9a77dfe2742a32e61d92499c3dc0004d36a
0xfd083ae5a628ef4a44a0868cf688d61ae154eb4e
0x8b5fbcff2b5cd20349f4aa49ebb9242f5a401842
0x2e357e35596cdc6310eb4dd6712b60a09110838e
0x5a2f76fecee91cf622d3617626095d05f07e7d34
0x4efb649f2f426bae720bad46766bf93b1648a919
0x40f40e7361621459e4c2369a7a9cfa5a42ccd3a5
0x62828ce862ffb5e66a3b6344f0c663bf3781b4a8
0x8dd6ed429fc3b3d76e01b9abc49418285c3e124d
0x891a76e74e8c496ac1b59de0c528b8abeb2b01da
0x385601d78b1feff84421894740b2908025b40b59
0x81b773330aa4890ff0e205280dd00d5252187426
0xcf0574082b0e548ea57dbd4785863094f856da2c
0x5dfa97d1d1746e19bc5fbb28213c23eb33da498e
0x705cca342b7a36c46442c06e7117d33be661d711
0x93bb9aa2f46f3775d0ff0a916ffac650c574b96b
0x5cf25a39b7015a1f49208e88e7c45a0ad5921861
0x8d1534aabe5296ebbab5158d4cdfad6723e6ec0a
0xac2cab720ce08beccb69ffe5ec9d5aac3cdc7f3c
0xd66292d9ee2ddf4772dc94fe3d2791c38ed7605f
0xa60b106cf6ed64a2d39369b8673af49e4caca260
0xe6e94ba16e7c752424cff7afa0c87602be3e3eec
0x72002988e532ea1cab05dc2af0f730860e8aa5c2
```

The owners who created these Safes are

```
weigu.eth,0x1d0239e4e185f5f3fba605897849744ae8b5f333
obyer.eth,0xee33d688fe27a3a754435c50f8a12654d5327a16
pypke.eth,0xd57e9df75381553ce9c154712ac7f73eb206bd63
lgtzz.eth,0xdc7ec05bf7781f9e861ee5486023dc6cf71fa7c4
aqytu.eth,0xfd7d9173403efd29f6b0b576217a59fd426170b8
qybxi.eth,0x66109b3b6348d1df6bf1f8d998e527b967f682ea
bugbu.eth,0xa129d5436fb797ff1d9c11b5f9d3ab0e27dd34b5
tnfps.eth,0xe274ae86ff13c1bbaacd3662ec5fd7279a18e28f
onzjq.eth,0xbafaf28d01aefec4cf16830d2187becd502c6e0f
xkyoy.eth,0xc9ac69013f041ebee6009bed69047db1a795dbe9
qepdm.eth,0x41602b8582f474eb9c029dd502e7dda119345931
ntqbd.eth,0x33d7147b957c1d1d0bb17d2b09e1d85e86be9873
lgxbl.eth,0x81d53cd3e96fd8d51cef3de47e546d0b325af8bf
knxyc.eth,0x4e4b40b1a3f945d6ecc00f65adba063be82439f0
amoef.eth,0x1e265fdd0654120c739639b87e967f65339aa4cf
ydlup.eth,0xf9039ae1e299486d8e6c5740ca6340797fd42736
xffxf.eth,0x7f64716cfb04ef0b78a3fcf02d3406a1b9dd0c42
ecsqr.eth,0x94d4d40759af1cd2addb95252278dbae38c78d1b
oqtgh.eth,0x02e9e647e041854ad3c4c56d8c4f4b69c68a7682
xggbi.eth,0xb4d50b4e31181a004beb14e8b0a522bb434ea1fe
smpkm.eth,0xf574fbbbd0c29ff2dbd10839e33793a6eafde809
tbkgl.eth,0xe8fcdb117a5f0ec16ef040e6fe3f675390a7bb5c
xgejq.eth,0x1d7375a6ffc5a60b435558859a2762cfd6c6b07f
aqziq.eth,0xa3728c1f3ac52ded2fc69d3b95235d7a6fd2b377
fgdzg.eth,0x6069a291fc1dbbb0782a1314b6fb06e6d25b22da
szirh.eth,0xe874411d6e354b93be52b05280052c193550fa03
plglk.eth,0x1cd1a6c4570c039368f5456aa82574af6567e6f6
nsqlw.eth,0x2338e4897119a104a3145f7b500fe98b51a56637
ondkl.eth,0xbbdfe37f2b5d2b7e86721324336abdc2221c4be3
ihwww.eth,0x3b174445371dd00fb766357f29118ac6a0aeec1c
hfpqr.eth,0x8a36c41e2b7d0ee24668729d08543ab77a99dced
```

# Reasoning

Majority of these 5-letter ENS wallets have transacted with [0x54c7bb00d5b38ea2583069eaac8b42d56b6aaff2](https://etherscan.io/address/0x54c7bb00d5b38ea2583069eaac8b42d56b6aaff2). All these ENS wallets have the same activity pattern:

![image](https://user-images.githubusercontent.com/100975555/189399731-cbc20018-9414-41c7-9e9c-825834690281.png)

https://etherscan.io/txs?a=0xc9ac69013f041ebee6009bed69047db1a795dbe9&p=2

https://etherscan.io/txs?a=0x8a36c41e2b7d0ee24668729d08543ab77a99dced&p=2

https://etherscan.io/txs?a=0x1d7375a6ffc5a60b435558859a2762cfd6c6b07f&p=2

In their first tx, they were funded by another 5-letter wallet in the group. Next, they made a small deposit into zksync. Next, they donated to RektDAO. And somewhere in the middle of their tx history, they created a Safe. 

Some of these Safes are funded, and some are not. If they are funded, the funding source is from one 5-letter wallet in the group. [example](https://etherscan.io/address/0xc2f38537f14c707ea75a6bfe719a8dab9eee1f3b)

![image](https://user-images.githubusercontent.com/100975555/189400569-7d5b3faa-7569-42b0-9085-676d7a15fc47.png)

Plus, all these Safes were created on May-18-2022 UTC.

# Methodology

Scripts: https://github.com/PulsarNetwork/safe-analysis/tree/main/5letter

Algorithm:

1. Look at the "master" address 0x54c7bb00d5b38ea2583069eaac8b42d56b6aaff2, get its tx history
2. Find all 5-letter ENS wallets that it has transacted with
3. For each 5-letter ENS wallet found, we use breadth-first search to find any other 5-letter ENS wallets that it transacted with. Duplicates are not counted
4. For each 5-letter ENS wallet found, search its tx history to identify `createProxy` function calls
5. For each `createProxy` tx, decode the transaction log to find the Safe address

I encountered the "master" address by chance. After the deep dive, it's obviously an experienced airdrop farmer.

# Safe Address

0x984129b1C8D6048DF516D81f730475AF7D0E4223

**Comment by PulsarNetwork** [comment]
The ENS addresses have another thing in common: they all have layer3.xyz profile. Every profile participated in exactly the same sets of bounties, including Slingshot, Avalanche, Balancer, etc. The scores they achieve for a bounty are also the same.

examples:

https://beta.layer3.xyz/pypke.eth

https://beta.layer3.xyz/ecsqr.eth

https://beta.layer3.xyz/xffxf.eth

**Comment by CaptainTee** [comment]
Kudos!!!
Much of intelligent works done here!

I now understand why some airdrop farmers wants the team alone to run the filtering tasks themselves without taking the community along.

Once again, well done job @PulsarNetwork

**Comment by CaptainTee** [comment]
I would appreciate if you can help me look into work in ticket #319 and tell me what needs to be added as evidence.

I'm not a Dev or expert in coding but I believe those SAFE addresses pointed in ticket #319 are suspicious

Your help on it will be gladly appreciated

My primary aim to ensure only real users get the Airdrop not the sybillers, the 25% reward is only a secondary objective

**Comment by luoxinyang** [comment]
`- I don't agree with you, layer3 has a lot of people with the same level, which means they have a lot of `users``

**Comment by CaptainTee** [comment]
@justdoit12341111 
I guess you miss something.
- All SAFEs were created on same day May 18, 2022
- All SAFEs has five letter ENS name 
- All SAFEs were funded by one wallet that also has 5 letter ENS name
- All SAFEs deposited to zkSync
- All SAFEs donated to RektDAO

If this is not airdrop farmer's way, I wonder who's way it is 🤷

**Comment by tschubotz** [comment]
Thanks for the report @PulsarNetwork. We've identified the following addresses to be related to airdrop farming:

```
0x74ce9337aab93ea1eba2f72fadd9dedef3f4ddcc
0x35345e852c4b70883cb0710945bf63bc32c01369
0xc2f38537f14c707ea75a6bfe719a8dab9eee1f3b
0x8157a6d2560840feb273a2d6f08170b7f16debef
0xde77b3daa28714e8a21ad1ae68d93bf65d7e4d34
0xf41e53a089854f71eeea2934967c759658d8560a
0x4429fb5d1282170c3c644bd4244700f272a71fc5
0xad9f8a27647e07914b47813c7705e2b3ae0fe0eb
0x6d8af9a77dfe2742a32e61d92499c3dc0004d36a
0xfd083ae5a628ef4a44a0868cf688d61ae154eb4e
0x8b5fbcff2b5cd20349f4aa49ebb9242f5a401842
0x2e357e35596cdc6310eb4dd6712b60a09110838e
0x4efb649f2f426bae720bad46766bf93b1648a919
0x40f40e7361621459e4c2369a7a9cfa5a42ccd3a5
0x62828ce862ffb5e66a3b6344f0c663bf3781b4a8
0x8dd6ed429fc3b3d76e01b9abc49418285c3e124d
0x891a76e74e8c496ac1b59de0c528b8abeb2b01da
0x385601d78b1feff84421894740b2908025b40b59
0x81b773330aa4890ff0e205280dd00d5252187426
0xcf0574082b0e548ea57dbd4785863094f856da2c
0x5dfa97d1d1746e19bc5fbb28213c23eb33da498e
0x705cca342b7a36c46442c06e7117d33be661d711
0x93bb9aa2f46f3775d0ff0a916ffac650c574b96b
0x5cf25a39b7015a1f49208e88e7c45a0ad5921861
0x8d1534aabe5296ebbab5158d4cdfad6723e6ec0a
0xac2cab720ce08beccb69ffe5ec9d5aac3cdc7f3c
0xd66292d9ee2ddf4772dc94fe3d2791c38ed7605f
0xe6e94ba16e7c752424cff7afa0c87602be3e3eec
0x72002988e532ea1cab05dc2af0f730860e8aa5c2
```

(2 of you addresses have been found be another report already.)

**Comment by xiaohu1882** [comment]
I believe I found those safe wallets first in https://github.com/safe-global/safe-user-allocation-reports/issues/265. Should we follow "first come, first served" rule? @tschubotz  Could you please double-check my report?

**Comment by PulsarNetwork** [comment]
I think @xiaohu1882 found 14 addresses earlier than this issue of mine. @tschubotz please double check the edit history of #265
