### ISSUE TITLE
0x2236b3a9c23a2e7847a8d2125d1828bc8b9b9713

### ISSUE THREAD

**Issue by yebin-xu** [safe-global/safe-user-allocation-reports#30]
# Related Safe Addresses

0xfeb785dd39787919e3f5545847f284525d9e9d69
0x63a93eec6694f4546d01f4b658f2e1edaa95e571
0xe70351a7dcb3920dd06c4f50afb098685f1d0bfb
0xcb81dbc7e50505a0dc369de7a562fd0689ec264f
0xbd9b2b88dd4311057a78d126827071bb3e74d824
0x32e80c77525e818c3072b2ac7cdaf420a9a6f2f8
0xad80abe44289a78fd412bc99a1dc45bd0aba2683
0x0cb1d4a24292bb89862f599ac5b10f42b6de07e4
0x84ae80c522c2a0fdb26e63f2ae527755d0000b81
0xf41aa9b289b651d16f6c3aa4ee2d8df44f8d0b10
0x34ae9566fc4ebb8bd25b584478edbbf6f6993984
0xe41eeeada1446a9c1fdc84220396bd5a026088e0
0x8d5b5444e503e78086c31a63c84af6afd1ebf93e
0x8064bcf4a7892b99c1ce4b92d23252ab2fa129b6
0xe8b229d68cf5e7362eda7f4bef99579adbe84b64
0xe373a19084753bc4746a05fba80d10534ede2c10
0xe7ac5591b1fbc9ba96eb053f2c80a7816934887e
0x081d84829b1b8f8a46cce0392c524604ee785508
0x24372e2fccad9df74b71830b6008d7d6fc7328d7
0x652e6bd691c6b07a2efb22ad04924664f07c9b9d
0x8e4d87ad4dafdac06d86a3ed002f5085dc036e08
0x9d7ddd11ffd969419e21712389d19edf78938180
0x3c9a4785b16d33ac8033ae6973392724736009e1
0x679824d755b054a2a50358008472a6f400740319
0x6bcbcaec86e64c3c8a21c6505e53c3bc53e69118
0x9b884134dbde2608c89b5bbf387c74a3301bbf30
0x21d1b28eab88fd89663d3c0ce6bf27ccd883635b
0x1b59500979e7761f9f0128d358535eae044b41b2
0x4bba903a0e59489d739e99c46ff86603f7a4dd76
0x7f5be839ba94a371c2814dd1baeb35769544e6da
0x9a972915c17f1d50e9d9fa19d282c4ea4dba0e30
0xbb83d92c8d2b1523b6be79c822c20865d70321cc
0x1e3fc69c9d80dab3a0dfd92f32079711ef532e75
0xfd7d929c260a74a6da3ed07f3460c8f0522d01dd
0xf660fdf47901c60e3474ce48eb8092e12249b076
0x36dba8fb6f63b862e830294e71750f5ae6f4cbe8
0x67cf4b2cb7432e773838f7cfa215246a7f060f48
0x4548c7fbe12da1a9c58c39eb9a159c777dd1f6e6
0xc7a2dc6471e2d35aa0736dfdc171106e89b70bec
0xbb137633e404bce7b8ef30034f214b38ca4a6837
0x80d8164edf65a049a1d31a72cc44ddc3e5a7a8d2
0xdb1d6586dd989697577f76d573f1b2212ebfe931
0x8a8fddae15d73e71503a9ae07d3de6d69f9a0c75
0x4cbbc970437f72b7c0c6df82b67c01fc116a829b
0x5dfe867a46b65600576afdf64210303fb11ab6a7
0x58e39e3fcd327474fd03ee53db7f2a612b69d1db
0x33cfad88d5c823f368e2861871b4a1eccfe68a07
0x2cb57bb3df79f85e61a03f20c7bab77475b67308
0xaa934561ab2b59751765f9f42a84baa3aa19fb47
0x5c4f5ddcc03d15571a752799770488cf6844f2cc
0x582790a29e1b25fdae341992b573082dfcf79caf
0xee5300e1fa754de6e37c722c53603da44a4488bc
0xc5fa7389f8cec545edae26ad3de67a5641598f9e
0x6e5a9cf7e2d663ff23fdd067f71f2f8a15798781
0x88f16ddd20efb7677bcd2c1b5f8c6236cba5bc9c
0x3e68f4a53255783c48d484c28515c5501c125925
0xf3e33320bd13be7780c5bbfc457da02b32cf7b0c
0x90be0b11c5bc616fd4dbb239f3625699b97bf367
0xa7e8f6cfad7e9b97ab96d37d42e3fd926536d06d
0xf975235f197be16cc0759cb05ca3760c37e3892a
0xc1c36a62ec4d22306af755b2fd63772846061981
0x8910cd40bd6979a988bace2bec5a58026d004fff
0xdba2a62ecd13afe09e82ea9cb3d74a4a24b81936
0x07944147cd1d166179edc226ee0201ef0bdb32ca
0x51f89b2fa8df460c133ebf51b80ef8f048e9c04c
0x572eb3f6c92d46e8c024d58c07366cdfe5a34ebb
0x291a745b0892c2e7a11d5cc22781552ad002af9f
0xf74a9d91c33817c0ae0232aad9c0e65e96290c3a
0x3c592d56559c68013b05cb6021ae400fb3222a95
0x9a0a50a369fe633003b3415c24fab35c05461bf3
0xb8ff96cd9150971f89517152574186691c066bdd
0x92270a45dab34eaf066089133064d7660691fefe
0x7de6f32f829c904cd9373f248d596e7bc512dd2e
0x06874c6f62209508115593d90c9b03110baec64a
0x368dc37a4d9c544ed56f786e3ad789f203727402
0x57236dfb077fc0916d84b274c56daef3d24c7f97
0x12b1b98ea4e85a78638da14820159377141826f5
0xf99f6a71d697b9466c4ee019cdc551e0a5ce79ec
0x42419ab87b76ff45dc6ac1699918caad8c514894
0x296f815f7eb37318f2e20b47259af2a025bc5f96
0xf2ab22623ad29347f01b3e214e14fff7e8836f55
0xf729988d3ccb9ff12b272b603f7dcacf6d0dee0c
0x1c5f6bad55a67aaf49c989aa9340110f300169df
0x9cd3b108ce8f249628fdad3d34f9b58845fb50b9
0xf82780c287f1b889aa6175a0b0fc96f4710e130b
0xd2322055c669d04fff2e61e2546b72764ba54deb
0x4fd4ae89eedaa3cbfc01933d981f4cb91d29e8ac
0x72ba343820aa81a372a20f39f9d43cfab08ccd14
0x8317b68f0cfd62f9dc930a575369ffe21df64e06
0x006b1baa7469adf48fa632e9efc00635d77ea1f5
0xd8faaf39ffb7798303cb6e0cd4c6e844b20f59af
0x6e64ea9b1b680a4c9be07b0b5aa7cd4ff56233f9
0xb6124add975572c9677f9fcdf582583a3d12518c
0x0d7de98d473671fdad81d602f417e6aac0a3e9a8
0xf3a2563ed1b0600e43370b0d59f2e4b59f1c107e
0xb08446632baa6466330a6885dec3a9b383030cee
0x2677deb3bb2249b7c53c77f8726dc202bfaebdb1
0x3ec16626a7f7ae05202e2add486c05b155c9ae7c
0x6bf9f2dd61b4929c5d5c9f24d7498792694c95b4
0xb24c5c740a883d919434cc25473cf5b434aa201a
0x9deac721e0102dbdf1dd08cc5695d1f02e85d80f
0x4cc9f836a4b37066a5e25255bd00701d147772bf
0x770cae3462a887dd00394e9e35ce1134aacb25fa
0xd52da2a20ff3badf7b486884bb5166c21b33eb53
0x300786a907a466611c3ddbc5b0cba43c566deb80
0xdb24617164c407b441caa0b9776602fdbac31483
0x37fc6dd6bdd8bf268bbd360311c87aafbd99ff45
0x9ec1f6cbffb3537246e49e52b92bb0fa5818c2dc
0x4a51f3cc61014ca6046ebc27cfe9e26c046a316c
0xf31d209fad990e9d1aba9d031bc692b6e7de3267
0xe9d935ae50e1c2195fab2156c8113bd43056b84f
0x538d9f006ed4c712b0ba16bda221d0bc84d32b0d
0x5801ca3b46f958885510699d927df243e075c515
0x2a336a205a0b4a26f663036cf77c25ae93e74d56
0x6eaa9b858b466d21251cfc9e49af9046cd42c580
0xa87d2358ae35993afd165368e1f73f9902f9368d
0x6bcf2c2581619694511a9d72083305ad05fb8f57
0xeaf9586f362be6dd0063c01c2d5c52b975cc31d3
0x43d3fcc8ce47729122cd48c20f48a0b86acd96d4
0x7e4aeefd1123278e23891b48c233b2056503af85
0x50b0d55c6356d9e105c5d5cbe1f99750f77eea0d
0x3ea3ee4e326e9651c8b9dd4ec9a19b8be1543201
0x13fae4b0cce08a5de028809af6fa4eaf76321265
0x2fb1ec7c57cd2c656590a0ea7c4d27cc6954a41c
0xba60bc169a2f111fc86618218ae1cb7169f59037
0x5b76a9de0925850d5565bbf6da9f51c4dd066db8
0xb9a4f350d2d97e846a397634eef60b83ea72cab4
0xeca1dd220de90d846eb473225cdbc9f869026482
0x43a0eef9a759b18633dc74ac493a3b21927b4cb5
0x83190454f24e653a221875079f35502afb1980f1
0x7319760904a48e66b54a3112082eb3d8f0df27cb
0x70db345b42bea81303002348532a26c0ed0e9d3e
0xb7f5760ec8276207857790ee183488de0559e655
0x2c58390e3c484f18b0e8de90660d82199efa4165
0xce4d2fddd35849de047fc73d230321cf9764878c
0x7032cdb36d093d6a5375d91bfdd172a661c6d1d2
0xc77e7c4f5ed5cdaf22cf3fe54002e288af3ed7ff
0xc72dea5c57efc488e620664607794ae75e0c5e6a
0x3d702fc7f9d7d7b9fe5844db3493cf3671ce8caf
0x58dc7e2a6f8a6419f5f804aedfd52b3366a9d378
0x8d23ff68db1ca94739ec6745a7a4f66411cfc4d4
0xc2da1f86f7b212f55efee1897c330109b9efeb6c
0x47c70c6ac14b1aeeb90fb3c712b456d021f7725b
0x9fc97df40bcb6c95deec0c14cafe86b0eaf99a29
0x066419eaef5de53cc5da0d8702b990c5bc7d1ab3
0x772982158a2bb6b92680474d8bf1880f68d68bde
0x3ae755e5e4d668533eb6a0890ee57194b0013307
0x5788df4c7c46772dfcf56688c360b3bc942250c2
0x4bc3c9a61f070548cecbc0e561a8c05d5201c728
0xc51848d50c13b39c8d8670189793a5a995d81427
0x756cde523ecc2da52295cb6732655f31246fc37a
0x5148c9bfaf135ad365cd2cf2d9dbc59d4a7ac786
0x8183cccac1841e0237982dfe60228b5ca19265a2
0x6cc720a12696d368544bee77feeb179ffb6eade3
0x09c065b2895a7e9614289684d66bb05d41494e72
0x5e3149c7f6ed6c12ef6b71fa1f91a81b3ec48e81
0x23c94d8648b9bd8a2664cd0e4863eebd04c61ff2
0xaf2be20c3bb87186d5d2ccfb711096177ada37f7
0x27b203543b7f44b3267b89594fd771acf51c3146
0x31b83b1298af01892c5304791e2ba0938df99c96
0xe74a90cea32519bc7a6b944b59b813b3bbf8956c
0x362aba929b1f641deabdd4445cd241da378a39db
0xe6c47f851f78524427c4f8cc10e6252493c8dc0a
0x4b5ba8e8425b76cf14ce9efed37fe4dc0936a3e5
0x06cb966d1de30caa6f8845dd94e4bde9ece56d4d
0x15908632892f2de63c932624fdde4badd93c8c57
0xaae40bce61c3db09085e59a8d138b659ef1d46e0
0x176494af057d0e5a57afc9324f070f34a2099dbf
0x5c1d9b780bae92da88af009f0e25b4899efc51b3
0x755c8daa24e8673553a0c35e0ff7c6778d61c93f
0x1cf7780310e22720f58a4b0923045d5b426c5994
0xa3acc5bc4d8204ef6cfe02d97719ef235565cd2d
0x0c5fc8cb663615d82e5144ff50800649d1201f79
0x100028eaaed23e6ec8c0ee690a761b291dec3a99
0x01c439abc0bb34d3cc10279e150cde4afda19642
0xc188f50bcfb7a2f8deb69c6c1ccbcaa8499e01c5
0x06ea07c21c7e85608267466fc03b368f752ca102
0xb42f5ba29882e3aeaab529337c2fdec136e49dad
0xf2642f01f768505bccbd976147ee647bdc75c2c7
0x258c67ffdc280ec3e4e7b324c4916ddf4ea4890a
0x9434a5e4d831a91221028affd036a378c1fedd41
0x14a498fc210e702d9ca469e5d7add598e2e8fe48
0x159326c9fbd5fcc95a6817ad70115faf71f07e1e
0x2b253798fde6c0afa8bea954a9c8344e0e8cef18
0x6ac7bd35643e139cc151967547284af97e72457b
0x1a78233dbf28e1535ad55b3789840c8deb74b096
0x1fea17bcf1826eba805f01f202a11336a88c3b31
0x826e1bd4d36b7b9f2897ceb7c184499958c345c7
0xdd506b429b84d22314c5e529a0279d7899e3563c
0x9d3c36ce01ec67a3777f12bed6dc493da6ff2fcd
0x6da2c9e4233f12c216f2da104d7628e750186d2e
0x006d1194256a0754b489dc9b8596a4c4a721cb9c
0xd14bcd12b6de2d368fdac741a6fe660ff802bd9c
0xe467dceedb127f6faa24919801bc2c4c1e82ef8d
0xc63e80eb8b6550498aa8011b2a9ff7e31cb135a8
0x61eb65b7f6e7534fa09808b14f088e21ee9b9c80
0x50c79872c1d96173eea7a52bdb935ee4464e6d02
0x19d32439cefb793e1f52c7dd985e52ecf5b0f0bc
0x24d3da9b86f8c2ab3191a5c7dc23ece013231cf6
0x95fbe2926434880d1c41a60f070254f16ad3bfd3
0x5541cebe4c8bf946fb233d0d17c0ffcafd7b491d
0xa0a94182896fa1e95497020609ef8d1822ab8fc5
0x77ecc452f8256b7eba39be34ed959c1686929e70
0x53e25390f9adfe1ef7afe7ed8a987ad67fd8b9d8
0xa863052f72890f33110b9675c9d3368168092106
0x0fee1bb1c5376d660ea0b40841ebd71a55b98d4e
0xb5eb5b3a9c181f40c62e595ffe8997621bf68211
0xd386a52571c17c5354695b60b4ff5173e0a99ecf
0x3eb819da70622ee440d1aca68e0caa7c71d4600e
0x7bcbbd0dfbdacba424e527e1c4b14eb4c63afe45
0xd20651c319650a36defc4a4eb0156c4b75618f70
0xad906190e977981815e4788b7bfdb8f92868e445
0x1fcab3d2988e9c6a0607be08285b7f940314c023
0x9739ac6f635da3ff2181102ed6678c58856cb546
0x7be323864e0da8b67192c2df70c4f920919b5a48
0x910bdbcda07dd91c4235d47635c52184a063f05a
0x9cb3af04c3de653a19ff083c82f4dbe37aea3a19
0x7eb3d76b6be18234c76bdbf9316090702a9b7911
0x0ea5b54caf4fd76dccde9c51151c2187b8327338
0xbcabb38637d8240c541098e02a334ebd974417d8
0x139bf961be9a8c6381c58b1ad642f532b370ad13
0x57f75d080ea360166142bdd41c096c0e313a2b80

# Reasoning

These safe accounts are all created by 0x2236b3a9c23a2e7847a8d2125d1828bc8b9b9713

# Methodology

Execute at luabase.

with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = '0x2236b3a9c23a2e7847a8d2125d1828bc8b9b9713'

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
