### ISSUE TITLE
5693 Safes that interacted with 0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7

### ISSUE THREAD

**Issue by PulsarNetwork** [safe-global/safe-user-allocation-reports#301]
This is a follow-up of https://github.com/safe-global/safe-user-allocation-reports/issues/237

# Related Safe Addresses

entire list: https://github.com/PulsarNetwork/safe-analysis/blob/main/df21.txt

I list 10 examples here

```
0x782cd5782852da009e3422dd1b34379e62c2aa23
0xbdbc2721254dd29b8638871108b1e5af358ef641
0x174cce510e7ac18ae05c9d67540ac686ebb51810
0xe4117d452bf2944e433a1825a000bacd7d5ca5bf
0xfaf987b0989efd38086fcc4525f1d97686d61406
0x2f82e0265a116f61690df3746dbf7c8db99df8aa
0x076549e08e78d4a473412a8298fb0d370e008e09
0x4926b6a9f0c78938a52382dbd923c17f4765a2f3
0x8f1e1532384648f3e44ca8f617a3852c031bd1ab
0xd21a5d84baf43daec5bf68f7641e614b7a4f0c26
```

# Reasoning

These Safes have only 1 tx in its entire lifetime, and that is like the following:

https://etherscan.io/tx/0x934eab25eb98b64106fa3f26030cef71ef7973b769c57c6414b8acfc7696dce1#eventlog

https://etherscan.io/tx/0xb67f18efc13c0ae420a5e7356a45886a1f6b1c857ae49e5c4f91dde914fe21b2#eventlog

From the event logs we can see, 0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7 sent a tx to remove owner [0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d](https://etherscan.io/address/0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d), and assigns a new owner. This is the only tx that these Safes have.

These Safes were created by [0x5769770f5efe8fb017fb09b6de3b2d096668377d](https://etherscan.io/address/0x5769770f5efe8fb017fb09b6de3b2d096668377d). This is an address that creates Safe proxies in batch. For example: https://etherscan.io/tx/0x5bf24dd77e6aa807f2db992de7e5993ade0255ad0a1e74fa415513d472af65f6#eventlog In this tx more than 30 Safes were created.

Following the same arguments as in https://github.com/safe-global/safe-user-allocation-reports/issues/237, I believe the creator of these Safes is a relayer. It created Safes for users in batch. After creation, 0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7 who used to be an owner of the Safe, and then renounced ownership and transferred ownership to users.

Generally, this indicates a valid use case where the protocol configures Safes on user's behalf. However, if such an owner configuration tx is the only tx that the Safe has, should it be qualified for the airdrop? I don't think these are airdrop farmers, but neither do I think they should be qualified. I'll leave it to the team to decide.

The tenet of the airdrop is to incentivize / reward organic usage of Safe but not to send free money to whoever just happened to create a Safe without actually using it. That's why those Safes without any tx history are ineligible. Having 1 tx in Safe's tx history doesn't necessarily mean the user has ever used it for real transaction. Instead, the user may have never heard of Gnosis Safe, but just happened to create one via third-party apps.

# Methodology

Algorithm:
1. I identified 0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7 (let's call it the "manager") interacted with multiple Safes that have only 1 tx in the history, and those interaction times are close. There were 9995 interacted addresses in total.
2. Retrieve the manager's tx history from etherscan API
3. For each tx initiated from the manager, I filter those txs calling "execTransaction" method, and record the callee addresses. These callees are the Safes.
4. For each Safe obtained from last step, I filter those safes with only 1 record in the tx history. 5693 addresses are obtained.
5. Lastly, I manually checked a handful of safes to validate that the creators belonged to 0x5769770f5efe8fb017fb09b6de3b2d096668377d

Finally, these Safes are the ones that users didn't actually interact with, but instead the manager configured the owner as the only tx in their lifetime shows. The Safes were inactive ever since then.

The script I used is https://github.com/PulsarNetwork/safe-analysis/blob/main/df21.js

# Safe Address

0x984129b1C8D6048DF516D81f730475AF7D0E4223

**Comment by PulsarNetwork** [comment]
Final results are aggregated here, and some false positives are removed: https://github.com/safe-global/safe-user-allocation-reports/issues/365

**Comment by tschubotz** [comment]
Closing this one since #365 seems to be the complete and best report.
