### ISSUE TITLE
HOP Protocol Sybil Attack & Safe Sybil detection

### ISSUE THREAD

**Issue by yaoydong** [safe-global/safe-user-allocation-reports#314]
# Related Safe Addresses

0xf91e7b8ae9c6a128f0f7255b57e36dded54beb12
0x0368a8a67b53911afa9a031e3bc5a279e120ab4e
0x1ba3e9a047f95d54eb7cdef35c89250d3b93c165
0x2d136ad767a6dc9171aadcbf0ba63db96f9833c3
0x32726ded43fe043618ce4058d677918172c3c7de
0x447f47ec9fd19553eef567087c071280f630ca86
0x652ff793db520466c0897896a1b342801cddc0a4
0x67b39e7bdc8ce1ec4a7786b49e2af5da178f5b68
0x8bbdf82ad7e6bba715316ace25a8b1bef64f9327
0x9aae6faf121d50b447d10487c1000d7c3bc3e00c
0xb11d9ba961abcc7b44caf094984fd30f43b29cfd

other SAFEs have been reported as below:

0x033d00fc07c5fd0a714c39d70ed41c2d27896259	(reported by #247)
0x048c5abccecff12281f936a375b76773ce0ffc5e	(reported by #247)
0x0547847774be131affb807d8a77d2be55f30ab7a	(reported by #247)
0x07f48b1a03e1169c15654a47d533a699041476bc	(reported by #247)
0x0820d420e2b117ab1bcf7419b0429d16209d985e	(reported by #247)
0x0b683590f3f6637a890a4dfa007a229f16897ff4	(reported by #247,#49,#148)
0x0e59fdf43927d5dde3fec3c525e851948a1319fe	(reported by #247)
0x0f2daf24466fcb6898bb2cd6ec8e31089325cfc0	(reported by #247)
0x14c40ea486bcab3a89ede068a158080fdf9cfe10	(reported by #247)
0x1a1da0146af964550ab620fb5278125ec2e3a7a4	(reported by #247)
0x1a7aa01a566fc81201f7be7c6e78339ea28aaf01	(reported by #247)
0x1d27aeb6f4d86f9ba25f440bfc970465a7b5c79b	(reported by #247)
0x1d4eefa3ebd6d6e9d13c3e43f32b127d739493f8	(reported by #247)
0x1d60af0eba8521206cb7f90a85ef0f5ab45aa047	(reported by #133)
0x1f29d3d41a44b391bc0c4d2758cb632514f18baf	(reported by #41,#49,#148)
0x20e0d4b6892fab48fee40e4fc4131e23b388a162	(reported by #247)
0x22e52b001faea90588179bf4ce961ff73f99534a	(reported by #247)
0x244e765fc17cde65c8d5894bba68824eee47fdad	(reported by #247)
0x2a829f2c869b3f72478a88e2d4814a448243adb1	(reported by #247)
0x2ab8093c199cb818abe6543976356e2e8484cc87	(reported by #247)
0x2b6f8e4b67657260001962772f44339c0fb4e3fc	(reported by #247)
0x2c637b3963f60cc8af75c41275b55ee06a848fbc	(reported by #247)
0x3c00aa36b23606e627f165caf8c2ea6eff990065	(reported by #247)
0x3e23fb99463b06faa4cd6176e89e5172ef30fba1	(reported by #247)
0x3eab92956bd393c222e22a5065674075e651541d	(reported by #247)
0x482b4cb3d5e25287eab66a306bb79ea8ff1416b4	(reported by #247)
0x48f7fd042bda7e19584e7d4f0ab75ed3a26409ca	(reported by #247)
0x4b151114afca39297df2c1dcc6e2083db6a82f2d	(reported by #247)
0x51daa444ac0483380ec7e5cd39523eb9705d7e9d	(reported by #49,#148)
0x53368b290b2188c15aeb69c6fb11b1ce15ec1e3c	(reported by #247)
0x55cc89666309636921fe37be8316aaf701e163a4	(reported by #247)
0x583f5a736f62a838fbb00b076593d588a1033674	(reported by #247)
0x5c7d903b6023834ab49f3a251f081265f2e9ea18	(reported by #247)
0x5d39c755ffdb3193a42d65e13fbb0dfc0d4ee140	(reported by #247)
0x5f8ae1a4d621432c218ec44c20edb0ab469bcb4f	(reported by #247)
0x5ff8d8d3bee52918bd6dfbd22030847afa4cb329	(reported by #247)
0x6129217939025a4cf575a2a215301b91130871c7	(reported by #247)
0x6525617a828dadb66460eaac035b0769e11f474e	(reported by #247)
0x6684db920f87fd3ba8f35aa89397ae308c636abc	(reported by #247)
0x66f2a2faa695dd7f171f03435649d4d5d6b6c137	(reported by #247)
0x67c002cbeb8e0ce4eadb8cd4bd1ca262f1c1e578	(reported by #247)
0x69ed884522820266f6d50c0e71e7d90ec4048cd4	(reported by #247)
0x69f575f089742ba40946e744168167424da305a7	(reported by #247)
0x6e230e42cf2f1a5c5b4af3a4527c63b124495cb6	(reported by #49,#148)
0x74b504c209fc2c2956fb3745371bbc8d204c39b6	(reported by #247)
0x76ec326d705802b4358ff817a7d8fd70774717db	(reported by #247)
0x7740bfda05f1148f07c06d14de1ec5f92010599d	(reported by #247,#278)
0x78e2bbbab92d313adfa7c3a78e459025600387f0	(reported by #247)
0x79a684767eebe458682f083bd099fe2239be2b7a	(reported by #247)
0x7b23ebcd241b360ef20797667d141d391033e8f6	(reported by #247)
0x7b6ca3cac31610ddba46b4da5c356858d8f74a27	(reported by #247)
0x7d83873044596597226a69dea67b610f4e0b0a2a	(reported by #247)
0x7ede32be8fff518920aca509098f874e16bea3db	(reported by #247)
0x8107cb0ba9686a4feb1c355d54b2e2535fd635f6	(reported by #247)
0x8116aa233416b5639593ad8ecbb667e183568c55	(reported by #247)
0x870556b89db0d4684f2efdbe6f74d0d67cf453cb	(reported by #247)
0x87b03eb944eee7fe10952e217bad5b0bc4ed89c5	(reported by #247)
0x893d2b013937f00e70bc5edc00ddfed8cdc636b0	(reported by #247)
0x89862cbbe11a0d5af808f1428c8d8542e2356044	(reported by #247)
0x8b227db1a4b3c158785a89eb39f6dfccbd0bff0a	(reported by #247)
0x8fadf8979e57c968e53e879731cc26c9933dd532	(reported by #247)
0x92b100aa3fdbe71fc8286bfa199c7cdfe63dc98c	(reported by #247)
0x98c17ad86f6548115e732af4e90b64ded1781291	(reported by #247)
0x99c5b29d688badf230bb3b3346f42f8fe65c643d	(reported by #247)
0x99fe9743c3e770801c67c82e9b4a8d18e1654015	(reported by #247)
0x9a080e585515994d97784514b78e2b978dc08c84	(reported by #49,#148)
0x9aff41a486cb48873c4f55c8cea4bf35dee57d87	(reported by #49,#148)
0x9b9c078dd79b67d19a26bbd294cc11ec13dbd048	(reported by #49,#148)
0x9f6703bf9e33b14cf1dd094cfe5b16ca654bcf3d	(reported by #49,#148)
0xa320ccfb86fe2aef6c009e13b829611a9d187776	(reported by #5)
0xa6a12838021f5d860754e6cc7d261f155ebde270	(reported by #278)
0xaa04bd0231af84a91b2ef58d69633aae9a13471c	(reported by #247)
0xaad0ca45d8f543bac2cd35221d27bff3fb1f4679	(reported by #247)
0xb0deae9ed99b795531aaabf36881afb8b07d69a5	(reported by #133)
0xb230e78e07339127c065dd877e357ed1cdef30a2	(reported by #247)
0xb47a0dca4026f3186f7aa99ea4328be66fe0cd99	(reported by #247)
0xb7080983ff76377acde4a8a5e94a29290c5ae91e	(reported by #247)
0xb8da19bc85a709ee2ffb3ba8836fdb90bdd17704	(reported by #247)
0xb90ad12f148dbffab6d4eaba17a44931ec9cc892	(reported by #247)
0xbad208a710df50eb00a81479c9741c39b33a333e	(reported by #247)
0xbba9bfb0f7cefe755b890bdf582f94523b260f76	(reported by #247)
0xbc052f490853da99d14cb837413d3c80c1a54ff5	(reported by #247)
0xbc825c3094436b00a2fff7576073c974772879ec	(reported by #133)
0xbea336626a2d370f4795eb5c3ee04ad8d544853c	(reported by #247)
0xbec2b75b9f14bd42f5818ffbd0455e09b0af905c	(reported by #247)
0xc0f773d1d12930884e3ae013e4173ad3211d2108	(reported by #247)
0xc1a144f7366560baa9daa3ca2296ae3d21389a10	(reported by #247)
0xc2943d9bc16df11d0454daf4caffbd53a6fb0388	(reported by #133)
0xc63fa445ef568ad20528010f7559cb2daab305fa	(reported by #247)
0xca68e8b606d9f2aa650660707e4756796ac8bde1	(reported by #247)
0xcd37dcb108d6b992e40503634263f4022761a504	(reported by #247)
0xce9efd3278127af4a44101dc3cb8fbe9307d7875	(reported by #247)
0xcf8cf10f249369fcb200b02c763a7665b07d9963	(reported by #247)
0xd110abdb22b9d09c5eeb927047fe29b206c57bab	(reported by #247)
0xd27741ac18d9cb3df03ceafa605c29546b421edf	(reported by #247)
0xd29c371ce139f82e1a374cfe4a04ead91c3170b9	(reported by #247)
0xd3e630a984c9b8961e646bddfd4c2d80a1abb498	(reported by #4,#5,#49,#148)
0xd49da37e2c89b27d6358df36048dd5b2dc6cdff8	(reported by #247)
0xd529dbedcb38d4501231305c632fa8d857094cb7	(reported by #247)
0xd531fa380b2146027331035f7a5a2cfe0e85a052	(reported by #247)
0xd5e3dd7de6088a4df46a1cbb1389928759e05a8b	(reported by #247)
0xdc44a717f3005fa1056d054904a5534d8b0bd9ce	(reported by #247)
0xe250ac543342183c8c71d0a75e949df43b6b4e31	(reported by #247)
0xe2792f0d37f5f995c069c227de437dad47ba035e	(reported by #247)
0xe478c8f35f18d694bf85352317339a3ee17a9daa	(reported by #247)
0xe6e8714f7764c44921e7abf01f566aa789686f45	(reported by #133)
0xe6ff7cb23e34d39b71a08b855d9ec1df8daf6d1a	(reported by #247)
0xe828c7a072079e42bff9fbae403cd6e90f23c730	(reported by #247)
0xe8b9ca6cb7b637b067dfe047c46f7501a6404457	(reported by #247)
0xe8d601728cf47a31c0fb45fc7fcebaf3e25c5374	(reported by #247)
0xe94d259ce91020c4a07fdaec85eb9f17f9b179a5	(reported by #247)
0xeef590d31ceac4e8dfda964e9f4ed20fcb5d1765	(reported by #247)
0xf1e9f52f4f31aeb2fb24c3cbc7db05c771679c46	(reported by #247)
0xf241afed1ce84c267d6caf770299f1feb7c493cb	(reported by #133)
0xf31f0ebeb746cce429c9b2001f80d50065275ab4	(reported by #247)
0xf3a22647a4abf109dd1542d9dab4998dc27212ef	(reported by #247)
0xf430fe9b620536693957b10fd01895becb030d48	(reported by #247,#249,#278)
0xf4b0b32b9fb3d9289674424447715eb694e9974a	(reported by #247)
0xf668b876db6777a62d3e1e651a4e4063c717db4e	(reported by #247)
0xf6cd884abe036221605ee091d1a1f03d2833c276	(reported by #247)
0xf7248323647e47d342893fee3a237efb0c796546	(reported by #247)

0xfecd580c94f95eba4780c375ff6bbc1a95285716	(reported by #133)

# Reasoning

The addresses who created these safes had been involved in the Hop Protocol’s Airdrop Sybil Attacker List  and are recorded.

https://github.com/hop-protocol/hop-airdrop/blob/master/src/data/eliminatedSybilAttackers.csv

the SAFE addresses and creators info as below:

0x033d00fc07c5fd0a714c39d70ed41c2d27896259 0xa1a52925369c3870aacf26decf7a8727e5a47fb7
0x0368a8a67b53911afa9a031e3bc5a279e120ab4e 0xda5b7f6d7c32dbc04e3ea7e0e9b1eed6342275b1
0x048c5abccecff12281f936a375b76773ce0ffc5e 0xe44af0be65ba52302d1477315accd085bdd04691
0x0547847774be131affb807d8a77d2be55f30ab7a 0x61d9e931a72c9fb3eb9731dcc5a30f1f6c3ab63f
0x07f48b1a03e1169c15654a47d533a699041476bc 0xddf85cb54be5ad31e9e14418233ca80e59eca2ff
0x0820d420e2b117ab1bcf7419b0429d16209d985e 0x5c600f23e2c4dd1b7f65878f04709b6b06ec1678
0x0b683590f3f6637a890a4dfa007a229f16897ff4 0xcd75942b66c1a82d7e04f65a34ce7f93791fa8a8
0x0e59fdf43927d5dde3fec3c525e851948a1319fe 0xe6318ac14dc1235e01af21d354088118e15783ba
0x0f2daf24466fcb6898bb2cd6ec8e31089325cfc0 0xdb72c506f95fe747166b0c9abab78cb9228acade
0x14c40ea486bcab3a89ede068a158080fdf9cfe10 0x42acf5773af88b0e49f413e10edf9bcef93c3805
0x1a1da0146af964550ab620fb5278125ec2e3a7a4 0x86e6034c0eb6ec8d323c709c345b36219f3d3261
0x1a7aa01a566fc81201f7be7c6e78339ea28aaf01 0x65aaeec60c6149bf18753f5d2c361ecbba22651a
0x1ba3e9a047f95d54eb7cdef35c89250d3b93c165 0x5017729a41f315075bba1e669b0d8e8a5e4db8c6
0x1d27aeb6f4d86f9ba25f440bfc970465a7b5c79b 0xdb57f1613ef9d26af65bcc5dd197a9f31a5aa091
0x1d4eefa3ebd6d6e9d13c3e43f32b127d739493f8 0x20a37a8e185e48a2690f339b6d0792e9383511ab
0x1d60af0eba8521206cb7f90a85ef0f5ab45aa047 0xe1ad4a3f64df1c98fea91af310445bd0aea6dec0
0x1f29d3d41a44b391bc0c4d2758cb632514f18baf 0xcbcc36af59675e7b291dcbcf7c5adc7b9894969d
0x20e0d4b6892fab48fee40e4fc4131e23b388a162 0xab6f255dac71103ea6d57b320eaf0eec901b05aa
0x22e52b001faea90588179bf4ce961ff73f99534a 0x13baa80a256ce171485224d7a427e594125f18fa
0x244e765fc17cde65c8d5894bba68824eee47fdad 0x6c13fc8ef50144a21702415d57ece0a09879fcfb
0x2a829f2c869b3f72478a88e2d4814a448243adb1 0x03f9bc4648a98cdc61fca7a177d809edab2c14fc
0x2ab8093c199cb818abe6543976356e2e8484cc87 0xe40c9db4b30c32dfb29f48379c21fc459337ea95
0x2b6f8e4b67657260001962772f44339c0fb4e3fc 0xcf8e24538e6e8c6d7ca711f84539aeac0892e28b
0x2c637b3963f60cc8af75c41275b55ee06a848fbc 0xbddf8194ccc04be52d3e66d5dfb63edba8735e40
0x2d136ad767a6dc9171aadcbf0ba63db96f9833c3 0x18f70a29fbc1389030822de6c56f3ce2cdfaec00
0x32726ded43fe043618ce4058d677918172c3c7de 0x10bf0cc5fce2f6b8cae0dc97255c2e3a57ee9d47
0x3c00aa36b23606e627f165caf8c2ea6eff990065 0x5ee9b86f3d4c48bb5c72927e1e051466d5b0a41a
0x3e23fb99463b06faa4cd6176e89e5172ef30fba1 0xec561dd73346f761d1c09f46999bc8ea1b1e95a2
0x3eab92956bd393c222e22a5065674075e651541d 0x59d186ce5968b3b5cd6730f45ad4a79c17646e20
0x447f47ec9fd19553eef567087c071280f630ca86 0x2aa40b4f2c62c70b12ca2295f3657632a21d5396
0x482b4cb3d5e25287eab66a306bb79ea8ff1416b4 0x9497243478392b1f7f508874f606379f989c6eea
0x48f7fd042bda7e19584e7d4f0ab75ed3a26409ca 0xb27bd8ee31e3796a5168fe6bb27054e62a07e155
0x4b151114afca39297df2c1dcc6e2083db6a82f2d 0x15446371fe06e86fcd27b1f567491a3eee9c238e
0x51daa444ac0483380ec7e5cd39523eb9705d7e9d 0x75c1e14cd2d114686bd5b765fcfe376176e41f1f
0x53368b290b2188c15aeb69c6fb11b1ce15ec1e3c 0x12d5cae401268d459484eb4a00c55fa6acc73398
0x55cc89666309636921fe37be8316aaf701e163a4 0xe1d1c5f48f708aa038aa6a9976308cd1d19d951a
0x583f5a736f62a838fbb00b076593d588a1033674 0x0e6aed5b0a6d815c21512d928221773f9bd124f2
0x5c7d903b6023834ab49f3a251f081265f2e9ea18 0x2aa40b4f2c62c70b12ca2295f3657632a21d5396
0x5d39c755ffdb3193a42d65e13fbb0dfc0d4ee140 0x3f4be1b1c3403d19388e31634ac1029254d6a000
0x5f8ae1a4d621432c218ec44c20edb0ab469bcb4f 0x080a75c96bf646cd9f78aaf8c9869a510e9c68bb
0x5ff8d8d3bee52918bd6dfbd22030847afa4cb329 0x2eb4f35b998ba230562f646dc235ac25f18a3034
0x6129217939025a4cf575a2a215301b91130871c7 0x73f61e66345b8f78951508e8f1cd0ab51e1d9b6b
0x6525617a828dadb66460eaac035b0769e11f474e 0xe5214a481f2c2bbd501c14dfa66254a8a907cf39
0x652ff793db520466c0897896a1b342801cddc0a4 0xfe0d9c8fb18da8628eeba33ff9649594421fb62e
0x6684db920f87fd3ba8f35aa89397ae308c636abc 0x495e827e540ca60c93bbac919b4627554211f33f
0x66f2a2faa695dd7f171f03435649d4d5d6b6c137 0xb2c68c5df1688953ac0fd81e0e460da59f72e95c
0x67b39e7bdc8ce1ec4a7786b49e2af5da178f5b68 0xd0e80683d9799516363401c18764340d5ef74edd
0x67c002cbeb8e0ce4eadb8cd4bd1ca262f1c1e578 0x7302c7e150ae4d035cf9e71f09580d59ce61fa54
0x69ed884522820266f6d50c0e71e7d90ec4048cd4 0xde88d146f61463d582262a1dcdf6ea1323aba34a
0x69f575f089742ba40946e744168167424da305a7 0x597ddaf79527d46a3d838ed4b06bb37ebba8fc87
0x6e230e42cf2f1a5c5b4af3a4527c63b124495cb6 0xd942010f8808996a682502df5d5b2af7fcbc7318
0x74b504c209fc2c2956fb3745371bbc8d204c39b6 0x82b1d4b86d5588b8442c7a7a77986b365dd4c698
0x76ec326d705802b4358ff817a7d8fd70774717db 0xd0e5122084f90d49cd8ffea056e431f94cb174c3
0x7740bfda05f1148f07c06d14de1ec5f92010599d 0xd52b5da2136081a1df0b065f083e144c96481f2e
0x78e2bbbab92d313adfa7c3a78e459025600387f0 0x99d6d24012361620bfa1a3f16d4e745066fc7c69
0x79a684767eebe458682f083bd099fe2239be2b7a 0xa3fa994c98c37e97a71a440a1725b1571b1bfb02
0x7b23ebcd241b360ef20797667d141d391033e8f6 0xbd129349ec13ad73c279047cf1ae66454373161b
0x7b6ca3cac31610ddba46b4da5c356858d8f74a27 0x50c2b9c3acda872dd71d88aa2c198aed0b788e5b
0x7d83873044596597226a69dea67b610f4e0b0a2a 0x706d961ab69d54a0fcbaa13e77842279a5724139
0x7ede32be8fff518920aca509098f874e16bea3db 0xe4fabf869fdcdc457c87ebae40ab78be7d345d4b
0x8107cb0ba9686a4feb1c355d54b2e2535fd635f6 0xbf5310fae4d7a0c6df0452bcda09aefa2748ad59
0x8116aa233416b5639593ad8ecbb667e183568c55 0x4a7d7691d628670bd350cb684fdf34d63f6e9e0f
0x870556b89db0d4684f2efdbe6f74d0d67cf453cb 0xf19aeb0f2d0f53e6e2f015a7c531f6c271858ba4
0x87b03eb944eee7fe10952e217bad5b0bc4ed89c5 0xbee71a04d6966dd056f55a9ad2fda1db281e1d9d
0x893d2b013937f00e70bc5edc00ddfed8cdc636b0 0xbb7bb43af885549f1bbf5724213ee48b40ebee83
0x89862cbbe11a0d5af808f1428c8d8542e2356044 0x91f7c7dc5a44276482c102178fe1d620b397c276
0x8b227db1a4b3c158785a89eb39f6dfccbd0bff0a 0xce9cc2efb00a730009346b173045dba73fd3327c
0x8bbdf82ad7e6bba715316ace25a8b1bef64f9327 0xd0e80683d9799516363401c18764340d5ef74edd
0x8fadf8979e57c968e53e879731cc26c9933dd532 0xe9006c3732dde8c2d5c4ce65568179035ace744d
0x92b100aa3fdbe71fc8286bfa199c7cdfe63dc98c 0xdd4a19dc351ba42421db282196af38b433aa86ba
0x98c17ad86f6548115e732af4e90b64ded1781291 0x7b5a8cbc77876421f1dcfb22ae2a1c404d7b71cb
0x99c5b29d688badf230bb3b3346f42f8fe65c643d 0x3082f27581a2449268a14af56d810cacd9984ec1
0x99fe9743c3e770801c67c82e9b4a8d18e1654015 0x807a1cf8586164c3d56fa6bf0295fa358b233b74
0x9a080e585515994d97784514b78e2b978dc08c84 0xf201b83ab58b2e72cdcf8ffffd05fdc43032abee
0x9aae6faf121d50b447d10487c1000d7c3bc3e00c 0x5716e900249d6c35afa41343a2394c32c1b4e6cb
0x9aff41a486cb48873c4f55c8cea4bf35dee57d87 0x696d181a7961ee66c42f1ebeddc0b48b106c45ad
0x9b9c078dd79b67d19a26bbd294cc11ec13dbd048 0x1fe6a806e0a9858359e16c58e4f84c790171596b
0x9f6703bf9e33b14cf1dd094cfe5b16ca654bcf3d 0xd54c755bf34a109b65c599dcdb59e51b2cd9adb6
0xa320ccfb86fe2aef6c009e13b829611a9d187776 0xbbe82615988f669d2b6bae63e24f4d44397894d5
0xa6a12838021f5d860754e6cc7d261f155ebde270 0x51f61fad9513d06ccc2ec312b0852913015e612d
0xaa04bd0231af84a91b2ef58d69633aae9a13471c 0x6c99e8ea19074d37badb3a2826be8a1088e7877c
0xaad0ca45d8f543bac2cd35221d27bff3fb1f4679 0x93ba368cfa7c4f672ca68292f695132ed30c4f1a
0xb0deae9ed99b795531aaabf36881afb8b07d69a5 0x8e8e31cfb9298a432e24b7f94acf06bec8f5c887
0xb11d9ba961abcc7b44caf094984fd30f43b29cfd 0xafc3faeb81d3ac75e52556f88dfd144b56523281
0xb230e78e07339127c065dd877e357ed1cdef30a2 0x9a779bc11ab33dc173a409cf6e7e2ac906350f82
0xb47a0dca4026f3186f7aa99ea4328be66fe0cd99 0xae9393288285043daed4b89853d0a299d082b02a
0xb7080983ff76377acde4a8a5e94a29290c5ae91e 0xafa9c4b52c3416515c8882f2a65f46aa89e19c81
0xb8da19bc85a709ee2ffb3ba8836fdb90bdd17704 0xe2e8fee9ac2af4352a0e424650b77da25c36bf80
0xb90ad12f148dbffab6d4eaba17a44931ec9cc892 0xafc3faeb81d3ac75e52556f88dfd144b56523281
0xbad208a710df50eb00a81479c9741c39b33a333e 0x0d801699678375e43d14f67453e24f17ebbaef8a
0xbba9bfb0f7cefe755b890bdf582f94523b260f76 0x89768ca7e116d7971519af950dbbdf6e80b9ded1
0xbc052f490853da99d14cb837413d3c80c1a54ff5 0xbbb2d07823a2e97e84969382233461ac82d1079d
0xbc825c3094436b00a2fff7576073c974772879ec 0x23fe60c2e63ddcc13d651946c24baace2bc295e2
0xbea336626a2d370f4795eb5c3ee04ad8d544853c 0xb8a9c37240e8b72f42a88f1099e6c61dc3e96756
0xbec2b75b9f14bd42f5818ffbd0455e09b0af905c 0x9c28fe17800865f0b7e635ec658daea056db370e
0xc0f773d1d12930884e3ae013e4173ad3211d2108 0xcd5c1bb777c937d993bc5e16e48b1669becc77aa
0xc1a144f7366560baa9daa3ca2296ae3d21389a10 0xb798e1944d57dac59da1ddd833506f49967dd6f3
0xc2943d9bc16df11d0454daf4caffbd53a6fb0388 0x5e1e0f59774052344cad68939025f2d959bd6e79
0xc63fa445ef568ad20528010f7559cb2daab305fa 0xdc4a04c3a9e4f3d6674e3ea292d946a8185abed9
0xca68e8b606d9f2aa650660707e4756796ac8bde1 0x10bf0cc5fce2f6b8cae0dc97255c2e3a57ee9d47
0xcd37dcb108d6b992e40503634263f4022761a504 0x60c63bbb27f1f49f63eacadc773c79bf0c17ac7a
0xce9efd3278127af4a44101dc3cb8fbe9307d7875 0x04661a2f774b746d03c437d74d4788634a3c42da
0xcf8cf10f249369fcb200b02c763a7665b07d9963 0x0ce567bd9e1c9c3141be185219fb4ddf346c9d95
0xd110abdb22b9d09c5eeb927047fe29b206c57bab 0xaad15739bbba6a0a964d6adbaf746ed1107b67f6
0xd27741ac18d9cb3df03ceafa605c29546b421edf 0x394bc1ee5687397b354943516d04f07b28967ff3
0xd29c371ce139f82e1a374cfe4a04ead91c3170b9 0x4639b83faed52e978e0b5d9a4b0f3f7d1b17d33f
0xd3e630a984c9b8961e646bddfd4c2d80a1abb498 0x8c2e843664be468522769b0d1b3b604a17962249
0xd49da37e2c89b27d6358df36048dd5b2dc6cdff8 0xc89ebc3ab47abdfa150d6e880dd44d8250c5a904
0xd529dbedcb38d4501231305c632fa8d857094cb7 0x90ff89c637fd1537e151b8ced1d1d0cb94e31ca6
0xd531fa380b2146027331035f7a5a2cfe0e85a052 0x3db00d1334b5fadd2a897d8a702cdcbb6f159d87
0xd5e3dd7de6088a4df46a1cbb1389928759e05a8b 0x2abf33485edf704511dfa42dfb8afa71a0450a8e
0xdc44a717f3005fa1056d054904a5534d8b0bd9ce 0x271d8e39108990e89de0aef49275a194269b58c5
0xe250ac543342183c8c71d0a75e949df43b6b4e31 0xddeff0c54214528e12298e6207cc260914c294d9
0xe2792f0d37f5f995c069c227de437dad47ba035e 0x48f73a47f17a374ba42253c665bd8389f2efdd31
0xe478c8f35f18d694bf85352317339a3ee17a9daa 0x597fc897b6ab221c18cf51a31cef41285597aef1

0xe6e8714f7764c44921e7abf01f566aa789686f45 0x31e9a9a158d88628beffb2dfb8319615e377edf0
0xe6ff7cb23e34d39b71a08b855d9ec1df8daf6d1a 0xdf627f524a24212acb573e8b1ae5f47e6ab83f69
0xe828c7a072079e42bff9fbae403cd6e90f23c730 0xa1a670d5fcd74dd496a93644c11eb750b18e1526
0xe8b9ca6cb7b637b067dfe047c46f7501a6404457 0xc17b32ec5b1e02231a41abdb38d476f20fa00d41
0xe8d601728cf47a31c0fb45fc7fcebaf3e25c5374 0x5cfc2c648ba36144644758f8d39553c0ce355fc6
0xe94d259ce91020c4a07fdaec85eb9f17f9b179a5 0x484adfda2b22b76109087bfffcb1d120f8e045a9
0xeef590d31ceac4e8dfda964e9f4ed20fcb5d1765 0x236884bb674067c96fcbcc5dff728141e05be99d
0xf1e9f52f4f31aeb2fb24c3cbc7db05c771679c46 0xe7e207e94d07a370de80e7d38093b49a7217ec23
0xf241afed1ce84c267d6caf770299f1feb7c493cb 0x39af030facc2da718b12c490054c1f75887e862b
0xf31f0ebeb746cce429c9b2001f80d50065275ab4 0x6a82e96360153cd5982e6283e4c6a8af23ec7dce
0xf3a22647a4abf109dd1542d9dab4998dc27212ef 0x05feb7cc73b0e522a360d0d0bc0e0360e8b630d6
0xf430fe9b620536693957b10fd01895becb030d48 0x052e4c0307fe3a4670b7e94a817886fe2a582b73
0xf4b0b32b9fb3d9289674424447715eb694e9974a 0x939bac3bad78752763be4dd1da19e8e70995a408
0xf668b876db6777a62d3e1e651a4e4063c717db4e 0xddd8fc242bdff7feb7d627e9b350176293756424
0xf6cd884abe036221605ee091d1a1f03d2833c276 0x0d801699678375e43d14f67453e24f17ebbaef8a
0xf7248323647e47d342893fee3a237efb0c796546 0xade883c2d201faee374ee238b88f4c0d9adf0d04
0xf91e7b8ae9c6a128f0f7255b57e36dded54beb12 0x12d5cae401268d459484eb4a00c55fa6acc73398
0xfecd580c94f95eba4780c375ff6bbc1a95285716 0x27dac4f72f2de2c4d8c1d702f25009ac7e189106

# Methodology

First, associate the SAFE address with the creator address.
Then download the list of addresses related to the Hop Protocol’s Airdrop Sybil Attacker List .
Finally merge them for retrieval.

# Safe Address

0xfdf11fa8ae68ddb3ff2b9138a517e6518f2e8796

**Comment by hechenxiao** [comment]
I only have 1 gnosis-safe address, the signature wallet to generate this address was previously used HOP, why is it that some people say I am an airborne hunter, you can't report it in order to get the reward, don't report it, okay?

**Comment by yaoydong** [comment]
> I only have 1 gnosis-safe address, the signature wallet to generate this address was previously used HOP, why is it that some people say I am an airborne hunter, you can't report it in order to get the reward, don't report it, okay?

ser, I checked with HOP Protocol Sybil Attack List and SAFE address airdrop list.

if there are some problem with HOP Protocol Sybil Attack List ,maybe you can chat with Lukas in DC, hope it works

**Comment by zsandwf** [comment]
I only have 2 gnosis-safe address, the signature wallet to generate this address was previously used HOP

**Comment by tschubotz** [comment]
```
0xf91e7b8ae9c6a128f0f7255b57e36dded54beb12
0x0368a8a67b53911afa9a031e3bc5a279e120ab4e
0x1ba3e9a047f95d54eb7cdef35c89250d3b93c165
0x2d136ad767a6dc9171aadcbf0ba63db96f9833c3
0x32726ded43fe043618ce4058d677918172c3c7de
0x447f47ec9fd19553eef567087c071280f630ca86
0x652ff793db520466c0897896a1b342801cddc0a4
0x67b39e7bdc8ce1ec4a7786b49e2af5da178f5b68
0x8bbdf82ad7e6bba715316ace25a8b1bef64f9327
0x9aae6faf121d50b447d10487c1000d7c3bc3e00c
0xb11d9ba961abcc7b44caf094984fd30f43b29cfd
```

I'm unable to see any pattern, hence I can't really conclude that these are owned by the same person. There's a chance this is legitimate usage imo.
