### ISSUE TITLE
A broader explanation of Ticket #204 (A MUST READ)

### ISSUE THREAD

**Issue by CaptainTee** [safe-global/safe-user-allocation-reports#319]
This ticket is a well arranged of data in ticket #204 for clarification purpose.

**BATCH A: 121 SAFE addresses**
I have read several responses that one address creating many SAFEs doesn't necessarily amounts to airdrop farming.
However, I have currently identified 121 SAFEs created by `0x07F455F30e862E13E3E3D960762cB11c4F744d52` tagged on Etherscan as `SAFE relay service- deployer` and the following points worth giving attention to;

1) The `[SAFE relay service- deployer](0x07F455F30e862E13E3E3D960762cB11c4F744d52
)` sometimes fund the EOA address that was used to create SAFE i.e `Contract Creator` for the sole purpose of creating the SAFE and after successful creation of the SAFE, the remaining token in the SAFE is returned to the `SAFE relay service- deployer` through a contract execution on a dApp or direct.
For Example;
`0xfa30beaf5480e85a539e039a16cc1feee6f23c95` `0x0effa3089e4073368e5ee588baa4dee38af82fdf` which are both SAFEs address were created by different addresses `Contract Creators` but those `Contract Creators` were funded by `0x07F455F30e862E13E3E3D960762cB11c4F744d52` tagged as `SAFE relay service- deployer` and the remaining token in the SAFE were immediately returned to the `SAFE relay service- deployer`

2) The `SAFE relay service- deployer` sometimes create a SAFE and another EOA wallet address fund the SAFE but the token sent to the SAFE immediately gets sent out to the `SAFE relay service- deployer`.
For Example;
`0x0F125b3BBFA7ab95A6cB04DCD636229bBB8Ee1E4` which is a SAFE address was created by `[SAFE relay service- deployer](0x07F455F30e862E13E3E3D960762cB11c4F744d52
)` and funded by `0x1E97897708649B4b3B5239CC3C673f9F875cA991`. **1.22561745 SAI** out of **1.23 SAI** sent into the SAFE was immediately sent out to the `SAFE relay service- deployer`

3) All the SAFEs created by this `SAFE relay service- deployer` and other related SAFEs received DAI, SAI or ETH worth between **$0.9 to $10** at the time of the transaction and never been put to use since the day they were funded.

If you think this is truly Airdrop farmers way, kindly disqualified the 121 eligible SAFE addresses created by this `SAFE relay service- deployer`. Here below are the SAFE addresses in question;
0xc6c15968322418985380bef6f11fde85bf565cb9
0xdb08f138ac75db97636f5d1cf490dea98fc44f9a
0x313deda1640142c3db2af38eccd42af5796ed051
0x173e7598bd290dbb1346318081f9122c71815e33
0xbb63c2c8ddf964166f6c61104b6c5ff05148265e
0x1d5fceb726fcbaa3d7d9885b8666305ed44ad23e
0x6ff9a594d17310462ad6559a1f41cebf5b6fbc33
0x247443e4a373f0c70fd4ab6d03e16011d50295c7
0xebc223769aea7088451716572bdb7b1f4226fa57
0x902d3818fbea7fd76c5fab407b135011c6c715dc
0xe30d326fec0425c309baa33c7f479ddeb955e153
0x547b8b0c0a553874aa50a7d533971c8e1f10679a
0x03e4e842d35d359cd776fe527fe77fe5bbb0ecd0
0x84f17c80a5ba165d8d98d00170c60ca9ac719a35
0x7be98abc0a666265d323d1d901e31fd3e3aaf5f4
0xa2cf37d31f606f7280cd01c488e58cc7438d3cbf
0xf9be62ececda4d8d25d8d4fe345a2654262df240
0x6270301a6b6aee5a1cca7cafbb340e6373b42c84
0x65d1c65151e50b1e60854e1c11e0efc87d116457
0xcb66860bede476ab2a34640e70690f437634a287
0x16fb9d158f8fd058d2bf3fccdcfb8ecb70e42253
0xb6c4fc9e1aa445675cd1f428447a12224f6a6b8e
0x965056ac7542dc3477654c6998ef63335949b6c7
0xbcfc032eb694a36a8aaeba583fa3809d82094cfc
0xfb4f1e2dc0707945dda19035738f6f9e6e0d72b3
0x8c19dd7529403ef0ca3bb4b10f60af7b0919de1b
0xab3e0a99c61276a2b3471b6a0b59dce3c89f6d11
0xfe088064cf3bf02be53127c7d1831f64d8c79293
0x545ddee106841e82eb23d225d0f3ef073bd4248c
0x79de38fa14e88f723e085bf25a1ccc98d75ec8c0
0x3c1e2cc566bf1a745927d7e3c57cb080a449dc46
0x811d88dd0e75ae8b92ac50249690ffdbc0f47024
0xafbbf2b7d60fe4e6b4ff81edb8ad0cefbfcd3b6e
0x0d3c54a0e7f8e1f41f6214a3613510951869851f
0xe67c58a43356c2c76f17b5997a37488b138bd771
0x71ace54578d77f5cc505c2d1701daa00af695da6
0x3f8b6291a243f6ccd1adda8f7b676ae851cd2fed
0xd88cabc045a8bed0223c45e5a7af3a4ed4716b17
0x497bce08648eff58c2f353dc45ff46d1850edc29
0xb999009cf74be1a93c10896d2a7e7136b9ca4770
0x1df85ce4f62f024cf37e6790ffff53e179d7135e
0x92bb7e705e14b97d266f56f4d69ccda566e74e17
0xc416ccfccc399b58cb85ae649963e5e8d242374e
0xb1e8b3d5e748a5c8b8800942348897c23aadf319
0xa6763707d63c37679c171a1745d9cbad7986fc1e
0x304ae9fbd30e42db348ff0265864c7db255e34c8
0xfcc9928935f265e8a739f5f83b4b52b4af2608be
0xca3de2788326a96a226b6e38956c8a5234ece2ea
0x154f467ca52a7cd6e8fc6a4a6f1f165cbf338bf8
0x86f0ed47030c6e7e7b1bf912dbbd55ad937170b0
0x518cac68328406e743f10746c5325e91a4e8bf97
0x2bc54ce6972902d43c221e9600c8fdea6e13ced5
0xa62773a4dd6ee30107ea8865b124c8fed091398b
0x5a4c976c16f37ae03b855edd62942d982159eae2
0xb8d34ba8e54b72d94a9631203a203eba7e51cb35
0xfd9ada0495f935236e5a10580972291293a3f7c0
0x83fdfd060e21913a1625c8dcaae36cc84197cf37
0x37cbd65148a0b4341a1e1b5618dae1653aae5c1a
0x1296f1463b548c84025d1783e6601d37dfeb2884
0xfe3767fd33ddee1f128d6e65268b9b9a71dbab86
0xa68c0551bde8b20b8368ddc6b21421ec7a4151ee
0x72e49065c9dde4cdb946a134ae7dd286cb27a26d
0xb70968ad7e0ea11920c38699e035a061ab35b94a
0x872d06c2ce9d22eec5ea3b86fe3e1051746a5201
0x8c85712a0b7fdd30aa4183a8b0e5e419176b84aa
0xeccbcda958d2ad7dc8c859db53d2d01c9908dbf1
0x3bcac3eee26cb4ea45ce1ffb3352097f3d36ebde
0x87bdaa78903f6336c8aeb8c6f14c13b375896fdc
0x2661d7c7b5f380e3dd7d3b42938605ed5cbe33db
0xc012510476e2e0f69744e644dfca4dc6fdaf0762
0xdafa7e4c660a88683b644ed6a2f9d45fea8f9018
0x39c758cb58f73475fad324bfc1995e4b459191b5
0x7ec229380f7b66e51ca26360c29ff1d59a3fdaf7
0x972736bd9026646be25bdcb18216153495703387
0x8f8abc534ab8d9a7647a272b2e27ae03f4382309
0xdc12e5cc245564122eea978f290b81dbfb972c75
0x1844540b937e7fca0f7b8bd4b251f02ca2976b97
0x7498131d15fb2b8377d948410dfa3250b01f9d1b
0x8a7a352802d091613777e73a793887b077e0f6e1
0x172fa6f5ef97d2eee3ae3cb0d0904df47cf1d192
`0x0f125b3bbfa7ab95a6cb04dcd636229bbb8ee1e4`
0x8d1eaaab70da888f4f25b360cac1061bfd560d4e
0xd181b1abc3d6513cff9112b7d5d34d8e4019af73
0x57e9c153a0a81b61690ba1fb3fa6f544a0a94573
0x5a42e1c66833df0572699da5bb149740d5e09483
0xf8335e5b37f93edada4c67e28f38cfcdbd016493
0xcf64c015b157b36f5df4135f1ca0f45728b88a8a
0x91536946d85da0b135ceb4c436337c0ad0b7a757
0xc3a97666de65681be819934cf4c4320540b0c7e2
0x7343e833423d152d901008576a6869870be4df0e
0x788cf9998b4d9438f83cbd111a33bbe02065d918
0xfb373cf80d09898dfff255e89b8c7062d7277022
0x6ce6abc68224810f4e68fd3461123057167a826f
0xa5a448ff6c94510f4f421c349eef85aae225ced7
0xc09b2344b053b3e7c3ba01f67a5ec9652888fcc5
0xec58c4d646efea1cb52c40d056a751518246a9be
0xffc0ab0af95e2ad19ff3f53b1807477891a0b6eb
0xa9166b9208142ce1c59572086265b4bee16df638
0x2161f722d473144ee759842b6293206ff072b18b
0xbc8ab342ac968618017827f4d06914dfb2d5c394
0xed0b5619e7104fb03efa143f08cde2e360efa80f
0xf28b168f5ad0f06a6e0afad6f12bb1865e2b3c3d
0xc94db4abbfcbbf5775a5adae5205dbc033dba86e
0x4fcc30ec98e302364b52ae1867dde5b979718955
0x950a5fd51af22f220a3330f1bea561a0d07a1b74
0x7a00719b9b38fda711757cb0cea7995d7c56f76a
0x3ec0f5be34490fe592fd4cea835ec8bcc0bee1b3
0x60e0976a7ad5d9eb50d46f44c376826ee9fab089
0x271fc4559f5650ca41b17283e3932e3ac03ceb7d
0x6a3563ab46385816fe607c3cea67aef09986499a
0x921e3eab09f024f26fe6419fc2a184bc29ad92c8
0x7a99d882f1f035604c87852f1b45979f77ec5f74
0x6cf45c47bc1fe215226ac573b03c2daaa3bffa03
0xb02cffcd5431e19aaa1e842d1f6a414d1927b6c5
0xc592b3d8fc0ee736553133fcc8fe914f4b760f4f
0xc1044285871363b8db1b1de203a9af5760ad14a5
0x88022119456deb8efb337fa0461a15cf5e308ba7
0xc5796ca9060a0d5e620d2a153d1532c288378337
0xbb232f34c431b7b1f16da8610bd539aa9aac2e34
0xfa30beaf5480e85a539e039a16cc1feee6f23c95
0x0effa3089e4073368e5ee588baa4dee38af82fdf

**BATCH B: 5 SAFEs are identified**

The SAFE addresses that made up my `Batch B` has the following characteristics that worth taking into consideration.
1) All the SAFEs were created by same `[Contract Creator](https://etherscan.io/address/0xf7D44D5a28d5AF27a7F9c8fc6eFe0129e554d7c4)` on the same day and at the same time
2) All the SAFEs were funded with **0.000001 ETH** worth **$0.00** each at the same time.
3) All the SAFEs were never put to use since creation day

If you agree that this is airdrop farming strategy, kindly disqualify the 5 SAFE addresses listed below
0x16e016e5d801388a2682cc8369ffce0ad89f81d6
0x6159275fea1f9a6e197bd35cd317152fe6f08423
0x3b6befb464d620e956439fff48ab149e2e37048f
0x72d6c0c43067ac24a802508bebd803c9dc67d290
0x822fdbd45b2bbdce402103d63a885c1253c6190e

**BATCH C: 4 SAFEs are identified**

The SAFE addresses that made up my `Batch C` has the following characteristics that worth taking into consideration.
1) The SAFEs were created by same `Contract Creator`
2) The SAFEs were funded by different EOA addresses but the remaining ETH after 1 time execution in one SAFE is sometimes sent to another SAFE for the other SAFE to has its own 1 time execution.

The below are the addresses in question:
0x3155468409f81451134c6ee644a3e9f57d612193
0x9e76cbea77c0a581d45c8d6cbe7ec3a264c73639
0x7524f87f8c27e69c9e60a08a0346c55119c9358e
0xe3f083558a6631d475eb98ed3e5ece7b62cbe2e8

**BATCH D: 3 SAFEs are identified**
The SAFE addresses that made up my `Batch D` has the following characteristics that worth taking into consideration.
1) The SAFEs were created by different `Contract Creator` but at the same time of same day
2) The SAFEs were funded by same EOA wallet
3) The SAFEs were funded with very negligible amounts 0.00015 ETH, 0.0002 ETH and 0.00012 ETH respectively

The SAFE addresses in question are:
0x23c9d5741fe7077954f218ea9daf101b81735324 0x54C0421a4E30552182B76AfCc79B1edc52DF9D2c
0x072cfbcb95c255046ac2f81abe969e42af8ad3d6 0xB3C17E200E872119379C52995399E1cA9f1a56ac
0x5499a79083316047edfa096801b6f5e012644690 0xfa99537541451BE9B4Cf86611361597e6F1C19B2

**BATCH E: 2 SAFEs are identified**

**Safe Address**
0xebd217f5b00ee777dfafcf8d5663c824949c677e
0xbbe24603813d7acf87a080633741880e5758347a

The above listed SAFEs were created/deployed by same Contract creator with only negligible 1 transaction each

**BATCH F: 2 SAFEs are identified**

**Safe Address**
0x06db4a5a8d100f7be80a4682b9b8dd1b9396f98d
0xf68ade90d0f96f1a7d8ecc5fa79bb3eaa808e4e3

The above listed SAFEs were created/deployed by same Contract creator with only negligible 1 transaction each

**BATCH G: 2 SAFEs are identified**

**Safe Address**
0xc411e2b26b8276a7ae5871818d2e25bb51395f39
0x005b55988ee303a06eadde47b7b2f3e05a1801ae

The above listed SAFEs were created/deployed by same Contract creator with source of the only transaction (incoming)

**Method of Finding used:**
The Google sheet that show the 55,719 qualifying address was exported to Excle and sorted according to number of $SAFE eligible receive starting from Low to Highest i.e 100 and above.
I started by scanning the eligible SAFE address to know the `Contract Creator` and The `Funding wallet` to the SAFE to point out any correlation among the SAFEs.
Scans made on first 100 to 200 eligible SAFE addresses show that identified and above reported findings.
**DeBank** platform was used in digging on wallets where Etherscan doesn't show all transactions

_More address will be identified and posted as checking continue_

Attached document is the workbook used in finding the correlation among the identified SAFEs
[BATCH A - SAFE SYBIL.xlsx](https://github.com/safe-global/safe-user-allocation-reports/files/9539190/BATCH.A.-.SAFE.SYBIL.xlsx)

My SAFE address:
Kindly reward my hardwork with the 25% of the recovered token to my below SAFE address
**0xcee6063D59e3fF951677AD1E1B2b58C686efFA50**

Well done, Team!!!

**Comment by CaptainTee** [comment]
Cc: @tschubotz 
Please check the above and feedback

**Comment by PulsarNetwork** [comment]
I checked a handful of Batch A addresses. They were all created by Safe Relayer Service in 2019 and 2020. I found some common patterns

1. (Majority) Only 1 direct tx in "Transaction" section where it received tiny amounts of ETH: https://etherscan.io/address/0x37cbd65148a0b4341a1e1b5618dae1653aae5c1a
2. No direct tx but it used Safe Relayer Service to trade some ERC20 tokens: https://etherscan.io/address/0xbb63c2c8ddf964166f6c61104b6c5ff05148265e
3. More than 1 direct tx history: https://etherscan.io/address/0x0effa3089e4073368e5ee588baa4dee38af82fdf

2 and 3 do not look like sybils or unused smart contract wallets to me. As for 1, we don't have a clear idea why it always received a small amount of ETH. Was it for gas fee refund from relayer / 3rd party dapp? This is only my guess. You can try tracing the source of these small incoming ETH transfers to figure out.

**Comment by CaptainTee** [comment]
Thank you @PulsarNetwork for digging into this as I requested.

I will leave this to the team to dig more on. $SAFE should go to real users and not sybillers

Cc: @tschubotz

**Comment by skydotone** [comment]
@tschubotz. could you have a check about my issue? [issue124](https://github.com/safe-global/safe-user-allocation-reports/issues/319)

**Comment by lukasschor** [comment]
Most of them are created as far back as 2019. These might be mostly un-used Safes, but they were at least not systematic airdrop hunters as in 2019 "airdrop hunting" was not even a thing yet. In order to not exclude any legitimate early adopters (even though they might be inactive since) I will mark this as invalid. Even if early adopters have become inactive since, they have helped us with early product feedback and should be rewarded.

**Comment by CaptainTee** [comment]
Good judgement, sir😉
Well done 👍
I have more good and informative report in 
#504 that awaits your review
