### ISSUE TITLE
Warning of drop hunters

### ISSUE THREAD

**Issue by BountyHunters1** [safe-global/safe-user-allocation-reports#327]
0xC41Dd7D65444cdCD80d7E2FBd9d20c4B191Cf988
0x2d737cd0eBbdB40f4bCDDCbd0FcE1C03eB4a60Ba
0x821B7C84313B4901094246621181e995E5F1A83A
0xA4E870BFf703007E8a039b8947168cff22b50C90
0xB7E850025f77292c1602E2a48123b1455864FeCE
0x78eDDdE998E446A09A5b2054516f1da0B72CadA5
0xbdAE68423e2aB0Ff3164e02478a62CBfd73FbB68
0x865032F9ecF34F31f901bd420A476C6322fD13d4
0x5Adb607541cA9c1FA7bfc451A4b825EB56fD04D9
0x6E7497241C416fCC5E3447180882756dcf7Df5a0
0xEB17f902307dC052701e501F07e1C556Beb1a368

0x9d2457F5eb132415b8f3c7582791bDAEf0ae77ad
0x2C681dfaeb767b0d2566e60C0f78Bfb7c59c72DB
0x3bED69632A03a987CDEA408788845bD4818844d4
0xfCe853eAF6e6256033c2dE33A0E850838aB0dD4d
0xF7a116312c6cc8aF4e7e1D31E89642B681C14829
0x0167efcf8779540c0c663988223c8aF1C987dD27
0x0e0D46D1Eb35faaf40ec9D6b1EbB20Ed4EBaA6C3

Reasoning
The airdrop hunter used the 0xf9d38489b6fd704fd112934322908ee0b6cfbdd4 mainnet wallet to create 19 multi-signature ，
0xf9d38489b6fd704fd112934322908ee0b6cfbdd4
0x442f821b35c919b713625e0a7a1564c5d9f8d0a0
0x3620e4ba3927181acb286ff481e275fd29a39530
0xeac3bf0b39a5e3e7ee8bdc92bf3cdb18f82e69ba
The four addresses above are used for signing

Methodology
Analysis according to the query results of the Ethernet browser，Most of the executed transactions are used to trade TRVL, hash:0xb9bd9cb25235b6240a24b5163aa87d765f0416a9315e16222ec91c21700237d8
Tokens with some contract addresses are transferred from the wallet creation, hash: 0x1fa79f947a5d70565351ecc12c50f8f325aae856e904faa94f4c841e46c7a98c
Or transfer from Binance
All of them have nothing to do with the repeater, because 40 wallets that execute transactions and create contract addresses are initiated,0x3620e4BA3927181ACb286Ff481E275FD29A39530 Execute 142 strokes。If it is a repeater, its signature and execution will have nothing to do with the creation of the main wallet, rather than from the main wallet。hash:0x7473339c827c3f2ac889ec076dc604a3a55d912011fe9ef2975bc9f616e4a481
most important point 0xf9d38489b6fd704fd112934322908ee0b6cfbdd4 and 0x3620e4ba3927181acb286ff481e275fd29a39530 Of the nearly 200 transactions initiated, all were transfers TRVL

My Safe Address
0x737CD34E12E8aC795F39a1b6754F9BF53B5295d1

**Comment by tschubotz** [comment]
> Reasoning
> The airdrop hunter used the 0xf9d38489b6fd704fd112934322908ee0b6cfbdd4 mainnet wallet to create 19 multi-signature ，
> 0xf9d38489b6fd704fd112934322908ee0b6cfbdd4
> 0x442f821b35c919b713625e0a7a1564c5d9f8d0a0
> 0x3620e4ba3927181acb286ff481e275fd29a39530
> 0xeac3bf0b39a5e3e7ee8bdc92bf3cdb18f82e69ba
> The four addresses above are used for signing

Owning multiple Safes is not airdrop farming per se but a rather quite common things that projects and individuals do. That reasoning is lacking details on why you think this is in fact airdrop farming and how you can be sure that no leigitmate user is eliminated.
