### ISSUE TITLE
Some wallet addresses with the same behavior track

### ISSUE THREAD

**Issue by hupeqgavec** [safe-global/safe-user-allocation-reports#331]
# Related Safe Addresses
0x4abd863f4278d8ab592861a62fcdb972c3295613
0x7eff07da9a1ffdac0ca2bd37863807cb0cbcddeb
0x54c26b4fcfca7de9810f48e27a67c59f3fe8b720
0xe3dc3296f103035cf7d50d153b36829a2f34ff47
0xb2ad6480bc5839de1ea97cd2cb786bcf881317e0
0x3e1820ca4b5b4d03f85185ac9ce764ace27654a3
0x32ef0fa8f9459d8d1e15fcdd82cd92cd99c8c5d3
0xbf21e3a426c10cad680a030cf9b52a67ff17368a
0x1cd5efa02e555b28fa1e8ac8ca888dd65f37cefc
0x6819bf4698848ac80e6f2f31edb223e8cbeaa4e9
0xb103519fc5395773ebc3aaf700b7118422e0ce12
0x5a2d67f6a1bbef88638e76454f5ac7359a3afe14
0x6406e80be7380e1873603a2685ee94dd02a937eb
0x41ac48762fc1c6cc0f871d277179e5cbe86ab7ca
0x331db66d9a103735b8db890faeb691ef8e9283d0
0x727a69cf2fc7ea7a274b4939d2036d5a3e8994de
0x8c8f4b0d2098f442e33047812f3cde0266fe057a
0x2d7390a22c16c3bb6d0a4b5def23f67b2c4424ed
0xde05ecac194319baf95e6d54952b703db7e1fcb7
0x34b33569be4c5fcfded935b9668cdeebd39e188f
0xeb1abf67940412ff902d6228c093227c601d1ce3
0xab8d87237e06521aaea203c183d6fe8cd675c011
0x69719e87836a819e397cb504a883691061ecc3b8
0xd804b70b3cd22cf744cf1bd08f137faf6b8dcca1
0x84cefb82155271c8f5b69850c542256ed159fb9c
0x12a92325a95ed1ec6459b043df7950ae145475e8
0xffca0f7fd2aa5f4812fdf82e0fd05652bd17f089
0xe09e9558485b569d2b3fc6d450273ec75ddf851a
0x1f07c24e75585597610b05222a7c4246e29d6745
0xe155bdc4d18373ed9a93e39f38d61700c7eec7ef
0x63dfc1a4ecac369837ea77bf6f2948d35bb66300
0x0e5bbbb7d3025c9aeb4d6bde7c6fb481650899b9
0x767f085ad0dfc98995d7e60e4b3832e282c161b9
0x994d7d801aca8b5ff72ba54cfa03870c436c2f64
0x55956676dea07d588d99310d94cbd1bbfdbfcb87
0x0b0424a949ca5fa794652fda213fa0afc836915a
0xea0b24e8d63101c9adcb9106f53bffd88241336c
0x58137b14b26d0ff95fbcc398d525c5ef23c0b340
0x9417dd3d8ac63da92c6755fd8df344bf629902d1
0xe037cc6188a3b642c348e9f061c0adca51f5be85
0x53163d2e01be809a874dc9a2179c5e3eb320bf20
0xde2c488b5071ff7b723f6bbbb80ee123125c1e55
0x1ecf874a3ad8e5fe1320e0563cbc3108485faffa
0xb97b0b91c09ef2e35e601231743c2e0c42326913
0xd06a7f7a971e32b8c807006a48d51fb37f00a28b
0xf295a1911a766b88227dae6a824507b25b7f632a
0x4438a1e0e40ca3e26fdeaeafa1a140a5193549b6
0x5dfe9a38a69f74ba0481d1f66cd86699565b90ce
0xb33d8b86d6584f511930d0d4e7ccb3b2eedbbf7b
0x40d55fab33214afe642f2bbc10c0fd63b86d95e2
0x4aa619f6a729336f4f6ab56ccf97508959cb4660
0x49f55ca4248c44e6e922c736d56f3734862030a4
0xd767d6f6fac02f2bf3652a42ae4c45c9ee5ce671
0xf6fd1bdba4d38d7ff0c5e67ddd75550cf79baf5a
0xc630f55453f5871692ab72dc85f22e7605d9263f
0xaf50909c9f009b8b29ff9fd63c1e48a8f50f7f8a
0xb9a6d6ca19a7b916ff1bc9f3cdf61f6cae8bad36
0xa3ebdd64900ce73413a4a15da3fbb6e6362de01f
0x70c16c78d74a95d4807418c3d5485cb3ad14ef8c
0xbbf065cd0d4385b263676ec9798e70ce5ae763b8
0x9f9eb7d465061fecd7b405d0de0fd591738230a0
0x8cabadcc427df1c09c99116f30e7342d0f523785
0x1d84a2cb6fe85a4e95f3ffe75a440e04870df610
0x9e0ad13467683cf9c522eaa67d41f38ca741c642
0x41334378233faf785cf919a57d0ebf3732f44519
0xcf84393fcd75649d0a674d77a92bbe463062fe56
0x7415edc19b7329a9841adb5cc91e43a845a1f9f7
0x5c13133dafa328d43f4dc5465bb1758c640d979e
0x16c1ec2c74977f60f96feea37e1367b5ec7969b8
0xf4b75dfe149ec871b57760f91ecf170a4659ffb2
0x59c3073b4062be9ce87d775daf8a8957a38e7baa
0x7e8be25329d6117ce84dfd27c7bc8f064c495a87
0x170dc88e017f4b8eb536aadd57825d1928d387e0
0x7ddde7e478ae944342cb3eb087d4ea9aa61cca8a
0xfbf05eae9aa0d0b21add137723c0cd0df90495fa
0xf0b2960386de8a7f1c7b062a5d92a7bbdaad3bca
0x37b494a711c81e466abd2f214e40edf683304f77
0x5c7f44e612bb0f833e8d3545e2966e8966224193
0xd6871bca176871b2e922051ae77f9265b5f43646
0xe963c3ddb8bf455e6c09719b5347761d8333dc95
0x9cc9e5338f1d27ef8b53e3c9e3303aa3e00d1f15
0xab94241ea04630b3cdbcbb52fa801cf9bb4a0abf
0xfc5983f46a4c44a295efc85ace4bef735c32f2d6
0x89a8882e3cf2108487cb72c84f8403f49b523d2b
0xbefcdf0c0baf75b21df86cc3bb5bfb44ac307c78
0x282f90992c66ce68c2a141b90698483506964f8a
0xf7359696914cf1534ec86958970153f76620401c
0x990e3015c17694055f2ad70de411bceb3aacc3e5
0x3ee2e12ccddeb9176c8f246008b07fddbf8e4434
0xab8008327afbfd4b0a9b812701e27af21feacd8e
0x2e9cd991cfc05acf47459ce555c6242d34e3ca78
0x76fbd544c4ebceeaf1baf37f59225c56db8e3b46
0x42b024127c15f0570e0555b8ca28b17112a8de87
0x71dc79586f140b74da38dfd703def4b316200152
0xd2303924f01f62b3bcf28762c29af3fbe1f965bc
0x3ed0c510b8be32dd08ffdf83fda7e9276466625d
0x50cc33ef4b2367dfa629bb6a2a8e13bfd069dd63
0xf68ff829dc50197b6f467bcd4c718233ee3a1512
0xb2313da3992b5c8b5b0b4a2056505b88aaafad2d
0xea739e482a67fffce46c94056db762514b1a460d
0x6041580c9dcd47ae8b0feea7640a4811f2439062
0x6a14fdcff68943189302e55c97cf8ac346fa341d
0x03ccdfe8c26ba668388cbb4acf261cf42918683a
0xcac207b4040176b9f3ea6232c8cba5ed85b05fec
0xcd556faf1bd2a1c0611d80467a540a25220354d9
0xf296d6e978249ccfb9679ad031f6784fe765c44f
0x50776d5310f57fdb87ae13d471e90eb797e0e418
0x0b6f38f04b9f1fd6db60affb514da93e200a82a0
0xce2d5776dd1b049bb9fc62f7235d38716b7454af
0x3ab9ab963ff79401686dfeec8ed5926d4ec7f1a4
0x9b499017ff47e6a6c78ff2a6b5dba446c0414c37
0x886cd62341ad20cda049d842382f206be3c73a00
0x3fb8fac8e32b8437c4dcfd63e7146b53b39101f5
0x00692712b3b80ec3be7fff5927c3e96cf77bbd86
0x6309bf8e66d1ab7f13895835570c4d355cd0a63d
0x59ab82468243477057828f7ad000a87fc0cee985
0x1cc4b10c6e5945b3d2c633550902a37c4d79ec3e
0x7482b6342a69fb0fdcf34330c7c83d20e6e92145
0x6f7e5f91f136eff4178c572090b9c7a97088958c
0x66f3b8d24175b0f31671c4781d0c179dd7c06352
0xae07bf198f75f5c2c47a021ffe8852a04a0f354f
0x2e84374a6d88e6a85bf9cffe30e809c1782cdccd
0x457589a91886f9f9d2b8f0d47fce100be9add545
0xe5c0e49036203f0c58fdcaf247a93401370c6900
0x7795951461b26a389b2292fb154291a4a6887930
0xe712c335926a54eb06761a0408c44cb12d727ee9
0xc0fa7f21e40644802a7cd1cf302003421892e28a
0x5d5397f2328e53225d10958f3f244e43b78b7ee0
0xba2296bc8ca5b2aa2f1535b322e03b8f8dd71bcb
0x675238b1b5ea11fbaa55d33a2ec88ccddc6a9a17
0x7c699010f8f3fa50b66233023dfbe2d9350b495c
0x2ffdfcd7d6acb079227d37484d66b0464787303d
0x20006f0e1429466d2d7870d8cc9cbde8da59cbfb
0x729baa8139fc68262798316c7bbefc992f76fa9c
0x2530351288fad5e378427a6c735a3a15d5138086
0xef0106cca00f1ad4c8d9a2d6e5ac3524c0d794fa
0xb78857dbc372749a57c236da1a7c8718a569ce18
0xab707d8cbbff3ccde1154837728cf7b837021c61
0xe94b0e104fc03ad1cdaf3131fe6a300bd14c0c0b
0xb81e7b24848b4d5e41acbc53a803dbc1a0101ba2
0x59a21cb997d824f98ffd24e61dc5e986e39e9c61
0x600f2fc4ed1097e68dba0d10350836fedad78df2
0x2f63fca72a577e7dc582a0c54db53b041b21712c
0xd1013d06f32b74adea7ad4ad63f502056a1896d2
0x5bd2ebf45c5e2a4762a6790261cde058ce042904
0x6908e48d54127a318508bcb818d1a558b6feed25
0xd2e6fecc5df7c9febbfcf0e788f734702afe59fe
0x83b617d7f56332eba4de341ed8036b84618a3b7b
0x43b064b577c5a90f6a288ec83d8672c141c8d3c7
0xf3a867fca5f960b485eeec116a5ee1670a3d7712
0x4368a58cdc6692381bca00465b08fbaeaa0f0f00
0x028b641e28a35bbad7bbc8736dd45e730ba6e769
0x9827d2635d1af3d058e8faf1b89b2e65f0578620
0x396469e8fd25586aea8bc41bae308ecad50ca7ef
0xab55cce51900bdb672619ce4462004d486079370
0xf5b2d16051b79132c913097653dc8eee1cca9f0a
0x221692218c68573618a82cffbb51f8cf3a8675e9
0xbd72d43b045bbe8ffd6e58a73365c0463a9d4e33
0xdc36c1265322e0ea6e9c1527ad0b774a54ea4316
0xf3ea4f81aa9b84643b34fb21b042a7a808ed8834
0xebab78eb37ec3adec1b722b6bd83e946ef9a5430
0x1d8f045f3963aafb8b08421d0e5a007bd0a5f47b
0xc20f9f64b778223c92cd4b789228beb5bb50074a
0x930d3b346a146d8b7ea487131d8d0190c3683f36
0xa03e6852f64dfd6a305b97314137f75c15267024
0xd436db12d7dd416ec052c511076244f6d0b23830
0xd3906407abcf1f06d02a78eadecb3e11ff8c24e2
0x9d29e9fe1576821a4c8fc3db4d258209b6f9bb19
0x286489df0a7b100b9a089aaf0f724777fa5ed26b
0x15894f78cf8100cd55a4907d1cf474a8dc2ac1db
0xf817924a1dadd01023c23cf693a0a9717942a22e
0xecb4e5c49463145224c9af3ce444178b149957ef
0xd083fe22c60dcd1b240cb9109da47b0b5fd31fa0
0x703df1d8fddde5cdc21215343a26cbdcd43ee21f
0xe6dc92da880c64812188779fbd79e24f239ff599
0xc6e8ed45e84a7ba0f805145158f0d39c1c3d943f
0x9fa4e6c2ce6db1026af72f1d75f384d867dd6776
0x14477b387374385df50cc88de240228042aae7ba
0x907b4c6218db8fbd3b0471d8200ddc7d61e0bae0
0x4d983f76bd9bf60fac9bda13db77a3f079ee0ef0
0x611ff5cac9c8b78ad38a15b903fe25291d682d05
0x4a63773e5a2f428a8cfec078c9e914794bc086b9
0x2bbd427e395fbe55f204b6079bb6f3c4836d8dda
0xd129b70f6b3cefb3cb203493bd4ab2b556678947
0x9e5b24a4e8699d91b9d635681952f94b7a927809
0xbaa5427a95c152921d8117238b97b918c5d92737
0x518741193893edac1eed180e91433e8575efb3d8
0x0139283163eba5dea4fbe9b015391cfe1072cff7
0xdfcb3d191caae0dc035637a9120c6c8423642590
0x862cb714c33da2c5bfe3d169f7349ae9eb2ec55b
0x5103cdbe18fb544115059fea02abfd0a068759cc
0x6b14d1577fbe647e65ad8a10839dbdd7dc8b5740
0x9f471ce70190b05d9826d8fb94b3e764fb17d35b
0x8dd5db529b00d25e67645127afb3db8ff1d2343a
0xbdb1c0afce46c832fb2e71f9328b5c8e2fb15679
0x29aa71a3ef410aa2137cf94a587e099940a76380
0xc68c5004a8f3ecf3fd0b6eb6df32ff53a85cbcfc
0x883ea1601ad760b47ed4d3945a2552c5e870ec9b
0x65a0ff61a9e9cc637cd01a1fa75901db08093c0e
0x423727aa2bd3cc82b286f3e2a4f31abf382c84f2
0xd71df373ee3d6ecf7172c3eab0409626db330bdf
0xf6285f1868bd1ba753d21edcd83bdfe77b24b328
0x84ce5e77a8f1b4185e90f7d757f94fba34927ec9
0xea3679eca389ba44be53a1cd56ac1799a7c0b6a5
0x4d4c8119d1ccb3ff8adba23aa2016bd5257d7ae4
0xcc0778bdf56328af8a9d0ff8cc3801f7283e5c5b
0xcb0b166c211c034d9f6910a5c45996837205219b
0x2ab7ba561a72c6a9a637e80e780db6805c73d4c0
0x4804e8176cd88fdf768038dba6a9b2645f742897
0x0ee05bc255babc685d3b1f9816e30dabd253ea29
0x3cfef485bd51d2afe5c1323f11644897c7b7b243
0xc31fe0fac46bf4f3ee1d85fe1e5d36a02808226c
0x6450b7de563a88795d9114c0d653a4b53dfb345e
0x3e34c0e2edaf066d0b7d942684dff66afcdccabb
0xbeee6059953c7bf13656c637523b358b9c8ce762
0xb62081f10b0e020bc90f2a4b0f798cae9d29bc3c
0x88adc95a3b1cc165eb84e07f604bfca32670c81b
0x1ce7500857e70fa779af51273e863db29cca6121
0x2fb1823910245eec417c36bb3e71e38984383741
0x278f612f7895b93ac6f2dce84a69a7ea708d445e
0x3225d759da17f8c4c3106e86b946639818c8f94c
0x8336f39f23e1281efa416cb103fc95d54d72fb29

# Reasoning
After setup, thousands of Safes are created by one address 0xdf21b894a490cbdf49d9de7b9d780b79f7cb0ac7. All the wallets are involved tx associated with $HEX tokens. For some wallet, the hunter transferred ~0.6 in, using 1inch to swap for $Hex tokens and send it to another address (https://etherscan.io/address/0x8699a98830062434bfb666125c01160e6362f2c9). For other safes, they receive and send $HEX to other safes.
# Methodology
The reported addresses were discovered by checking irregularities in the Safe addresses created by one unique owner. Then I analyzed each address manually, checking the tx patterns. All txs are involved with either swapping, sending or receiving HEX tokens.

# Safe Address
0x7675be26622B0885d96e2969f9681aF0E270E6a6

**Comment by lukasschor** [comment]
Reasoning is not sufficient. Staker App is using a relayer to create Safes, so this would also cover many legitimate users.
