### ISSUE TITLE
118 address farmer

### ISSUE THREAD

**Issue by likewaterg** [safe-global/safe-user-allocation-reports#333]
# Related Safe Addresses

0xA034feEA9A469D72f5ED05BA383E4e28c2BE4282
0x8E87E73AC03958d29664252e2470f1DA9b15a712
0xd0569A0C682dd5Ca22836370a602701ffa2d1a79
0x2127f9D7bC11F1434725183e46DF72477616a866
0x812Bf39418c0A6373DA91914620be4AbB388FAEA
0x469c213E700A8355457a037f8C25866ebd0E4F6c
0x87768FA05dCE4BD82CC9d2Aa81Eb1eb426af1D70
0xcAF542EC04DeA1E6aA8880f80598C99Aa0768e44
0xBA8374b4E8b7D906ADF702A033ca833F46cb0699
0x46AE685E8Cdb19FAa00D6e1dDA38c2aF78188Eb9
0x17dc59dA0ff23f07c89BF80E5b49207CFD89f721
0xcE6Cbf1198Fb3Ce7F7f9BE4C83a69BA2E35800B0
0x5B2C7292AD5A65301D565D43534e15ddA27e845e
0x2147BfcdF20399C545DB480B8bB4B0B6C35b4Ade
0x6E7E0D2B1579fc3288960f6284F31c4Ee24f86ef
0xDE62d919D03E85cAb5222A515B94751bf7dB6159
0x2b718F9Bef23125e743C2636796E6071fb7c81A1
0x1266A93B7a5258Cef199fe975B14716f288838d6
0xd9A7974cF7e8d0457025CEa6c5f74f97cF25a527
0xE10177fbA34e3Ac40f89E2Ac74CC9Ad00b833269
0x08c90a74792ba359aDf8B8599c87729253a30F07
0xd2bc4F2EE81b849E15839d44322F16C546126Cc5
0x0Aa870DC38556003d61cb8b9c45e09c9EC5a245E
0x7eCF09bD8ca887593D47FA715876f275F7cE7227
0x3813a12e16044668067a5429c128EF0633D88176
0x82C0C0b4a383352B82E892a884E82C94D458b024
0xfC7420888Ec2ad43886e2D9b6b0E6965A080Ebed
0xf2d78edcd90f6F52Cc4C421b381c812D9509B182
0xAe65292071bEb351f7Bf467236376747206C0cb8
0xE2aec992e70918106915B261aB290A59e14F6C85
0xDcDc9795E090b1DB09e966bd02AF537201bF6fCC
0x8C4d2c88F8127aEd495Ac93a1D3A84279E070EDa
0xdE5C6AFfC458136dCFC2D1e0c6c1F1fd172D2514
0xD6555e4C8064936E9689eB72C03370f203CC1922
0x793F410D6E27bD2A255bA3598a76cFFeC0Ff0e3F
0xabB81B2b97aD14C6D5c6D788D887256A497AFc5E
0x6c27C1eC042A64e8B39D81EfF33649a1334F7AD3
0x3006Fa35E30742241EB9Ee145ce416997600D85E
0x56Eb3E9974206CF9Fa91754cA8519226efd8b1E8
0xe75d423aEF82e809B47831A877Ddb30c226f3442
0x9ebC3301D31627593a9164DbfCc208077B52D1e4
0xB64faaE285c7453fAF70a7e951C9171e3F2B723a
0x08Da44502A931767D90D66308CAAe1ab5DfF3f08
0xd6273dFB6389325BcF4788051791262F62F7a0fb
0xB33D70ed7B093FdbE1835581dEC22e594d3E5bf0
0x59Bd691a7787638555b904137a1cDbFcaB9dc8e1
0x56589ceE2ca3C816A92F9B5e91bBbEBD809bE55D
0xd5C6120aDE5A8133F59250B84f820bE2dB5B30F5
0x951956984bd338dBA308C77F625983Eb6fC764AD
0xe2c9c32fE8271bfEf0765C2Ed4BA14b0d51CADA2
0xf12Ab45D171DcD406bA8fB640b46B265D1A46106
0xDFfEb421b9A51A38bbBFD988c63540eab20C0E6B
0xf38b2Ad2b4a8095bC582D0b6d702e79cDd601d20
0x189e307d57F7D9DBF94658986CF69A1a24175921
0x1dBb74d64d723b5F02Cf8C8b344a6d108B95aF57
0x3449c0669b9c341f5f35f77210071a9521364953
0x7AeA138F41857659603dF52037DF9d3123F618ca
0x7E00f16a60d86CC82Ea50fF7Cd01Ac2583A93888
0x92924Ef0d8FB13f9b7A05067154b662f6CcD00b0
0x1aaBccAE98e1c34625bebEeE7c980577410CdF61
0xEEf205db9196EBdB5b2c653DF0cA4db401784531
0x77502B6Db9656bE39099F7DC7B86097A3c626DA7
0x864FE78F21cCF839D555Aa567E030d4C1Ac21792
0x73Ddb4E69278Cb7D889bcd176a55037A3963Ac56
0xCA4f5Cf31B890e3A24eC061878980C63C5296c1b
0xC1Bf9CbE6464f93ABE77b5A2CCB67E912045C09d
0x4EACA53da79cc619908d8650473e38e4c63D99e8
0x42C8e7baAccA2e7697eDD89b148BDA7726FE7862
0xC883Db3cf5099584d0E014bBD2574C54D9d356CE
0x3197B70753cdf1940AfbA9B302907549fE3af260
0x1Bd9bB020dF083C5ebB8ab47252ECA0e10003bBF
0xd088Ac7ac48d59895b563D0c6faC46788FCD8272
0x9648bF225F2cCa2E028C3aAE509E835dfbC46c33
0xDd0686b02733DE2452C1aE04837D2f2aF003D5De
0x3B604b43587239dc59744fDc94dD49E00b9bD2d0
0x31D7f361160e26DD38FD0576999E40A473090452
0x62b5A2e429441032E1e76a3f59183a999FE25148
0xd5d51237063E7dAe04B2baBE3719B831f4D591EF
0x4cA1A33fBb6a18B4fb1110c60128134D20dAe828
0x4B08F3B662c01eD58CC19001bc397193d8d59d70
0xA1Ee409696CA9b62485D8D2BD58192DF8feDA675
0x119480965616c38BED1ECd996eA31311041B7213
0xD3E9075990e9D4890683fB678B37Dd68372BD94d
0xbc83E72AcE784ebec052CF28272460E167a9d76D
0x35B44E93B3c8E5E11C445612DA492Cb725Fb37b2
0x71F6C6c3A95812C2A36Db7a2D8fEA7F56DA590f6
0xFFa984905CdB5592163D4eD1f7A8f670aCAd3760
0x3fafB386B1b7A3857085096C0926bdf65bB1e584
0x23142F22eC7688731ba1F87fa541f9722F516fdc
0xdfFe454C592f8f35E504081726f3E562943BF26A
0xA603498744E04E9E97Eba2098409c563Ca9f20A8
0x6c8399D0D562cf2D7320FA827c5934Ffb15cC685
0xA89E3Ee7b73Fc55C316dfcAdE27e279a1168987a
0xD7CcB2eD24c05d5942768F32018de8a458790f81
0xfA77Cf9eBb3b4dB17E945113F8CF6869A2E3A88b
0x6a7de36E5D5e010a7BFa60718516F7B54611890d
0x6a3e9fA682A759b58378bAa209d418723D65a37A
0xF90f48a9b8De82b55F2Be87C02C64E6c3bB31275
0x173Ad4c340001F89009beB45c32458eCaf095C12
0x7b349c057D11111413cF8E132b288AE106a0EbEc
0xf37C3cD0e37A0f4844923A0858b2bcD0eCB13792
0x08ee36D1C1E0f932d64e54e8f774CE79b85C67a5
0xf083a179D5B5295fc9E7E5410Fa4adF6A81B23b7
0x5AB688956951db7dB6Df47418b7c2a6C8ae5Fcbb
0x47656e24A06c65cBf2c7C819cE9d1ACBA6cBD60C
0x09948E8AA34ee0b6C34aC0Be943a56eF51357e04
0xcaba54060c6FFf45B3aDeb4a79F66034967913CB
0x4C3499513EAB75634ec0E1383DC47Ee0169b92dc
0x99f6961E80a993ce72C6A2ffE99C76a96F1767c6
0x4a4C117B7326DC9Bf9E1bADCF4b58236737796e6
0x4cBAb19cE3fC077FE288b957e0445DD59e4d743c
0xdA55247e2009D227Da9ccaEf6A5d1dfE5a0Ce691
0x9A325aC99e5b41756E4b1f3605A90D184e9e5FD3
0x6eFc3122ec4e961580D8e6a2b03aAfa11e6E29e4
0x5B8478cd32235191411D9a0941513D3567b0198b
0xa565dA899944f97D9D56bD273B12B36635FB78D7
0xD490B292B19BAd0085D34ec7ae89F03fb16e7EE8
0x5D3c580673893d592533f008f6e10F6eb81E5B14

# Reasoning

1. All of these 118 safe contracts were created by 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d
2. all of them only have 1 tx.  
3. all of these transactions' from-address is 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d, An EOA, which is controlled by a single entity. 0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d executed all these transactions.
4. creation time of txs range from 2021-06-19 to 2021-06-27.

-->

# Methodology

1.get contract creators of all eligible safe addresses.
2.get addresses with the same owner.
3.get txs of these addresses
4.find out the same tx executor

# Safe Address

0x3F63C80C2f4194CEE024892D12E36597B56f3E6c

**Comment by tschubotz** [comment]
> 2. all of them only have 1 tx.

That's not true for at least the following 2 of your reported addresses:
```
0xd490b292b19bad0085d34ec7ae89f03fb16e7ee8
0x5d3c580673893d592533f008f6e10f6eb81e5b14
```

There is a non zero chance that your list eliminates some legitimate users, hence closing this as invalid.
