### ISSUE TITLE
Airdrop Farmers

### ISSUE THREAD

**Issue by hkermanin** [safe-global/safe-user-allocation-reports#347]
# Related Safe Addresses

To see safe addresses and owner addresses download below excel file:

[main.xlsx](https://github.com/safe-global/safe-user-allocation-reports/files/9541293/main.xlsx)

# Reasoning

In the Excel file above, you can see the owners who have less than two transactions in the Ethereum network, and most of these owners have only one deposit and transaction related to gnosis-safe.
And this can be very suspicious for us.
And what is more interesting is that in most of these wallets, the time of depositing and creating a multi-signature wallet is at the same time. And this case also increases our doubt even more.

The low number of transactions can be a sign that the user is not real.

# Methodology

To prepare this Excel file, help was taken from the https://flipsidecrypto.xyz/.
First, we have found all the gnosis-safe wallets and then through these contracts, we have gained access to their owners.
After identifying the owners, the number of transactions of each owner has been checked, and then the obtained list has been matched with the list of airdrop receivers.

https://app.flipsidecrypto.com/velocity/queries/890d1363-826e-40ca-a384-793042cc5eee

# Safe Address

arb1:0xEFdEC5C455Ea602b1464C0B7e534A2e5A46348F6 
@hkhk0861@gmail.com

**Comment by tschubotz** [comment]
> In the Excel file above, you can see the owners who have less than two transactions in the Ethereum network

At least the following 4 have more txs and look like legitimate use: 

```
0x5c6826bef8a31419fa7eb9b272ed3e79dea806a5
0x2fb62aef2731714a70665ec81172069dfb1f2b1d
0x236320542b85aaf03c6e6cc2fe03716832a95bfe
0x90e3086f181fc55e1c2727225634cfdaf327ecc5
```

Since there's a non-zero chance this would eliminate legit usage, I'm closing this.

**Comment by hkermanin** [comment]
Hello, I have calculated the number of transactions of wallet owners on the Ethereum network, not the number of Safe wallet transactions.

**Comment by d3centra** [comment]
> Hello, I have calculated the number of transactions of wallet owners on the Ethereum network, not the number of Safe wallet transactions.

@hkermanin Hey, I think you've did a great job. But I doubt that they will deem this report valid because there are too many unknowns. And if only 5 out of 100 reported addresses from you are legit users, this is still to much. As mentioned, the chance for including valid users should be as near to zero as humanly possible.

In your own words you said `[...] can be a sign that the user is not real`. This is just not convincing. The goal is to have zero valid, real users be included in any report, but that can't be said about this one here.
