### ISSUE TITLE
https://dscvr.one/post/4158188/__give-5000-paw-__-reply-your-paw-address-__

### ISSUE THREAD

**Issue by Timiwss** [safe-global/safe-user-allocation-reports#354]
# Related Safe Addresses

# Reasoning

# Methodology

# Safe Address

**Comment by tschubotz** [comment]
![image](https://user-images.githubusercontent.com/1380529/191098058-ff3c1730-ab18-46cb-9737-3a20fed4ff88.png)
no info provided
