### ISSUE TITLE
airdrop farmers list !!!

### ISSUE THREAD

**Issue by BountyHunters1** [safe-global/safe-user-allocation-reports#36]
The airdrop hunter used the 0xeD6FD1C824c7269e1f493Fb9aD802F049b67760F mainnet wallet to create 56 multi-signature addresses, and all of them received high token rewards,The query link is https://etherscan.io/address/0xed6fd1c824c7269e1f493fb9ad802f049b67760f?method=Create__Proxy__With__Nonce~0x1688f0b9

Querying an address through the Ethereum browser has created 56 multi-signature addresses, and all of them have transactions. The query link is https://etherscan.io/address/0xed6fd1c824c7269e1f493fb9ad802f049b67760f?method=Create__Proxy__With__Nonce~0x1688f0b9

0x69482418dEd8bA0b2b2F3Fdb93210895497F13E7
0xEF7a277DC145410084ED9A31F7B20437298E8bD4
0xE6F0F92e0a0B672fA7293a89F70BAa6Bcf77d087
0xD6251A28D17b53C4d59EE85FcEEf992ca3420c9E
0xf4f31dAE77842165FEF83abdc902337Dad6169E0
0x8ac00Ae8DB651c46A7e35263Ef0E4350b22ffE68
0xf2b7195805E7c1e66775D811Ebc02D9b83ab54e5
0xDa43394F4C403DF53E95865B1a2659039ECDb2A2
0x06f328725C02888dF24385aaAbc5Fa1FEa619394
0xc56B328027dEfB5fb49780e09370d8a101eC76BD
0xAEa51eca9E454b4372CCb41B39096041A7f67ab8
0x230C32978925741145d5C41af39865F49fD84c27
0x296caFB17f581C3E0A0C6Ac53EE5D11b8312ad56
0xBe0DAe118b8A7eA1E8aad7C116993D20A622430c
0xf826b4d578db80004Cef06014bce6471FC09de53
0x4a864E5ae7DDdE835d39f061Db35479a63b44255
0x3aEcC3eABd0655dd20903a0A7D5434dDb1B9706D
0x6cc56D62e803EaC16fCDC51440aAc291f94301F6
0x6d9E930B3fBB7De79EB4fAcf4c22Ed261935Ae3b
0xFd0DD0be4E59370bf3fee8AB9E81a932C94D5Bd9
0x05a9c1b5769da4FDdCC620963AdC8A3D7f47B984
0x7513c27ed855e0664D5A222d5df2234a5e22a0A0
0x3D5f51D57c9a705722a2B28c356de92E36EcFC91
0xB5b5e056b75c2919f0B95310B08e61309E6859C7
0x586d2Cba9427883244b642e0EA898caA87663fa2
0x7e4458C71bFa1843C654FD55b74A8e84c077fBA5
0x07a8d768644F57312df2cc38FC6c800D0DA5c210
0x5410dDb4446dc311433471290f219a64fcCbA830
0xe3748b93F54a539e13CCAF3a96dBC17219Be8895

Reasoning
The airdrop hunter used the 0x7bdd6529fdfd78b1125aa4d4d152e37b58fe49c0 mainnet wallet to create 56 multi-signature addresses, and all of them received high token rewards,The query link is https://etherscan.io/address/0xed6fd1c824c7269e1f493fb9ad802f049b67760f?method=Create__Proxy__With__Nonce~0x1688f0b9
Methodology
Querying an address through the Ethereum browser has created 56 multi-signature addresses, and all of them have transactions. The query link is https://etherscan.io/address/0xed6fd1c824c7269e1f493fb9ad802f049b67760f?method=Create__Proxy__With__Nonce~0x1688f0b9

My Safe Address
`0x737CD34E12E8aC795F39a1b6754F9BF53B5295d1`

**Comment by BountyHunters1** [comment]
Please reclaim the reward for these addresses

**Comment by tschubotz** [comment]
Please elaborate on why these are safes created for airdrop farming. Just the fact that 1 addresses created all of them doesn't qualify.
If e.g. a wallet uses a relayer to create Safes, the relayer would be the account that created all user Safes which is not airdrop farming per se.

**Comment by BountyHunters1** [comment]
First, this safe was created by the same person, which is very suspicious. Second, the chain transactions of these safes are almost the same. Third, these wallets are rarely used after being created. This is a common method used by airdrop hunters, which is easy to distinguish. Obviously, this is prepared for airdrop. I hope these hateful guys will be punished. Thank you.

**Comment by BountyHunters1** [comment]
Another point is that the address where the safe was created was once marked as an airdrop hunter by hop. So it's easy to distinguish, and I hope they can be punished.

**Comment by tschubotz** [comment]
These Safes have been storing quite sizable amounts of USDT. Store of value is legitimate usage.
