### ISSUE TITLE
about owner 0x204ea9a401bfd0b5e3b0ac81d3c92957f06abaef, 0x68dd071cd24b37e919245ebe1d2faa279121a06b

### ISSUE THREAD

**Issue by skydotone** [safe-global/safe-user-allocation-reports#375]
# Related Safe Addresses
```
0x07a548209a561aa4194d894a7d2ff1f17e8b5407
0xefcd73d806ef1daf5b09814e1a3faee68aa38ec5
0x0c01ecf03c9bbde21d5ae633b4aa724b39a4939a
0x5da052804920156c90691154a1cb920d3c26f382
0x725ec5c1e884d90519165d78aac336d0c30b09b9
0x96e85af1f121dc539afa770de49468b704d391f4
0xc724946ba20ef547a1dbea1158ec79711870af69

0x935c95e9558ea8387126463199ce6bc5fd08dc91
0xe17868f1da82aae105545a95d27161130feaf48d
0xccb86121542fcb08ead9e86ff7a7d8c0018e6c7f
```

# Reasoning

> There is an abnormal behavior that is understandable 🍄

> However, if there are many abnormal behaviors, then there is enough reason to determine that these addresses are airdrop farmer.

1. Both of the two group , the owner is `0x204ea9a401bfd0b5e3b0ac81d3c92957f06abaef` and `0x68dd071cd24b37e919245ebe1d2faa279121a06b`, else is empty wallet
    - Group1
        - `0x204ea9a401bfd0b5e3b0ac81d3c92957f06abaef` -- send 47 transactions -- wallet1
        - `0x68dd071cd24b37e919245ebe1d2faa279121a06b` -- send 14 transactions -- wallet2
        - `0xa8741f6668cd2a193a1b42f1767980c3b40f2c5b` -- send 0 transactions
        - `0xc7f9c0be88060a176bf674a6bb1e1271f7c9e37a` -- send 0 transactions
    - Group2
        - `0x204ea9a401bfd0b5e3b0ac81d3c92957f06abaef` -- send 47 transactions -- wallet1
        - `0x68dd071cd24b37e919245ebe1d2faa279121a06b` -- send 14 transactions -- wallet2
        - `0xa287ae074194c8296a1959ce49180676284b2a29` -- send 0 transactions
        - `0xa8741f6668cd2a193a1b42f1767980c3b40f2c5b` -- send 0 transactions
        - `0xac0dee2d8bc683b0b709b74b2cc9d5cda91481b2` -- send 0 transactions
        - `0xc7f9c0be88060a176bf674a6bb1e1271f7c9e37a` -- send 0 transactions
        - `0xce10a131e1ccd1159fa443cca0ee8bc87a33c11b` -- send 0 transactions
        - `0xd5475c6c7041e1bf0c2c7e58da5c3860aa390d56` -- send 0 transactions

    - analysis `0x204ea9a401bfd0b5e3b0ac81d3c92957f06abaef` and `0x68dd071cd24b37e919245ebe1d2faa279121a06b`:
        - `0x68dd071cd24b37e919245ebe1d2faa279121a06b` Last money transfer to wallet1 https://etherscan.io/tx/0xb2d349557e4bfc1d2c1098f9b3ada3daa8797427273ce90e522c0e0105df77c3
        - wallet1 first money came from `0x668b2e2f9fd9679e6f613f538872a91cf2c7cd6b` https://etherscan.io/tx/0x1a413259aa315a86137cc8e402d3df01d8d52e8f9c4b72368c2502e67014f7be
        - wallet2 usually send money to `0x668b2e2f9fd9679e6f613f538872a91cf2c7cd6b` https://etherscan.io/tx/0x283bdf51408380ead7998cdae642fc9cb0a34fdadab7a816a8d47332fd8bff0b
        - There are lots of transacitons between walelt1 and twallet2

2. All of the multi-sign address, the behaviour is always same.

- Especially Group 1, addOwner once, removeOwner once , and addOwnerAddress 100% is `0x204Ea9A401bfD0b5e3B0Ac81d3c92957F06ABAEF`, removeOwnerAddress 100% is `0x668b2E2F9FD9679e6F613f538872a91Cf2c7cD6B` 
- group2 had execute multi times addOwner,and multi times removeOwner, But the address is same, add `0xCe10A131e1ccD1159fA443CCa0EE8BC87A33C11B` and remove `0x46039ce43b151a7b7EAC680EcAd5b037a294e3aF`

- Please Check Table 
    - address -- multi-sign address
    - execute transactions -- The number of execute transactions by multi-sign address
    - AddOwnerTimes -- The number of add owner
    - AddOwnerAddress -- The Address of add owner
    - AddOwnerTx -- The tx of add owner
    - RemoveOwnerTimes -- The number of remove owner
    - RemovedOwnerAddress -- The Address of remove owner
    - RemovedTx -- The tx of remove owner

| Address | Execute Tranascitons | AddOwnerTimes | AddOwnerAddress | AddOwnerTx | RemoveOwnerTimes | RemovedOwnerAddress | RemovedTx |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0x07a548209a561aa4194d894a7d2ff1f17e8b5407 (group1) | 4 | 1 | 0x204Ea9A401bfD0b5e3B0Ac81d3c92957F06ABAEF | https://etherscan.io/tx/0xb0fd45b5ad075599e238874765c7e4f926c913a7d4416db62589b8392bf8d0fb | 1 | 0x668b2E2F9FD9679e6F613f538872a91Cf2c7cD6B | https://etherscan.io/tx/0xcc441a6a6068cb1eff33d6cb30a9946056cd238cd623413b20e857e5af535663 | 
| 0xefcd73d806ef1daf5b09814e1a3faee68aa38ec5 (group1) | 3 | 1 | 0x204Ea9A401bfD0b5e3B0Ac81d3c92957F06ABAEF | https://etherscan.io/tx/0x7e857412ef6c5843a72356a4a374aadfefdb94d366855a8631c005396bc2d90a | 1 | 0x668b2E2F9FD9679e6F613f538872a91Cf2c7cD6B | https://etherscan.io/tx/0x4ba180584eac0f3f79e5de134302564349b5d53eed7608247fb982614253da4a | 
| 0x0c01ecf03c9bbde21d5ae633b4aa724b39a4939a (group1) | 3 | 1 | 0x204Ea9A401bfD0b5e3B0Ac81d3c92957F06ABAEF | https://etherscan.io/tx/0xe1ccb129df28623b7b492c7a39e739269fbc96230a7d1c0a4e7fc7ae0e59a62c | 1 | 0x668b2E2F9FD9679e6F613f538872a91Cf2c7cD6B | https://etherscan.io/tx/0x5b197fe20f0143723dfe7a58bf675c89ba7f89e8f0be17c0af09b90a364e49d9 | 
| 0x5da052804920156c90691154a1cb920d3c26f382 (group1) | 3 | 1 | 0x204Ea9A401bfD0b5e3B0Ac81d3c92957F06ABAEF | https://etherscan.io/tx/0x37b44abbd3f57982f1822732031939819cdd7ecd248f31a4e00a6026c022902f | 1 | 0x668b2E2F9FD9679e6F613f538872a91Cf2c7cD6B | https://etherscan.io/tx/0x2b0c80e5f96d9d0d101305ff89473da7b6fead6d78bffaf37b8ec4cf2489092d | 
| 0x725ec5c1e884d90519165d78aac336d0c30b09b9 (group1) | 3 | 1 | 0x204Ea9A401bfD0b5e3B0Ac81d3c92957F06ABAEF | https://etherscan.io/tx/0xdf7746ca771816df60e9b971c70c04f0322d75d21fe29c415bcb3cefab9ff26f | 1 | 0x668b2E2F9FD9679e6F613f538872a91Cf2c7cD6B | https://etherscan.io/tx/0xde27c0e4b3a252dde7893c4156e8a776311a725970e4a4b65900e9af7e3b2500 | 
| 0x96e85af1f121dc539afa770de49468b704d391f4 (group1) | 3 | 1 | 0x204Ea9A401bfD0b5e3B0Ac81d3c92957F06ABAEF | https://etherscan.io/tx/0x69574476f84fd3842f8ad1d92b69bce1a01af83171b05be94d145786a95d9657 | 1 | 0x668b2E2F9FD9679e6F613f538872a91Cf2c7cD6B | https://etherscan.io/tx/0x07b3ac335a5b9fd328903c9566aec074057775d6c4fe7520c0ac50b7bf042d4a | 
| 0xc724946ba20ef547a1dbea1158ec79711870af69 (group1) | 3 | 1 | 0x204Ea9A401bfD0b5e3B0Ac81d3c92957F06ABAEF | https://etherscan.io/tx/0x7fe784cb5167a33cb62b7aa3134f501ef5a89406e735d27ac1dc51126d0f80fd | 1 | 0x668b2E2F9FD9679e6F613f538872a91Cf2c7cD6B | https://etherscan.io/tx/0xf28aec01576c9ec10039c0c4cd1419f91ae9d30fbe6965c8e9a9fe562f5a5034 |
| 0x935c95e9558ea8387126463199ce6bc5fd08dc91 (group2) | 9 | 5 | 0xCe10A131e1ccD1159fA443CCa0EE8BC87A33C11B | https://etherscan.io/tx/0x1906397c6bbf942b509c6c5813f89b4f675fdfa3fb6a4adc25685e93bdcded85 | 1 | 0x46039ce43b151a7b7EAC680EcAd5b037a294e3aF | https://etherscan.io/tx/0xb294ddb0ae3c70096d51d214ade1b87f82c1f7edf28118ea993f8297d1970f09 | 
| 0xe17868f1da82aae105545a95d27161130feaf48d (group2) | 9 | 5 | 0xCe10A131e1ccD1159fA443CCa0EE8BC87A33C11B | https://etherscan.io/tx/0xdf12a77db524e5be1ac0c9a4e56fd9ca6e0acbafe356d8c70c07c9e0355b3b3a | 1 | 0x46039ce43b151a7b7EAC680EcAd5b037a294e3aF | https://etherscan.io/tx/0x3c4a309e4d1adf7953cb667a862db5b3a40cc7b6c4b54f1f78f11465404ab59a | 
| 0xccb86121542fcb08ead9e86ff7a7d8c0018e6c7f (group2) | 15 | 6 | 0xCe10A131e1ccD1159fA443CCa0EE8BC87A33C11B | https://etherscan.io/tx/0x193d02b172ac3021c7bd42bc06eb4050c7f88e5971dfa08a4b3e00f988e631b0 | 2 | 0x46039ce43b151a7b7EAC680EcAd5b037a294e3aF | https://etherscan.io/tx/0x0f4442b8b968e6b793b50025742c243814fcf5b123a7262ea9e69ebb0fea834b |

---
# Methodology

Addresses are reported by retrieving information from the chain, using bitquery's graphql, and detecting abnormal behavior, such as empty wallets, mutual transfers, etc.

When only some of the anomalous behaviors are present, we can consider the address reasonable, but when an address has all the anomalous behaviors, we have good reason to suspect that the address is false. **Especially if the multi-signature address and the owner address have obvious exceptions both, then it is obvious that this is airdrop farmer**.

Abnormal behaviors include 

- For Multi-Sign Address
    - Few transactions were executed
    - There is a lot of overlap in the interactions, such as the destination address, and the time
    - The owner of multiple multi-signature addresses is exactly the same, and never changes from start to finish

- For Owner Address
    - Empty address
    - The first source of funds is the owner.
    - Mutual transfer
    - Behavior similarity

**If the verification is passed and  my strategy is great,  I can provide my source code, but for now it is not conveninet**

# Safe Address

`0xce495858e36c95f491b5a32ca2664405cf10ab76`

Thanks

**Comment by tschubotz** [comment]
These Safes stored significant amounts of USDT. Store of value is legitimate use.
