### ISSUE TITLE
owenr 0x9d9ac81a6dc308f305b2873d5cc89619bc37080f, remove and add is same

### ISSUE THREAD

**Issue by skydotone** [safe-global/safe-user-allocation-reports#385]
# Related Safe Addresses
```

0x1cad3fce04bde3331673a08ac548a91f2150306d
0xfd19c73ce941b9a1d0a76b01a71923e90610d933
0x2f072cd437be94643ebcecb9ece75fe57133a7ed
0x3aa0c85c761f571e7b7be32ccb991b47302b276d
0x4b5746ac60b2a2b0c8ec27811b64f6b41f94bb0c
0x4f57e7c4d064ccd90dee170af26c393ac3b58e02
0x562275c26d10b6cf74813abb1f915f4ca13c20a4
0x5e88de4dcfbe0d697c2a01ab9a4a9cbba413d612
0xab17db84c397a88a11996d3f5b623c60fc74f77e
0xb94df7d769b285bf440bfdd6b15c51d2d2afee2c
0xbc1d55b9360e8cd0a00cde02ccd5d56847acbfa6
0xc04a53d0b70e1976880e128a82a5d9ad0da93bad
0xc1eef48153cfae993d7477eaac7344905c5d22e8
0xd1cd56f9c36cdc9c5bbf3631af81f631159f2129
0xe28ec8ecedbb2dce9eb8e0dd603a92b8448c076d
0xea93c06ef0d7720debe21abb2c7625a4981b465d
0xf9b43d7c510c810e5722f459d32b1518c53b9c56
```

# Reasoning

> There is an abnormal behavior that is understandable 🍄

> However, if there are many abnormal behaviors, then there is enough reason to determine that these addresses are airdrop farmer.

1. All of them the owner is same `0x9d9ac81a6dc308f305b2873d5cc89619bc37080f`

2. All of the multi-sign address, the behaviour is always same and stange .

    - All their addOnwer and removeOwner transaction took place `from 2021-02-15` to `2021-02-28`. (99% happend in `2021-02-27` -- `2021-02-28`)

    - All of them execute 1 transactions, add owner and remove owner in 1 tx, always same.

    - Add owner address is always `0x9d9ac81a6dc308f305b2873d5cc89619bc37080f` , remove owner address is always `0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D`

    - Please Check Table 
        - Address -- multi-sign address
        - Execute transactions -- The number of execute transactions by multi-sign address
        - AddOwnerTxAmount -- The number of add owner
        - AddOwnerAddress -- The Address of add owner
        - AddOwnerTx -- The tx of add owner
        - AddOwnerDate -- The date of add owner
        - RemoveOwnerTxAmount -- The number of remove owner
        - RemoveOwnerAddress -- The Address of remove owner
        - RemoveOwerTx -- The tx of remove owner
        - RemoveOwerDate -- The date of remove owner

| Address | Execute transactions | AddOwnerTxAmount | AddOwnerAddress | AddOwnerTx | AddOwnerDate | RemoveOwnerTxAmount | RemoveOwnerAddress | RemoveOwerTx | RemoveOwerDate |
|---|---|---|---|---|---|---|---|---|---|
 | 0x1cad3fce04bde3331673a08ac548a91f2150306d | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x4d6599418dfa5a82ccafd55e96c8f61b4fcad80374f9df034aa84c01a9333cd8 | 2021/02/27T01:47:47.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x4d6599418dfa5a82ccafd55e96c8f61b4fcad80374f9df034aa84c01a9333cd8 | 2021/02/27T01:47:47.000Z |
 | 0xfd19c73ce941b9a1d0a76b01a71923e90610d933 | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x64cd21dc24c4ad2f097231701f769c1ac0255c740f0bb67c9c3e6b6582fba282 | 2021/02/28T23:47:53.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x64cd21dc24c4ad2f097231701f769c1ac0255c740f0bb67c9c3e6b6582fba282 | 2021/02/28T23:47:53.000Z |
 | 0x2f072cd437be94643ebcecb9ece75fe57133a7ed | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x8c382072345ca2335c236e4c50c78bb3b4e073ab2096682f17d30317e089c79a | 2021/02/15T05:54:44.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x8c382072345ca2335c236e4c50c78bb3b4e073ab2096682f17d30317e089c79a | 2021/02/15T05:54:44.000Z |
 | 0x3aa0c85c761f571e7b7be32ccb991b47302b276d | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x3ad24f1365fa055ea06e80f41d7edd47deac21a2f418781018d7fd712302a302 | 2021/02/27T04:48:36.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x3ad24f1365fa055ea06e80f41d7edd47deac21a2f418781018d7fd712302a302 | 2021/02/27T04:48:36.000Z |
 | 0x4b5746ac60b2a2b0c8ec27811b64f6b41f94bb0c | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x014b82b6fb485cc908854c6f4c4d78f787a262e69f1c479b56d4554cceb0f962 | 2021/02/28T01:58:10.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x014b82b6fb485cc908854c6f4c4d78f787a262e69f1c479b56d4554cceb0f962 | 2021/02/28T01:58:10.000Z |
 | 0x4f57e7c4d064ccd90dee170af26c393ac3b58e02 | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0xa78c2689ace1fd079e09bc3fad70cb60443b432119fc63bc87b37d64ead20146 | 2021/02/28T23:23:58.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xa78c2689ace1fd079e09bc3fad70cb60443b432119fc63bc87b37d64ead20146 | 2021/02/28T23:23:58.000Z |
 | 0x562275c26d10b6cf74813abb1f915f4ca13c20a4 | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x614deebf947387487d50a43a7d56ece5e8432e53e4ab5ce58f32fc296383209b | 2021/02/28T02:46:17.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x614deebf947387487d50a43a7d56ece5e8432e53e4ab5ce58f32fc296383209b | 2021/02/28T02:46:17.000Z |
 | 0x5e88de4dcfbe0d697c2a01ab9a4a9cbba413d612 | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0xd8d85235fc022c57f60b8f5d4d363769f9d1c86b8f94328451c0a14c09dad2e8 | 2021/02/27T05:54:41.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xd8d85235fc022c57f60b8f5d4d363769f9d1c86b8f94328451c0a14c09dad2e8 | 2021/02/27T05:54:41.000Z |
 | 0xab17db84c397a88a11996d3f5b623c60fc74f77e | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x762457364361d6741fb3b6304cec20016481cd0860618e7f488b26ee7b7204f7 | 2021/02/28T22:15:15.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x762457364361d6741fb3b6304cec20016481cd0860618e7f488b26ee7b7204f7 | 2021/02/28T22:15:15.000Z |
 | 0xb94df7d769b285bf440bfdd6b15c51d2d2afee2c | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0xd11e6eee931ab347d7fb5aa1f2b64d9470387ce378b202f46e9d947ab7583be2 | 2021/02/28T23:53:07.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xd11e6eee931ab347d7fb5aa1f2b64d9470387ce378b202f46e9d947ab7583be2 | 2021/02/28T23:53:07.000Z |
 | 0xbc1d55b9360e8cd0a00cde02ccd5d56847acbfa6 | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x8e072836dbbab139b0ad62914c882039c7312b8767409d059804b78e21aa3aba | 2021/02/15T07:18:23.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x8e072836dbbab139b0ad62914c882039c7312b8767409d059804b78e21aa3aba | 2021/02/15T07:18:23.000Z |
 | 0xc04a53d0b70e1976880e128a82a5d9ad0da93bad | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0xa38f17b53452477aa672bbde5e1345deef2aa871fdfa418571724e233a48b344 | 2021/02/28T23:37:21.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xa38f17b53452477aa672bbde5e1345deef2aa871fdfa418571724e233a48b344 | 2021/02/28T23:37:21.000Z |
 | 0xc1eef48153cfae993d7477eaac7344905c5d22e8 | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x60104a63403b4e30f105d6f8feb0a1e06705fe858d76a9e8905d36b62be9223a | 2021/02/27T06:00:42.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x60104a63403b4e30f105d6f8feb0a1e06705fe858d76a9e8905d36b62be9223a | 2021/02/27T06:00:42.000Z |
 | 0xd1cd56f9c36cdc9c5bbf3631af81f631159f2129 | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0xa0c8287ce2484470777b7c3678192500bd932f7147796b5933c0aaa5e6ace4a0 | 2021/02/28T02:09:48.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xa0c8287ce2484470777b7c3678192500bd932f7147796b5933c0aaa5e6ace4a0 | 2021/02/28T02:09:48.000Z |
 | 0xe28ec8ecedbb2dce9eb8e0dd603a92b8448c076d | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x17578a5a625cafb44a0478a7f8cb520b2f044950b713f43c64242aaca477c132 | 2021/02/28T01:49:53.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x17578a5a625cafb44a0478a7f8cb520b2f044950b713f43c64242aaca477c132 | 2021/02/28T01:49:53.000Z |
 | 0xea93c06ef0d7720debe21abb2c7625a4981b465d | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0x3b5eadb77b4239f4022590aa7b3e436db661b3b309302ce7dcf4ea7334b11612 | 2021/02/27T06:10:51.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x3b5eadb77b4239f4022590aa7b3e436db661b3b309302ce7dcf4ea7334b11612 | 2021/02/27T06:10:51.000Z |
 | 0xf9b43d7c510c810e5722f459d32b1518c53b9c56 | 1 | 1 | 0x9D9AC81a6dC308f305b2873d5cc89619Bc37080f | https://etherscan.io/tx/0xdc473276432bca69b72cd04bcfcd21f1aa74b1001c4181604374f16ff4d6a548 | 2021/02/27T02:12:57.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xdc473276432bca69b72cd04bcfcd21f1aa74b1001c4181604374f16ff4d6a548 | 2021/02/27T02:12:57.000Z |

---
# Methodology

Addresses are reported by retrieving information from the chain, using bitquery's graphql, and detecting abnormal behavior, such as empty wallets, mutual transfers, etc.

When only some of the anomalous behaviors are present, we can consider the address reasonable, but when an address has all the anomalous behaviors, we have good reason to suspect that the address is false. **Especially if the multi-signature address and the owner address have obvious exceptions both, then it is obvious that this is airdrop farmer**.

Abnormal behaviors include 

- For Multi-Sign Address
    - Few transactions were executed
    - There is a lot of overlap in the interactions, such as the destination address, and the time
    - The owner of multiple multi-signature addresses is exactly the same, and never changes from start to finish

- For Owner Address
    - Empty address
    - The first source of funds is the owner.
    - Mutual transfer
    - Behavior similarity

**If the verification is passed and  my strategy is great,  I can provide my source code, but for now it is not conveninet**

# Safe Address

`0xce495858e36c95f491b5a32ca2664405cf10ab76`

Thanks

**Comment by PulsarNetwork** [comment]
It's someone creating multiple Staker App smart contract wallet with the same owner private key. Already included in https://github.com/safe-global/safe-user-allocation-reports/issues/365

**Comment by skydotone** [comment]
> 

no, man, just create is not airdrop farmer

**Comment by tschubotz** [comment]
Thanks for the report. All of these Safes have been found by a previous report, unfortunately.
