### ISSUE TITLE
owner 0x907a04ad5ac49acde9e197ae1f1c66b94250fcc6, add and remove is same

### ISSUE THREAD

**Issue by skydotone** [safe-global/safe-user-allocation-reports#386]
# Related Safe Addresses
```
0x12f6ea48da5edd60ec6077c7657109c92e908625
0xeef205db9196ebdb5b2c653df0ca4db401784531
0x1aabccae98e1c34625bebeee7c980577410cdf61
0x2a509d75f0d06b84578f230faa953f6062262ce9
0x3197b70753cdf1940afba9b302907549fe3af260
0x3fafb386b1b7a3857085096c0926bdf65bb1e584
0x42c8e7baacca2e7697edd89b148bda7726fe7862
0x4ce426850f2fd04f44dd16ced2e9851c2abc4b12
0x62b5a2e429441032e1e76a3f59183a999fe25148
0x6a7de36e5d5e010a7bfa60718516f7b54611890d
0x6ff5ee43ee9d7878acb1d22818921a21d82c8bb5
0x71d1e3e46336328e0b01c7514377f0795f504aa0
0x77502b6db9656be39099f7dc7b86097a3c626da7
0x864fe78f21ccf839d555aa567e030d4c1ac21792
0xae331114cf1e9679632e5cb25c69310e7b63f0f9
0xb5cbfacb1e628e48ec54940c29e0c08e97fd4200
0xb62d7df9e8e0b0495a328a6397d2d083ddbbaac9
0xc36c385e454e5bb86cdbdd2bf805c4c82459788c
0xca4f5cf31b890e3a24ec061878980c63c5296c1b
0xd284b2bdfe1a7636f5d540ed46f7bbdf5c82b3d4
0xe8e5e5db490e2bf4407017588b1927432e4a677b
```

# Reasoning

> There is an abnormal behavior that is understandable 🍄

> However, if there are many abnormal behaviors, then there is enough reason to determine that these addresses are airdrop farmer.

1. All of them the owner is same `0x907a04ad5ac49acde9e197ae1f1c66b94250fcc6`, only this address

2. All of the multi-sign address, the behaviour is always same and stange .

    - All their addOnwer and removeOwner transaction took place from `2021-05-27` to `2021-06-23`. (50% happend in `2021/06/23` one day)

    - All of them execute 1 transactions, add owner and remove owner in 1 tx, always the same tx.

    - Add owner address is always `0x907a04ad5ac49acde9e197ae1f1c66b94250fcc6` , remove owner address is always `0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D`

    - Please Check Table 
        - Address -- multi-sign address
        - Execute transactions -- The number of execute transactions by multi-sign address
        - AddOwnerTxAmount -- The number of add owner
        - AddOwnerAddress -- The Address of add owner
        - AddOwnerTx -- The tx of add owner
        - AddOwnerDate -- The date of add owner
        - RemoveOwnerTxAmount -- The number of remove owner
        - RemoveOwnerAddress -- The Address of remove owner
        - RemoveOwerTx -- The tx of remove owner
        - RemoveOwerDate -- The date of remove owner

| Address | Execute transactions | AddOwnerTxAmount | AddOwnerAddress | AddOwnerTx | AddOwnerDate | RemoveOwnerTxAmount | RemoveOwnerAddress | RemoveOwerTx | RemoveOwerDate |
|---|---|---|---|---|---|---|---|---|---|
 | 0x12f6ea48da5edd60ec6077c7657109c92e908625 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0xf5235cf11c8518bbcba3568a4228e0f5a4d095d214bbcac2b833080955d4eb99 | 2021/06/02T22:11:59.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xf5235cf11c8518bbcba3568a4228e0f5a4d095d214bbcac2b833080955d4eb99 | 2021/06/02T22:11:59.000Z |
 | 0xeef205db9196ebdb5b2c653df0ca4db401784531 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x91c2a9d70a780d30beaf0655f48f4a9a08880d73f4b70ba94e179d8dd082c046 | 2021/06/23T01:52:01.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x91c2a9d70a780d30beaf0655f48f4a9a08880d73f4b70ba94e179d8dd082c046 | 2021/06/23T01:52:01.000Z |
 | 0x1aabccae98e1c34625bebeee7c980577410cdf61 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x7e21f98c55804dbdf723fa901f79384f79427f49a1d5fd0abc223100a38e0c84 | 2021/06/23T02:41:36.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x7e21f98c55804dbdf723fa901f79384f79427f49a1d5fd0abc223100a38e0c84 | 2021/06/23T02:41:36.000Z |
 | 0x2a509d75f0d06b84578f230faa953f6062262ce9 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x1e21b2abf80ead56998b9cc369075b1f04d355976b04a424d41538feb0233641 | 2021/06/01T16:33:31.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x1e21b2abf80ead56998b9cc369075b1f04d355976b04a424d41538feb0233641 | 2021/06/01T16:33:31.000Z |
 | 0x3197b70753cdf1940afba9b302907549fe3af260 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x62cc210be74c54dba3fa5e8cc7bc118d991d8ffb8eb306c4baf5f85e1dc7d0a4 | 2021/06/23T01:47:57.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x62cc210be74c54dba3fa5e8cc7bc118d991d8ffb8eb306c4baf5f85e1dc7d0a4 | 2021/06/23T01:47:57.000Z |
 | 0x3fafb386b1b7a3857085096c0926bdf65bb1e584 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0xf75cac88d5af99a0f0ebde6fb4b661c4a4282d16fda69e0c4d418589dbd157fd | 2021/06/23T03:12:18.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xf75cac88d5af99a0f0ebde6fb4b661c4a4282d16fda69e0c4d418589dbd157fd | 2021/06/23T03:12:18.000Z |
 | 0x42c8e7baacca2e7697edd89b148bda7726fe7862 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x185a6f0d5f48a3a8dec4102caa98f9f71f1205ad1cae805011bc6b5a332ef861 | 2021/06/23T03:22:55.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x185a6f0d5f48a3a8dec4102caa98f9f71f1205ad1cae805011bc6b5a332ef861 | 2021/06/23T03:22:55.000Z |
 | 0x4ce426850f2fd04f44dd16ced2e9851c2abc4b12 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x61e016141c5ef4d39212056c46a23c5a6ea279c62c3a8c82c8a4494498f81f22 | 2021/06/08T21:46:53.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x61e016141c5ef4d39212056c46a23c5a6ea279c62c3a8c82c8a4494498f81f22 | 2021/06/08T21:46:53.000Z |
 | 0x62b5a2e429441032e1e76a3f59183a999fe25148 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x642575c00e12adfd3eb85ba339aa036e3a53ee5150453236a140bfa32c315ada | 2021/06/23T02:13:03.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x642575c00e12adfd3eb85ba339aa036e3a53ee5150453236a140bfa32c315ada | 2021/06/23T02:13:03.000Z |
 | 0x6a7de36e5d5e010a7bfa60718516f7b54611890d | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x52a0aeae9289ae4fe44824b0d694da2a10f4be9768f7135d9f470b5aeab369c3 | 2021/06/23T02:48:15.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x52a0aeae9289ae4fe44824b0d694da2a10f4be9768f7135d9f470b5aeab369c3 | 2021/06/23T02:48:15.000Z |
 | 0x6ff5ee43ee9d7878acb1d22818921a21d82c8bb5 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0xd641d3cfdb00baf65bd55dc4dcd6a78f2db20b6559a0dc4d493ac7c8faef4758 | 2021/06/08T17:58:26.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xd641d3cfdb00baf65bd55dc4dcd6a78f2db20b6559a0dc4d493ac7c8faef4758 | 2021/06/08T17:58:26.000Z |
 | 0x71d1e3e46336328e0b01c7514377f0795f504aa0 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0xa41f4076ab5f10bdf8037c9febf35a8ebca32e429b9a7ec78376341876a90774 | 2021/06/23T01:54:18.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xa41f4076ab5f10bdf8037c9febf35a8ebca32e429b9a7ec78376341876a90774 | 2021/06/23T01:54:18.000Z |
 | 0x77502b6db9656be39099f7dc7b86097a3c626da7 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0xa7ccbc4b85a37dc819eedbe1f4ae24034036f52ed07618385fb11710ff21a301 | 2021/06/23T02:59:45.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xa7ccbc4b85a37dc819eedbe1f4ae24034036f52ed07618385fb11710ff21a301 | 2021/06/23T02:59:45.000Z |
 | 0x864fe78f21ccf839d555aa567e030d4c1ac21792 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x96a37e72803dbe255f83b70e62d7b296c42bf4f43e866f457ab3a59250d7cc98 | 2021/06/23T03:40:51.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x96a37e72803dbe255f83b70e62d7b296c42bf4f43e866f457ab3a59250d7cc98 | 2021/06/23T03:40:51.000Z |
 | 0xae331114cf1e9679632e5cb25c69310e7b63f0f9 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0xf788e7947644d7b23fa3067dc37ee4b81001bdfcdf4447b14f30588df151410b | 2021/06/08T20:33:57.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xf788e7947644d7b23fa3067dc37ee4b81001bdfcdf4447b14f30588df151410b | 2021/06/08T20:33:57.000Z |
 | 0xb5cbfacb1e628e48ec54940c29e0c08e97fd4200 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x4aece49342cb58c388f557ebd80355e323c1f0b8edf8035569919eb6718f9ada | 2021/06/08T20:24:35.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x4aece49342cb58c388f557ebd80355e323c1f0b8edf8035569919eb6718f9ada | 2021/06/08T20:24:35.000Z |
 | 0xb62d7df9e8e0b0495a328a6397d2d083ddbbaac9 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x0397dbb01f011533f87f0eaa6b376077c0c92265ed3fcaba9c993ccae8979d04 | 2021/06/01T16:44:59.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x0397dbb01f011533f87f0eaa6b376077c0c92265ed3fcaba9c993ccae8979d04 | 2021/06/01T16:44:59.000Z |
 | 0xc36c385e454e5bb86cdbdd2bf805c4c82459788c | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x05c0cc0872d242924abc3f94fc600ccc5446149c7d68aefb49a1e98b4c7d1eee | 2021/06/08T18:33:44.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x05c0cc0872d242924abc3f94fc600ccc5446149c7d68aefb49a1e98b4c7d1eee | 2021/06/08T18:33:44.000Z |
 | 0xca4f5cf31b890e3a24ec061878980c63c5296c1b | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x54270711abf6592897a592ec4b3d51b8f5259e8f629e8dfff9c2bc0ae779aa17 | 2021/06/23T02:44:04.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x54270711abf6592897a592ec4b3d51b8f5259e8f629e8dfff9c2bc0ae779aa17 | 2021/06/23T02:44:04.000Z |
 | 0xd284b2bdfe1a7636f5d540ed46f7bbdf5c82b3d4 | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0xcd4318efc75f472cd0700cc964c723387f263fa8b29d979f8423e48f4430925a | 2021/06/08T04:06:35.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xcd4318efc75f472cd0700cc964c723387f263fa8b29d979f8423e48f4430925a | 2021/06/08T04:06:35.000Z |
 | 0xe8e5e5db490e2bf4407017588b1927432e4a677b | 1 | 1 | 0x907a04ad5aC49acDE9E197ae1f1C66b94250fcC6 | https://etherscan.io/tx/0x98a3f444c9f6faa1ca44979ec30f3de86ed8d77150edecf10aa927b2926cc089 | 2021/05/27T17:00:14.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x98a3f444c9f6faa1ca44979ec30f3de86ed8d77150edecf10aa927b2926cc089 | 2021/05/27T17:00:14.000Z |

---
# Methodology

Addresses are reported by retrieving information from the chain, using bitquery's graphql, and detecting abnormal behavior, such as empty wallets, mutual transfers, etc.

When only some of the anomalous behaviors are present, we can consider the address reasonable, but when an address has all the anomalous behaviors, we have good reason to suspect that the address is false. **Especially if the multi-signature address and the owner address have obvious exceptions both, then it is obvious that this is airdrop farmer**.

Abnormal behaviors include 

- For Multi-Sign Address
    - Few transactions were executed
    - There is a lot of overlap in the interactions, such as the destination address, and the time
    - The owner of multiple multi-signature addresses is exactly the same, and never changes from start to finish

- For Owner Address
    - Empty address
    - The first source of funds is the owner.
    - Mutual transfer
    - Behavior similarity

**If the verification is passed and  my strategy is great,  I can provide my source code, but for now it is not conveninet**

# Safe Address

`0xce495858e36c95f491b5a32ca2664405cf10ab76`

Thanks

**Comment by tschubotz** [comment]
Thanks for the report. All of these Safes have been found by a previous report, unfortunately.
