### ISSUE TITLE
airdrop farmers list2 !!!

### ISSUE THREAD

**Issue by BountyHunters1** [safe-global/safe-user-allocation-reports#39]
The airdrop hunter used the 0x7bdd6529fdfd78b1125aa4d4d152e37b58fe49c0 mainnet wallet to create 56 multi-signature addresses, and all of them received high token rewards,The query link is https://etherscan.io/address/0x7bdd6529fdfd78b1125aa4d4d152e37b58fe49c0?method=Create__Proxy__With__Nonce~0x1688f0b9

Querying an address through the Ethereum browser has created 56 multi-signature addresses, and all of them have transactions. The query link is https://etherscan.io/address/0x7bdd6529fdfd78b1125aa4d4d152e37b58fe49c0?method=Create__Proxy__With__Nonce~0x1688f0b9

0xBef0E77E3C2c3D07C02Ba8a419DaB3d95C74DEC9

0x5Dd2c4b7CEe0d63f59fbD40E345dc7FAD66550F6

0x27B838c2e151E45b82828630841dc58C75929540

0xfc60020375d6EAF86E299870448B88624cA0202f

0xc44b3e6889C08d0df9Ef494aD8a7cBe176896d11

0x7e704B7fA936e14bE948338fC9bec46B192bD101

0xdb251227116046f5076aE327BD2E8b8cfFc22479

0x3b0D3Ff250ba494DB67FEe61d7DB296e71a73884

0xCeC93b333d4140a7d53B6d72ccf4F5f9dFF951b6

0x5698a89AC10842e658804a9c36A8C5085Bfbe3C0

0x8e1E78354c240F28a01DA55611d1bbac2F17Fe39

0xb0C67d860158e0592b317488685fBCb3F836C8D6

0x53Ff9B7E00C601DcDFEb9D3Da5dB4252D72757D6

0x95905e9795c6242e1b70C7dca6Cb7Ff70AfE53Fb

0x2377420b05bB2df71a5B130ac0e472a46e3297F0

0x61e00016d26a700352E8e7ba3868426b000c8E79

0x7aF79F67Ab00a50B4a08390247Cc65B8A9512ab4

0x993D5ADCB4Bf8E848ba25a42C92934f59cff5f0A

0xEDf65B05908C75a447f3B0462C935429011B318E

0x344C416cc1e616223665c0618d123caDA1A948FD

0xBEABD76e274f9F56c2762e4a5991e3D52F730cfc

0xAB5C0F10Edd3972B5Cd3911c9a81eD2180c218D2

0xe36aaF75975720C0FA3D56087Bf910d2A53Cc959

0xa63d3836d37146a8B186C7B20258f988B5d74426

0xCC191076ef2337cCFA15ce7986e68d45A4144Ee8

Reasoning
The airdrop hunter used the 0x7bdd6529fdfd78b1125aa4d4d152e37b58fe49c0 mainnet wallet to create 56 multi-signature addresses, and all of them received high token rewards,The query link is https://etherscan.io/address/0x7bdd6529fdfd78b1125aa4d4d152e37b58fe49c0?method=Create__Proxy__With__Nonce~0x1688f0b9
Methodology
Querying an address through the Ethereum browser has created 56 multi-signature addresses, and all of them have transactions. The query link is https://etherscan.io/address/0x7bdd6529fdfd78b1125aa4d4d152e37b58fe49c0?method=Create__Proxy__With__Nonce~0x1688f0b9

My Safe Address
`0x737CD34E12E8aC795F39a1b6754F9BF53B5295d1`
-->

**Comment by BountyHunters1** [comment]
Please reclaim the reward for these addresses,thanks~

**Comment by tschubotz** [comment]
Please elaborate on why these are safes created for airdrop farming. Just the fact that 1 addresses created all of them doesn't qualify.
If e.g. a wallet uses a relayer to create Safes, the relayer would be the account that created all user Safes which is not airdrop farming per se.

**Comment by BountyHunters1** [comment]
First, this safe was created by the same person, which is suspicious. Second, the chain transactions of these safes are almost the same, so these lists were created by airdrop hunters, who destroyed everything, hoping to be punished.

**Comment by BountyHunters1** [comment]
Another point is that the address where the safe was created was once marked as an airdrop hunter by hop. So it's easy to distinguish, and I hope they can be punished.

**Comment by tschubotz** [comment]
Those Safes store quite some stable coins for at least a short period of time. Store of value is legitimate use. Hence there are chances this would eliminate at least some legit users.
