### ISSUE TITLE
owner 0xa1caaf4f7cb317b62beff4c76366e1087afcd117, 0x0d09a1bb9479a8fef0c38839fcfa70e810ce508f. add and remove same

### ISSUE THREAD

**Issue by skydotone** [safe-global/safe-user-allocation-reports#397]
# Related Safe Addresses
```
0x221cc2ad3d74dd9bf68603f032b88fdbf3158241
0xfcf90c4b6e0824e835095293f3caa586f89c97b0
0x31f1722c92337074871473262b89f4936f7988d2
0x8bd0fd084b482b6f8b69760f7256623105502d47
0x9976bc5975b1816abff09d80aff04b8404ba4b8b
0xbb555300bb8b218116f9e009984a3b89f93bc5de

0x03154d383d10852afc8ad9f8c51bd501436ab211
0xeaf4a1b853c09641706f36e77e612de602a9675f
0x5b2c7292ad5a65301d565d43534e15dda27e845e
0x6e7e0d2b1579fc3288960f6284f31c4ee24f86ef
0xce6cbf1198fb3ce7f7f9be4c83a69ba2e35800b0
```

# Reasoning

> There is an abnormal behavior that is understandable 🍄

> However, if there are many abnormal behaviors, then there is enough reason to determine that these addresses are airdrop farmer.

1. All of group1 the owner is same `0xa1caaf4f7cb317b62beff4c76366e1087afcd117`, only this address

2. All of group2 the owner is same `0x0d09a1bb9479a8fef0c38839fcfa70e810ce508f`, only this address

2. All of the multi-sign address, the behaviour is always same and stange .

    - 100% of the group1 multi-sign adddress addOwner and removeOwner transaction took place from `2021-09-15`.(at the same tx, no exception)

    - 100% of the group2 multi-sign adddress addOwner and removeOwner transaction took place from `2021-06-26` to `2021-06-29`.(at the same tx, no exception)

    - The group1 and the group2 , All of them execute 1 transactions, add owner and remove owner in 1 tx, always the same tx.

    - the group1 add owner address is always `0xa1caaf4f7cb317b62beff4c76366e1087afcd117` , remove owner address is always `0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D`

    - the group2 add owner address is always `0xe062084D2FEc1C9334E67A9dcd7b4A12AF98bC55` , remove owner address is always `0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D`

    - Please Check Table 
        - Address -- multi-sign address
        - Execute transactions -- The number of execute transactions by multi-sign address
        - AddOwnerTxAmount -- The number of add owner
        - AddOwnerAddress -- The Address of add owner
        - AddOwnerTx -- The tx of add owner
        - AddOwnerDate -- The date of add owner
        - RemoveOwnerTxAmount -- The number of remove owner
        - RemoveOwnerAddress -- The Address of remove owner
        - RemoveOwerTx -- The tx of remove owner
        - RemoveOwerDate -- The date of remove owner

| Address | Execute transactions | AddOwnerTxAmount | AddOwnerAddress | AddOwnerTx | AddOwnerDate | RemoveOwnerTxAmount | RemoveOwnerAddress | RemoveOwerTx | RemoveOwerDate |
|---|---|---|---|---|---|---|---|---|---|
 | 0x221cc2ad3d74dd9bf68603f032b88fdbf3158241(group1) | 1 | 1 | 0xA1CaAF4F7Cb317b62BEff4c76366e1087AFCD117 | https://etherscan.io/tx/0x417cbe9c110591aff86cb66ec97d3d11634378f011e381587766c8442f09a2f2 | 2021/09/15T01:04:07.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x417cbe9c110591aff86cb66ec97d3d11634378f011e381587766c8442f09a2f2 | 2021/09/15T01:04:07.000Z |
 | 0xfcf90c4b6e0824e835095293f3caa586f89c97b0(group1) | 1 | 1 | 0xA1CaAF4F7Cb317b62BEff4c76366e1087AFCD117 | https://etherscan.io/tx/0x0bf74301acceaae0a6f8a74fa76ce0094ae1df13b357d0d70ecba52268254a2b | 2021/09/15T01:01:01.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x0bf74301acceaae0a6f8a74fa76ce0094ae1df13b357d0d70ecba52268254a2b | 2021/09/15T01:01:01.000Z |
 | 0x31f1722c92337074871473262b89f4936f7988d2(group1) | 8 | 1 | 0xA1CaAF4F7Cb317b62BEff4c76366e1087AFCD117 | https://etherscan.io/tx/0x389481daa5f3594fb63721d1cbb94d0e60d5299483b18c5492b974751c1876ca | 2021/09/15T01:11:46.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x389481daa5f3594fb63721d1cbb94d0e60d5299483b18c5492b974751c1876ca | 2021/09/15T01:11:46.000Z |
 | 0x8bd0fd084b482b6f8b69760f7256623105502d47(group1) | 1 | 1 | 0xA1CaAF4F7Cb317b62BEff4c76366e1087AFCD117 | https://etherscan.io/tx/0xce7bc3b4f1b3814107b5344dd40e8c25f18b6b655b6f2ede945dc6736583beac | 2021/09/15T00:54:19.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xce7bc3b4f1b3814107b5344dd40e8c25f18b6b655b6f2ede945dc6736583beac | 2021/09/15T00:54:19.000Z |
 | 0x9976bc5975b1816abff09d80aff04b8404ba4b8b(group1) | 1 | 1 | 0xA1CaAF4F7Cb317b62BEff4c76366e1087AFCD117 | https://etherscan.io/tx/0xf92634e83d0291deaea5f2e827fc123e43fd1495d6d688eacb64d02aea2a0347 | 2021/09/15T01:05:37.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xf92634e83d0291deaea5f2e827fc123e43fd1495d6d688eacb64d02aea2a0347 | 2021/09/15T01:05:37.000Z |
 | 0xbb555300bb8b218116f9e009984a3b89f93bc5de(group1) | 1 | 1 | 0xA1CaAF4F7Cb317b62BEff4c76366e1087AFCD117 | https://etherscan.io/tx/0x732b2cab49e5415b737b5888b62b1410bbf5149078f49971d2e2dedee3922955 | 2021/09/15T00:57:57.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x732b2cab49e5415b737b5888b62b1410bbf5149078f49971d2e2dedee3922955 | 2021/09/15T00:57:57.000Z |
|---|---|---|---|---|---|---|---|---|---|
 | 0x03154d383d10852afc8ad9f8c51bd501436ab211(group2) | 1 | 1 | 0x0D09A1Bb9479A8feF0c38839fcfa70E810cE508F | https://etherscan.io/tx/0x1fff9b8cad8554c83dc6f2d0bb50896dfda64d9db451c05b680a02665e6d7efb | 2021/06/29T21:12:31.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x1fff9b8cad8554c83dc6f2d0bb50896dfda64d9db451c05b680a02665e6d7efb | 2021/06/29T21:12:31.000Z |
 | 0xeaf4a1b853c09641706f36e77e612de602a9675f(group2) | 1 | 1 | 0x0D09A1Bb9479A8feF0c38839fcfa70E810cE508F | https://etherscan.io/tx/0x1e11fd066cd831eb3b9ceea9d8c4ba1e10974d428e830d92b2d1cb443c270364 | 2021/06/26T21:44:05.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x1e11fd066cd831eb3b9ceea9d8c4ba1e10974d428e830d92b2d1cb443c270364 | 2021/06/26T21:44:05.000Z |
 | 0x5b2c7292ad5a65301d565d43534e15dda27e845e(group2) | 1 | 1 | 0x0D09A1Bb9479A8feF0c38839fcfa70E810cE508F | https://etherscan.io/tx/0x0f0312e304fab181e2497a395cbfbd8cde09be43fd2bb3ba5fd9a63aeedebd83 | 2021/06/26T19:51:18.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x0f0312e304fab181e2497a395cbfbd8cde09be43fd2bb3ba5fd9a63aeedebd83 | 2021/06/26T19:51:18.000Z |
 | 0x6e7e0d2b1579fc3288960f6284f31c4ee24f86ef(group2) | 1 | 1 | 0x0D09A1Bb9479A8feF0c38839fcfa70E810cE508F | https://etherscan.io/tx/0x969f7f0b52f196ea7986e42b940dd4e5f28d090165b5c7714ff5f6e2e3a09f8f | 2021/06/26T19:44:20.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0x969f7f0b52f196ea7986e42b940dd4e5f28d090165b5c7714ff5f6e2e3a09f8f | 2021/06/26T19:44:20.000Z |
 | 0xce6cbf1198fb3ce7f7f9be4c83a69ba2e35800b0(group2) | 1 | 1 | 0x0D09A1Bb9479A8feF0c38839fcfa70E810cE508F | https://etherscan.io/tx/0xa3e9772ceedd541b10402480bbcb6536d730b8cea00f9fb6b0ad49ece43b0ecf | 2021/06/26T19:53:55.000Z |1 | 0x66A0FF664f8509370C5D718A0f69AC1DC01f5c3D | https://etherscan.io/tx/0xa3e9772ceedd541b10402480bbcb6536d730b8cea00f9fb6b0ad49ece43b0ecf | 2021/06/26T19:53:55.000Z |

---
# Methodology

Addresses are reported by retrieving information from the chain, using bitquery's graphql, and detecting abnormal behavior, such as empty wallets, mutual transfers, etc.

When only some of the anomalous behaviors are present, we can consider the address reasonable, but when an address has all the anomalous behaviors, we have good reason to suspect that the address is false. **Especially if the multi-signature address and the owner address have obvious exceptions both, then it is obvious that this is airdrop farmer**.

Abnormal behaviors include 

- For Multi-Sign Address
    - Few transactions were executed
    - There is a lot of overlap in the interactions, such as the destination address, and the time
    - The owner of multiple multi-signature addresses is exactly the same, and never changes from start to finish

- For Owner Address
    - Empty address
    - The first source of funds is the owner.
    - Mutual transfer
    - Behavior similarity

**If the verification is passed and  my strategy is great,  I can provide my source code, but for now it is not conveninet**

# Safe Address

`0xce495858e36c95f491b5a32ca2664405cf10ab76`

Thanks

**Comment by tschubotz** [comment]
Thanks for the report. All of these Safes except for 1 have been found by a previous report, unfortunately.

And for this one I'm unable to follow your reasoning. It might be legitimate use.
https://gnosis-safe.io/app/eth:0x31f1722c92337074871473262b89f4936f7988d2/transactions/history
