### ISSUE TITLE
airdrop farmers list3

### ISSUE THREAD

**Issue by BountyHunters1** [safe-global/safe-user-allocation-reports#40]
The airdrop hunter used the 0xe5342d500d7E5578D412f0379AbEd1Fe08Ba85b5 mainnet wallet to create 31 multi-signature addresses, and all of them received high token rewards,The query link is https://etherscan.io/txs?method=Create__Proxy__With__Nonce~0x1688f0b9&address=0xe5342d500d7e5578d412f0379abed1fe08ba85b5

Querying an address through the Ethereum browser has created 31 multi-signature addresses, and all of them have transactions. The query link is https://etherscan.io/txs?method=Create__Proxy__With__Nonce~0x1688f0b9&address=0xe5342d500d7e5578d412f0379abed1fe08ba85b5

0x29967e4825E0918c60ff14e85C5289Bd0DB59838
0x87E85Da80725508eFD6925fA9C67E8853bfC6B31
0x19C0E462C9CF1C988c5dbdb93EB70c3f2f6E3A41
0x8dd946CbdAdD25b08e0042eA7964783832A3d236
0x8fc4cF7868a53FdD592bC574Ea8b48DEB4d7AfB3
0x748680b31D0D910d98776151e50E6a4b51aa24CE
0xb8a2Dd81bdB8d29B2867c68A1EBe917bd3c1cd1A
0x6935409a0d45bf30E1296ba8aE886650119Ee76f
0xEEA2C1D6207d563E42CC573E72771e5dD1088F78
0x537882BF07759250659724798cf0Dc133682818b
0xd66f2Fa280C2f2B008Fd0356fBaff09944FBf282
0x54F4689f34ce3117F1d6e2877ed55CDF36444b6F
0x6c9c6282A9e5F06511db2ad38C7D9E3fed5B0b90
0x10ea6C3338b238b3bf95d6B8d3ab8113ca4Ac67d
0x259A31E3Dc51E050D8fC3f3cC2a6aDeA822761ef
0xfc31C7d16514E3584D875563122e9Db97Cf83c0d
0x0c674b15271344A46002a722765F6c36932fFdB7
0x5397903B354330d6b6F2DfDa54DDf48c2BDF5D7c
0x21fab53d04a9a2A41fA8728E20F9dD7F974AbbA4
0xD9b05F432dB2755C84f7053577C918ccF84adCA2
0x22D3eceaD2572955832504545a8283cdb122B928
0x907328363E6e1Cc631E23675129D214B933B7BFA
0x8B8BbaC4Df4D4bEe5C1704F9587d80C5487BC825
0xFde435e94b7D0030D4D95E2fb050A1FcC2EdE5a5
0x689d5493F40108decF104243AE15B41C7A5CdCD6
0x65ed9Abe998ad11bE02B2267A06B7da4fAdB8464
0x5b195c3a82d3C1e38aA63092B646ADa797d41d78
0xA28482431Ac42F31f194689e30358956db6B5968
0xE7d046e291Ff8D870592c18bc93F735E25C1EE03
0x810b71759CC2e742d56A6C4eCf9EC036AFD1A095
0x06Ca151A59E83668cc5295770A43d6607b8F9B45

Reasoning
The airdrop hunter used the 0xe5342d500d7e5578d412f0379abed1fe08ba85b5 mainnet wallet to create 31 multi-signature addresses, and all of them received high token rewards,The query link is https://etherscan.io/txs?method=Create__Proxy__With__Nonce~0x1688f0b9&address=0xe5342d500d7e5578d412f0379abed1fe08ba85b5
Methodology
Querying an address through the Ethereum browser has created 31 multi-signature addresses, and all of them have transactions. The query link is https://etherscan.io/txs?method=Create__Proxy__With__Nonce~0x1688f0b9&address=0xe5342d500d7e5578d412f0379abed1fe08ba85b5
they all call Create__Proxy__With__Nonce
My Safe Address
`0x737CD34E12E8aC795F39a1b6754F9BF53B5295d1`
-->

**Comment by tschubotz** [comment]
Please elaborate on why these are safes created for airdrop farming. Just the fact that 1 addresses created all of them doesn't qualify.
If e.g. a wallet uses a relayer to create Safes, the relayer would be the account that created all user Safes which is not airdrop farming per se.

**Comment by BountyHunters1** [comment]
0xe5342d500d7E5578D412f0379AbEd1Fe08Ba85b5   All operations of the safe box created at this address are unified   There must be something wrong with this.

**Comment by BountyHunters1** [comment]
Another point is that the address where the safe was created was once marked as an airdrop hunter by hop. So it's easy to distinguish, and I hope they can be punished.

**Comment by tschubotz** [comment]
The reasoning in this report is not sufficient. Also looking at some of the Safe, there are chance that at least some of it is legitimate use.
