### ISSUE TITLE
Witch Problem Report

### ISSUE THREAD

**Issue by coinbtc13** [safe-global/safe-user-allocation-reports#406]
# Related Safe Addresses

  0xdB24617164c407B441cAa0b9776602fdbAc31483          
 0x100028EaAED23e6eC8C0ee690A761b291DEC3A99         
 0x50b0d55c6356d9e105C5D5Cbe1F99750F77EEa0d 
 0x58E39E3FCd327474Fd03Ee53dB7f2A612b69D1dB
 0xb24C5c740a883d919434cC25473cF5b434AA201a
 0xE41eEEAdA1446a9c1fdC84220396Bd5a026088E0

-->

# Reasoning
I'm sorry I didn't find ten associated addresses But I think what I'm doing is working,
But I found out that all six safe deposit box addresses were created by the same person
This link is the main Ethereum address where I found them. Please note that these ENS domain names were actually created by the same person. The reason is that I found the safe-deposit box security wallet address in the internal transactions of these wallets with the record of transferring money to each other
# Methodology
I didn't use any fancy technique to find this airdrop farmer, it's actually pretty simple, right

#393 This is the Ethereum address of the airdrop farmer
0x5BA1031BB03110D4443f5Df83002338428C4C8Eb
0x0C85891C036ecd0dd902eBB722A4eCB71e8e0D12
0xa63859b66F63A36Fd114B3fAEdE1e117Ce5351da
0xCbDbAc2F68dC35398981Cf76D4f0DA76Fadba8ea
0x0E5610b7E42E134D9d57224DB6B47Ce75afA87c9
0x8e6327a2513C4e9ceaF1080d5cB35442b737bf40
These etheric lane address is associated with 0 xa63859b66f63a36fd114b3faede1e117ce5351da this address
[https://etherscan.io/address/0x0df0bb2c43b76491adfbb401acd9644941ed6fef  ](url)
You can find it here

# Safe Address

0xd80709322C86757e3F1aB1624169e7f7Cf7DA85f
-->

**Comment by roobee18** [comment]
Safe Address

0xd80709322C86757e3F1aB1624169e7f7Cf7DA85f

**Comment by lukasschor** [comment]
Unfortunately we only accept clusters of >10 Safes to make sure only systematic and bigger airdrop farmers are excluded and reduce the risk of excluding legitimate power users.
