### ISSUE TITLE
[Discussion] SAFE WITCH HUNT: False Accusational Reports to Farm SAFE Rewards

### ISSUE THREAD

**Issue by sbycdao** [safe-global/safe-user-allocation-reports#408]
What's to stop people from making fake reports on innocent Gnosis Safe addresses in order to farm tokens received?

I'd like to see this discussed in depth before the September 19th deadline!

**Comment by CaptainTee** [comment]
Bring it on, friend! I can't wait to read your full write up

However, I may suggest you comment directly on posts pointing to your address(es) as farmer and defend your address(es)

Commenting on such post also gives the team member(s) in charge of verifying the finder's claim a better chance to make best decision

**Comment by PulsarNetwork** [comment]
We probably need a dispute period after the cutoff time for whoever is misidentified

**Comment by lukasschor** [comment]
Please discuss this in the forum instead.
