### ISSUE TITLE
These addresses have the same active path

### ISSUE THREAD

**Issue by opop369** [safe-global/safe-user-allocation-reports#418]
# Related Safe Addresses
0xf0bc143b5af806c62c174b59393b2427a2a33383
0x91fa6a8de5b8cca0e0af5e320134421158b1a45c
0x1b59531e89f5c61424e3f85f6ecd062783b968d1
0x903e5a15cb15d6fcee36491863044f0d5921edcb
0x86bb83bf6290c6353ea95292e90c7f87b25732c0
0xc64e25ea0d840135a668039c3e33ba32beb866dc
0x8826f5ea3e4342b1414dfb40d4560faf1abfc4ff
0xba410934d0045a39402fd6211fcc2ce9d98a5089
0x86a683502d2e145347e80f084afe441c5313b9d7
0x25251eaf795fe1535030afbeed3493cae1c90cac
0x0e369ce5f16677ed76cf0b1706b13cb8e354f083
0x7a732459ec7f3642cba755f148ff3e2aa33b88a0
0xc3ed136ea4cc21e6960688076c82433b7bd3d889
0xf91d7b3648fd9ff499447e1dd42c1822d04f50fe
0x9952ad08add1d12dba644fa9da1f43f012017207
0x52b871b602fd12ea161e1a37dfac3148bbec508e
0xad47e0d47882e8961b4ee521e227b5c2656c09dd
0xb52667d635df2feb7d77f22cf455d800935d2e46
0xa93838de45700e86af2324e1956286c32153539b
0x01f6ea895ce104c279f7c9fb6413ffab67e04ed7
0xf38fedc98485a942508229557c244cf0238d10af
0x2fc90115f70518ac4bfcc863ca7ed8554aa5c0c3
0x3f6dc3710191358850ce09126a7047a7229bb917
0x651396749fa6fc5195967a363418cf6726701856
0x76e9158d98cd99cb62aa17566f7786d6ed4d84aa
0xda617fd42882541c0e364fc495fcab2eb830220a
0x6fdca020c2ae2fc8342212fc4eb417409157cc7c
0xe87290018782ee5367b76e9b0ba8cd7fd4194ed5
0x1969732ff22b2e9876989ecaa82a398c74e6c922
0x854f52bee0e42aa5a154d4649f940749a3391afe
0xeb6cce6bb6373101482b164eb8f3774a126de983
0x63fafc6ea2ea5262a50cd53184d99167c1b9ccab
0xff4158854df724c41f66e31fd95804f3b4611820
0x69c46fe952ceee0169ac7b373a52f47c76a50614
0x13e6916ff7d37d03f48a3d48400a07bf221ad484
0x7a8cd91bfa2c65fe15fa24e901fe998d5bb3fdca
0x3840e8aea9622f9952f124a5763cf0ff1db49000
0x60fb6e18eda38cb80a0350176cc005ec012086aa
0xa493f32f2c5044ae13362a704939959581ef2504
0xc1e87373c2c7fb36a8b210d9d1170cbf4d90ccc0
0x3d40266331932eab327712ec5bfb5ff4b3366fae
0x58107062ef073403fa07479e317066fef15ab355
0x47a6642333767204456155b53ad05549a7789777
0x32059a66eaf58396531331ffca0f31a0ff375628
0xad034b46509924e5cf2e8ac17325b4bfdd6e2e24
0x6745821ac1ee2030e075995334248708af79c700
0xc6f8e725e920595dacd064e7bf4c53fc2a258a58
0x49431e62ad8177560367e9413e95824a84a7083e
0x3711fa6e92c68cf415d847e1ca36a4a9b9cb97a0
0xdf113bb9ea6a52d2dbf0bfa0456d0dbcaf4155a3
0x5a5f8b1393aa74de67255a5c47399d6925bcff1e
0xdbc2faea71206faa3650dfcceb6852236dc25287
0x2d442c1f1fbf6302c5f28a51a783a61c0582e35f
0xff276942316d27e4452096d1a54fa48e4859032b
0x53dd7d73f44557a44253320abb4a4270f357a8e4
0x4451f2962b52b220d367750b6b395945dc6c7181
0x58e93e97d83300b5426b58266b04d98ed8384d3b
0x935ec79a9ab0af7cd8cf5580dad1ef5da90387de
0x362dccf384940b4650af5731ab4e3df334c2ad81
0x430f99a782652929639cd37ad1f03c8120fad49b
0xacb4072c576252832a0e75c080007db5f304788b
0xf85ce5cda183d04f459f32a4cf439c9ffeb24e1b
0x217a3406bd4a543ee4ca739402a342d326af1315
0x926220200fbb376a54ed6a8adfdbc26432be0b3f
0x3ccb48edfc70633b8af6171a9f3070abfabb8762
0xf709186222ed56cc12b38c2c5f5f644a1033debe
0x79a86b6e46764e5c94d13f4118901e4f2258cab7
# Reasoning

These Safes have only 1 tx in its entire lifetime, and that is like the following:

https://etherscan.io/tx/0x934eab25eb98b64106fa3f26030cef71ef7973b769c57c6414b8acfc7696dce1#eventlog

https://etherscan.io/tx/0xb67f18efc13c0ae420a5e7356a45886a1f6b1c857ae49e5c4f91dde914fe21b2#eventlog

From the event logs we can see, 0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7 sent a tx to remove owner [0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d](https://etherscan.io/address/0x66a0ff664f8509370c5d718a0f69ac1dc01f5c3d), and assigns a new owner. This is the only tx that these Safes have.

These Safes were created by [0x5769770f5efe8fb017fb09b6de3b2d096668377d](https://etherscan.io/address/0x5769770f5efe8fb017fb09b6de3b2d096668377d). This is an address that creates Safe proxies in batch. For example: https://etherscan.io/tx/0x5bf24dd77e6aa807f2db992de7e5993ade0255ad0a1e74fa415513d472af65f6#eventlog In this tx more than 30 Safes were created.

Following the same arguments as in https://github.com/safe-global/safe-user-allocation-reports/issues/237, I believe the creator of these Safes is a relayer. It created Safes for users in batch. After creation, 0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7 who used to be an owner of the Safe, and then renounced ownership and transferred ownership to users.

Generally, this indicates a valid use case where the protocol configures Safes on user's behalf. However, if such an owner configuration tx is the only tx that the Safe has, should it be qualified for the airdrop? I don't think these are airdrop farmers, but neither do I think they should be qualified. I'll leave it to the team to decide.

The tenet of the airdrop is to incentivize / reward organic usage of Safe but not to send free money to whoever just happened to create a Safe without actually using it. That's why those Safes without any tx history are ineligible. Having 1 tx in Safe's tx history doesn't necessarily mean the user has ever used it for real transaction. Instead, the user may have never heard of Gnosis Safe, but just happened to create one via third-party apps.
# Methodology
Algorithm:

I identified 0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7 (let's call it the "manager") interacted with multiple Safes that have only 1 tx in the history, and those interaction times are close. There were 9995 interacted addresses in total.
Retrieve the manager's tx history from etherscan API
For each tx initiated from the manager, I filter those txs calling "execTransaction" method, and record the callee addresses. These callees are the Safes.
For each Safe obtained from last step, I filter those safes with only 1 record in the tx history. 5693 addresses are obtained.
Lastly, I manually checked a handful of safes to validate that the creators belonged to 0x5769770f5efe8fb017fb09b6de3b2d096668377d
Finally, these Safes are the ones that users didn't actually interact with, but instead the manager configured the owner as the only tx in their lifetime shows. The Safes were inactive ever since then.

# Safe Address
 0xe0E84EE75F74e9d2f291b96366601D083952627a

**Comment by PulsarNetwork** [comment]
You copied my report! https://github.com/safe-global/safe-user-allocation-reports/issues/301

**Comment by tschubotz** [comment]
This one is a copy of #301
