### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by SybilAttackerDetector** [safe-global/safe-user-allocation-reports#438]
# Related Safe Addresses
```
0x377c364e09057dbe4169ebabb857b1663511ed23
0xb4c87e483546a35b7666c5fdab89920acf0cc463
0x0e2dbf98bdfa0dd2f2a6031c989d0bd0f7be4fd7
0xb255ad9ca333bd456fc9dd3fc79851d7fd6724a9
0xfc2cfc73ef51c660c4da5fd510e9500a9e77512e
0xb3df9e9c713433208d6c62bb578dd6759f6c7275
0x2f64a5ed71230e60db2cb55a8a2ebb3ec7d6cf35
0x71557990b0d8913a6874642cddd4046d3c244ba4
0x922fe6d42668f96484409ecada8699467195d439
0x0ef98a437746bf1808523a0772fb3278af777279
0x84b4eade5f61397df7e4550a31f72fd545cf696b
0x5db437f110ef8b05b7e37a85b64e2486b2d58b33
```
# Related Safe Creator Addresses

```
0xf0687e090fe3b11160596bcca10ddd2415012881 0xf0
0xb9178768f6d8d61f00bcf9767885befe7e54b48a 0xb9
0xe4da6192a89dff5c02d754e5e7b319155109f43c 0xe4
0x9e25d80b3838e816b07a868f598f4c115e9d7eca 0x9e
0x7a3cac5012e7fbe9b0557757598da7e9c4e6a87e 0x7a
0x772cb5a031623cd7ac3fa8fa4125596672b6c4ac 0x77
0x503612b9914f1c74618d30ea167d58a55d132335 0x50
0x2aff3c5f51c0ae4a111edaec1daa305395361896 0x2a
0x54a9aadbfb39ea9906b823353978193da0032684 0x54
0x0e61ff4845d4e365fc8e44a410102a5b0bb2a5ee 0x0e
0x0196ded59afe1df493cd2ae4c205c549f6e6d6fc 0x01
0x6d4a56f6d55dbc0531d380752ba17d2c13f3ad9d 0x6d
```

# Reasoning

We analyze 12 safe addresses creator and found they are highly related by checking their Ethereum transaction history.

**Below are the evidence that 0xf0/0xb9/0x9e/0x7a/0x77/0x01/0x6d receive initial ETH gas from 0x50**

(0xf0)687e090fe3b11160596bcca10ddd2415012881 Receive initial Gas from (0x50)3612b9914f1c74618d30ea167d58a55d132335
TX: https://etherscan.io/tx/0x23395fa1c24ccd5289d8410d706cf590d7feb1268955797bebc4d0029e73d895

(0xb9)178768f6d8d61f00bcf9767885befe7e54b48a Receive initial Gas from (0x50)3612b9914f1c74618d30ea167d58a55d132335
TX:https://etherscan.io/tx/0xc3f1239accdd9d346657296c0e220621984f930ae581eebb0e0dbd02d9f3edeb

(0x9e)25d80b3838e816b07a868f598f4c115e9d7eca Receive initial Gas from (0x50)3612b9914f1c74618d30ea167d58a55d132335
TX:https://etherscan.io/tx/0x7e8c14f6e7de72d94cfff24de31d541eff0e28832f08f8d98cd31dd3da73954f

(0x7a)3cac5012e7fbe9b0557757598da7e9c4e6a87e Receive initial Gas from (0x50)3612b9914f1c74618d30ea167d58a55d132335
TX:https://etherscan.io/tx/0x459906d528f753b0093da771bb069ad8fb3dfba51a3d8dd36cbe38ceac182170

(0x77)2cb5a031623cd7ac3fa8fa4125596672b6c4acReceive initial Gas from (0x50)3612b9914f1c74618d30ea167d58a55d132335
TX:https://etherscan.io/tx/0xe590d6d13aacbd294854500ca3ad633a590f1199105fdacebc17011e60c8a8fe

(0x01)96ded59afe1Df493CD2aE4C205c549F6e6D6fC Receive initial Gas from (0x50)3612b9914f1c74618d30ea167d58a55d132335
TX:https://etherscan.io/tx/0xca7730b1937d3b99c9447cb8eee42abf12d50ad5e80167df7260caf9fe7c047b

(0x6d)4a56f6d55dbc0531d380752ba17d2c13f3ad9d Receive initial Gas from (0x50)3612b9914f1c74618d30ea167d58a55d132335
TX:https://etherscan.io/tx/0xb209618b0f79ab7ab6fcd27180efaf479fcdf48d96431d35ae2c7145280e36d6

**Below are the evidence that 0x50/0x2a/0x54/0x0e Receive initial Gas from 0xe4**

(0x50)3612b9914f1c74618d30ea167d58a55d132335 Receive initial Gas from 
(0xe4)da6192a89dff5c02d754e5e7b319155109f43c
TX:https://etherscan.io/tx/0xa8dcdafc4952ad25a381078fd4b138ef6520c9eb4a3cbfed1ab7284f36a72015

(0x2a)ff3c5f51c0ae4a111edaec1daa305395361896 Receive initial Gas from 
(0xe4)da6192a89dff5c02d754e5e7b319155109f43c
TX:https://etherscan.io/tx/0xa88acd2a25402288cbb5910ec161c1c2651dea7932a6544deac6f2552881008a

(0x54)a9aadbfb39ea9906b823353978193da0032684 Receive initial Gas from 
(0xe4)da6192a89dff5c02d754e5e7b319155109f43c
TX:https://etherscan.io/tx/0x6e4d48f139781c7d97a4343ab9323ce10577f2691224e60b0b5b3be88c6e95e0

(0x0e)61ff4845d4e365fc8e44a410102a5b0bb2a5ee Receive initial Gas from 
(0xe4)da6192a89dff5c02d754e5e7b319155109f43c
TX:https://etherscan.io/tx/0x53a1cd45e8008cb96cbc2a88894791100310385050dd19537412efb0f79ffa37

**Besides they have same initial gas provider, they are have multiple transactions with each other.**

This alone can connect them with each other, and we also find that some of the addresses shares very similar transaction history and they are interact with Aztec at the same period.

(0x01)96ded59afe1Df493CD2aE4C205c549F6e6D6fC
![image](https://user-images.githubusercontent.com/105185231/190102348-55b8f943-c2f2-4a04-b443-38700ed73776.png)
(0x54)A9AadbFB39EA9906b823353978193DA0032684
![image](https://user-images.githubusercontent.com/105185231/190102379-e7d8261a-8bdc-4bd2-a83e-710f68eb7def.png)
(0x7A)3cAc5012e7fbE9B0557757598dA7E9c4E6a87e
![image](https://user-images.githubusercontent.com/105185231/190102408-abf56f42-9203-4acb-a99d-5b32cb15941b.png)
(0x77)2cb5a031623cD7AC3Fa8fA4125596672B6c4aC
![image](https://user-images.githubusercontent.com/105185231/190102424-04fa5266-6f38-4ef8-89d3-6b9e027a10a3.png)
(0x61)0e8A3Be9Ad6c0bFcE18D3bb3878bDE894fb6c2
![image](https://user-images.githubusercontent.com/105185231/190102445-1e51a5e6-c8b0-405f-a18e-86cc5917ef2a.png)
(0xb9)178768F6d8D61f00Bcf9767885BeFE7E54b48A
![image](https://user-images.githubusercontent.com/105185231/190102455-cd435209-87ac-4a05-900d-f75f0d4bf68d.png)
(0xf0)687e090fe3b11160596bcca10ddd2415012881
![image](https://user-images.githubusercontent.com/105185231/190102473-2c73d720-29db-46c8-80d3-2c0ac181b73e.png)

# Methodology

We used an algorithm that generate address groups based on the Safe creator address. 

Basically, if  addresses have one of these relations, they get grouped together:

- have the same initial gas provider
- are other addresses' initial gas provider
- interact with the same CEX deposit addresses
- have multiple transactions with each other
- have similar transaction history

We run the algorithm to automate group creator addresses and find many groups.

Here are some stats:

![image](https://user-images.githubusercontent.com/105185231/190104640-d3584a59-7b89-4812-8fdb-90edbe40a94e.png)

We choose one of the groups to check their Etherscan tx history to extract detailed transactions to provide the above reasoning and will keep analyzing more groups in a later report. 

If the team is interested in our full group results, we can talk in private.

But we can be 100% sure the addresses in this report are controlled by the same person.

# Safe Address

eth:0x4038982805b0Eaa4cD075b59d0EA5Ba1d8E0E311

**Comment by tschubotz** [comment]
Thanks for the report, we've found the following to the related to airdrop farming:

```
0x377c364e09057dbe4169ebabb857b1663511ed23
0xb4c87e483546a35b7666c5fdab89920acf0cc463
0x0e2dbf98bdfa0dd2f2a6031c989d0bd0f7be4fd7
0xb255ad9ca333bd456fc9dd3fc79851d7fd6724a9
0xfc2cfc73ef51c660c4da5fd510e9500a9e77512e
0xb3df9e9c713433208d6c62bb578dd6759f6c7275
0x2f64a5ed71230e60db2cb55a8a2ebb3ec7d6cf35
0x71557990b0d8913a6874642cddd4046d3c244ba4
0x922fe6d42668f96484409ecada8699467195d439
0x0ef98a437746bf1808523a0772fb3278af777279
0x84b4eade5f61397df7e4550a31f72fd545cf696b
0x5db437f110ef8b05b7e37a85b64e2486b2d58b33
```
