### ISSUE TITLE
Safe Airdrop Farmers by @KARTOD

### ISSUE THREAD

**Issue by 0xKARTOD** [safe-global/safe-user-allocation-reports#442]
# Related Safe Addresses
List of addresses that have yellow 🟡 and green 🟢 score: ***See all info at Methodology part***

[green_and_yellow_addresses_reworked.csv](https://github.com/safe-global/safe-user-allocation-reports/files/9589555/green_and_yellow_addresses_reworked.csv)
https://dune.com/queries/1277996

List of addresses that have red 🔴 score:

[red_addresses_reworked.csv](https://github.com/safe-global/safe-user-allocation-reports/files/9589852/red_addresses_reworked.csv)
https://dune.com/queries/1268823/2173773 ~ 500 addresses

All addresses list:

[score_results_reworked.csv](https://github.com/safe-global/safe-user-allocation-reports/files/9588476/score_results_reworked.csv)
https://dune.com/queries/1262047/2162924

# Reasoning

In this report we tried to analyze the addresses of airdrop farmers. All the data was obtained using the Dune Analytics database. 

A ranking system was built for airdrop addresses based on the following parameters:
- Number of transactions in a given period.
- Specific fees per transaction - fees to transactions ratio
- Created after GIP-29
- Made by the same wallet

Of course, satisfying one of these points is not proof that the address is a farmer. For example I could create a Safe address in 2021, but have only 3-4 transactions during GIP-29. Therefore, a model for evaluating such wallets on a 100-point system was proposed.

# Methodology

First of all, let us mention three important references to Dune query:

- https://dune.com/queries/1261763 [1]
- https://dune.com/queries/1261367 [2]
- https://dune.com/queries/1266505 [3]

Using the query [2], let's look at the number of Safe addresses created by one wallet and build the distribution. In a [recent tweet](https://twitter.com/RZinovyev/status/1569355516094054400?s=20&t=NojhEHQ3i9D8LKWuGt5hCA) I already mentioned wallet **0x5769770f5efe8fb017fb09b6de3b2d096668377d** - this address created 5900 Safe addresses in the period from early 2022 to August 18, 2022 (hereinafter - event period). 

It turned out that during the period of this event:
- At least 5 wallets created more than 100 Safe addresses
- 13 wallets with more than 50 Safe addresses
- And etc.

Next, using the query [3], let's look at the activity considering all the official master copies (singlet) in the Ethereum main network:
1. 0x8942595A2dC5181Df0465AF0D7be08c8f23C93af (0.1.0)
2. 0xb6029EA3B2c51D09a50B53CA8012FeEB05bDa35A (1.0.0)
3. 0xaE32496491b53841efb51829d6f886387708F99B (1.1.0)
4. 0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F (1.1.1)
5. 0x6851d6fdfafd08c0295c392436245e5bc78b0185 (1.2.0)
6. 0xd9db270c1b5e3bd161e8c8503c55ceabee709552 (1.3.0)
7. 0x3e5c63644e683549055b9be8653de26e0b4cd36e (1.3.0L2)

Namely, the following parameters - the number of transactions during this period, fees spent on transactions and the relative fees ( Fees / number of transactions ). _**Gas spend on txs is a good indicator on how valuable a txs was for the executor at the time of the tx**_ .

Thus, the following important data were obtained:
- The maximum number of transactions is 2,256
- The maximum Fees to tx ratio - 1.49

But now how do we determine what is the optimal number of transactions to determine the airdrop farmer? Is the creation of a Safe Address proof that it is a farmer? We need to come up with a system or methodology to measure activity, amount of gas spent, address creation in 2022, etc.

Let's make the following grading system, where the maximum is 100 points:
- If the address was made in 2022 (during GIP-29), it gets a penalty of 10 points
- If the original address has more than 1 Safe address, it gets -30 points
- If the number of transactions at that Safe address is <3, it gets -15 points 
- Also a penalty of (1450 - txs count)/48, that is, the maximum penalty will be 30 points
- As well as a penalty for the amount of gas per transaction (1.18 - fees per txs ratio)*12.7, so the maximum penalty will be the size of 15 points.

### Why 1450 txs and 1.18 fees?
Let's first look at the number of transactions for each wallet. 
![image](https://user-images.githubusercontent.com/100310858/190373198-43d156fd-3d42-418f-8f3b-8b45980e26eb.png)
We see that the maximum number of transactions is 2256, but further we see a big gap between the first and second address, between the second and third, that is up to values ~900 transactions distribution has dedicated steps, which is best to smooth. So the best we can do is to take the average of the first five addresses and get 1450. Similar steps are done for gas.

# Changes:

Lots of feedback has been received directly on the forum, that is why we have changed the criteria and methodology for calculating the score. 

***Tx fees***

First of all, we excluded gas from consideration in this methodology. First, because the price of gas varies depending on the period you want to consider. And secondly, not a few users simply save and wait for the right time when the price of gas is lowest, and only then make a transaction.

***Related Safe Addresses***

Let's go a little deeper into the Related Safe Addresses system and say that if, for example, the original wallet has two addresses, he gets a penalty of 5 points (30 before).

If the purse has three Safe addresses - penalty of 15 points
If more than or equal to 5, then a penalty of 30 points
And the highest penalty, if more than 100 Safe addresses - 45 points

Also, we took into account the two addresses:
'0x9e0bce7ec474b481492610eb9dd5d69eb03718d5' - Tokemak address
0x5769770f5efe8fb017fb09b6de3b2d096668377d' - Staker App address
We treat them and the related addresses as separate addresses

***Transactions***
Added regular transactions such as "Transfer", not only official master copies.
Instead of calculating something by formula, taking averages, and so on, let's just say the following:

- If the address has 0 transactions, then we impose a penalty of 50 points
- If the address has 1 transactions, minus 40 points
- If the address has 1 to 3 transactions - that is, the minimum number of transactions requested in GIP-29, then a penalty of 30 points

We also add a couple of points for addresses that have more than 50 transactions

***Difference in the time of Safe address creation***

A new parameter to consider is the time difference in creating addresses (with the exception of Tokemak and Staker App). For example, if the same user creates two addresses 1 hour apart, is that suspicious? I think so. And what if it happens on one day, for example? - That's not so bad. So again we introduce a penalty system and calculate the minimum and average interval between the addresses for each original address. The query below will help us with this.

https://dune.com/queries/1261299

If the minimum difference is less than 1 hour - remove 25 points
If 3 hours - 15 points

If the average is less than 5 hours and there is only one Safe address, another penalty of 5 points

***Score calculation***

Given that the maximum penalty will be 100 (if the address has more than 100 Safe addresses, has less than 1 transaction in the GIP-29 period, if there are additional Safe addresses and they were created less than 1 hour apart) the Score is now calculated as:

- Score in range from 0 to 33 then red circle 🔴
- Score in range from 33 to 66 then yellow circle 🟡
- Score > 66 then green 🟢

# Safe Address

0x1B491d59846cb605A24a4690Df631946E52a2D0e

**Comment by df158888** [comment]
Well, you will be the whale of Gnosis. This project will become yours. excellent

**Comment by guodong4856** [comment]
If the address was made in 2022, it gets a penalty of 10 points ?
I don't think it's right ,please be careful..

**Comment by jimmylao888** [comment]
I don't think this is more reasonable, I think the community is more important, thank you

**Comment by lztfi** [comment]
You mean there are only 6500 real users? What a stupid proposal that killed most of the real users

**Comment by 0xKARTOD** [comment]
> If the address was made in 2022, it gets a penalty of 10 points ? I don't think it's right ,please be careful..

I think it makes sense:
First of all, we only take off 10% of the total points - that is not that big a deal.

Second, if the address was made during the GIP-29 period, from 2022-01-01 to 2022-08-18 (not before 2022), then suspicion may arise - whether it is an ordinary user or it is a farmer who just wants to get airdrop. Of course this is not direct proof that he is a farmer, so only 10%.

Also, we have a lot of addresses on our lists that were done in 2022 and yet made the green and yellow lists

**Comment by EjayFang** [comment]
Great, I have two safes, one I haven't used, and I don't expect this one to get an airdrop, and deduct points for it

**Comment by washiontan** [comment]
和什么时候创建的关系度应该降低的。什么时候创建都是用户啊，创建多个的才是。

**Comment by EjayFang** [comment]
Also, if I only have two safes and I need one to be bound to an address and the other to a different person, can I deduct points?

**Comment by 0xKARTOD** [comment]
> You mean there are only 6500 real users? What a stupid proposal that killed most of the real users

This does not mean that the green and yellow ones are real addresses/users. These are only users who are somehow worthy of this airdrop - active users of this project. If you think the orange ones are also worthy - I can tell you that most of them have 1 transaction.

**Comment by 0xKARTOD** [comment]
> Also, if I only have two safes and I need one to be bound to an address and the other to a different person, can I deduct points?

You mean that one of Safe address was created by (for example) address number 1 and the second by number 2?

**Comment by hinesec** [comment]
又搞什么幺蛾子啊

**Comment by EjayFang** [comment]
> > Also, if I only have two safes and I need one to be bound to an address and the other to a different person, can I deduct points?
> 
> You mean that one of Safe address was created by (for example) address number 1 and the second by number 2?

I mean, I have a safe bound to a and one bound to b and they are different people and I can't tie their money together, so I think it is reasonable for one person to have two safes, the condition should change

**Comment by PulsarNetwork** [comment]
Hello sir, 0x5769 who created 5k Safes is not a user. In fact, it's operated by Staker App wallet for creating user wallets in batches. Please see https://github.com/safe-global/safe-user-allocation-reports/issues/365 for details. (I do think most of the Safes it created should be denied airdrop)

**Comment by EjayFang** [comment]
Of course there is a problem with having multiple safes at the same time, but this number needs to be changed, otherwise it will hurt normal users

**Comment by 0xKARTOD** [comment]
> > > Also, if I only have two safes and I need one to be bound to an address and the other to a different person, can I deduct points?
> > 
> > 
> > You mean that one of Safe address was created by (for example) address number 1 and the second by number 2?
> 
> I mean, I have a safe bound to a and one bound to b and they are different people and I can't tie their money together, so I think it is reasonable for one person to have two safes, the condition should change

I see. Let me explain and refer to my previous reply. 

Of course here we deduct 30 points immediately for a second account made in 2022. Note: if you made address A before 2022 and address B in 2022, i.e. you actually have two addresses, points are not deducted. Naturally, there's a good chance that addresses with more than 1 Safe address are farmers, but again, that's just a guess. 

![image](https://user-images.githubusercontent.com/100310858/190674729-c7b91029-e747-4170-bb08-e2b9ae107ce0.png)

Plus, I will say that there is a good example, when the owner of the Safe address also has other Safe addresses and thus gets a yellow circle. In this example is clearly seen when one of the addresses is passive - that is, has few transactions, etc., and the other is active and has 1700 transactions

**Comment by EjayFang** [comment]
> 1700 transactions

What is the concept of 1700 transactions, how many people will have 1000 transactions in their own addresses

**Comment by EjayFang** [comment]
It is unreasonable to infinitely increase the requirements and even not be afraid of harming normal users

**Comment by PulsarNetwork** [comment]
About the number of transactions, have you considered token transactions besides normal transactions?

For example: https://etherscan.io/address/0x2dbb38ddd7ae50b215bd0359a2793974ad545f81#tokentxns

This address interacts with a relayer to forward token swap transactions. Therefore, there's only 1 tx history. But from etherscan you can see plenty of token txns

**Comment by billionmonero** [comment]
> Well, you will be the whale of Gnosis. This project will become yours. excellent

yeah next time just ask for my private key

**Comment by MccreeFei** [comment]
It's not fair

**Comment by wyt159** [comment]
渣渣项目方，空投规则总是改过来改过去的。妈个巴子。

**Comment by wyt159** [comment]
我的只有2个真实钱包，都被刷下来了。垃圾项目方

**Comment by orrvan** [comment]
30.03... hurt my heart

**Comment by RENXINPAN** [comment]
This proposal doesn't look very smart. Looking for airdrop farmers doesn't mean excluding new users

**Comment by hisen2fighting** [comment]
If the original address has more than 1 Safe address, it gets -30 points?????Points will be deducted for having two safe deposit boxes? This is obviously a wrong decision. First of all, not to mention whether this is an official function or not, and one of the times that happened to me was that there was a network or web page problem before, resulting in no response. I repeatedly submitted the creation transaction twice, so I have two safe deposit boxes. If these are all points deduction items, I would like to know what is the significance of this screening. Simply designate insiders directly. This is not something that ordinary users like us can enjoy. feel angry.
LOL

**Comment by cyt1234567158** [comment]
如果行得通，你快照22年干毛线？直接212年的不就行了。脑瘫一样

**Comment by Jaywongg** [comment]
In order to complete the rabbit hole task, in August I created a wallet. Experienced the project. Now you are hurting real users by doing this.

**Comment by cyt1234567158** [comment]
有交易还不是用户？要你爹天天陪着你，你才知道你爹爱你吗？

**Comment by cyt1234567158** [comment]
幸好都不像你这种脑瘫，不然区块链早死了。绝对脑子有问题才去这样算，是不是到目前为止除了写代码一事无成呀？

**Comment by wyt159** [comment]
你是项目方么？这般骂我。我也没有惹你。



---Original---
From: ***@***.***&gt;
Date: Sat, Sep 17, 2022 00:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [safe-global/safe-user-allocation-reports] Safe Airdrop Farmersby @KARTOD (Issue #442)




 
幸好都不像你这种脑瘫，不然区块链早死了。绝对脑子有问题才去这样算，是不是到目前为止除了写代码一事无成呀？

**Comment by cyt1234567158** [comment]
> 你是项目方么？这般骂我。我也没有惹你。
> […](#)
> ---原创---来自：***@***.***> 日期：2022 年 9 月 17 日星期六上午 00:13 至：***@***.***>; 抄送：***@***.******@***.***>; Subject: Re: [safe-global/safe-user-allocation-report] Safe Airdrop Farmers by @Kartod (Issue #442 ) 幸好都绝对是你这种脑瘫，这样区块链早死了。算了，是不是除了写代码一事无呀？ — 直接回复此邮件，在 GitHub 上查看，或退订。您收到此消息是因为您发表了评论。消息 ID：***@***.***>

不是，我是骂提这个规则的人

**Comment by cyt1234567158** [comment]
绝对是脑瘫。一开始就是寻求覆盖范围，这家伙上路6500地址。要不直接宣布内部空投或者大户算了，也别要用户了，自己去玩

**Comment by cyt1234567158** [comment]
> 绝对是脑瘫。一开始就是寻求覆盖范围，这帮人上来投6500个地址。要不直接宣布内部空缺或者大户算了，也别用户了，自己去玩

**Comment by wyt159** [comment]
我只是个小韭菜，原本2个有空投的，现在也不达标。我不是项目方，也不曾提案过，也不曾为这傻逼项目方做过任何事。不知为啥你骂我。



---Original---
From: ***@***.***&gt;
Date: Sat, Sep 17, 2022 00:16 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [safe-global/safe-user-allocation-reports] Safe Airdrop Farmers by @KARTOD (Issue #442)

**Comment by cyt1234567158** [comment]
safe卡过，保险箱估计很多人创建了两个
剩下的分数看gas  说白了这提案的人  自己有大量地址，而且是21年做的
  这规则，就呵呵了。幸亏这提案的傻逼不是做项目了，不然早黄了改行了

**Comment by wirelessfuture** [comment]
The link to the CSV is broken, can you please fix it?

**Comment by 0xKARTOD** [comment]
> The link to the CSV is broken, can you please fix it?

Yep, sorry. Work in progress

**Comment by wirelessfuture** [comment]
No problem sir!

**Comment by freedomwant** [comment]
It's shameful to determine real users by gas fees, because you have to realize that a gas fee can be the cost of living for a family for a day.

**Comment by freedomwant** [comment]
Are you only responsible for the rich, I don't understand

**Comment by cyt1234567158** [comment]
> 你只对有钱人负责吗，我不懂

有钱人是他爹，肯定得负责

**Comment by konami0334** [comment]
Check the witch's right, as judged by the score, then I dare say, this advice, he created address all conform to the standards and drop more than 50 points, he must have been the biggest beneficiaries and when by gas costs to judge whether the hunter drop strange rules, it makes people feel unacceptable, I save the cost of gas is wrong? Is safe for rich people? When poor people save gas fees are airdrop hunters, then we don't have to be! Because you only need to serve a few rich people

**Comment by 0xEuuuler** [comment]
All addresses greater than 50 points were created before 2022, which means that all new users in 2022 are fake, are you serious?

**Comment by gxmjy** [comment]
我是创建了两个安全地址，第一个我觉得它尾数不好我又创建了一个，到目前为止我只用一个进行多签安全存款，难道这也有错？

**Comment by usee1100** [comment]
why did you remove the wallet address list ?

**Comment by cyt1234567158** [comment]
垃圾，地址别删吧。等查女巫。笑死了

**Comment by 0xKARTOD** [comment]
> why did you remove the wallet address list ?

Work in progress. Sorry

**Comment by usee1100** [comment]
My wallet is for 2022. I hope you don't remove me from the list :))

**Comment by 0xKARTOD** [comment]
> My wallet is for 2022. I hope you don't remove me from the list :))

I'm reworking my system. will write about what has changed in "Changes" part

**Comment by cyt1234567158** [comment]
几万个地址，被你搞成6500  我可以任务你自己至少拥有5000+地址。说实话没见过这么恶心的。别人需要的是用户，好家伙，你全部给自己。会乞讨呀

**Comment by PulsarNetwork** [comment]
"If the original address has more than 1 Safe address, it gets -30 points" rule is a big mistake

It goes against the principles of sybil hunting:

> Methodology that has a non-negligible chance of eliminating legitimate users will not be considered. When in doubt, we opt for “this is legit usage”.

https://forum.gnosis-safe.io/t/community-challenge-identify-airdrop-farmers/847

**Comment by 0xKARTOD** [comment]
> "If the original address has more than 1 Safe address, it gets -30 points" rule is a big mistake
> 
> It goes against the principles of sybil hunting:
> 
> > Methodology that has a non-negligible chance of eliminating legitimate users will not be considered. When in doubt, we opt for “this is legit usage”.
> 
> https://forum.gnosis-safe.io/t/community-challenge-identify-airdrop-farmers/847

No rush sir. I'm working on that

**Comment by PulsarNetwork** [comment]
Regarding newly added criteria:

> For example, if the same user creates two addresses 1 hour apart, is that suspicious? I think so. And what if it happens on one day, for example? - That's not so bad.
> If the minimum difference is less than 1 hour - remove 20 points
> If 3 hours - 10 points
> If the average is less than 5 hours and there is only one Safe address, another penalty of 5 points

This assumption is arbitrary and unnecessary. I think it's against the principles of this airdrop as the reworked airdrop rules by @tschubotz indicates:

> Minimum value stored in Safes: No minimum value required now (was 1 ETH before)
> In the original proposal, Safes that stored 1 ETH over time were included. This restriction was removed since it again sets an arbitrary restriction. Instead, the number of tokens allocated will just consider the value stored over time, relatively.

https://forum.gnosis-safe.io/t/new-proposal-reworked-safe-distribution-for-users/594

It's preferred that no arbitrary restriction is set, otherwise some legit use cases are likely to get excluded or discredited.

**Comment by 0xKARTOD** [comment]
> Regarding newly added criteria:
> 
> > For example, if the same user creates two addresses 1 hour apart, is that suspicious? I think so. And what if it happens on one day, for example? - That's not so bad.
> > If the minimum difference is less than 1 hour - remove 20 points
> > If 3 hours - 10 points
> > If the average is less than 5 hours and there is only one Safe address, another penalty of 5 points
> 
> This assumption is arbitrary and unnecessary. I think it's against the principles of this airdrop as the reworked airdrop rules by @tschubotz indicates:
> 
> > Minimum value stored in Safes: No minimum value required now (was 1 ETH before)
> > In the original proposal, Safes that stored 1 ETH over time were included. This restriction was removed since it again sets an arbitrary restriction. Instead, the number of tokens allocated will just consider the value stored over time, relatively.
> 
> https://forum.gnosis-safe.io/t/new-proposal-reworked-safe-distribution-for-users/594
> 
> It's preferred that no arbitrary restriction is set, otherwise some legit use cases are likely to get excluded or discredited.

I think this might hint to us that this original address created a) multiple addresses and b) over a short period of time. But again - this does not directly indicate that the address is a farmer. If, for example, this address is active or has only 2 Related Safe Addresses

**Comment by PulsarNetwork** [comment]
> 我是创建了两个安全地址，第一个我觉得它尾数不好我又创建了一个，到目前为止我只用一个进行多签安全存款，难道这也有错？

someone said:

"I did create 2 Safe addresses. I don't like the ending digits of the first one so I created another. Up till now I only used one of these Safes for transactions. How is it bad?"

and I have some hypothesized use cases for creating multiple Safes within a short time frame. 

(1) a fund manager creates Safes for multiple clients

(2) a DAO sets up multiple wallets. One for community funds, another for receiving investor payments, another for salaries, etc.

Please consider these valid use cases.

**Comment by 0xKARTOD** [comment]
> > 我是创建了两个安全地址，第一个我觉得它尾数不好我又创建了一个，到目前为止我只用一个进行多签安全存款，难道这也有错？
> 
> someone said:
> 
> "I did create 2 Safe addresses. I don't like the ending digits of the first one so I created another. Up till now I only used one of these Safes for transactions. How is it bad?"
> 
> and I have some hypothesized use cases for creating multiple Safes within a short time frame.
> 
> (1) a fund manager creates Safes for multiple clients
> 
> (2) a DAO sets up multiple wallets. One for community funds, another for receiving investor payments, another for salaries, etc.
> 
> Please consider these valid use cases.

Yeh, I see what u mean. Just because you have two addresses does not automatically include you as a farmer. All you get is a 5-point penalty, which is no big deal. As for DAO or manager - if these addresses were later active and made more than 3 transactions, there is also nothing wrong.

But with time, yes, I agree, there are several addresses that have 100 or more Safe addresses. Two of them we found are Tokemak and Staker. But as for the others, we have to do it manually and look for who owns these addresses.

**Comment by PulsarNetwork** [comment]
Thank you for your consideration. The point system can actually act as effective pre-filtering rules that help us identify suspicious wallets.

**Comment by 0xKARTOD** [comment]
> Thank you for your consideration. The point system can actually act as effective pre-filtering rules that help us identify suspicious wallets.

Yep, that make sense. Thanks for the feedback

**Comment by Sean20216** [comment]
@0xKARTOD I am aslo feel weird about Gnosis team did, even though they knew that it would result in a lot of invalid addresses and farmers get airdrop, they also decided to change the minimum number of txs made count from 3 to 1 and no minimum value required. What happened after this new proposal passed? farmers make money, hunters make money, real users get taxed.
I find ironic about the team decided to lower the airdrop threshold without being able to exculde ineligible addresses.The minimum number of airdrop tokens that were dropped from 400 to 100, and the remaining 300 were given to farmers and hunters. The team did not benefit anyone by lowering the airdrop threshold, they just approved [report](https://github.com/safe-global/safe-user-allocation-reports/issues/115) so you may be labeled as a sybil attacker even if you only use third-party dapps and not use it send transaction yet.

**Comment by Sean20216** [comment]
Is it possible to compensate for lowering the airdrop threshold by labeling ineligible addresses as sybil attackers?

**Comment by 0xKARTOD** [comment]
> Is it possible to compensate for lowering the airdrop threshold by labeling ineligible addresses as sybil attackers?

Do u mean addresses that have less that 5 or 3 or 2 transactions?

**Comment by Sean20216** [comment]
@0xKARTOD yep, you will see a large amount Sybil attackers which just the addresses have less 3 transactions finally. And these addresses Gnosis team should filter them by themselves, they are not Sybil attackers, but these addresses will be seen as attackers on other projects after this challenge done.

**Comment by 0xKARTOD** [comment]
> @0xKARTOD yep, you will see a large amount Sybil attackers which just the addresses have less 3 transactions finally. And these addresses Gnosis team should filter them by themselves, they are not Sybil attackers, but these addresses will be seen as attackers on other projects after this challenge done.

Of course, right now I'm trying to load all the Dune requests. This time I'm trying to focus on user activity - the biggest penalty is the lack of transactions - 50 points

**Comment by skydotone** [comment]
Listen, in the statistical community, we have different measures for outcomes, such as AUC, ROC ... 
In Safe Sbliy Attack Detection, you need to consider the confusion matrix, which is the probability of misclassifying a good guy as a bad guy and the probability of misclassifying a bad guy as a good guy.

I'm 100% sure that the address you've determined here must be wrong, 
You need to be more granular about the same type of address, you know?

**Comment by ww941019** [comment]
> 你的意思是只有6500个真实用户？多么愚蠢的提议杀死了大多数真正的用户

6500个是哪来的数据？

**Comment by stringStar** [comment]
That's stupid, if you want to catch a witch. Please show us the evidence of witches, which is not to exclude small capital users. If I only use your application once and become a witch, will I continue to use your system in the future? If you need to exclude users with small funds, you can directly let the official rules limit the number of uses. If you want to give a score. Please go to debank

**Comment by stringStar** [comment]
This score proposal cannot be used to screen witch accounts. Your score only indicates whether he is a high-quality user, not whether he is an Airdrop Farmer. Airdrop Farmers has only one standard to prove whether the account is related. Don't persecute normal users here

**Comment by PulsarNetwork** [comment]
> This score proposal cannot be used to screen witch accounts. Your score only indicates whether he is a high-quality user, not whether he is an Airdrop Farmer. Airdrop Farmers has only one standard to prove whether the account is related. Don't persecute normal users here

@stringStar don't worry. It's only for screening, not final decisions

**Comment by stringStar** [comment]
Also, your score evaluation looks ridiculous. All the reference indicators are imaginary, and there is no large amount of data reference. I haven't used safe. I saw this proposal on Twitter

**Comment by PulsarNetwork** [comment]
I still can't agree with identifying the current list of 500 addresses as sybils in https://dune.com/queries/1268823/2173773, even though I think many of them are suspicious. 

According to sybil hunting principles:

> Methodology that has a non-negligible chance of eliminating legitimate users will not be considered. When in doubt, we opt for “this is legit usage”

https://forum.gnosis-safe.io/t/community-challenge-identify-airdrop-farmers/847

Procedure justice means that once the rules are set, we should follow the rules. This ensures fairness and integrity of this sybil hunting community challenge.

**Comment by Wsyglsr** [comment]
I hate air investment hunters, but your rules really hurt ordinary users and new users.Can't a address be created 2 safe?You should give him a quota and normal users to avoid very expensive gasoline fees.

**Comment by hjg888** [comment]
Real and fake users can send an nft to https://galxe.com/ and require verification of Twitter, discord, and email address to receive nft. The created address of nft will be airdropped, and the addresses that cannot be received will not be given. That's it.
