### ISSUE TITLE
Gnonsis Safe Airdrop Farming Report by Jason

### ISSUE THREAD

**Issue by ahkek76** [safe-global/safe-user-allocation-reports#449]
# Related Safe Addresses

0xc2943d9bc16df11d0454daf4caffbd53a6fb0388
0xf241afed1ce84c267d6caf770299f1feb7c493cb
0x07f48b1a03e1169c15654a47d533a699041476bc
0xe6e8714f7764c44921e7abf01f566aa789686f45
0xbc825c3094436b00a2fff7576073c974772879ec
0x68acb1b8e33f812c6eab5dfc2cf8e5db5dfcf406
0x7a709470a9dafe7a3a67d11e6d867297bf8663f1
0xeeb8081bf0aa6002bf1c8281bd83818502f0ad83
0x0d9b5595b600c4adb496868d8b71ad77ad718ea2
0xf6d099d3f7f2e79187fa217b50ef11bd64d94cbd
0x9490167933fdbbcd7aa5b6b66f79e2ea42ddd6fb
0xbd7cd83ad7b9b37ec83d2761f1924ef6c71ccc11
0x6bc568adec8a41d63ba171c45915e2dfc9c1c198
0x81a17e70b728fe99df00672a14ada95aa1b934dd
0x8bdbed9f9604899f376072888d64505ff0f11597
0x0bbfc21124db443b7894ca02fbd7a70e3b41146d
0x4e3fe972d4b3d93a3ce8f576297529919e8ae129
0x9df36b57910dbe2023398b9880b077d0a93082c7
0xd03078756f74ee044dcec42fea37eb6c97f53755
0x410e6d8d6cee731cfa4949533b45c923829c71af
0x3bfd3afddf145e5ab6ba617ca31d5bf4846c75e8
0x353949accf605829d97a01dd6cfc39dabc81723d
0xecbf0bc1272b9ba9d0c0937f6068792325aef292
0xeae5e0d63285f24f3a089fdb6a0082ff6801eba1
0x1deafddfc62c7d6113204adff6fda8a2d2e55a69
0xadca2254b9b40a48ef44140482e912a03cbc7f5d
0x7c3d8bc495b7d2dcc995a3a0dc6444480483988c
0x30cd6df997d3c153624fcc560823a32e8886d69a

# Reasoning

1 of the airdrop farming technique is by creating multiple accounts and funding those accounts with a minimum or less than the amount of 0.05 ETH and doing some small transaction over.
Any user can create one or multiple safe wallets just by themselves and fund them with any amount of ETH. 
Users need to fund their ETH-safe wallet to cover ETH gas fees in doing transactions. 0.01 ETH or below is definitely not enough to do more than 1 transaction. 
Furthermore, no other activities by those 'dead safe wallets' can be counted as the account created by the farmer solely for airdrop purpose 

Let's keep the rule simple as an airdrop farmer. 
# Must hit criteria: 

1. Safe addresses created post GIP-29 announcement (Feb 9 2022 - August 18 2022)

2. Look for the SAME source address that funds MULTIPLE unique safe addresses AND has only the transfer (fund) transactions of less than 0.01 ETH on those unique safe addresses

![image](https://user-images.githubusercontent.com/112602432/190317278-fa1c5bca-3515-41a2-bd89-d546b43464cf.png)

3. No internal transaction at all EXCEPT safe proxy creation
![image](https://user-images.githubusercontent.com/112602432/190317331-43745e1b-820f-4ee7-b1b2-33d73b96c3c0.png)

Satisfying ALL our criteria above will confirm in spotting those airdrop farmers

# Methodology

Build out the query on Dune using gnosis_safe table
1. Find all safe wallets created between Feb 09 2022- Aug 18 2022
2. Filter out those who only have 1 activity on the safe wallet
3. Find the SAME source address that appeared MULTIPLE times to fund unique safe address of less than 0.05 ETH
4. Export to Excel and sort it by date, source wallet, and amount of ETH funding. 
5. Check one by one on etherscan to confirm the following:
- Only has transfer (funding <0.01 ETH) 
- No other internal transaction except proxy creation transactions
- Current amount left same with amount funding (meaning dead wallet with no transaction at all)

(Reason to use excel to sort out, more convenient and time-saving as Dune keep crashing in running queries)

# Result
[gnosis airdrop farmer finalized.xlsx](https://github.com/safe-global/safe-user-allocation-reports/files/9571998/gnosis.airdrop.farmer.finalized.xlsx)

# Safe Address
0x9D49CfE50Bf195f6823FDBF264182Ca436672a52

**Comment by ahkek76** [comment]
The dune queries
https://dune.com/queries/1260967?d=4

**Comment by tschubotz** [comment]
> # Safe Address
> 0x9D49CfE50Bf195f6823FDBF264182Ca436672a52

That's no a Safe address. Please provide an address of a Gnosis Safe.

**Comment by ahkek76** [comment]
here 
0xd42ccAa658d460b5DfBCEe6bbbeAF1B6667a30F1

**Comment by ahkek76** [comment]
here 
0x5d74D4F393BF74C5b5EA689c619fbC9A1deab4dD

**Comment by ahkek76** [comment]
> > # Safe Address
> > 0x9D49CfE50Bf195f6823FDBF264182Ca436672a52
> 
> That's no a Safe address. Please provide an address of a Gnosis Safe.

here
0x5d74D4F393BF74C5b5EA689c619fbC9A1deab4dD

**Comment by tschubotz** [comment]
Thanks for the report. Some of the Safes have been found by another report already. However we still found the following to be related to airdrop farming:

```
0xf241afed1ce84c267d6caf770299f1feb7c493cb
0x07f48b1a03e1169c15654a47d533a699041476bc
0xe6e8714f7764c44921e7abf01f566aa789686f45
0xbc825c3094436b00a2fff7576073c974772879ec
0x68acb1b8e33f812c6eab5dfc2cf8e5db5dfcf406
0x7a709470a9dafe7a3a67d11e6d867297bf8663f1
0xeeb8081bf0aa6002bf1c8281bd83818502f0ad83
0x0d9b5595b600c4adb496868d8b71ad77ad718ea2
0xf6d099d3f7f2e79187fa217b50ef11bd64d94cbd
0x9490167933fdbbcd7aa5b6b66f79e2ea42ddd6fb
0x6bc568adec8a41d63ba171c45915e2dfc9c1c198
0x81a17e70b728fe99df00672a14ada95aa1b934dd
0x8bdbed9f9604899f376072888d64505ff0f11597
0x0bbfc21124db443b7894ca02fbd7a70e3b41146d
0x410e6d8d6cee731cfa4949533b45c923829c71af
0x3bfd3afddf145e5ab6ba617ca31d5bf4846c75e8
0x353949accf605829d97a01dd6cfc39dabc81723d
0xecbf0bc1272b9ba9d0c0937f6068792325aef292
```
