### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by rick-best** [safe-global/safe-user-allocation-reports#45]
Example:
0x0b1937f6ee406ca9e44dd99035da38840c242a9d
0xd5521ec73340df8522f47ecfed7324405d9312d5
0x71c4fa6a4fb81f67b670b06ddc44de24ed7f5326
0x7f405cf888cd86b6ddf239b6e800fe041c9bbc32
0x354044d39f1e31109ecab3407b99b2ad5ed6515d
0xa4caccef0dd28212b2aff92443bd560ba83ff428
0x1d19da85322c5f14201be546c326e0e6f521b6e6
0x992fb4f41663388cc611e8ef25e714a1541e456f
0x738c5dbca9f2d022174c7abf99da5bec001fc54d
0xcce0e1ab3ad9a9935a8b6814a337afe96b87b759
0x1b3dff537b7d46a0d30b1d20b101c483586747aa
0xad05b50b71d1c05e3309e9f99e633a21741b77d9
0x2b5ef7f8d42feb86ba3d4eec6e325ec314105f29
0x3f0c713b4e3fc2f56cfdbfcac0b45c927045a833
0x1fd8a6cf3ff837799d7416af511249df06fa3399
0x713996bb0e138f3b72f67baa9dc162dcccae132f
0x044504d5b1e4a2fe9822f290cfb836c82db1995a
0x082b9b776e5d0b1771594676d12619f479b0a69c
0x950a0be4d5e7c63017debfae67ada866b55e7335
0x659a88d1fc5065126a90ebf908379db1d5c94e37
0x0b1937f6ee406ca9e44dd99035da38840c242a9d(https://arbiscan.io/tx/0x72ff8af64a4bab6afbb75da52fc8925bacc71420a5eb8f5b821b557bf508b277)
0xd5521ec73340df8522f47ecfed7324405d9312d5(https://arbiscan.io/tx/0x2fb94e1fc7f091534dc7ccabef348fe128b6779c880ea52fc59f3c596ba54a43)
0x71c4fa6a4fb81f67b670b06ddc44de24ed7f5326(https://arbiscan.io/tx/0xfa9bb83430e75dfdc3c54133a8a5c6b831ed4b54cde8d58f67769be6ffad07bc)
0x7f405cf888cd86b6ddf239b6e800fe041c9bbc32(https://arbiscan.io/tx/0xd4cf2efab465f3ed3d8228e6f417e3506cfcdcf41e50e511eb2a96b315c344b2)
0x354044d39f1e31109ecab3407b99b2ad5ed6515d(https://arbiscan.io/tx/0x9e346bad526e1319ae27831be301a12ca180629c8471eb2affb10a462fda9167)
0xa4caccef0dd28212b2aff92443bd560ba83ff428(https://arbiscan.io/tx/0x0bf2ea5c17a99b5b34cd0ca84c979d53284cd09c6b74fd197a75a01147d9636c)
0x1d19da85322c5f14201be546c326e0e6f521b6e6(https://arbiscan.io/tx/0x08bba579ab29f5124a7a2588cb117862ac69e5bedd4a40cb266a255bbe2e6fcf)
0x992fb4f41663388cc611e8ef25e714a1541e456f(https://arbiscan.io/tx/0x85b069d0c9436c0fd41447d3b019b388ac62b70ee6f2c4419074d105f8756e97)
0x738c5dbca9f2d022174c7abf99da5bec001fc54d(https://arbiscan.io/tx/0xc225a4c37f6a6b82a3a51f71ae87705f8fc32348811b9a659e9c244c3c2c7f7c)
0xcce0e1ab3ad9a9935a8b6814a337afe96b87b759(https://arbiscan.io/tx/0xf2c7c15c5fe44d339d89a8f29a539077d03dfef8ed0a015ac8b1198ba584e667)
0x1b3dff537b7d46a0d30b1d20b101c483586747aa(https://arbiscan.io/tx/0xe5def2c3e2595b350220df228e1ce1a3d3915e44a8a4394d7e6a0b795a33d019)
0xad05b50b71d1c05e3309e9f99e633a21741b77d9(https://arbiscan.io/tx/0xfe2553a056ebcc31cc5eddc81a7b2ae219a6f2d472e827568151425980c84570)
0x2b5ef7f8d42feb86ba3d4eec6e325ec314105f29(https://arbiscan.io/tx/0x3fa5b8c7f96f04cdd1e6d691f1bc3e570bbb5c3e63fa037175a2ec75e2877c7e)
0x3f0c713b4e3fc2f56cfdbfcac0b45c927045a833(https://arbiscan.io/tx/0x5d31d43b03b3e7846c6427bdfe402cf73d2b7a63e32310b1c6f2e6f70971821b)
0x1fd8a6cf3ff837799d7416af511249df06fa3399(https://arbiscan.io/tx/0x155d3d9a9eb2e390da3afcbb26f66a64baf40ccd09843930ac431895a60d3c19)
0x713996bb0e138f3b72f67baa9dc162dcccae132f(https://arbiscan.io/tx/0xd26b7c3ba5962d2d5b29f10f577185031084dc5d70745e5048d4104938fd17c7)
0x044504d5b1e4a2fe9822f290cfb836c82db1995a(https://arbiscan.io/tx/0x5dea1a67895be989634df43a68211f8bc5d02e1c6be00f5171f7a5df0f223f57)
0x082b9b776e5d0b1771594676d12619f479b0a69c(https://arbiscan.io/tx/0xc22996c8ac522a3e806d222ce4f2b17497e1b8d1a6ea95d5a7e5080a81e424c8)
0x950a0be4d5e7c63017debfae67ada866b55e7335(https://arbiscan.io/tx/0xe39b8d927e72405cd4d3822a3bdd83ad4a4f3ca8df24c66fdada470618a4a23a)
0x659a88d1fc5065126a90ebf908379db1d5c94e37(https://arbiscan.io/tx/0xa3704d2d1b9121f4727596485509a7264bb66430e31f2ca5320bc4ddb05a36f5)

All addresses farmed [Galaxy OAT (OAT)](https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95) around 2022-04 for GAL airdrop.

Tx details:
0x0b1937f6ee406ca9e44dd99035da38840c242a9d(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x0b1937f6ee406ca9e44dd99035da38840c242a9d)
0xd5521ec73340df8522f47ecfed7324405d9312d5(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0xd5521ec73340df8522f47ecfed7324405d9312d5)
0x71c4fa6a4fb81f67b670b06ddc44de24ed7f5326(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x71c4fa6a4fb81f67b670b06ddc44de24ed7f5326)
0x7f405cf888cd86b6ddf239b6e800fe041c9bbc32(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x7f405cf888cd86b6ddf239b6e800fe041c9bbc32)
0x354044d39f1e31109ecab3407b99b2ad5ed6515d(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x354044d39f1e31109ecab3407b99b2ad5ed6515d)
0xa4caccef0dd28212b2aff92443bd560ba83ff428(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0xa4caccef0dd28212b2aff92443bd560ba83ff428)
0x1d19da85322c5f14201be546c326e0e6f521b6e6(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x1d19da85322c5f14201be546c326e0e6f521b6e6)
0x992fb4f41663388cc611e8ef25e714a1541e456f(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x992fb4f41663388cc611e8ef25e714a1541e456f)
0x738c5dbca9f2d022174c7abf99da5bec001fc54d(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x738c5dbca9f2d022174c7abf99da5bec001fc54d)
0xcce0e1ab3ad9a9935a8b6814a337afe96b87b759(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0xcce0e1ab3ad9a9935a8b6814a337afe96b87b759)
0x1b3dff537b7d46a0d30b1d20b101c483586747aa(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x1b3dff537b7d46a0d30b1d20b101c483586747aa)
0xad05b50b71d1c05e3309e9f99e633a21741b77d9(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0xad05b50b71d1c05e3309e9f99e633a21741b77d9)
0x2b5ef7f8d42feb86ba3d4eec6e325ec314105f29(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x2b5ef7f8d42feb86ba3d4eec6e325ec314105f29)
0x3f0c713b4e3fc2f56cfdbfcac0b45c927045a833(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x3f0c713b4e3fc2f56cfdbfcac0b45c927045a833)
0x1fd8a6cf3ff837799d7416af511249df06fa3399(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x1fd8a6cf3ff837799d7416af511249df06fa3399)
0x713996bb0e138f3b72f67baa9dc162dcccae132f(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x713996bb0e138f3b72f67baa9dc162dcccae132f)
0x044504d5b1e4a2fe9822f290cfb836c82db1995a(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x044504d5b1e4a2fe9822f290cfb836c82db1995a)
0x082b9b776e5d0b1771594676d12619f479b0a69c(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x082b9b776e5d0b1771594676d12619f479b0a69c)
0x950a0be4d5e7c63017debfae67ada866b55e7335(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x950a0be4d5e7c63017debfae67ada866b55e7335)
0x659a88d1fc5065126a90ebf908379db1d5c94e37(https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0x659a88d1fc5065126a90ebf908379db1d5c94e37)

# Methodology
These addresses were found in the hop witch and have a high similarity in the operations in time

The address tx corresponds to the contract address of the airdrop
0x0b1937f6ee406ca9e44dd99035da38840c242a9d=>0x7f5d3c1fe1c73d3e4c44cc38eafa731b6e61e6c44b73ee1e78b2a3f4cff9daf1
0xd5521ec73340df8522f47ecfed7324405d9312d5=> 0x567bf4db20b04c1309562e3b5d3b1140a163d3e6616df4854dd8f6e287bba934
0x7f405cf888cd86b6ddf239b6e800fe041c9bbc32 => 0xb1db464bc22c9c4c701fd35ccbf44bfb15fac05249d3c30bf23320c7aedee212
0x354044d39f1e31109ecab3407b99b2ad5ed6515d=>0x97267da01ba29558d831f2448b42ae719f9b2218a550d1871c9f01b633b1a287
0xa4caccef0dd28212b2aff92443bd560ba83ff428=>0xfad64f2ba94da7f99d9450cfd9f76c9a20ce8a2b14187b1f5fc7de0a1477ec95
0x1d19da85322c5f14201be546c326e0e6f521b6e6=>0x9fac1de819e80acb8669a5d657466ed4d33884ecf0a3934b6d650e800d403544
0x992fb4f41663388cc611e8ef25e714a1541e456f=>0x712b3bfca7b683336fb21d2224f2eebc0ac7375d893e9a15915a9fb7f4e152ee
0x738c5dbca9f2d022174c7abf99da5bec001fc54d=>0xf849305691425f23fa4332b88c7ce1e3eb8bcf53f559c83c86e216ac4bab1728
0xcce0e1ab3ad9a9935a8b6814a337afe96b87b759=>0x9dfcef9ed17e4ef26ba85c86eeec3cac671c5355c7cd4ce3c4938bb4ab7556d4
0x1b3dff537b7d46a0d30b1d20b101c483586747aa=>0x32ceecf33a7d53081f2573a607c4dba910d6e3d229cb67a31a475cbf1fba32db
0xad05b50b71d1c05e3309e9f99e633a21741b77d9=>0x29ec07081671243873e5db02445781cf878694ad7668faf05a54f388ff6df1e7
0x2b5ef7f8d42feb86ba3d4eec6e325ec314105f29=>0xe3e39c16a3d6d0fec77c4da9e57d4e1483517054cad91d1aeeb3f9470fda6d51
0x1fd8a6cf3ff837799d7416af511249df06fa3399=>0xbe197f886764a6cb4e353fcad877c6901b3b800a01ec1b8dfcaaeb09365fb62e
0x082b9b776e5d0b1771594676d12619f479b0a69c=>0x3aa571acb49e3f2b2568dfff525819b1964fb0ed95dd6802041b8eece173203d
0x950a0be4d5e7c63017debfae67ada866b55e7335=>0xabbe0dd689eead0dd126326ffdd7d8734ef0df6b33fe2551bd3a4809a01c2b42
0x659a88d1fc5065126a90ebf908379db1d5c94e37=>0x8bcd9e03ea503f3d037959e1d31f6c4a725305bf91b5924e8a1fb915e9ac7122

# Safe Address

Example:
`0xb3AA154D7a6D26b3A3275f7281BA9570ce8cf33E`
-->

**Comment by tschubotz** [comment]
I checked the first 3 addresses.
```
0x0b1937f6ee406ca9e44dd99035da38840c242a9d
0xd5521ec73340df8522f47ecfed7324405d9312d5
0x71c4fa6a4fb81f67b670b06ddc44de24ed7f5326
```

None of them are Safes, so I'm assuming the others aren't either. Hence closing this report since it's about Safes, cf. https://forum.gnosis-safe.io/t/community-challenge-identify-airdrop-farmers/847
