### ISSUE TITLE
Airdrop Farming Report

### ISSUE THREAD

**Issue by yaoydong** [safe-global/safe-user-allocation-reports#450]
# Related Safe Addresses

0x72a16a01f04942dc323cbdc39503b9751c69408d
0xe6b204c2c65517467c9761b4dd8b29b38143dad5
0x6cc58768f31317ade77ff5d64be15a34fcd72acf
0x9015cb88e98accde420eebfa6582b2f4c55fb22e
0xc5628bb6c1d8663fc853e42a2eef5c4f8df894a7
0x335b1fb970c0edb5952e2c08efbbd945c4523c42
0x8fffaec3b4c3eb69b144d541ec59677572a1957c
0xc3c867d12cd1e2f8cb18c250d8d635d19a78b311
0x46ccd2808fa9c56e26e7dc045522871080a0f9fc
0x87df8d98a843d8b7047bc2d1b74476d7a5a9e264
0xf5136db6db09f009cb6bcd273d9bd18f3de6b740
0xb6e55627572506756ba2a86d8214ac59e9e7edea
0x4d736ba35a602891af476e7dba877f144ecfc1be
0x66b67c4eba388bac86bfafcad2989ad0a2674506
0x7af3daa93ecfc89f367f7d082692d2d21bf420bb
0x034ff617c5daf5eb85a2014b3fd476fc4bb216a6
0xef1ec9e35f841627aa52024f282f3a4d4f7cb7f3
0x0e6de3dd5b1b68fae358bb0fa2e9c4689de6c452
0xd73885a166e7f9cca6b592ef2fa7f9f970092cd5
0xe12369dfd61a12f3ecdb9333358085dd770b2bf6
0x3d3718a02a93c4647fed9699911fb0b028a30a1e
0x8bed7ac1cd73c5fe3da6c90e8e9dcc0d5ad5783f
0xd2482a0bca4c96cf4799b78fb5430aad1e75f866
0x38a21f4b53d0365fb49a693b5d2a52c3a5ee7738
0x672a7aa6b905dab3e1e1a57e842850f0da4b6448
0xfdb59373fcfc09e7351294677b5025dc9423c38e
0x33ccb273e607e4a2d02166638116c6a570382e28
0xb4959ae6be5f594252a0c177fe50fee1dbe8171f
0xfb7d6ecbaeda97d2402f8357dadb2183d5e86f56
0x7e6c46d1a3fe2bc3414f65b81626174b9b873dd5
0x713d22c682d42480953c685f901795df7e2985df
0x74c041e9254289a443702850711b1f18f33559b7
0x8fe5f2e15cd638cb7f15062b8e6230126817ab5f
0x78d87a824154bbc408067ca7db3f5ed3615e4d14
0x67c72a01e326a7ec84681d37539f82287f35551f
0x7854e996686edca87933f3247e74353d8691bada
0x96203bd3267d6367ad061c44b99184d10943a95c
0x517525224f0df062d3b59fb6b183abf8a32f087b
0x009c840544c81e34e0fedfe3861e3d563b5ec017
0xe96bfb63003c75447c590beeab65b036d10f4032
0xf6d925ae45f2e4ae6930f51cd1cf9feb368a85f3
0xab541cac2d756aa75c6e8d304c844c4358323cc5
0x061cb949cd83b9af26d36b386cd62a1633be28fa
0x29c9d60b15125ecf567078f91ee677d91c79518d
0xc9dc1ee10e34e02d726a5ac1f329b91d9b3b4973
0x818550927eb22e357784977760d6fb6559ae5783
0x267707c94828b2e91a0a32d012bb845c2314d94c
0x43854a4a41b635cfe78c6deac467805cc7ea9b55
0x16bf41363e4bec54bec2c66f4df365b93a76d0ac
0x794fa4aed2e09d2d30a51a88024ccb7b547cbd59
0x2db27822d2ba158552b3f6d0d9ed0589d2423eb8
0x5237e14b9d4ee03746baafefd0c82a8bce65ddc3
0xcfaeb80a7db360a7dceb148e2ad5f8337b730399
0x3d8c20120f73a6216904f6fefab93e7902a73bf1
0x1c95139a844259f2553f9b2b637bc40cf75326df
0xcb694d29b94d2fc3cbb76fa6e5bf99a73479b3ea
0x6d205207c148705775607a5e7696ddd605a6c79c
0xa62b8af6091517faf09363b451afdcc4e11e9a11
0x981c405bf5b0d5453b4a739101504d57d5672554
0x1927a8d9074276c9e54130fba01356896c9e181b
0xf3cdf8cc182963bee5b8a244a4545007e971c345
0x81b7de9df1ffe8db00b9a30622eb005813fe28cf
0x106025de1880265cb1962f0da20ef1eae56a8b64
0x0af5f6038fe7abe4c3324517cecf5f652001f0ba
0xd38fbadcbedd5907baeef46bdc5fd87dbf7896b5
0xdd3b0d759e6f51a5dedfaeb3d16a717fc59c218c
0xbf31151562e507d17138f73a58c4eee927a10e82
0xa78f1f5698f8d345a14d7323745c6c56fb8227f0
0x90d99570593a2e5b84393d2856cd1e1e36a9ad45
0x504a9c37794a2341f4861bf0a44e8d4016df8cf2
0x39a6e3110007c363bccbb26c28b54dfafd747c0c
0x5a34e0a8a94841d882c8866165a985a776ef3472
0x15a1429a08d94d148f6d20fada088914c65f05b1
0xd7b05850ba22a3f3ad5c491f7274c8604131583d
0x84649485845656f30c4691dbd92c778b5afbec92
0x6d07c3c16db5da0038cf0b2e24c9f4ae97e5e1b8
0x1d2a4c959adc6485861e7fd7899937345be51c70
0x0683d3846f082fbb6a6a20ab80c4f4eb101869d8
0x8251f63e8dbca5a36d410f346642b42131a425d9
0x16b52484a61b2d7782c3b75090c47545c00be52c
0xc1c4017a5f0c84c2b1fd71b590a5d2155120fa14
0x268b2d03ea1054e4f14356d005b7ce138ebf229f
0xe6953bca7923db05da362a95954335d59c65ea60
0x4d1efd469cc64b0d9e9240fee740667ec66c7747
0x18e7088eaf3f6421e12ed8ef1ca48b20ced17981
0xbf64505112c4ffc7299e70f9f10de68c60eeabc9
0x7e2ad0bf320383f2fade494235108ed9fbd85c1f
0x3b2dc435d6f6bde990eda7f8df260ca46759dd29
0xbbf0f62e4806a5e7432ea8e4504c4e98e0333492
0xd66a930d7f5c9501973ecbcc0a7f52743c5b00ae
0xd66084e347db7b853771bc2191300cec457e9ab7
0x1330d374dad46d7343816ee8a627538dbe160bfb
0xf24abff471a1bf1603fddbe3e15ff11fed2c796d
0x82ca20d0423e8b7bd8137639f5dca72d1d47231c
0xfe3030ee66756f40fcc9873539feee1ea1d7e1e1
0x550551ca436ae78a890cdc60320b53ea84b82250
0xa664693d89b7086e9f7a4299e3b9cae74b54a313
0x47d47e1486c2a6dbf0c82c4cf9b78d3c9e5f28f3
0x81185b28fc504ab63c375fd2b4f07fbafd94b323
0x4bd595642e3d500d45188c3f62720f17d3440ce8
0xee1a424b8310f50ab7b93fe4fbfa554ea06995d2
0x333dc285fccfaf28d55b257de112206f84ce5b2d
0x731655e58d4d8a504d8553db28b2fcda4a69de82
0xd7431d87ac9303c8e3336cf8620c2f6c75bc9372
0xc674b5f3d1b78549daebcc8673d8b74c27d08713
0x6b6ef11c8ce7320a9c5584c2dc5c2d5e5b5cd0bf
0x961e49cb52cc65f3d6d4d1227cb039bd34a920a8
0x53f80a64e17c9b8ee302794a0c402dd9ecc75972
0x4d966cab2811ed6613c3ede35f9b9a413c564e7a
0xf823bf8a01b1413759857c8815e382db0f7668f1
0x7111b5264cf0ca4d0b94d77a834d339e42870b28
0x0654dab395fc4eae96e64a1d3094258096b190ce
0xf9d67ee9cbdc848220e376a6a0594c3ed7cc5372
0xc1881e18793fa508bed0f880cb44c007e89717ab
0x2396c22ed5718984573fda3f1a37e785e0485fa9
0xa048077e1df9f717f47841add0cee61fb33d131e
0x6fba407193003ed3f1df4c7c3283f928e33ef3ac
0x0aa90f757c45194441a5b90a0ec7825bd30014a1
0x73c38b5dacdf9ae5685076e19614eca714abd25f
0x2f6cd5452878891e4d85bc0dd81c78720b251570
0xc84dbb2da739e29a97e11169e0e2c0ceda0a0404
0xffd08abdf1413a2b2e63a33ede47aa49de684253
0xdd5cf359156b394660d24f65486f3f88072c066d
0x7786438f73f0b9cabc5afaa95c2253037cb143d5
0x4ae8a002d0e1a400d41dace88eb1ff11ea2a1cdf
0x16253f63c383cd5fa9063b5475e4fbec63a8dffa
0xc4be994d5748008e5af8491906d19a44d425c618
0xff488bccdd18425a8de134be5779e4991a781927
0xec43d1f4bcdf98fb527216238d57e8b2b7db9a6c
0x2a90e608299d057f842bbe450a39a2e862c874eb
0x59b72ed11a160c20af39dadb53a3d1d6e0bd136a
0xbf346f01a9bb0572e9681c982a21133500961fcf
0x10f2886f691bc60bad33c7b8c1f8da14c6807f0a
0x767ce2a942b56565fcb292624ad867ce8d4024a2
0x521cf3d673f4b2025be0bdb03d6410b111cd17d5
0xa3fb684308d31091e73b072efec3f3ec6f245342
0x17ebe01c86c8824f2345cc6a23772e35915f7523
0x47ab24b4b400365ff693c63487fbb6d3560bdde1
0x6c17c4aa30587499506c405475665b500702d422
0x52033e1f448c69ed6addcebf47f9a5836df6395d
0xee7886c12983d315743017a3e0b23bb65ac1d370
0x2032883170f010d5699a5288ae6aafffa50da156
0x0027a3105733dd5f01defc0a3680365f361dc762
0x85a0dd12a535fb5992600b3e96294992508b955a
0x237f8788134e61f96cb9cbcd754d2d296e5ce289
0x1387225c4f8a8edb6b87462cc99348cfba87a8fa
0xdfa363b48db93402a8658e3b129d42ac0a8f7b88
0x6b82cc2257b92958cbedb2f08192cc6f528972d1
0x104d34e3ffcf14fa544db8823c5efb27e47b29a1
0xcf711ee098373dcd869c98d495bfdb52f91c3f66
0x4bb8527bad8989b424c3069240e224ddcf66f767
0x84775e84fb46c25f4ebf444bbae31bc900f624b4
0xf62517b4f58b31bc554ab0234c333fc094d59203
0x22d2acb788edbc8141d175dd72a4715dbe7d23a0
0x2b5236de89f9ed6380cd3a69dcdd00cc7020285d
0x8efbec90906cb4a98871ee6a35e820ad55f36458
0x8e256b4dcbba825127099075e39bbcc14d792c7a
0x56585fb217f6309499473753b7a4e20d72698741
0x5d23061f330c045755ab7f7572e13f5da463d8d5
0x118934d9589382ef4d72db3208ed92c8104e8a60
0x574e2703fb199a59e2067461e442ae61b365e83e
0x070ec4884edace3b972fcc48fc564c4f53183637
0x95548bab4c79389de01fdc151a8f0516e25c75b1
0x323aff9163300320a9f1f5b0201ae76b6930a2f1
0xdccac3f64dbc37114f6d21fdeb3d800d6e51b466
0xaf865694570db2f4677a2b6f291027944ac9e3b1
0x2da54b40c7ebf754472f0227eac8656d647c8be6
0x8fac1220e11badf0e47ebfcb723080ada3be4634
0x5bab8b88dddfcc3f218a0549eccf6f21e9f3357b
0xa5351d6dbc41389d179a1a856f2591f113ede931
0x9135ba4c48209b14864963b61ee8609f89733583
0xc7e69da60f139afda7e38f30d9bb8430ebb038ba
0xb49a09a7deac0f3a295205478bf8a600fd81d20d
0x47329a2784acd6d022a51a3c8172841369a98e3a
0xdfffb256fbf2fbd9a132f5bf94d98e4eb8da836d
0xf2c52772028c9a14f871c508ef204e52319a39e0
0xe83867033ac19d27ffd062936b267d748a0c8594
0xccbf6d247d59685cbe950700712f84d30f5e3f65
0xfba7fa6ebb34d5949718761532e2c47c4cea3e48
0x884b9bd7d609f4f97f8ebbcf3e2aefc1d6cfa434
0x3e3e2f9480aa23d0c37ad74303daa97d264acadb
0x2c048f227950289567d8e0d55f3ddbe1dd7c4e22
0x5568b54da0be52da6189c587fbe71a215420d0a1
0x931100706c81269cd13ed9d481de5e1777279a8e
0x1d57e23fd5bbb9d4ca61eee6bde62fa274ab0e71
0x5039c7f3a02ce4c9dadc5b129a02d690254512cd
0xfe2e4e67ebe528b31b6defae846ac539262aca13
0x029600237cfd4d579cca414655a2eef63a9e7e7f
0xe96bdb514b0d85e49a70443991fc412863b658a2
0xe733cd5c2427eba1092be9574b2ab1529cf5701c
0x4816fae09fdfaf6927e785efe68e5d68f5740840
0xc6411f700f5b75a9f298d8f436666af88804ff4d
0x429dfd011cf3549a2569159266714a66f49c4c4d

# Reasoning

I think SixDegreeDev provided a good method in #427 ,but there must have some farms even before the "GIP-29: Spin-off safeDAO and launch SAFE Token", so I modified the rule as below:

1. Safe accounts created before 2022/02/102. 
2. Total transaction counts more than 1 but less than 303. 
3. All interactions with a Safe wallet are from the same account4. 
4. Interaction in a very short period of time (All TX in 6 hours since wallet account setup)
5. Current token balances of the Safe account are less than 0.026. 

after this ,I Got 415 safes.  after that ,I checked this safes with the rule: there are a same wallet who created this safe and execed transactions with this safe（That means: one wallet created a safe and the safe was execed transactions only with the wallet）

after that, I got 193 safes as above.

# Methodology

Firstly, we establish a database containing the $Safe airdrop addresses on Dune. Then we extract suspicious accounts that satisfy all types of behavior at the same time from this database.
In other words, an account created before 2022/02/10, having few(5-20) transactions with only one account in a short time(6 hours), leaving no money(<0.02) now, sharing same owners with several(>10) brother/sister accounts from a same parent account(creator) , is most likely to be an airdrop farmer's account.
Furthermore, we track not only ERC20 tokens, but also NFTs, in order not to mistakenly hurt real users.
Based on that, an algorithm was used to identify potential airdrop farmers' accounts. The details of algorithm can be found in the query listed below. All the numeric parts in our method are set as parameters to dynamically modify our strategy. Just simply input the rational parameters and run the query.

Dune link: https://dune.com/queries/1272695

here we can get 415 safes.

after that, I checked with python code below:

<img width="1026" alt="WX20220915-153422@2x" src="https://user-images.githubusercontent.com/33407242/190343625-eebcb5d1-be51-445e-a891-5a1c8ddb754e.png">

# Safe Address

0xfdf11fa8ae68ddb3ff2b9138a517e6518f2e8796

**Comment by yaoydong** [comment]
update rules:

1.Safe accounts created before 2022/02/102.
2.Total transaction counts more than 1 but less than 30.
3.All interactions with a Safe wallet are from the same account
4.Interaction in a very short period of time (All TX in 6 hours since wallet account setup)
5.Current token balances of the Safe account are less than 0.02.

**Comment by yaoydong** [comment]
and 415 safes info as this file:
[415.txt](https://github.com/safe-global/safe-user-allocation-reports/files/9605171/415.txt)

**Comment by yaoydong** [comment]
Add a note:
1. transfer in
<img width="1290" alt="WX20220920-164457@2x" src="https://user-images.githubusercontent.com/33407242/191212416-90e28ec8-59da-4f90-b9ee-1cc7e73fbea1.png">

3. exec transaction and transfer out
<img width="1206" alt="WX20220920-164520@2x" src="https://user-images.githubusercontent.com/33407242/191212446-20ce27b3-fb2a-4b47-bf85-903cf231b59b.png">

**Comment by tschubotz** [comment]
> # Reasoning
> I think SixDegreeDev provided a good method in #427 ,but there must have some farms even before the "GIP-29: Spin-off safeDAO and launch SAFE Token", so I modified the rule as below:
> 
> 1. Safe accounts created before 2022/02/102.
> 2. Total transaction counts more than 1 but less than 303.
> 3. All interactions with a Safe wallet are from the same account4.
> 4. Interaction in a very short period of time (All TX in 6 hours since wallet account setup)
> 5. Current token balances of the Safe account are less than 0.026.
> 
> after this ,I Got 415 safes. after that ,I checked this safes with the rule: there are a same wallet who created this safe and execed transactions with this safe（That means: one wallet created a safe and the safe was execed transactions only with the wallet）
> 
> after that, I got 193 safes as above.

e.g. checking this Safe: https://gnosis-safe.io/app/eth:0xe83867033ac19d27ffd062936b267d748a0c8594/transactions/history
Seems like it doesn't fit to your restrictions. It stores a significant amount of USDC and has made txs during a longer period than 6h.

Also you say that one indicator for airdrop farming has less than 303 tx? So e.g. 300 txs seems to be airdrop farming? That doesn't sound reasonable.

There is quite high chance we would eliminate legit users with your list.

**Comment by yaoydong** [comment]
Dear @tschubotz 

I'm sorry that I made two mistakes: 1. The deadline in the dune program was written incorrectly, resulting in the generation of unqualified addresses; 2. The serial numbers written in advance in the instructions are merged into the previous line after automatic typesetting.


I have made changes:

1、The description text above has been updated;
<img width="968" alt="WX20220920-191732@2x" src="https://user-images.githubusercontent.com/33407242/191249428-19761433-c163-4330-b9a8-5320d55a4d0a.png">

2、The DUNE program has been modified and rerun. The new DUNE address is https://dune.com/queries/1287862  See the following file for new operation results:
[safe.xlsx](https://github.com/safe-global/safe-user-allocation-reports/files/9607327/safe.xlsx)

and the final address are:
[safelist.txt](https://github.com/safe-global/safe-user-allocation-reports/files/9607331/safelist.txt)


I would like to ask if you can take another look at whether the materials currently submitted are acceptable. 

Thank you very much
