### ISSUE TITLE
Airdrop Farming Report

### ISSUE THREAD

**Issue by Timiwss** [safe-global/safe-user-allocation-reports#452]
# Related Safe Addresses
0x8adc75aa643cd5d804bab300a2d5becd9a9e6b8b
0x84443f61efc60d10da9f9a2398980cd5748394bb
0x113e304d9bd13ec54929399e265d8ec723c4bbe3
0x1260af8fdbe715bcfc13b257404c07327a600819
0xf029f8f3265e77ef6e6eb71511145c5c6ba5d39d
0x209584d708633dff4c6a4d7359525bbe26d07333
0x83640976768d490f8456f50456b383a320f0baf9
0xa9d04e8b992248834a06e61e4d8602e3434ece37
0xd55929ff0f0d9e30a158baca29cd10300adca839
0x4b435b57ab0aa32f169aba415122a4a981dad2a1
0x52ca5a12c80633c6cac0504a6007a760ad9c3ff9
0x8700c81883b46922d4a9bc1edea0b77337ec0eb1
0xd2e4f9136490d6cb48eb64ceaf1c6fa165f4d2c7
0xc2890a210b1f4f7248dfb57491512bd21c53a9cf
0xdd282d17b0b2c282e4e83f2b7747017f852be4ff
0x0c5095a8837e633312d897b9f51535c5161c8b71
0x1eaa6365c625b09ef45c3b8a6f2aab43376e531f
0x9d65822e35310342294afb07f5a32347db890fed
0x292bacf82268e143f5195af6928693699e31f911
0xeecaca98f3d4851092e7089d922c61f1feadb843
0x7589b95b1c732d06d134381f16650fef4e03a1b9
0x27d530b25f13996e9c77135e361eb8bf73759d63
0x5aea111f6f1e65ffc4d3b31f3320405d3f294f05
0x436ab15705e0ed23284512770748770ee4c16155
0xc0495a7bd160c1aa2a71f9e16891079c7a9de747
0xf5668fbc7378bcc5a6f0795d7e9b5e5c3b4f7215
0xc133439da7da854f84f25685d2191464ecd3d21b
0x89b311f344ccddc54c2f7258f6e84a54390cdb89
0x9f10dbe6f9419f73117483503116105d2c7b2c15
0xbe0fa187c0d25eb1ccc4a482912d30f66565101b
0x94ddea50b0b0846d6a65404a9bd9547ee7995989
0xd67fdeeb0dea8693aac0c04efee0786c31b90cb1
0x5a1bc518e8d34979479aa9c48cc3e3c062248fa7
0x1adf825f650938a6a93f899d347f3d2cd073dc29
0xb0cf84945f0d8c7535e787c5dfbb4cfa5a672baf
0x9fefd869afc9e88aec611a2f5a0510a1be578f1b
0xbc2f73492bed65351b319ccb6fe66a8485a1cb03
0xa89f55b203e289af2c7b13dd1085ff31d3178371
0x2bfd56b4742a63778cc5c034655d5275f0c5e7e1
0xda2d6f7062e8703c79145fa16f7f9f52980c2e77
0x7ab3057b217dedaba453dab9d0b95b5803250007
0xdb4a1a616e2cc782911ec19cdb5651647f8111c9
0x6e68b398924e3da3d29714feefb82400f9993cc7
0x98a168e8ae8141e505d7d4bb9c47ba3eb1fa8e57
0x23cce7a20f4d012424253b5433576e2dd943330f
0xd8bba4d0d953fedd3dcd5a29b2b52e93215544a3
0xfb87640660b4164c1be3b45c1e6a0fb9f40c4691
0x91c6842b79ad4a0f4a03ae274af12a54ab71ee8d
0xeb7b1c0ec3d3a5170356fd21ae6ac41423e28403
0xc3f955a5737840394050e526610475407a4e1b23
0x032d80848be927200fb06b47d985f84e49977ae9
0x104d1fee1e1e3647083bfc770074f89e2d4bee4f
0x4504282c1ef82e23260f0573eaf5c0463fcc77b3
0x1a67197536c1019b732b64f9d29a1f7a3a892fa9
0xbbbed61c90d6c7f0db93820584fabe06b8570ec7
0xe51befe06f6dfdfa43665b8739eae551b165f255
0x1eda046c1aa126b459572a7e6ae329696496671f
0x489fe30ca2e433c04f15fcc1d8935c12b4d8183d
0x9d59e70d478a50833e0c834e79220e3d13775d3d
0x65a830849c9889349d30fad4d8efd471ff057a60
0x65ccec3b3563255fc6d7a47dab55984ba1d438c6
0x65cd5e3d7283fed6c0bc8c196c8f49627c4f6e2e
0x65d1c65151e50b1e60854e1c11e0efc87d116457
0x65e16c02a8473345a954f34ee9b64f4c818aa941
0x65e2410bca0831c344952c6e4f1006e9ac11f559
0x65e6974244ea0fa0da01dc8188d066b1f18b0554
0x65edf08ec00c6fb890744f2075fff2e6737d1929
0x6604d59b3328e0b5649e502e50b261ef2992c9ee
0x660e531c1890a427e63d0f08f6afbbccdedc398b
0x6613a5500e852620140ac295871f741a5ea091c0
0x661c3824e4b391329c35310fcf7d40a543b82ce7
0x66257c9b5800930da0a5d9fad820c093aec486d8
0x662d5ab860bc5a1940d3f065c11f4b5b00270c5c
0x66370cd05e10c3b030afa841481b4d2a63b86f30
0x6654c9e7d9671a46ebb85964fc529d93fe0446cb
0x665cb996c10244486377f66b9521b0441b603e22
0x6673fa2045ae0324c68c0cc6f66e7d91c446d728
0x66825cae42bec42e3294416224417c5dd78460cb
0x66aa35ab40a75c26d92d0e448d79d363c19c4cc5
0x66bd26155ba31b22442c6d7e0e15c66bfb98b5ac
0x66c250a0e9dd5dc11a2e9e5517581b1d6a386a84
0x66d655b4a3982d7ca9b0e5735fcf133e68a4c673
0x66daf9d508a490b05076dc082f03b5697a3fc76c
0x66dd58d57819baf994774ecb1d25fc4637634b2a
0x66eceef0ca5427d2516db117d00fdee2772739a2
0x66f1ff46734a1141a9345aa8a6f71df1edeb5069
0x66f3b8d24175b0f31671c4781d0c179dd7c06352
0x66feb6924cd41a8b7e0631b1743ac2e8e2d8431c
0x67098ce38885fc164aec37c27ccf993f86e2e594
0x672d40d26a7902a85c5f991ef523b92bb40b65dd
0x672ffa86cf971ac0dd10542b441375e31ae9d02e
0x673650ff5bc6c7592503c3f798e473938f7766e5
0x6747085c6fa6151f61ee470d2fd23dbafd26fe64
0x6747c184d86ff660403e7b61515a10518efd86c2
0x675238b1b5ea11fbaa55d33a2ec88ccddc6a9a17
0x67575860eefc18b98c6ff2cd50f7c7684fa85676
0x676758b7c610acec42d47e414d5335cf6fa11899
0x676b78de1b8c8645bdfc9b5353045c32de5f9caf
0x67791c819476ec6e422c3cd3655e3c484706e9c6
0x677bf05e844d877d8808f189f4f320bb570a85f2
0x677dd1b9554439cbe2fe6f05d3c503fda316ae87
0x678141b710e680380167aeb0fcbd6010213fe339
0x679667dc82fe51b56681654a2b0b141ecfc0f242
0x679a39ba9390eca0f1cfc8e299f5677366ce6396
0x679efa8620bc0b51cfbbc0315ca5cca78b176941
0x67a32000a2300c87a41bb89a9d1db9d115234564
0x67b1ee66adc39d37eb5c21636b64da4e791c8916
0x67b8abe7ed6de738b4ce7126a36bbbace438b0bc
0x67c7b941a6bed59a1ea529058b9a6c799f5317a0
0x67d0334ff1bb18059ca7db372eb7fd44297c8325
0x67dd3fc2566f73fd926ede3a433dd21e6e5bc9dd
0x67e39f811be481b53f950dc9ad8fa15e9f48e992
0x67e5ae3c8216db8a5a60d6f369c347d692e19e75
0x67ecd07f60f3c3779fef388aa156abad3a85afea

# Reasoning
There must have some farms even before the "GIP-29: Spin-off safeDAO and launch SAFE Token", so I modified the rule as below:
1.Safe accounts created before 2022/02/102.
2.Total transaction counts more than 1 but less than 303.
3.All interactions with a Safe wallet are from the same account4.
4.Interaction in a very short period of time (All TX in 6 hours since wallet account setup)
5.Current token balances of the Safe account are less than 0.026.

After executing luabase found，There are many associations between the above addresses

First, the main address: 0xA5b39e8438264691103Ff4a35c8034658FEE1227, the most recent transfer record https://etherscan.io/txs?a=0xA5b39e8438264691103Ff4a35c8034658FEE1227&p=1, the most recent transfer happened 346 days ago to the sub-account, and the last 25 records were transferred to the sub-account through Relayer token, which is unusual in itself, unlike what a normal user should do, as shown in the figure below
![189489516-84412d14-cf46-45cb-8ada-338ea686ed56](https://user-images.githubusercontent.com/113116150/190519876-21e2bcda-4f2a-454b-82b1-5d80f9af277b.png)
Then check the earlier records, take 904 days as an example, still mainly rely on Relayer transfer
![189490032-afd67a46-07de-47f0-ae1f-bc2f88924a60](https://user-images.githubusercontent.com/113116150/190519933-291e900c-3061-4f03-adc8-879f3c851953.png)

After investigating all the associated accounts, most of the interactions of the addresses were before 600 days, and the number of transfers in all accounts was less than 25, generally between 3-10, and most of the wallets were empty, or there was a small amount of gas left. , which means that there is no transfer other than interaction. Basically, it can be considered as the multi-signature address of one creator. The following are links and screenshots of some associated addresses.

https://etherscan.io/address/0xf029f8f3265e77ef6e6eb71511145c5c6ba5d39d
![189491143-b66ae863-21d2-4327-ad15-cedb8daee156](https://user-images.githubusercontent.com/113116150/190519974-e5c8fa37-df24-4f49-adea-286feb740a98.png)

https://etherscan.io/address/0x83640976768d490f8456f50456b383a320f0baf9
![189491176-09063d9f-9f7f-4318-8243-7ad5daec4d6b](https://user-
images.githubusercontent.com/113116150/190519992-00e8fe1f-0620-472f-8b6d-8426cf0a0318.png)

https://etherscan.io/address/0x1eda046c1aa126b459572a7e6ae329696496671f
![189491202-5d955ab3-9607-4a39-ad2b-b4848d153464](https://user-images.githubusercontent.com/113116150/190520064-5064902d-0a5e-449e-8687-1693356d590a.png)

https://etherscan.io/address/0xc3f955a5737840394050e526610475407a4e1b23
![189491264-9a5fe587-294a-44aa-932e-d12d6a9e98fd](https://user-images.githubusercontent.com/113116150/190520088-46799598-cfb7-4a54-bde5-ed827d431e30.png)

https://etherscan.io/address/0xeb7b1c0ec3d3a5170356fd21ae6ac41423e28403
![189491284-ab0bbb8c-5977-4cce-9e1e-f2ca70cdaab7](https://user-images.githubusercontent.com/113116150/190520112-27cc4ae6-d9b4-4eea-859b-cbd84825f52f.png)

https://etherscan.io/address/0xa89f55b203e289af2c7b13dd1085ff31d3178371
![189491414-d6795617-a87a-4c98-a18c-f79ba1437942](https://user-images.githubusercontent.com/113116150/190520137-9eccc512-67e0-41ed-8650-56c2d8d7f78d.png)

https://etherscan.io/address/0x7589b95b1c732d06d134381f16650fef4e03a1b9
![189491535-b996abee-8507-416e-bea8-e79c09930e30](https://user-images.githubusercontent.com/113116150/190520191-c0cd8758-2a61-4bb4-b7db-1ce11ae9e619.png)

https://etherscan.io/address/0x5aea111f6f1e65ffc4d3b31f3320405d3f294f05
![189491757-338033be-23cd-49a0-9324-41a4917dcb0b](https://user-images.githubusercontent.com/113116150/190520220-34717321-c5d5-4e48-ad52-75b442a61855.png)

https://etherscan.io/address/0x9d65822e35310342294afb07f5a32347db890fed
![189491835-7b009b13-625e-4493-be53-c4cb3d0f8665](https://user-images.githubusercontent.com/113116150/190520256-f99f4127-931f-4d6f-8afd-7d347a276e0c.png)

# Methodology

Firstly, we establish a database containing the $Safe airdrop addresses on Dune. Then we extract suspicious accounts that satisfy all types of behavior at the same time from this database.
In other words, an account created before 2022/02/10, having few(5-20) transactions with only one account in a short time(6 hours), leaving no money(<0.02) now, sharing same owners with several(>10) brother/sister accounts from a same parent account(creator) , is most likely to be an airdrop farmer's account.
Furthermore, we track not only ERC20 tokens, but also NFTs, in order not to mistakenly hurt real users.
Based on that, an algorithm was used to identify potential airdrop farmers' accounts. The details of algorithm can be found in the query listed below. All the numeric parts in our method are set as parameters to dynamically modify our strategy. Just simply input the rational parameters and run the query.

Dune link: https://dune.com/queries/1272695

# Safe Address
0xefC8a642F073EdcAA3cc2bD3A3fF9230661BE59A

Gnosis airdrop farmer Excel
[gnosis airdrop farmer.xls](https://github.com/safe-global/safe-user-allocation-reports/files/9579417/gnosis.airdrop.farmer.xls)

**Comment by DeveloperThing** [comment]
see https://github.com/safe-global/safe-user-allocation-reports/issues/63#issuecomment-1243398345
