### ISSUE TITLE
64 airdrop addresses

### ISSUE THREAD

**Issue by DOGEKINGGL** [safe-global/safe-user-allocation-reports#460]
# Related Safe Addresses

Full safe address and creator address.
[1-address list.csv](https://github.com/safe-global/safe-user-allocation-reports/files/9591238/1-address.list.csv)
[2-update, new address..csv](https://github.com/safe-global/safe-user-allocation-reports/files/9591239/2-update.new.address.csv)
[3-update, new address.csv](https://github.com/safe-global/safe-user-allocation-reports/files/9591240/3-update.new.address.csv)

A total of three forms contain 217 addresses.

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/79995313/190706310-fca3225c-2f0f-4e1d-8613-7542892c0607.png">

Hunting other addresses can be done by observing their USDT receiving addresses, and checking the contract creator addresses.

Check out SSV, it will give you a better understanding.

# Reasoning

All safes are created within 250 days, and safe transfer records interact with other creator safes.

After the safes are set up, each safe has executed transactions in close time.

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/79995313/190705087-f58bf052-e99c-40b0-b095-6bf6c331ce5d.png">

# Methodology

View a large number of addresses that create safes, check the token transfer records of their safes, and easily find illegal transfers. The safes created by other addresses have the same USDT receiving address.

And I have collected their addresses to transfer out to other addresses. You can easily find out that he is breaking the rules.

Because he has created a safe with other addresses and has sent USDT to the same receiving address record.

Model: 

A creates a safe deposit box - executes transactions with other addresses - safe deposit box sends USDT to C address.

B creates a safe deposit box - executes transactions with other addresses - safe deposit box sends USDT to C address.

When they use safes created at different addresses and send USDT to the same receiving address, it is a violation.

# Safe Address

0x3B928329f3dA134c1D72123B7731330D88068777

**Comment by DOGEKINGGL** [comment]
Waiting for my update tomorrow because I haven't found it all, I only found part of it.

**Comment by DOGEKINGGL** [comment]
I have completed the statistics, this time the total address is 217 addresses.

**Comment by DOGEKINGGL** [comment]
All addresses are valid hunting addresses, and the proof is done by checking the USDT receiving address and the contract creator address.

**Comment by DOGEKINGGL** [comment]
The ssv is created by the creator of the 0x3B928329f3dA134c1D72123B7731330D88068777 contract.

0x7c48b3308f27Ce45EA40BB0593b1355bef17F992

**Comment by DOGEKINGGL** [comment]
All addresses I have mentioned in #107 , and I am the first to mention valid evidence, hoping to pass the review.

**Comment by DOGEKINGGL** [comment]
After I did a full relationship chain check, the valid addresses reached 217 addresses.

**Comment by mikaelyoulove** [comment]
Although they made a large USDT transaction, it is still impossible to deny that they are doing airdrop farming, and the address listed in my CSV clearly tells us that this is indeed airdrop farming.

**Comment by mikaelyoulove** [comment]
Airdrop farming cannot deny him just because he made a large USDT transaction.

**Comment by mikaelyoulove** [comment]
Because he himself already has the conditions for airdrop agriculture.

Contracts with different deployment addresses are finally transferred to the same address.

**Comment by mikaelyoulove** [comment]
meet the conditions

1. Safes deployed at different addresses.

2. Use the safe to transfer USDT to the same address (created by a different address).

3. You cannot deny your own agricultural behavior because of the large amount of USDT.

**Comment by mikaelyoulove** [comment]
Because I think you're right, but I checked #107 and the team has closed it, Lol, for the large USDT transfer.

So why are there so many large USDT transfers? Now that the address is relevant, it proves to be an agricultural practice!

**Comment by tschubotz** [comment]
These are Safes storing significant amounts of USD stable coins. Store of value is legitimate use.
