### ISSUE TITLE
Report airdrop hunter by yaoydong

### ISSUE THREAD

**Issue by yaoydong** [safe-global/safe-user-allocation-reports#475]
# Related Safe Addresses

0x04f4dc42a30cda9facb3fb59507b20a98c614125
0x0b941a53d1c40ad93b73783a10f8cbc04c581855
0x14e227e6e020751933be07b67c112fd8653bc0fb
0x1e64a50eee46a5b07556e478c52d4d23947b646b
0x6006ea4f24eeebeea3e6a0d525881023c2e16670
0x6866113d695d45576d502c01c91a209cb6b8bbb2
0x820ebc8ee4fd80931f713b9fa2146dae4622e298
0x83e2a003cc30c018a906373540ca137450d4ffb6
0x89c90bfd709069c8cefd2ee64417b686cc9571b0
0x99bd94e9533e88f651f318c53e4f2eadaa47ee63
0x9efe06da0deb200ca57198f64c4b8fbc1f6ea959
0xac5a9b5549b77ee0a7cd15e3c3bba7e31a0a3cbe
0xb4d16e01c7e508f22fed3957cfb4e72074c59ae8
0xb8f55a7bed3c62a75704854537f87f9515bc059f
0xbceebc0e41199d2886aa16aac66bb7825cc87c64
0xbcfab12cd8e469c1a8c49b22eba353281a8df5db
0xbf15939f46a669e6ba6e99fdbbe49ffeaf493fce
0xca71aae250473a660d5b2e70750efc0c132b61e7
0xde3a859069b2d098db61bf69924a6b11477be03a
0xee38eb83031ff8a74532c62b4a0a21073888f335
0xf3fb7e9126af0b49d5c92dd713a6411709eb2977
0xf463af2f5376b1cbe95ea4d52071c1b72f1dd705

# Reasoning

same Safe airdrop (180.7490492)
same safe creator:0x5769770f5efe8fb017fb09b6de3b2d096668377d
same exec transaction txs: 1
same execed by: 0xdf21b894a490cbdf49d9de7b9d780b79f7cb0ac7
same execed time :Mar-28-2022 11:02:49 AM +UTC  [timestamp:1648465369]

same event logs: AddedOwner and RemovedOwner

for example:
https://etherscan.io/address/0x04f4dc42a30cda9facb3fb59507b20a98c614125
https://etherscan.io/address/0x0b941a53d1c40ad93b73783a10f8cbc04c581855
https://etherscan.io/address/0x14e227e6e020751933be07b67c112fd8653bc0fb
https://etherscan.io/address/0x1e64a50eee46a5b07556e478c52d4d23947b646b

# Methodology

I checked the winner xls, filter according to the air drop value, and then obtain safe's creator, caller, and the txs  of safe, and then manually check the safes with the same air drop value, creator, caller, and number of calls

checked with code:https://github.com/yaoydong/safe-checker

# Safe Address

0xfdf11fa8ae68ddb3ff2b9138a517e6518f2e8796

**Comment by tschubotz** [comment]
Thanks for your report. We found the following that should not be eligible with regards to the user allocation criteria:

```
0x04f4dc42a30cda9facb3fb59507b20a98c614125
0x0b941a53d1c40ad93b73783a10f8cbc04c581855
0x14e227e6e020751933be07b67c112fd8653bc0fb
0x1e64a50eee46a5b07556e478c52d4d23947b646b
0x6006ea4f24eeebeea3e6a0d525881023c2e16670
0x6866113d695d45576d502c01c91a209cb6b8bbb2
0x820ebc8ee4fd80931f713b9fa2146dae4622e298
0x83e2a003cc30c018a906373540ca137450d4ffb6
0x89c90bfd709069c8cefd2ee64417b686cc9571b0
0x99bd94e9533e88f651f318c53e4f2eadaa47ee63
0x9efe06da0deb200ca57198f64c4b8fbc1f6ea959
0xac5a9b5549b77ee0a7cd15e3c3bba7e31a0a3cbe
0xb4d16e01c7e508f22fed3957cfb4e72074c59ae8
0xb8f55a7bed3c62a75704854537f87f9515bc059f
0xbceebc0e41199d2886aa16aac66bb7825cc87c64
0xbcfab12cd8e469c1a8c49b22eba353281a8df5db
0xbf15939f46a669e6ba6e99fdbbe49ffeaf493fce
0xca71aae250473a660d5b2e70750efc0c132b61e7
0xde3a859069b2d098db61bf69924a6b11477be03a
0xee38eb83031ff8a74532c62b4a0a21073888f335
0xf3fb7e9126af0b49d5c92dd713a6411709eb2977
0xf463af2f5376b1cbe95ea4d52071c1b72f1dd705
```

**Comment by CaptainTee** [comment]
What a huge blow to my issue in #504
You've found 22 addresses which are also found in my report.
Your report was earlier though, so, congratulations to you, friend
