### ISSUE TITLE
25 safes with same action

### ISSUE THREAD

**Issue by 0xETH999** [safe-global/safe-user-allocation-reports#496]
# Related Safe Addresses
```
0x199aa8a209884ffb1e0849eaeb072bce573bf871
0x1deafddfc62c7d6113204adff6fda8a2d2e55a69
0xeae5e0d63285f24f3a089fdb6a0082ff6801eba1
0x30cd6df997d3c153624fcc560823a32e8886d69a
0x521fe1bd7dec39362809cac1a237629d458e459b
0x52b14b11ef687dbad8e422d655a45ea551948760
0x61f744a03b89f7267d26839d4913693c58eadbde
0x6673fa2045ae0324c68c0cc6f66e7d91c446d728
0x676758b7c610acec42d47e414d5335cf6fa11899
0x3204596e8cd53a791767340c93fb5ee2f11b5840
0x692a7d771c69bf1664690b5a072e04f14254aece
0x70c9fd1651ca952314965764012ab63e60fd4eb9
0x7c3d8bc495b7d2dcc995a3a0dc6444480483988c
0x7ec0740988c8d01ef4acfb8ac280dbc7b1d2462b
0x7f630885074b976570152a712589e0ceca9086d3
0x8cb1f9ad02e57eca18065d83efdfb6ff0c57392c
0x91155176f8911c6a34dbca8537a59c2c4816d2d3
0x4153f0145d48bbd3eb2438dbe1d4535734ec78e3
0xab61f7cb67dbce3612f3eefd617b2df2a27d5215
0x1d02f0a433a999a777d1b11311c4bc9fac33af65
0xadca2254b9b40a48ef44140482e912a03cbc7f5d
0xBFA3e74eCAC5b2Ecf20B2BaFcdc02Cd659435a45
0xde7a69f62a0746cf93bf97bca16038d05fb700e5
0xf03a139c3d0d26a07e2939204ae7f3ea1dbd9919
0xfed79ad04bc452420e6df9f40625cec8e8a3373d
```

# Reasoning
I downloaded all the ETH transaction logs for this wallet and found :
_UTC 2021-9-27  12:37:11 --2021-9-27  13:30:10 created 8 addresses created at no interval
UTC 2021-12-18  7:15:00 -- 2021-12-18  8:19:32  created 12 addresses created at no interval
UTC 2022-1-17  17:24:59-- 2022-1-17  17:50:03 created 17 addresses created at no interval
UTC 2022-1-19  16:49:56 --2022-1-19  16:55:04 created 9 addresses created at no interval_
and so on
The addresses  I listed  have only 1 transaction , and the transactions were sended by 0x20c05cf93223e39d75b6266b4044e2e5c588d089,I found that each of these addresses was transferred by eth:0x20c05CF93223E39d75B6266b4044E2e5C588d089 for 0.001 ETH and never used again，for example.
```
https://gnosis-safe.io/app/eth:0x199aa8a209884FfB1e0849eAeB072BCe573bf871/transactions/history
https://gnosis-safe.io/app/eth:0x1deafddfc62c7d6113204adff6fda8a2d2e55a69/transactions/history
https://gnosis-safe.io/app/eth:0xeAe5e0d63285f24F3a089fDB6a0082Ff6801eBA1/transactions/history
https://gnosis-safe.io/app/eth:0x30cd6df997d3c153624fcc560823a32e8886d69a/transactions/history
https://gnosis-safe.io/app/eth:0x521fe1bd7dec39362809cac1a237629d458e459b/transactions/history
https://gnosis-safe.io/app/eth:0x52b14b11ef687dbad8e422d655a45ea551948760/transactions/history
```
This person repeats the same operation and gets a large amount of airdrops with a small amount of money and a single trade，which means it's a very potential airdrop hunter

# Methodology

I first found this address through the airdrop list and my own code
Then I analyzed the time and number of gnosis safe created at this address and found something suspicious.
Then I manually checked the transaction history of each gnosis safe and found the same operation repeated for each address
# Safe Address
0xD64C9C6601CDb12D02f2A60cE1C55Cd6aD49c278

**Comment by tschubotz** [comment]
Thanks for the report. Most addresses have been reported already. Expect these 3:

```
0x692a7d771c69bf1664690b5a072e04f14254aece
0x70c9fd1651ca952314965764012ab63e60fd4eb9
0x4153f0145d48bbd3eb2438dbe1d4535734ec78e3
```

However they don't fit to your reasoning.
