### ISSUE TITLE
Airdrop farmer report 2

### ISSUE THREAD

**Issue by xiaohu1882** [safe-global/safe-user-allocation-reports#499]
# Related Safe Addresses 
0xFDf93167Aa8647eF06E92ccC8e31feBe9B509FD1
0xca932cf70e41d703931baf1e592c3049a8c73606

# Reasoning
The above safe wallets are added as the supplement of https://github.com/safe-global/safe-user-allocation-reports/issues/193 that I reported, as the owners of those safe wallets are closely related to the address in the issue https://github.com/safe-global/safe-user-allocation-reports/issues/193 and it is already valid and closed. The evidences are shown below

1. The owners of the above safe wallets and  the reported safe wallets in [issue ](https://github.com/safe-global/safe-user-allocation-reports/issues/193) have very similar behavior pattern
**transfer - pledge - transfer - transfer - transfer - Mint - Mint - Mint - Deposit ETH - Fill Order RFQ**

0xD822e41EaC767c7e675Df314DEfDF5b1601fe8Ae
0x9D2D543b4Da2fb6e45a9ad85ab90D2A6EF8f913e

2. The address "985211.eth" sent 0.015 ETH to the above 2 owner addresses and the addresses in https://github.com/safe-global/safe-user-allocation-reports/issues/193 on the same day.  The link is added below.

https://etherscan.io/txs?a=0x6e4ef712decbe435c2e7edcb2ce4a3c7fa46317a&p=5

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/106882397/190925380-7aa0c37c-3423-4c11-82b8-524e365cdce3.png">

# Methodology

Based on the addresses of the airdrop farmer in https://github.com/safe-global/safe-user-allocation-reports/issues/193 and the transfer trasnsactions, I noticed that the airdrop farmer created more wallets to hunt the airdrops. All of the wallets in this report and report  https://github.com/safe-global/safe-user-allocation-reports/issues/193 have the same behavior pattern. 

# Safe Address

0xc78CdC3dd169f1308f11a0E9Fb30d86dBfED444b

**Comment by tschubotz** [comment]
Thanks, we've found the following Safes to be related to airdrop farming:
```
0xFDf93167Aa8647eF06E92ccC8e31feBe9B509FD1
0xca932cf70e41d703931baf1e592c3049a8c73606
```
