### ISSUE TITLE
16 other airdrop farmer addresses found by accident, inspired by a rug pull project

### ISSUE THREAD

**Issue by STephcuYY** [safe-global/safe-user-allocation-reports#508]
# Related Safe Addresses
0x74e7B2EBA34168107E69d1b75453098937D2c848
0x57144F872E84DE007711aD8591f0124b40E1aF6b (by [mannyog.eth](https://etherscan.io/address/0x9f16f3d5c1bd2abd7ba9c4cb1cea10514955174f) )

0xc380cFf83b13bCF8E3567c35BBA5f4dcD5FDdf0E
0x8eDc3b0df806F65F86c8729AeD0F8aea7E487Fe8  (by [biricik.eth](https://etherscan.io/address/0x5f78fbab81f9892bbe379d88c8a224774411b0a9) )

0xa2777a1EfAbeeCF1857FFb942f1b2c97A1A6b38d
0x3C89a0B1c159374947314AaC3CCd88b319637d7a (by [incanous.eth](https://etherscan.io/address/0xdf9e7f58be74ff111c7c06000971cf1e10b92dd8))

0x142f807511122F527E446ad4819eC2925f1AE62b
0x25F575E53F50f15BF214DE7c99431Dfb35a3d1c6 (by [fb8caa905a2e.eth](https://etherscan.io/address/0xfb8caa905a2e87ef0790df090d90765f83eafd5a) )

0x1c8ac19488c1763CBCE41A73C50395CD7F43cDc9
0x7Be323864e0da8b67192c2dF70C4f920919b5a48 (by [0x63616.eth](https://etherscan.io/address/0x1e9f72c28b227cbb56577dc6f693b95237ac0bfe)) 

0x1bE0e19b685787C082D867d979a0555f50E0FE4d
0x40c85a54C7B3FEB9eedebF4b6F054DF3C167d701
0x3c8e59F37AD510863801db42A18761908f2f5409 (by [xboss.tokenid.eth](https://etherscan.io/address/0x05fcb1c0c4c96ac965942cba44180e932968fdd1))

0xd80e21D0B6990539e93E708542eF5f1a52ff13d1 (by [0x6a7df1c03ba4a8a33be1414a89396add7b162590](https://etherscan.io/address/0x6a7df1c03ba4a8a33be1414a89396add7b162590))
0x6cfaC14064733A70d6edf82468FC83E9f21e0d6c (by [smartaddress.eth](https://etherscan.io/address/0xddd984cb9cc3181d9ab07515846a9f4863c1825d))
0x7c4de4aa5068376033aeF8E3DF766aFF3080E045 (by [0x1430118732f564Ec474c4998D94521661143dF23](https://etherscan.io/address/0x7c4de4aa5068376033aeF8E3DF766aFF3080E045))

# Reasoning
here are addresses created the safe addresses above:
[mannyog.eth](https://etherscan.io/address/0x9f16f3d5c1bd2abd7ba9c4cb1cea10514955174f)
[biricik.eth](https://etherscan.io/address/0x5f78fbab81f9892bbe379d88c8a224774411b0a9)
[incanous.eth](https://etherscan.io/address/0xdf9e7f58be74ff111c7c06000971cf1e10b92dd8)
[0x63616.eth](https://etherscan.io/address/0x1e9f72c28b227cbb56577dc6f693b95237ac0bfe)
[fb8caa905a2e.eth](https://etherscan.io/address/0xfb8caa905a2e87ef0790df090d90765f83eafd5a)
[xboss.tokenid.eth](https://etherscan.io/address/0x05fcb1c0c4c96ac965942cba44180e932968fdd1)
[0x6a7df1c03ba4a8a33be1414a89396add7b162590](https://etherscan.io/address/0x6a7df1c03ba4a8a33be1414a89396add7b162590)
[smartaddress.eth](https://etherscan.io/address/0xddd984cb9cc3181d9ab07515846a9f4863c1825d)
[0x1430118732f564Ec474c4998D94521661143dF23](https://etherscan.io/address/0x7c4de4aa5068376033aeF8E3DF766aFF3080E045)

By chance I discovered that they had all been associated with this address: [xboss.tokenid.eth](https://etherscan.io/address/0x05fcb1c0c4c96ac965942cba44180e932968fdd1)

![1](https://user-images.githubusercontent.com/113139158/191014908-206920f5-907f-465a-b0fa-c43715558463.png)

There were a large number of transfers between them, so much so that every time I clicked on any one of the ens I could see several others appear on the transaction page, and it was clear that they were attributed to the same person.
Such as 
![3](https://user-images.githubusercontent.com/113139158/191016413-99d36f08-d6bf-4378-9af1-b77f874dda79.png)
![2](https://user-images.githubusercontent.com/113139158/191016407-0e905710-824b-4f7c-b666-af22e2e515c0.png)

# Methodology

I found the address I mentioned in https://github.com/safe-global/safe-user-allocation-reports/issues/170 ([xboss.tokenid.eth](https://etherscan.io/address/0x05fcb1c0c4c96ac965942cba44180e932968fdd1)) did something to that safe address, and I clicked it's tx page.
So much related address and I just try to find that if there is something relating. And finally I found that he used each ENS to control 1-2 safe address, and he did not segregate the funds of each address, but made a large number of transfers to each other to supplement the gas costs.

Though I can't prove the addresses I mentioned in 170 have some relation, but it's factly that It's all about a rug pull project called WCDS, which created so much pain to those people loving crypto two years ago. And I think the [xboss.tokenid.eth](https://etherscan.io/address/0x05fcb1c0c4c96ac965942cba44180e932968fdd1) really do have something to do with it, otherwise he wouldn't have been able to use that safe address.

# Safe Address

0xA61B43b55193670579d959c94a6b0303Ecd12201

**Comment by STephcuYY** [comment]
u can click every ens and feel surprised to find that each of them have some relationship like transfer gas/ register ENS/ do some swap/ buy NFT~

**Comment by lukasschor** [comment]
Closing this as the deadline for submission has reached. See the deadline mentioned here: https://forum.gnosis-safe.io/t/community-challenge-identify-airdrop-farmers/847/15
