### ISSUE TITLE
airdrop farmer address 

### ISSUE THREAD

**Issue by xiangdaye** [safe-global/safe-user-allocation-reports#509]
# Related Safe Addresses

0x798d328407055649acd4360201912e375413e999
0x05c81b8886a8f7c7efbac200d9effd8d7921200b
0xa4a5971ab41cd5af29d11849ab2a376c90f65441
0x59c97465be5b3c3fe1032ce30dd74404564d20dd
0x9d9d9ea1d9422375c6696c953cfba966e6c6c3a0
0xf0833df8eab2f7c4fd1f2d36831364103e844197
0xdd0a87380f8cd911e4ce2dfa82d8c983b002163d
0x8948837501562c53648a82fc5461942189bc65de
0x556f7b2318ec0060c8adc81982838e1a2e10315c
0xd58ac7c455fa89a64bdb271b1237f9d083f639cc
0x6c1cb30ad73f628fb5d0e99a94648a5802f6b51d
0x33d1f73fd14c73f064e4eb0217d7b56b2e0aef8c
0x7fddbf26e0d413f4b18cc8ecd8cb6cb1830f195b
0x069e1ea1c27d09c569cb8b24c7035fdefeed8e73
0x381033fd735a7b7b25d7c75674913e9a7259de4f
0x261c4a747ead7372a314567ed78c9ef7b9b5f5b9
0x014145161be0a3b0fb9000803d1bdddabe532d0e
0x4837044eb492842d6a504475bcf6bd014fb16fb0
0xdbaa3d3b16604b9f7106e42a8bc29c8845bd2a27
0xcf796a2d53477dec60e0c48aa9af5be857ba2900
0xc79f599d76d467bb50b0b4502ccd2ad4813fe9ef
0xc186ba966bd75877e02a883798065eba7e800403
0xa9b572fe554294b1242cc46dcd40684c15bfb446
0xa213abf398e49f648b159df09c2a546688955223
0x9ccb85703059b4dc79dfbd3470bb8fab81f840f0
0x94054904316680c58a81cc9199b5a5a825d1733c
0x873740f8b084e2414f57c33cf12b400af9652f72
0x7bfd671a422f7bf0db3b4bd5667968f0f1bfabf1
0x760217b519adfed670734109bdf24731d7adeeec
0x6e8c42d0eee83cef5c683304840adb360addc5c2
0x6d77ab75702e46aa231a89ab44d7e692edc4bf5b
0x6d29977834e1cef8e4b7cd80950e30bafa59d3bf
0x61fd7cd10bcc5fdfce30d02ab4555cf69b11dfc2
0x4ba3de2feb800d39da6383821cd3261d0bf2a89e
0x40b1e53af75bc9277616ec3bc17fc9d83f9c2a94
0x3432da99cd5f5136a4fa4dce43306b3c705f8560
0x2f64c6bcf8b8c15045caaab7cbf3c6fc6825fc18
0x1a32f44bea5ca2c7187e24a4a4648b46efd6c9ef
0x10d4607b1e311b28eaee8b195f4b837a18289e2c
0x106abb4fdf3da53855d8f0411c1507ba428ade79
0xfa52e390281c5f9a711bf57f7dc3900b2a80b835
0xbed293c4dc7d8b24316342409d50581059667a3f
0xb3badaeac59324b606fdacc8746e2387df127f3d
0x974b78174d904b60678430938d17f779d4d630ea

# Reasoning
All the above addresses are transferred from 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D to eth, which is obviously witch
0x569770F5EFe8fB017FB09B6dE3B2d096668377D is a personal address. The first transaction of the above safe deposit box address is the eth transferred from 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D. Without the eth safe address transferred to this first transaction, no other on-chain behavior can be generated. This operation shows that the above safe deposit box address belongs to The same user, this is obvious airdrop farmer behavior, real users will not appear such operations.

All Safe address were executed by this wallet 0xDf21b894A490Cbdf49d9De7B9D780b79f7CB0AC7   ago at the same time.
All Safe address were created by this wallet 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D 
All Safe address have only one executed transaction and never use again.
# Methodology
https://etherscan.io/tx/0x0bda5a5272520cbd9761b7d1ac95e4d4fc516ba3668ce2e4c224feb42706bbcb https://etherscan.io/tx/0xe762691cd6a72c47a69b7d4f5c25281ba22796642e57871c0683a8f736a4e53a https://etherscan.io/tx/0x9b6b52fa18aa5c0bab842ac710e9c2effee02831ebb121afb239d158fa1e25bd

# Safe Address
0x188950d274A7C23Ec2e180Aa0E5cf92997B69D70

**Comment by lukasschor** [comment]
Past deadline
