### ISSUE TITLE
first-come, first serve basis

### ISSUE THREAD

**Issue by deshawelafi** [safe-global/safe-user-allocation-reports#516]
Report[ #411](https://github.com/safe-global/safe-user-allocation-reports/issues/411) is the same as report [#317](https://github.com/safe-global/safe-user-allocation-reports/issues/317)

**Comment by d3centra** [comment]
That seems to be actually true, and even more dramatic as #411 by @BountyHunters1 is copied 1-1 from report #317 by @deshawelafi (which was posted 4 days earlier and only got one edit yesterday to change the Safe address needed to receive a potential reward).

**Comment by farmerxx** [comment]
That seems to be actually true. check plz ser @tschubotz

**Comment by tschubotz** [comment]
Thanks, fixed.
