### ISSUE TITLE
my issue #231 should be reopened and label as staker

### ISSUE THREAD

**Issue by TjdnskEhdksk** [safe-global/safe-user-allocation-reports#517]
my issue #231 ,which is mainly related to stakerapp. I have noticed that whether the StackerApp can be identified as the object of this airdrop through only one changeowner has not been determined, so I think that my issue should be opened and labeled as a "staker".

at the same time, I noticed that some stacker related issues have been confirmed to be valid. as below:

<img width="765" alt="gooddecision" src="https://user-images.githubusercontent.com/113167298/191414002-0003b818-35c6-4fbc-a403-212719c9577f.PNG">

No matter whether the team finally thinks that the staker should be airdropp or not, its acceptable. but I think at this time my issue should be opened and labeled as a "staker".

thx very much

**Comment by Architect0044** [comment]
Sorry decision is final
