### ISSUE TITLE
I want to clarify about of the label"heavily edited and potential copycat" in #108

### ISSUE THREAD

**Issue by airdrop-killer** [safe-global/safe-user-allocation-reports#519]
At First, The reason for the multiple edits in the first place was that I was using github for the first time，So I don't know the roles.
But even if I edit many times, it can only be judged as suspected plagiarism, rather than has been plagiarized. The following is my proof that I did not plagiarize：
  First of all, #108  is valid Because you have accepted the report #221 , and the author of #221 also acknowledge there has 290 addresses earlier than #221 
![image](https://user-images.githubusercontent.com/113131921/191502522-6f224217-23aa-4dc4-907a-a98789769ea3.png)
  This is the timeline reorganized by memebeat.
https://github.com/safe-global/safe-user-allocation-reports/issues/221#issuecomment-1250022810

  And then the 666 addresses listed in #298  are identical to #108 , even in the same order, according to the timeline #108  predates #298 , as shown in the graphic evidence
![image](https://user-images.githubusercontent.com/113131921/191503208-74792ac9-a2a0-4434-b878-5338cef5a104.png)
![image](https://user-images.githubusercontent.com/113131921/191503254-462b83f3-7610-4201-ad39-402a53ff6cbb.png)
![image](https://user-images.githubusercontent.com/113131921/191503290-ac49b6ae-d180-4108-9eea-6ba57c3f3d64.png)
   And, if I did plagiarize, how did I plagiarize to an address that no one else had submitted ?
   By the way if u look at the Form I submitted, you'll see that I found these addresses in other ways ，It's different from other guys.
   https://airtable.com/shrttPfyBh07QFVnU/tbltcklWQn3qTLBAE
@tschubotz

**Comment by wjw12** [comment]
Hi team, please review the timeline summarized by @memebeat https://github.com/safe-global/safe-user-allocation-reports/issues/221#issuecomment-1250022810 and the timeline summarized by me https://github.com/safe-global/safe-user-allocation-reports/issues/221#issuecomment-1250113842. We used different methods and found some overlapping addresses at different times.

I believe @airdrop-killer submitted some addresses in the 6th version of #108 before memebeat (author of #197, #221) and me (author of #214 #215). Hope you could bring the timestamps and contents under your scrutiny to give a fair judgement. Thanks!

**Comment by tschubotz** [comment]
Thanks, seems like all involved parties seem to agree. Readjusted the rewards addresses based on https://github.com/safe-global/safe-user-allocation-reports/issues/221#issuecomment-1250022810

**Comment by airdrop-killer** [comment]
Thanks and Godspeed :)  @tschubotz  @wjw12

**Comment by wjw12** [comment]
Thank you all
