### ISSUE TITLE
TICKET #504 NEEDS TO BE FULLY ADDRESSED - PLEASE RECONSIDER YOUR DECISION

### ISSUE THREAD

**Issue by CaptainTee** [safe-global/safe-user-allocation-reports#522]
Thanks for this @tschubotz 
However, I think it worth noting that 25% reward is one important thing, making the precious **$SAFE** token going to right hands is another and that's the essence of this exercise.

My added comments were as a result of the timing constraint. I spent more hours typing the notes to ensure that addresses identified as sybils are convincing enough and that's the reason I was late but the fact is that all the works were done at the same time.

Please reopen this ticket to ensure:
- **My 4 days efforts without good rest doesn't go in vain**
- **Precious $SAFE doesn't go into wrong hand**
- **The aim of this exercise is fully achieved**

I happened to be the last person to submit report because I took my time digging in order not to be a copy cat.

The section you want ignore contains more sybil addresses than the ones you've attended to.

Attending to the other sections shouldn't be seen as unfair to anyone if their report doesn't contain my findings and I was only hours late not days because I don't want to be a copy cat.

:exclamation: I have filtered addresses found by others before I do and I see I have a valid 596 addresses that are either Sybil or Relayer's

**Approving only 73 out of 596 is a wasted effort for me**

PLEASE RECONSIDER YOUR JUDGEMENT

**PLEASE RECONSIDER YOUR DECISION AND ATTEND TO OTHER ADDRESSES in TICKET #504**. 🙏 

Cc: @lukasschor

**Comment by lukasschor** [comment]
Hey @CaptainTee. I'd support @tschubotz reasoning here. 

While I very much appreciate the effort you put in, we want to stick to the rules and not reconsider the deadline. We have also disregarded several other reports submitted after the deadline. 

Additionally, I sampled some Safes from #504 and they seem to show legit usage. Especially some Safes showing usage as far back as 2019/2020, where the Safe Token was not even announced. Therefore it is unlikely that they are systematic airdrop farmers.

**Comment by CaptainTee** [comment]
While I appreciate your quick response @lukasschor 
I still think many addresses in the Sections ignore belongs to farmers, you're chanced to lay your hands on the SAFE addresses that were created many years ago.
(
![Uploading Screenshot_140.png…]()
See attached screenshot)

I truly wish you Reopen it and keep my morale alive.

Rendering 4 days with sleepless nights works useless will definitely be painful

**Comment by lukasschor** [comment]
Why would you think a Safe created in 2019 can be in any way related to airdrop farming? At that point we didn't even have the Uniswap airdrop, so airdrop farming was not even a thing back then. I do understand that this is not the result you hoped for, but hope for your understanding that we:
- do want to stick to our rules
- do not want to risk having legitimate users excluded from the airdrop

**Comment by CaptainTee** [comment]
I agreed that airdrop farming wasn't a topic for discussion in 2019 but it is also important that we don't let a single entity which could have possibly forget about SAFE controls larger percentage of the token.
Those SAFEs weren't used since the creation date.
Making someone who hasn't used SAFE products in the last 3 years have the possession of large token which automatically give larger voting right determining the direction of the SAFE in the future is not too satisfactory.

However, I have filtered those addresses reported and now, I'm only left with 523 from 2000 addresses reported. This should take you lesser time to work on

I will appreciate if you work on it for the next few minutes. This remaining 523 list is summarised in the below Excel sheet
https://docs.google.com/spreadsheets/d/15aSkXazOxbOK-_JojsqUfuvYcOfPR5wF/edit?usp=drivesdk&ouid=104966231854140804909&rtpof=true&sd=true

**Comment by CaptainTee** [comment]
Cc: @lukasschor

**Comment by lukasschor** [comment]
`Making someone who hasn't used SAFE products in the last 3 years have the possession of large token which automatically give larger voting right determining the direction of the SAFE in the future is not too satisfactory.`

I don't consider this as valid reasoning. The airdrop criteria did not include any "last active" metric. To the contrary, early users actually contributed much more to the success of the project than recent users, as they took more risks.

**Comment by CaptainTee** [comment]
Work on those 523 addresses and keep the 25% reward into the Treasury.
It's painful to see my findings not being checked at all

**Comment by lukasschor** [comment]
Look, with all due respect. I have checked about 20 Safes and all of them are legitmate users. With Mesa, a lot of users were onboarded to Mesa and conducted a similar sequence of transactions. Therefore they look like airdrop farmers, but they are not.

**Comment by CaptainTee** [comment]
Thanks for this, I appreciate :pray:

**Comment by Architect0044** [comment]
@CaptainTee enemy of progress with African mentality and selfish interest.
Go and huge transformer
