### ISSUE TITLE
Reward safe address mistakes in issue 204 and 220 

### ISSUE THREAD

**Issue by farmerxx** [safe-global/safe-user-allocation-reports#526]
[https://github.com/safe-global/safe-user-allocation-reports/blob/42697e4438244c992ec993c417ea885b06a3d8af/review/valid_reports.csv](url)

Although these mistakes have nothing to do with me , i should point it out.

Thanks for the Safe team and all witch hunters.

**Comment by tschubotz** [comment]
For #220, `0x984129b1c8d6048df516d81f730475af7d0e4232` is used as specified in the issue: https://github.com/safe-global/safe-user-allocation-reports/issues/220#issue-1367323364

Fpr #204, `0xcee6063D59e3fF951677AD1E1B2b58C686efFA50` is used as specified in the issue: https://github.com/safe-global/safe-user-allocation-reports/issues/204#issue-1367189619

Where exactly do you see a mistake?

**Comment by tschubotz** [comment]
Found the mistake, thanks a lot.

**Comment by CaptainTee** [comment]
Can someone brief me what was the mistake in #204 , please❓
The SAFE address stated here for #204 is correct and match with my submission.
I understand someone commented his ADDRESS as a reply to my report but I believe the team would have ignored his address already

I can also see the mistake in #220 was the last 2 digit in the address was switched but I see no mistake in #204 yet.

Can someone tell me what's wrong, please ❓
Cc: @tschubotz @farmerxx

**Comment by CaptainTee** [comment]
Yes! I found the error now.

The error is still not fixed, please @tschubotz 
It was only fix for the first address on the list while the last digit for addresses has changed. This usually happen when one highlights number on drag is down on Excel

0xcee6063D59e3fF951677AD1E1B2b58C686efFA50 ✅ 
0xcee6063D59e3fF951677AD1E1B2b58C686efFA51 ❌ 
0xcee6063D59e3fF951677AD1E1B2b58C686efFA52 ❌ 
0xcee6063D59e3fF951677AD1E1B2b58C686efFA53 ❌ 
0xcee6063D59e3fF951677AD1E1B2b58C686efFA54 ❌ 
0xcee6063D59e3fF951677AD1E1B2b58C686efFA55 ❌ 

Please fix it @tschubotz 
Cc: @lukasschor

**Comment by farmerxx** [comment]
> Yes! I found the error now.
> 
> The error is still not fixed, please @tschubotz It was only fix for the first address on the list while the last digit for addresses has changed. This usually happen when one highlights number on drag is down on Excel
> 
> 0xcee6063D59e3fF951677AD1E1B2b58C686efFA50 ✅ 0xcee6063D59e3fF951677AD1E1B2b58C686efFA51 ❌ 0xcee6063D59e3fF951677AD1E1B2b58C686efFA52 ❌ 0xcee6063D59e3fF951677AD1E1B2b58C686efFA53 ❌ 0xcee6063D59e3fF951677AD1E1B2b58C686efFA54 ❌ 0xcee6063D59e3fF951677AD1E1B2b58C686efFA55 ❌
> 
> Please fix it @tschubotz Cc: @lukasschor

https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/review/valid_reports.csv 
Now it was fixed, no need to worry.

**Comment by CaptainTee** [comment]
Alright, Thank you, friend
