### ISSUE TITLE
14 addresses found first in Issue 265

### ISSUE THREAD

**Issue by xiaohu1882** [safe-global/safe-user-allocation-reports#527]
@tschubotz  There are 14 safe wallets found in issue https://github.com/safe-global/safe-user-allocation-reports/issues/265 before https://github.com/safe-global/safe-user-allocation-reports/issues/294. The author of the issue https://github.com/safe-global/safe-user-allocation-reports/issues/294 also agrees with me . Could you please check the edit histories to confirm it? 

0xe6e94ba16E7c752424Cff7aFA0c87602Be3e3Eec
0x705cCA342b7a36C46442C06E7117D33Be661d711
0xD66292d9EE2ddF4772dc94Fe3d2791c38ED7605F
0xF41E53A089854F71eEEA2934967C759658d8560A
0x35345E852C4b70883cB0710945Bf63BC32c01369
0x5cF25A39b7015a1F49208E88e7c45a0ad5921861
0x5Dfa97d1d1746E19Bc5FbB28213C23EB33da498e
0x72002988E532ea1cAB05Dc2AF0F730860e8Aa5C2
0xAc2caB720ce08becCb69FfE5ec9d5aAC3CDc7f3C
0x93Bb9aa2F46f3775d0ff0a916fFac650C574B96b
0xcf0574082B0E548eA57dBD4785863094f856dA2c
0xDe77b3DAA28714E8a21Ad1AE68d93BF65D7E4d34
0x8d1534aAbe5296EbBab5158d4CdfAD6723E6Ec0A
0x4429fb5D1282170c3C644bd4244700F272a71Fc5
 
![image](https://user-images.githubusercontent.com/106882397/191696101-b210f59f-33df-41f9-a2c7-dafba21568cf.png)

**Comment by tschubotz** [comment]
Thanks, fixed.
