### ISSUE TITLE
My report was valid but I didn't receive safe reward

### ISSUE THREAD

**Issue by p3rcy-eth** [safe-global/safe-user-allocation-reports#528]
# Related Safe Addresses

I reported 46 safes in issue #130 but my safe address was not included in the csv file (https://github.com/safe-global/safe-user-allocation-reports/blob/main/review/valid_reports.csv). Please kindly check. Thanks a low.

# Safe Address

safe address: 0xd5c6686A259D3C2625927Ba9E4db37D000433b92

**Comment by tschubotz** [comment]
Fixed it, thanks for the heads up.

**Comment by p3rcy-eth** [comment]
> Fixed it, thanks for the heads up.

Thanks! Appreciate your time.
