### ISSUE TITLE
report!!!

### ISSUE THREAD

**Issue by SeanCCkaka** [safe-global/safe-user-allocation-reports#59]
0x006b1baa7469adf48fa632e9efc00635d77ea1f5
0x006d1194256a0754b489dc9b8596a4c4a721cb9c
0x01c439abc0bb34d3cc10279e150cde4afda19642
0x066419eaef5de53cc5da0d8702b990c5bc7d1ab3
0x06874c6f62209508115593d90c9b03110baec64a
0x06cb966d1de30caa6f8845dd94e4bde9ece56d4d
0x06ea07c21c7e85608267466fc03b368f752ca102
0x07944147cd1d166179edc226ee0201ef0bdb32ca
0x081d84829b1b8f8a46cce0392c524604ee785508
0x09c065b2895a7e9614289684d66bb05d41494e72

https://etherscan.io/address/0x2236b3A9C23A2E7847a8D2125d1828Bc8B9B9713#tokentxns
through the link we can find that is a normal user of eth address. The address has the normal transaction behavior.

**Comment by tschubotz** [comment]
This report doesn't use the template and contains no reasoning.
