### ISSUE TITLE
He created 10 wallet addresses, and these 10 wallet addresses were airdropped!!

### ISSUE THREAD

**Issue by qlmessi10** [safe-global/safe-user-allocation-reports#66]
# Related Safe Addresses
0x9aDB2404Af11Ed004B9bCcF8bb6cEBA11833E6c0
0xEaCae0A7004C3466ee1C86aFFB08b738e6B11a2f
0xA123ee02e6673C2Ef0A7bfBde35956804EE6fc12
0x8c22A00a94F1FbB870ab65E4a30530Eb253Bc1fa
0x2fd8fff98f6fEa01d1d4E33262a6a9C70e4697Bd
0xa159AFEc31851B754AECA1be5c914eaA2eEf31a8
0x7524fbBB8a654eDe614dDec64Bf809240016Af27
0xA549cA95fBd5785d56029029d6D93Ad8D716e1dD
0x1413fbdee7f7547d8e35cAFAFde97Cf8aeEB59C8
0x2e016964119fCfb4F77Bee3A057152dBA9F89E9a
# Reasoning
First of all, we can see that the time when he created the safe wallet address is very consistent.<img width="933" alt="屏幕截图 2022-09-09 000255" src="https://user-images.githubusercontent.com/77811636/189174784-3368e400-85a5-4e21-aaa5-de1f2d17c7f1.png">
 Then we are checking his safe wallet. All operations are almost the same. All of them spend the same 0.0666666eth to mint an NFT.
<img width="950" alt="屏幕截图 2022-09-09 000600" src="https://user-images.githubusercontent.com/77811636/189174916-7d81f8c6-d8b8-4e62-bcde-5afc88a46a79.png">
<img width="960" alt="屏幕截图 2022-09-09 000432" src="https://user-images.githubusercontent.com/77811636/189174923-00202fea-7ecb-42ce-bf68-f493ee8d6826.png">
<img width="950" alt="屏幕截图 2022-09-09 000352" src="https://user-images.githubusercontent.com/77811636/189174931-45857083-2926-478d-8c2b-d1e8c884517f.png">
 But after checking, this wallet will not be a relay, because there are a series of operations that do not conform to the relay, such as donating to buy NFT.
<img width="928" alt="屏幕截图 2022-09-09 002202" src="https://user-images.githubusercontent.com/77811636/189175122-1a97e64a-864e-4636-bc1d-90070c76d6da.png">

 I think he is an airdrop farmer, The operation of the 10 safe wallets he created is all the same!!
https://etherscan.io/address/0x1ee199c1832d4cfd075ad2708feb75fc8c80b8c6
# Methodology
 First, I found his address
 Then I analyzed the behavior of his wallet on ethscan and all the safe wallets I created. Finally, I came to the conclusion that he was an airdrop farmer!!
# Safe Address
eth:0xab31c9A6504b82ec0B1021a8b294eBE04D3bFB4e

**Comment by tschubotz** [comment]
> Then we are checking his safe wallet. All operations are almost the same. All of them spend the same 0.0666666eth to mint an NFT.

I've checked the first 2 Safes
https://etherscan.io/address/0x9aDB2404Af11Ed004B9bCcF8bb6cEBA11833E6c0
https://etherscan.io/address/0xEaCae0A7004C3466ee1C86aFFB08b738e6B11a2f

Safes did not receive any SAFE allocations for holding NFTs, hence it's irrelevant for this effort. Other than that as far as I see the Safes just have inbound ETH transfers. So they act as store of value which is fair. Also those mints are done by different accounts where no connection between them is obvious. 

Just creating 10 Safes is not airdrop farming perse. The mints are done at different times, right?

So other than 1 account executing the Safe creation, there is no other reason to assume it's the same entity that does airdrop farming right.

Please elaborate on why this can't be legitimate behavior and how the entity benefitted.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
