### ISSUE TITLE
Related airdrop hunter 0xdf21b894a490cbdf49d9de7b9d780b79f7cb0ac7

### ISSUE THREAD

**Issue by kkyu2020-dot** [safe-global/safe-user-allocation-reports#71]
# Related Safe Addresses
0xbf51397608972087c5751460682d3bf33e6c4323
0x782cd5782852da009e3422dd1b34379e62c2aa23
0xbdbc2721254dd29b8638871108b1e5af358ef641
0x174cce510e7ac18ae05c9d67540ac686ebb51810
0x915f9956e06280c0438183322dca9d3022ed52a0
0xe4117d452bf2944e433a1825a000bacd7d5ca5bf
0xfaf987b0989efd38086fcc4525f1d97686d61406
0x394514b08b8d4383467e8beb3cf7f62c56eca894
0x076549e08e78d4a473412a8298fb0d370e008e09
0x9af26965e246fd8ec44f0bbbfe5ece3e15932179
0x4926b6a9f0c78938a52382dbd923c17f4765a2f3
0xfbb9145cb7cada2dd8609da517a4def116dac9da
0x8f1e1532384648f3e44ca8f617a3852c031bd1ab
0xdfc654c47909083beacd41f18984160d73947a27
0xd21a5d84baf43daec5bf68f7641e614b7a4f0c26
0x8c32960138f0387de89fb39c4355ec89bae24e2b
0x7387193d0ea093afd8d0c5857856811c984b6eb5
0x6ecb8c423a49eab3444d7fac879750113ad18852
0xfe9a15c9217801826e6658780a0d1bf0a8a21d05
0x4fe35f43c998ed486d16dc0fb1331f1fb7db3bbe
0xb433e13fffbd79432fb7f3fcffbb77c5ddcd7072
0x6910286783802b7c215601b79f1ec826d41b4f38
0x00564b75cad21eda503c9214f1e30aa204390a5c
0x4b4d21cc4a210e1267ae6eb9f1db5f8d8622dc4f
0x85d0a53df27d3e0d19f0b6f7ca8c5e31ac68d26d
0x04ff6cb3ee46892abc39204205e18d9cb3ec49b1
0xfeab0697182b871d34af9815aa1c731065da7547
0xf06a1fe01a19b83e6e323e4a977ed4cc12f7f677
0x33059596552b07b4de4e8ac36c8bd9588198287a
0x3ea23355ecdcfda257fae663c78c8a556ce5581b
0x000aa9987989de639988caabe4d54b2d2d644a0d
0xbea2577c7a3d85da6c5b6352f2d8033dd48f505c
0x8da58a0145f9daa60fbed5db6b0e340531c57b70
0xc1bd78bcd9abb1ce72f05b5984581a0e4eed2884
0x64a0bfe946990904330189c22278139e879a3384
0x8369b945340809e84f4e721cd155aba8e65d863e
-->

# Reasoning
The account sends the same amount (small amount of eth) 0.00077856471 to multiple established vaults

# Safe Address
0x76B5586a46B752a96Ba423b0d3aCd1b23bDc1d7C
-->

**Comment by kkyu2020-dot** [comment]
more related safe address:
0xd5c69f32978906ae3f1a44e2e242b38cc0849a05
0x5a88e61c4ee7f489F3aBDd6b65acCF919ed2D04A
0x4AB366bb8bC710C222B57BD2803806F3e53a5421
0xC186425f7bBf7A6C1D1EDE3dC40F5bf27bFb6eEA
0xBf374F68c519173816d96Ad6368839B3824c9BC7
0xf756c52816a0C8c7a4bfb0575F5B1e1e46171Fb0
0x2b3a6B9FD979f14B4Af5fF38ead6b1718DE5834D
0x93FA075eA1Ce1a0309174a0B882E323D24235CCB
0x3C0f3aB28A5d7558Ab11Ef0e569c15A253d32993
0x7CfdECE255141853DcCf3980f4Dc237C84DEf1b5
0xe1F666B99229513186FB542f95E4Bb7244A72777
0x0Fc8f70BcD007fF7197c68375a87D571aEc8754e
0x1514e5eb2E1E0514B6058023aa7d1cEc957Ae583
0xB0a13a50Bf39aFa507CE50a191Cc373B2F941594
0x058B63A3caa6D82041dB2Cc6Aaf6ce375eabd0A3
0xa37D1987F25E9E18E72383271ab68b760CaEFe83
0x82493dc8c62e2BA410114f4c078E43f218B392d1
0xB883375718F5dD55090c80Fa3A4b9642c14f798e
0xB2774fc74Cf0FFDB554fc159be282885d982BC23
0xB9003EB9E243568b2BEe8612f5D7C6f6c17831Fa
0xaD8A08301Fa20FD7b892FBC2CBAA482087e53Fcf
0x3AB4C4c4DeDfF1864D433e30934206A2a8Aa7365
0x124BE2675C373D8784F031A3143783b0E84DA64e

**Comment by tschubotz** [comment]
This report is incomprehensible and missing details, please structure it properly.



> The account sends the same amount (small amount of eth) 0.00077856471 to multiple established vaults

Which account, pls elaborate how this is airdrop farming.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
