### ISSUE TITLE
Airdrop hunter address，Here are 13 of them I reported,Duhe creates an address for batch small-amount transfers

### ISSUE THREAD

**Issue by yt00131** [safe-global/safe-user-allocation-reports#81]
0x7f630885074b976570152a712589e0cECa9086d3
0xAb61F7CB67dbce3612F3EEFd617b2DF2A27D5215
0xAFC1B3139d9FDf949c53e4743d4987e78dC1d781
0xe4cf7B2C9A95606238cAa760048e91B3865b341a   
0x676758b7C610ACeC42d47e414d5335cf6FA11899
0xB05335790892D06800fA6c13c9383DBa687c7914  hash:0xd4181786b84a9c05850f2d99c74639d52b9624736509c5fc31d9c90d149972e1 
0x6673fA2045AE0324C68c0cc6F66e7d91C446d728  hash:0x540b9bb8e0fa1efdc467d019fe0117898cf22e1c4f624b459330caed40b3b6eb
0xc813081D835C27eB08112a390654bF4b0E7C6F9F   hsah:0xd3f866aadfebbdd227690a504b2f5e2fda88e7ca3caa01e932e5c98d887a4c57  0x20c05cf93223e39d75b6266b4044e2e5c588d089>0xc813081d835c27eb08112a390654bf4b0e7c6f9f  0.001 Ether
0x3204596e8Cd53a791767340C93Fb5Ee2F11b5840  0x20c05cf93223e39d75b6266b4044e2e5c588d089 > 0x3204596e8Cd53a791767340C93Fb5Ee2F11b5840  0.001 Ether
0x61f744a03B89f7267d26839D4913693c58EadbdE   0x20c05cf93223e39d75b6266b4044e2e5c588d089>0x61f744a03B89f7267d26839D4913693c58EadbdE  0.001 Ether
0x310DD223a6999578F9C0738003cc6Ca665E3D830  0x310DD223a6999578F9C0738003cc6Ca665E3D830>0x310DD223a6999578F9C0738003cc6Ca665E3D830 0.001 Ether
0xDE7a69f62a0746cf93bf97BCA16038d05fB700e5  0x20c05cf93223e39d75b6266b4044e2e5c588d089>0xDE7a69f62a0746cf93bf97BCA16038d05fB700e5   0.001 Ether

Reasoning
The airdrop hunter used the 0x20c05cf93223e39d75b6266b4044e2e5c588d089 mainnet wallet to create 111 multi-signature addresses, and all of them received high token rewards,The query link is  https://etherscan.io/address/0x20c05cf93223e39d75b6266b4044e2e5c588d089?method=Create__Proxy__With__Nonce~0x1688f0b9
The above addresses have been queried in detail. All of them are the main address that transferred a small amount of Ethereum to the multi-signature contract address created. I have marked most of them, and can be queried in detail.
Methodology
Querying an address through the Ethereum browser has created 111 multi-signature addresses, and all of them have transactions. The query link is  https://etherscan.io/address/0x20c05cf93223e39d75b6266b4044e2e5c588d089?method=Create__Proxy__With__Nonce~0x1688f0b9
they all call  Create__Proxy__With__Nonce

My Safe Address
0x04b9f219331e4586Ae35cff9065eFc2A09F29751

**Comment by tschubotz** [comment]
This report is incomprehensible, please structure it properly.

Also, creating multiple Safes from the same account is not airdrop farming per se. e.g. when wallets use a relayer, that will be creator of all wallets. Please elaborate on why you think this is airdrop farming.

**Comment by yt00131** [comment]
![image](https://user-images.githubusercontent.com/28423265/190154666-469aa99f-6241-42fb-ac11-bffb0eb46fff.png)

0x3d326c63cc0f126866104c97bc130b31e1104bae
0x51f78d81194cb282e3bd5ff4bbd468f56fdbffe0
0xbfa3e74ecac5b2ecf20b2bafcdc02cd659435a45
0x91155176f8911c6a34dbca8537a59c2c4816d2d3
0x30cd6df997d3c153624fcc560823a32e8886d69a
0x199aa8a209884ffb1e0849eaeb072bce573bf871
0x8cb1f9ad02e57eca18065d83efdfb6ff0c57392c
0xf03a139c3d0d26a07e2939204ae7f3ea1dbd9919
0x7C3D8bc495b7d2Dcc995A3A0dC6444480483988c
0xadca2254b9b40a48ef44140482e912a03cbc7f5d
0xeae5e0d63285f24f3a089fdb6a0082ff6801eba1
0x521fe1bd7dec39362809cac1a237629d458e459b
0x692a7d771c69bf1664690b5a072e04f14254aece
0x1d02f0a433a999a777d1b11311c4bc9fac33af65

The addresses I copied all had only one small transaction, which was completely in line with witch behavior. And all are the same amount, the contract creator and transfer address are different, excluding the possibility of a repeater.

**Comment by yt00131** [comment]
![image](https://user-images.githubusercontent.com/28423265/190155213-2521a7ef-ddec-47e3-911e-eacdfd4246b7.png)

0x7f630885074b976570152a712589e0ceca9086d3
0xab61f7cb67dbce3612f3eefd617b2df2a27d5215
0x676758b7c610acec42d47e414d5335cf6fa11899
0x6673fa2045ae0324c68c0cc6f66e7d91c446d728
0xc813081d835c27eb08112a390654bf4b0e7c6f9f
0x3204596e8cd53a791767340c93fb5ee2f11b5840
0x61f744a03b89f7267d26839d4913693c58eadbde
0xde7a69f62a0746cf93bf97bca16038d05fb700e5
0x3d326c63cc0f126866104c97bc130b31e1104bae
0x51f78d81194cb282e3bd5ff4bbd468f56fdbffe0
0xbfa3e74ecac5b2ecf20b2bafcdc02cd659435a45
0x91155176f8911c6a34dbca8537a59c2c4816d2d3
0x30cd6df997d3c153624fcc560823a32e8886d69a
0x199aa8a209884ffb1e0849eaeb072bce573bf871
0x8cb1f9ad02e57eca18065d83efdfb6ff0c57392c
0xf03a139c3d0d26a07e2939204ae7f3ea1dbd9919
0x7C3D8bc495b7d2Dcc995A3A0dC6444480483988c
0xadca2254b9b40a48ef44140482e912a03cbc7f5d
0xeae5e0d63285f24f3a089fdb6a0082ff6801eba1
0x521fe1bd7dec39362809cac1a237629d458e459b
0x692a7d771c69bf1664690b5a072e04f14254aece
0x1d02f0a433a999a777d1b11311c4bc9fac33af65

The addresses I copied all had only one small transaction, which was completely in line with witch behavior. And all are the same amount, the contract creator and transfer address are different, excluding the possibility of a repeater.

**Comment by tschubotz** [comment]
This doesn't meet quality standards.
