### ISSUE TITLE
jpworld.eth is the airdrop farmer

### ISSUE THREAD

**Issue by SeanCCkaka** [safe-global/safe-user-allocation-reports#90]
# Related Safe Addresses

0x7c3d8bc495b7d2dcc995a3a0dc6444480483988c
0x8f6a8cbacb7aab99d80c39eac0a412653756f83a
0xf7525acad4cac16e4f4b873e514cb4ef171d7d69
0xafc1b3139d9fdf949c53e4743d4987e78dc1d781
0xf03a139c3d0d26a07e2939204ae7f3ea1dbd9919
0x5deaba8f3d9ac196df20987987a3b15eac629927
0x52b14b11ef687dbad8e422d655a45ea551948760
0x91155176f8911c6a34dbca8537a59c2c4816d2d3
0xde7a69f62a0746cf93bf97bca16038d05fb700e5
0x7f630885074b976570152a712589e0ceca9086d3
0x676758b7c610acec42d47e414d5335cf6fa11899
0x09778357c90993eb74c5dd80087c92fdf98e86fa
0xab61f7cb67dbce3612f3eefd617b2df2a27d5215
0x1deafddfc62c7d6113204adff6fda8a2d2e55a69
0x3204596e8cd53a791767340c93fb5ee2f11b5840
0x670a36a15e1435099c8621e3ea7fa928abd0ef2e
0x8afcf6938dae0439c68e2c4f533e3aad6e967e30
0x7ec0740988c8d01ef4acfb8ac280dbc7b1d2462b
0x30cd6df997d3c153624fcc560823a32e8886d69a
0x199aa8a209884ffb1e0849eaeb072bce573bf871
0xeae5e0d63285f24f3a089fdb6a0082ff6801eba1
0xc813081d835c27eb08112a390654bf4b0e7c6f9f
0x310dd223a6999578f9c0738003cc6ca665e3d830
0x56515294acc335ed825d640cc5dff615ffed132c
0x4d8a16f1f414852185e6216fbb9bc4daf4a23713
0x61f744a03b89f7267d26839d4913693c58eadbde
0xadca2254b9b40a48ef44140482e912a03cbc7f5d
0xb05335790892d06800fa6c13c9383dba687c7914
0x6673fa2045ae0324c68c0cc6f66e7d91c446d728
0xbfa3e74ecac5b2ecf20b2bafcdc02cd659435a45
0x3d326c63cc0f126866104c97bc130b31e1104bae
0x8cb1f9ad02e57eca18065d83efdfb6ff0c57392c
0x51f78d81194cb282e3bd5ff4bbd468f56fdbffe0
0x521fe1bd7dec39362809cac1a237629d458e459b
0x9063569beec766261538e7612ffb2d79bfcf6a00
0x692a7d771c69bf1664690b5a072e04f14254aece
0xfed79ad04bc452420e6df9f40625cec8e8a3373d
0x70c9fd1651ca952314965764012ab63e60fd4eb9
0x4153f0145d48bbd3eb2438dbe1d4535734ec78e3
0x082c22f06acf8f603b98946c8f6392a453ff63b0
0x1d02f0a433a999a777d1b11311c4bc9fac33af65
0x47d1ec908b261adf318f16d52752eec0b2c38be6

# Reasoning

This address hold the ENS service, and he has many ETH transactions from the Binance,kucoin and hotbit. Also he bought the Poolin mars project. Based on that I can difine it is a personal user, which airdrop farmer!

# Methodology

with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0x20c05cf93223e39d75b6266b4044e2e5c588d089')

# Safe Address

0xc7495E1c9A62e74473d890eaE40537713AAC73f7

**Comment by tschubotz** [comment]
This report is incomprehensible, please structure it properly.

> This address hold the ENS service, and he has many ETH transactions from the Binance,kucoin and hotbit. Also he bought the Poolin mars project. Based on that I can difine it is a personal user, which airdrop farmer!

e.g. the first address (`0x7c3d8bc495b7d2dcc995a3a0dc6444480483988c`) has no ENS interaction.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
