### ISSUE TITLE
One main address creates 17 contract addresses and transfers in small amounts

### ISSUE THREAD

**Issue by yt00131** [safe-global/safe-user-allocation-reports#94]
The airdrop hunter used the 0x20c05cf93223e39d75b6266b4044e2e5c588d089 mainnet wallet to create 17 multi-signature addresses，Use the main address to transfer 0.001e to the contract address, most of which are such transactions。
0x30cd6Df997D3c153624FcC560823A32E8886D69A
0x199aa8a209884FfB1e0849eAeB072BCe573bf871
0x8cb1f9ad02E57eca18065d83efDFB6fF0C57392c
0x8cb1f9ad02E57eca18065d83efDFB6fF0C57392c
0x30cd6Df997D3c153624FcC560823A32E8886D69A
0xf03A139c3d0D26a07E2939204aE7f3EA1DbD9919
0x8F6a8cBAcb7aab99d80c39eaC0a412653756f83A
0x7C3D8bc495b7d2Dcc995A3A0dC6444480483988c
0x47d1EC908b261aDf318F16D52752eEc0B2C38bE6
0xADCa2254b9B40a48Ef44140482E912a03cBc7f5d
0x56515294Acc335ED825d640Cc5dfF615ffeD132C
0x70C9Fd1651Ca952314965764012ab63e60Fd4Eb9
0xeAe5e0d63285f24F3a089fDB6a0082Ff6801eBA1
0x521Fe1BD7DEC39362809caC1a237629d458e459b
0x692a7D771c69bf1664690b5A072E04f14254AecE
0x1D02F0a433a999A777d1b11311C4bc9fac33Af65

Reasoning

One main address 0x20c05cf93223e39d75b6266b4044e2e5c588d089 creates 17 contract addresses ,Transfer 0.001e to the contract address through the main address, and most addresses have only one transaction of this 0.001e
Methodology
0x20c05cf93223e39d75b6266b4044e2e5c588d089>0x30cd6df997d3c153624fcc560823a32e8886d69a  0.001e
0x20c05cf93223e39d75b6266b4044e2e5c588d089>0x199aa8a209884ffb1e0849eaeb072bce573bf871  0.001e
0x20c05cf93223e39d75b6266b4044e2e5c588d089>0x7C3D8bc495b7d2Dcc995A3A0dC6444480483988c 0.001e
0x20c05cf93223e39d75b6266b4044e2e5c588d089>0x20c05cf93223e39d75b6266b4044e2e5c588d089 0.001e
0x20c05cf93223e39d75b6266b4044e2e5c588d089>0x521fe1bd7dec39362809cac1a237629d458e459b 0.001e
All of the above transactions, I just give some examples

My Safe Address
0x04b9f219331e4586Ae35cff9065eFc2A09F29751

**Comment by tschubotz** [comment]
At least 2 Safes don't follow the pattern that you shared:
https://etherscan.io/address/0x8F6a8cBAcb7aab99d80c39eaC0a412653756f83A holds >3k USDT
https://etherscan.io/address/0x56515294Acc335ED825d640Cc5dfF615ffeD132C holds more than 1M USDC

At least those 2 don't look like airdrop farming but like legitimate usage as store of value.

Closing this as invalid. Please resubmit a cleaned list if you believe the others are airdrop farming.

**Comment by yt00131** [comment]
![image](https://user-images.githubusercontent.com/28423265/190147565-04e2281f-62d7-42b7-8cbf-0bd9fb11d550.png)
0x30cd6df997d3c153624fcc560823a32e8886d69a
0x199aa8a209884ffb1e0849eaeb072bce573bf871
0x8cb1f9ad02e57eca18065d83efdfb6ff0c57392c
0x30cd6df997d3c153624fcc560823a32e8886d69a
0xf03a139c3d0d26a07e2939204ae7f3ea1dbd9919
0x7C3D8bc495b7d2Dcc995A3A0dC6444480483988c
0xadca2254b9b40a48ef44140482e912a03cbc7f5d
0xeae5e0d63285f24f3a089fdb6a0082ff6801eba1
0x521fe1bd7dec39362809cac1a237629d458e459b
0x692a7d771c69bf1664690b5a072e04f14254aece
0x1d02f0a433a999a777d1b11311c4bc9fac33af65


If there are two multi-signatures above that cannot be defined as witches, then all the following addresses have only a small transaction of the same amount, which is completely witch behavior. And the contract creator and the transfer are the same person, which proves that this is not a repeater, the contract creator of the repeater and the transfer to multi-signature cannot be the same.
